blockscout/blockscout

- apps/explorer_web/assets/css/components/_footer.scss
- apps/explorer_web/assets/css/components/_menu.scss
- apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
- apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #139
Tweaked the footer to play nicely with the sidebar - re-rendered as a partial in <main> and removed sidebar footer I had as a place holder. 
Before:
After:
> Footer implementation #139

- apps/explorer_web/assets/css/components/_blocks.scss
- apps/explorer_web/assets/css/components/_transactions.scss
- apps/explorer_web/assets/css/explorer/_button.scss
- apps/explorer_web/assets/css/explorer/_wrapper.scss
- apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
- apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #144
Added "View All" buttons to block and transaction panels on homepage
Before:
After:
> View all button #144

- apps/explorer_web/assets/css/components/_header.scss
- apps/explorer_web/assets/css/components/_menu.scss
- apps/explorer_web/assets/css/explorer/_wrapper.scss
- apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
Added Social Media links to header 
Satisfies issue #147 which is from issue #108
Before:
After:
> Social links #147

- apps/explorer_web/assets/css/_content.scss
- apps/explorer_web/assets/css/app.scss
- apps/explorer_web/assets/css/components/_footer.scss
- apps/explorer_web/assets/css/components/_header.scss
- apps/explorer_web/assets/css/components/_menu.scss
- apps/explorer_web/assets/css/components/_sidebar.scss
- apps/explorer_web/assets/css/explorer/_wrapper.scss
- apps/explorer_web/assets/css/theme/_neutral-variables.scss
- apps/explorer_web/assets/js/lib/sidebar.js
- apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Refactored sidebar and containers for maintainability
> Sidenav bug #150

- apps/explorer_web/assets/css/app.scss
- apps/explorer_web/assets/package-lock.json
- apps/explorer_web/assets/package.json
- apps/explorer_web/assets/webpack.config.js
- apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
When we installed fontawesome we didn't realize we were installing an old version (by `we` I mean `I`...).
> Upgrade fontawesome

- apps/explorer/mix.exs
- apps/explorer_web/mix.exs
- mix.lock
* Update to `credo` `0.9.2`
* Update `credo` to match CircleCI cache to fix build failures.
> Update to credo 0.9.2

- .circleci/config.yml
- appspec.yml
- bin/deploy
- bin/deployment/build
- bin/deployment/health_check
- bin/deployment/migrate
- bin/deployment/start
- bin/deployment/stop
- bin/deploy is executed by CircleCI to push deploy to AWS
- bin/deployment/* are executed by CodeDeploy in AWS
- appspec.yml is used by CodeDeploy to execute bin/deployment scripts
based on lifecycle events
> Initial AWS deployment config and scripts

- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Resolves #120 
* Change Gas Price to show Ether/Gwei
> Change Gas Price to show Ether/Gwei instead of Wei/Gwei

- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
- apps/explorer_web/lib/explorer_web/views/transaction_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #141 
- Display Gas Used as Gas instead of Total Gas Used as Wei
> Display Gas Used on transaction page

- apps/explorer_web/assets/css/app.scss
- apps/explorer_web/assets/css/code.scss
- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
resolves: #209 
**Changelog**
* Added a code block element for the transaction input content
> Handle large transaction input content

- apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
- apps/explorer_web/lib/explorer_web/views/transaction_internal_transaction_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
- apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
- apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
Resolves: #210 
- Added paging to transactions page's internal transactions list
- Move value unit to header on address page's internal transactions list
> Create consistency between internal transaction lists

- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
> Hide table and paging elements display if no internal/transactions exist

- apps/explorer_web/assets/css/_code.scss
- apps/explorer_web/assets/css/_typography.scss
- apps/explorer_web/assets/css/components/_header.scss
- apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
- apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
- apps/explorer_web/lib/explorer_web/templates/layout/_topnav.html.eex
- apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/views/address_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/views/address_view_test.exs
> Ui bug fixes

- apps/explorer_web/lib/explorer_web/router.ex
> Add Google Fonts to Content Security Policy

- apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
Fixes #317 
Adds the same styling as the labels above.
> Add same markup as the labels above

- apps/explorer/package-lock.json
- apps/explorer_web/assets/package-lock.json
- `explorer/package-lock.json` didn't get included in #288  because it wasn't generated because I was using an old npm version.
- some changes in `explorer_web/assets/package-lock.json` wasn't commited after some changes.
> Include and update explorer/ and explorer_web/assets/ package-lock.json

- apps/explorer_web/assets/package-lock.json
- apps/explorer_web/assets/package.json
A few vulnerabilities were fixed automatically after running npm audit, the rest of them need to be fixed manually.
```
$ npm audit fix
up to date in 8.606s
fixed 9 of 16 vulnerabilities in 13967 scanned packages
5 vulnerabilities required manual review and could not be updated
1 package update for 2 vulns involved breaking changes
(use `npm audit fix --force` to install breaking changes; or do it by hand)
```
```
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Cryptographically Weak PRNG                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package …
```
> Run audit on node dependencies

- README.md
Adding information to README to orient new contributors and let people know what the project is about.
- About POA explorer
- Features
- Instruction Formatting
- Added Acknowledgments & License Section
- Added link to Code of Conduct in Contributing section
> (enhancement) About us and feature details

- README.md
Changes current support to version 1 support item of ERC-20 tokens.
> Fix ERC20 token support

- apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
- apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/views/address_view.ex
- apps/explorer_web/lib/explorer_web/views/transaction_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Fixes: #379
* Fix pending transactions page display of contract creations
> Fix pending transactions page error

- apps/explorer_web/assets/css/_typography.scss
- apps/explorer_web/assets/css/components/_tile.scss
- apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
- apps/explorer_web/lib/explorer_web/templates/address/_responsive_hash.html.eex
- apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
- apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/views/address_view.ex
- apps/explorer_web/lib/explorer_web/views/transaction_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
- apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Resolves #368 
* Updated design for Validated and pending transaction pages
> Transaction list page redesign

- apps/explorer/test/support/factory.ex
Related to #434 and #436
* Restores a factory that was mistakenly thought to be unused
> Restore factory needed by tests

- apps/explorer_web/assets/css/_elements.scss
- apps/explorer_web/assets/css/_typography.scss
- apps/explorer_web/assets/css/app.scss
- apps/explorer_web/assets/css/components/_description-list.scss
- apps/explorer_web/lib/explorer_web/templates/block/overview.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/features/pages/block_page.ex
Resolves #370 
**Updated the styles for the block overview 
**Added in transaction tiles styling
> Block page #370

- apps/explorer_web/assets/css/_typography.scss
- apps/explorer_web/lib/explorer_web/templates/address/_responsive_hash.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/_internal_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer_web/test/explorer_web/features/pages/transaction_page.ex
- apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Resolves #369 
* Updated transaction detail over page to new design 
* Updated logs tab with new design for individual log events
Multiple Logs:
> Transaction detail #369

- apps/explorer_web/assets/css/app.scss
- apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
- apps/explorer_web/lib/explorer_web/templates/chain/_block.html.eex
- apps/explorer_web/lib/explorer_web/views/block_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #371 
Implement the new design styles and layout to the Block index page.
> Update block list page design

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc/mox_test.exs
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
- apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
- apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
- apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
- apps/explorer_web/priv/gettext/default.pot
- apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/poa-explorer/issues/478
Related to https://github.com/poanetwork/poa-explorer/pull/417
* Token sender page
* Token receiver page
* Contract page
* Token sender page (Notice that this address is sending POA beyond tokens).
* Token receiver page
* Contract page (Notice that this address is receiving POA)
* Token sender page
* Token receiver page
* Contract page
> Improve token transfers on transactions tab in the Address details page

- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/_transaction.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/token/show.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/blockscout/issues/485.
<details> 
<summary><b>Token link to token page</b></summary>
</details>
> Include a link to the token page on the address page, and show token type on the token page

- apps/block_scout_web/config/prod.exs
In conjunction with [#50](https://github.com/poanetwork/blockscout-terraform/pull/50), this PR allows real-time events to take place on a deployed AWS instance.
- `check_origin: ["//*.blockscout.com", "//*.elb.amazonaws.com"],`
The ability to deploy with real-time events.
n/a
n/a
n/a
> Fix real-time events on AWS

- apps/block_scout_web/assets/css/components/_nav_tabs.scss
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/chain_view_test.exs
Resolves: #525
Updated the visual aspects of the API docs to match the rest of the explorer app. 
* Updated code to match the rest of the web (tables --> Descriptor tags and columns) to have a little more flexibility. 
* Updated code inputs to our tile muted to match the other places we're doing something similar
> 525 design cleanup api doc

- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
I converted the links to buttons so you do not have nest links in links! Let me know if you have any questions.
> Turned links into buttons and styled

- apps/block_scout_web/assets/css/_typography.scss
- apps/block_scout_web/assets/css/components/_icon-link.scss
- apps/block_scout_web/assets/css/components/_token-balance-dropdown.scss
- apps/block_scout_web/assets/css/theme/_poa_variables.scss
- apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
- apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves #569 
*Combined tokens and balance to one card
> Updated address page so things do not wrap 

- apps/block_scout_web/lib/block_scout_web/etherscan.ex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
For API docs to include links to token standards.
> Adds links to token standards in API docs

- apps/block_scout_web/assets/__tests__/pages/block.js
- apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
- apps/block_scout_web/assets/js/pages/address.js
- apps/block_scout_web/assets/js/pages/block.js
- apps/block_scout_web/assets/js/pages/transaction.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/event_handler.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/chain_test.exs
- apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
- apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
- apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
- apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex
- apps/block_scout_web/test/block_scout_web/features/pages/transaction_page.ex
- apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
- apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/import.ex
- apps/explorer/test/explorer/chain/import_test.exs
Resolves #312 
Live updates of internal_transactions on address page
* Live updates of internal_transactions
* Improved test coverage for coveralls
> 312 live update internal transactions on address page

- .circleci/config.yml
- apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_token_balance_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/pages/address_contract_page.ex
- apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
- apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
- apps/explorer/test/support/factory.ex
- apps/indexer/test/indexer/block_fetcher/realtime_test.exs
Resolves: #677 
* Capture and re-throw original exit status so that CircleCI successfully reports test failures
* Fix (or remove) broken tests to get back to green
> Fix circle test reporting

- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves #524 
* Updated Token tiles to match other tiles through out the website
* Added token type to overview
* Added copy button and QR code
> Token Details Design Clean Up

- apps/indexer/lib/indexer/token_fetcher.ex
- apps/indexer/test/indexer/token_fetcher_test.exs
It's a temp fix for https://github.com/poanetwork/blockscout/issues/669.
We are receiving the above error trying when indexing [this token](https://etherscan.io/token/0x9aa770153ac4d9268046c64c319afe8c31e462d3) on Ethereum Mainnnet :
```
18:26:45.349 [error] Task #PID<0.8148.3> started from Indexer.TokenFetcher terminating
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0xa7
(ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
(ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
(ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
(ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
(db_connection) lib/db_connection.ex:1374: …
```
> Ignore tokens that have the name and/or symbols with special characters

- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Updated the search button to actually submit when pressed, we also switch it to the right side to balance the page a little more.
> Update search button

- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves #672 
Adds the ability to copy transaction hash
> 672 txn copy button

- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/_internal_transaction.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves #684 
* Added the missing gettext
> 684 the case of the missing gettext

- README.md
> readme update deploy

- apps/block_scout_web/assets/css/_code.scss
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/css/components/_button.scss
- apps/block_scout_web/assets/css/components/_dropdown.scss
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
Resolves: #708 
The details view has some layout quirks, especially on mobile devices, that need to be addressed.
* Improve button text readability
* Shorten the text within the buttons used to copy code blocks
* Add `ARIA` labels to the copy buttons to fully describe their function to screen readers and assistive tech
* Uglify the contract ABI code block
* Fix the layout of the Address/Contract Address sub nav on mobile devices
* Simplify the layout of the stats/info below the page title
1. Visit a contract address details page (a contract that has been verified is preferable) 
2. Toggle the device emulator within the dev tools (the second icon from the left of the dev tools nav bar on Chrome)
3. View the layout and style of impacted elements
* the info within the title section
* the sub …
> Address/Contract Address Details Mobile Optimization

- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/config/test.exs
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
- apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/block_scout_web/test/support/fake_adapter.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/explorer/chain_test.exs
Resolves #686 
Create a page to show the top addresses by balance in descending order.
* Top addresses page created listing the top addresses by balance in descending order with the number of transactions per address and the percentage of the total supply.
> 686 account list pg

- .tool-versions
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
* Upgrade node.js `10.5.0` to `10.11.0`
* Upgrade bootstrap.js `4.1.1` to `4.1.3`
* Run `asdf install` to upgrade to node.js `10.11.0`
* Run `cd apps/block_scout_web/assets && npm install; cd -` to install newly required bootstrap.js version
> Upgrade node.js and bootstrap.js

- apps/block_scout_web/assets/__tests__/pages/transaction.js
- apps/block_scout_web/assets/css/components/_animations.scss
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/assets/js/pages/transaction.js
- apps/block_scout_web/assets/js/utils.js
- apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
- apps/block_scout_web/test/block_scout_web/views/error_helpers_test.exs
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
- apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
- apps/explorer/lib/explorer/chain/import.ex
- apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Resolves: #372 
Resolves: #373 
Live reload pending transactions page.
* Add pending transactions to the list as we see them
* Remove pending transactions from the list as they get validated
> Live reload pending transactions page

- apps/block_scout_web/assets/css/components/_dropdown.scss
- apps/block_scout_web/assets/js/app.js
- apps/block_scout_web/assets/js/lib/token_balance_dropdown_search.js
- apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
- apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
closes #424
* search box to filter token balances
* update number of tokens being displayed as the user types
> dynamic token search on balance box

- apps/indexer/lib/indexer/block/realtime/fetcher.ex
* We want to add a retry mechanism, instead of waiting half a second for
every block the realtime fetcher attempts to fetch and index. We had
this half a second wait in place in an attempt to avoid "Unknown block
number" errors. The half a second wait was effective at reducing these
errors but it also meant we were waiting unnecessarily for most
fetches. Retrying after half a second, when Parity says it
doesn't yet know of a given block number, makes more sense.
* Editing `Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3` to
retry failed fetch/import attempts because of "Unknown block number"
errors. It waits half a second before retrying and retries a maximum of
three times.
> Realtime fetcher retries for unknown block number

- apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
- apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
Fixes #592
* Ensure that `Indexer.Block.Catchup.BoundIntervalSupervisor` acts as a proper `Supervisor` by ensuring it supports all `Supervisor` and `:supervisor` functions.
> Indexer.Block.Catchup.BoundIntervalSupervisor is proper supervisor

- apps/explorer/lib/explorer/chain/import/blocks.ex
- apps/explorer/test/explorer/chain/import_test.exs
Fixes #868
* Regression test for #868.
* `nil` `error` when forking `transactions`.
> nil error when forking transactions

- apps/block_scout_web/assets/css/components/_animations.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
- apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/views/block_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex
- apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex
- apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
- apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/block.ex
Resolves: #745 
Resolves: #837 
Display uncle and reorg block information in the UI.
* Create Uncle and Reorg index pages
* Create Uncle and Reorg detail pages
* Add links to uncles on block deatil pages
* Add links to the uncle and reorg index pages to the top nav bar
> Uncle Support in the UI

- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
Fix a bug with overlapping elements caused by conflicting z-index values.
n/a
* Adjust z-index values to ensure that the network selection menu in unencumbered.
n/a
n/a
> Fix z-index issue with the network selection menu

- apps/indexer/lib/indexer/block/uncle/fetcher.ex
Related to #919.
* Log and retry import errors in uncle fetcher
> Log and retry import errors in uncle fetcher

- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/errors.po
Resolves #878 
I wanted to see how many of the top accounts were validators.
> Address tile should display validations

- apps/block_scout_web/assets/js/lib/market_history_chart.js
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/explorer/config/config.exs
- apps/explorer/config/test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/supply.ex
- apps/explorer/lib/explorer/chain/supply/proof_of_authority.ex
- apps/explorer/lib/explorer/chain/supply/transaction_and_log.ex
- apps/explorer/lib/explorer/chain/wei.ex
- apps/explorer/lib/explorer/exchange_rates/source/transaction_and_log.ex
- apps/explorer/test/explorer/chain/supply/transaction_and_log_test.exs
- apps/explorer/test/explorer/chain/wei_test.exs
- apps/explorer/test/explorer/exchange_rates/source/transaction_and_log_test.exs
- apps/explorer/test/support/fakes/one_coin_source.ex
closes #905 
- add a way to count the supply from mints and burns
- change the chart on home for dai chain to use the supply of each day instead of the supply of today
- add a configuration to use the new modules
> dai chain supply and market cap

- apps/indexer/lib/indexer/token_transfer/uncataloged/worker.ex
- apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
Resolves #1000 
Module `Indexer.TokenTransfer.Uncataloged.Worker` checks for missed token transfers due to formatting issues. After deployment, I noticed the `UndefinedFunction` error. I updated `enqueue` for `push_front` which simply adds the set of blocks with the missed token transfers to the front of the async block fetcher. 
- replaced `:enqueue` with `push_front`
Fixes the undefined function error on Ropsten.
> Fix for undefined function error in TokenTransfer Uncatalogued Worker Module

- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
Resolves: #943 
The layout of the contract query response was jacked.
- Fix the layout of the contract query response
> Read contract query styling

- apps/block_scout_web/assets/js/pages/address.js
- apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
* In attempt to speed up the address page we are trying to load more of the data asynchronously.
*  Load first page of address transactions asynchronously
>  Load first page of address transactions asynchronously

- apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
closes #1085 
- change the controller to send the listing via JSON request
- change template to use the async loading javascript
> make internal transactions load async

- apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs
- apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
closes #1087
* change the controller to send the listing via JSON request
* change template to use the async loading javascript
> Async loading on the token holders page

- apps/block_scout_web/assets/__tests__/pages/address.js
- apps/block_scout_web/assets/js/pages/address.js
- apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
This code should be removed with the code removed in this PR: https://github.com/poanetwork/blockscout/pull/1063
Relates to https://github.com/poanetwork/blockscout/issues/60
> Remove references from pending transactions feature

- apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.ex
- apps/explorer/lib/explorer/chain/token_transfer.ex
- apps/explorer/test/explorer/chain_test.exs
Fix https://github.com/poanetwork/blockscout/issues/1163
This code was removed and it shouldn't :(. Besides bringing this code back, I'm adding tests in the controller layer to make sure that it will not happen anymore.
> Fix pagination issue on inventory tab at Token's page

- apps/block_scout_web/lib/block_scout_web/endpoint.ex
- apps/block_scout_web/mix.exs
- mix.lock
Resolves https://github.com/poanetwork/blockscout/issues/1011
* For our partner's front-ends to be able to work with our API
endpoints.
* Adding `CORSPlug` with defaults plus `x-apollo-tracing` header for
GraphQL usage with graphqlbin.com
> Add CORSPlug

- apps/block_scout_web/assets/__tests__/pages/pending_transactions.js
- apps/block_scout_web/assets/js/pages/pending_transactions.js
- apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
resolves #1147
* use async load on pending transactions
* use common pagination and remove infinite scrolling
> async load and remove infinite scroll from pending transactions

- apps/indexer/lib/indexer/block/realtime/fetcher.ex
Resolves https://github.com/poanetwork/blockscout/issues/1189
* For the realtime indexer's logic that fills in skipped block numbers
to account for reorgs. See issue above for details and examples.
* Editing the realtime fetcher to keep track of the max block number
seen.
* Editing realtime fetcher's `start_fetch_and_import` function to only
fill in for skipped block numbers when the block number received from
the `newHeads` subscription is not a reorg. A reorg in this case is
defined as a block number that is less than or equal to the max block
number the realtime fetcher has seen.
* Editing realtime fetcher's `fetch_and_import_block` function to wait 5
seconds if the block number given for it to fetch is a reorg. This is
useful to improve the chance that the latest fetched block for a …
> Fix realtime indexer's 'no skips prevention' bug

- apps/block_scout_web/config/config.exs
- apps/ethereum_jsonrpc/config/config.exs
- apps/explorer/config/config.exs
- apps/indexer/config/config.exs
- config/config.exs
Extracted from #1185
* Include date in addition to time in log fromat.
> Include date in addition to time in log format

- README.md
- apps/block_scout_web/assets/js/lib/redux_helpers.js
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/lib/explorer/chain/address/token_balance.ex
* docs in the redux helpers
* docs in the `Address.TokenBalance` and `Address.CurrentTokenBalance` schemas
* Update README including a Frond-end section
> Improve docs in the application

- apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Fixes #1253
* Ensure pending transaction import without timeout by chunking in case the node has a lot of pending transactions.
> Chunk pending transactions

- apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
> Use info style in verify contract message

- apps/block_scout_web/assets/README.md
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
Relates to #1161 
* Async load in the blocks listing at the homepage.
> Async loading to block list in the home page

- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/parity/http_websocket.ex
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex
- apps/explorer/test/support/fixture/vcr_cassettes/block_importer_download_block_1_downloads_the_block.json
- apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_duplicate_block.json
- apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_pending.json
- apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_saves_the_block.json
- apps/explorer/test/support/fixture/vcr_cassettes/ethereumex_extensions_trace_transaction_1.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_duplicate.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_earliest.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_integer.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_latest.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_string.json
- apps/explorer/test/support/fixture/vcr_cassettes/import_receipt_perform_1.json
- apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1.json
- apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1_with_contract_creation.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_binds_internal_transactions.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_from_address.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address_from_creates.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction_with_a_bad_hash.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_failed.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_out_of_gas.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_pending.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_receipt.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_saves_the_transaction.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_saves_the_association.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_txn_without_block.json
- apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_updates_the_association.json
Updating the `sokol` node RPC Endpoint on tests.
* Updated node endpoint
> Update Parity Sokol node tests

- apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Fixes #1308
* Delete `block_rewards` for the following conditions to account for reorgs:
1. If a block is non-consensus delete rewards for its hash as the hash should no longer have rewards.
2. If a block is consensus delete rewards for its number as rewards currently in the database were from before a reorg.
> Delete block_rewards for non-consensus or old consensus blocks

- apps/indexer/lib/indexer/block/realtime/fetcher.ex
fixes https://github.com/poanetwork/blockscout/issues/1326
- Added periodic polling for real-time fetcher
> [WIP] return polling to realtime fetcher

- apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql
Fixes #1335
Returns the number of rows to update.  This takes 16 minutes on Eth Mainnet Prod.
```sql
SELECT COUNT(*)
FROM (SELECT 1
FROM address_token_balances
INNER JOIN address_current_token_balances
ON address_current_token_balances.address_hash =
address_token_balances.address_hash AND
address_current_token_balances.token_contract_address_hash =
address_token_balances.token_contract_address_hash
GROUP BY address_token_balances.address_hash,
address_token_balances.token_contract_address_hash,
address_current_token_balances.block_number
HAVING MAX(address_token_balances.block_number) !=
address_current_token_balances.block_number) AS address_incorrect_token_balances;
```
**DO NOT RUN THIS ON PROD.**
Purposely makes some (`500`)  of the rows have a different block number.  
```sql
UPDATE …
```
> Optimize update_address_current_token_balances_in_batches

- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
* One piece of #1344
Alt tags are important for accessibility.
* Add alt tag to footer logo
* Add alt tag to header logo
> feat: add alt tags to logos

- apps/block_scout_web/assets/css/components/_animations.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves #1381, #1304, #1312
This pull request fixes some small UI bugs including:
* Add forum support link to the footer
* Update the font style of the version in the footer
* Fix the styling of the reward on the blocks page
* Update the copy button on the verified contract page
> Various UI Bug Fixes

- apps/explorer/priv/repo/migrations/20190208143201_add_index_on_address_hash_block_number_and_token_contract_address_hash_for_current_token_balance.exs
in this PR https://github.com/poanetwork/blockscout/pull/1357/files records are selected and deleted based on fields without index
- add index for address_current_token_balances
> add index for address_current_token_balances

- apps/indexer/config/config.exs
- apps/indexer/lib/indexer/replaced_transaction/fetcher.ex
- apps/indexer/lib/indexer/replaced_transaction/supervisor.ex
We are seeing performance issues and crashes due to the replaced transaction fetcher, so this will let us turn it off while we decide what to do with it.
> feat: make replaced transactions disabled

- README.md
* Learned that SafeChain is running a private instance
- link on README
*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing …
> add safechain link in README

- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/explorer/chain_test.exs
- apps/indexer/lib/indexer/block/realtime/fetcher.ex
fixes https://github.com/poanetwork/blockscout/issues/1427
- check if to_address_hash is contract address to fetch internal transactions
> check if to_address_hash is contract address to fetch internal transactions

- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
* We should resolve security issues whenever alerted by github that a dependency could be insecure.
> fix: resolve lodash security alert

- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/explorer/package-lock.json
> fix bootstrap vulnerability

- apps/indexer/config/prod.exs
- set correct log level for production
> set correct log level for production

- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/explorer/package-lock.json
Reverts poanetwork/blockscout#1517 due to
> Revert "fix bootstrap vulnerability"

- .circleci/config.yml
Make the test step sequential to resolve flaky build steps.
> Fix flaky tests

- apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/exchange_rates/token.ex
fixes https://github.com/poanetwork/blockscout/issues/1431
- disable usd value for an empty exchange rate
> disable usd value for an empty exchange rate

- apps/block_scout_web/assets/js/app.js
- apps/block_scout_web/assets/js/pages/admin/tasks.js
- apps/block_scout_web/lib/block_scout_web/admin_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/admin/tasks_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/admin/dashboard/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain/contract_method.ex
Resolves: #1502 	
* Add a "tasks" interface on the admin page, which can be leveraged for future requests of a similar nature.
* Add a task there for writing all contracts to the smart contract database.
> Create contract methods

- apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
- apps/block_scout_web/test/support/fixture/smart_contract/solc_bin.json
- apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
- apps/explorer/lib/explorer/smart_contract/verifier.ex
- apps/explorer/priv/compile_solc.js
- apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
resolves https://github.com/poanetwork/blockscout/issues/1541
- verify smart contracts with evm versions
> verify smart contracts with evm versions

- README.md
Relates to https://github.com/poanetwork/blockscout/pull/1572#issue-261495202
Add SpringChain to the list of Additional Chains Utilizing BlockScout in README
README Update
> Add SpringChain to the list of Additional Chains Utilizing BlockScout

- CHANGELOG.md
- CONTRIBUTING.md
We need to collect all updates into the release. It is hard to collect them at one time, keeping in mind that release can contain tens of PRs. To be sure that all updates are added to the release, it is suggested to update `CHANGELOG.md` with the description of update and the link to PR for each contribution.
- `CHANGELOG.md` is added with the description of `1.3.5` release.
- a step is added in `CONTRIBUTING.md`, where contributor should update `CHANGELOG.md` with every PR.
> Refine contributing procedure

- apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
> Added guard for fetching blocks with invalid number

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
- apps/indexer/lib/indexer/block/fetcher/receipts.ex
-  consider `creates` param when fetching transactions
> consider `creates` param when fetching transactions

- CHANGELOG.md
> 1.3.6 changelog update

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
- apps/indexer/config/dev.exs
- apps/indexer/config/prod.exs
- apps/indexer/config/test.exs
- apps/indexer/lib/indexer/address_extraction.ex
- apps/indexer/lib/indexer/block/supervisor.ex
- apps/indexer/lib/indexer/temporary/addresses_without_code.ex
- apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
- apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
- config/config.exs
fixes https://github.com/poanetwork/blockscout/issues/1389
> add process to fix contract with code

- CHANGELOG.md
> Update 1.3.7 changelog

- CHANGELOG.md
- apps/indexer/config/config.exs
- apps/indexer/lib/indexer/block/catchup/fetcher.ex
Resolves https://github.com/poanetwork/blockscout/issues/1598
- allow setting first indexing block
> allow setting first indexing block

- apps/block_scout_web/config/config.exs
Change other-explorers links for ETC
> Fix other explorers

- CHANGELOG.md
- apps/block_scout_web/config/config.exs
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
- apps/explorer/lib/explorer/chain/hash.ex
- apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
- apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
- apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
- apps/explorer/test/explorer/chain_test.exs
- apps/explorer/test/support/factory.ex
resolves https://github.com/poanetwork/blockscout/issues/1571
resolves https://github.com/poanetwork/blockscout/issues/1570
Example
set secret key
```
DECOMPILED_SMART_CONTRACT_TOKEN=123 iex -S mix phx.server
```
```
curl -v -X POST --header "AUTH_TOKEN: 123" http://localhost:4000/api/v1/decompiled_smart_contract\?address_hash=0x0\&decompiler_version=1\&decompiled_source_code=cat
```
> create decompiled smart contracts

- CHANGELOG.md
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/transaction_count_cache.ex
- apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
> add transaction count cache

- CHANGELOG.md
Fixate changes for release 1.3.8
> 1.3.8 release - update changelog

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address.ex
- apps/explorer/test/explorer/chain_test.exs
resolves https://github.com/poanetwork/blockscout/issues/1622
- add decompiled contract tab to address page
> tab for decompiled code

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/address.ex
- exclude decompiled smart contract from encoding
> exclude decompiled smart contract from encoding

- CHANGELOG.md
> finalize 1.3.9 release

- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/config/config.exs
Small coin customization for production-lukso branch
> Adopt BS for Lukso: customize coin

- CHANGELOG.md
- apps/block_scout_web/config/config.exs
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
The link in the footer is to unsupported telegram POA chatbox.
- Replace the link with the official POA announcements tg channel link
> (Fix) Update telegram link

- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/config/config.exs
> Aerum v1.3.9

- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/config/config.exs
Production branch of Callisto update. Adjusts coin display.
>  Callisto v1.3.9

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
Relates to https://github.com/poanetwork/blockscout/issues/1772
Update Github footer link to Blockscout repo
> Update link to the github repo in the footer

- CHANGELOG.md
- README.md
> Update README with the chains that use Blockscout

- CHANGELOG.md
- apps/block_scout_web/assets/css/_code.scss
fixes https://github.com/poanetwork/blockscout/issues/1794
- fix line numbers for decompiled contracts
> fix line numbers for decompiled contracts

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/block.ex
- apps/explorer/lib/explorer/chain/block_count_cache.ex
- apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
- apps/explorer/test/explorer/chain/block_count_cache_test.exs
- rel/commands/clear_build.sh
Closes https://github.com/poanetwork/blockscout/issues/1851
release 1.3.11 on LUKSO BS instance
> LUKSO 1.3.11

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/block.ex
- apps/explorer/lib/explorer/chain/block_count_cache.ex
- apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
- apps/explorer/test/explorer/chain/block_count_cache_test.exs
- rel/commands/clear_build.sh
Part of #1860
Release 1.3.11 on ETH Ropsten BS instance
> Ropsten v1.3.11

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/block.ex
- apps/explorer/lib/explorer/chain/block_count_cache.ex
- apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
- apps/explorer/test/explorer/chain/block_count_cache_test.exs
- rel/commands/clear_build.sh
Closes #1879.
Release 1.3.11 on ETH Rinkeby BS instance
> Rinkeby v1.3.11

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/block.ex
- apps/explorer/lib/explorer/chain/block_count_cache.ex
- apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
- apps/explorer/test/explorer/chain/block_count_cache_test.exs
- rel/commands/clear_build.sh
Closes #1882.
Release 1.3.11 on ETH Kovan BS instance
> Kovan v1.3.11

- README.md
*There has been confusion about where to run this command, some users have run from inside the apps/block_scout_web directory due to vague instructions.
* Updated README language
> add location clarification for mix phx.server command

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_tooltip.scss
- apps/block_scout_web/assets/css/theme/_lukso_variables.scss
We need to update _tooltip.scss and _lukso_variables.scss
> Dropdown color bug fix and tooltip color bug fix

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_button.scss
- apps/block_scout_web/assets/css/components/_modal.scss
Fixes https://github.com/poanetwork/blockscout/issues/1939
We need to update just components/_button.scss and components/_modal.scss
> QR modal button color issues

- apps/block_scout_web/assets/css/theme/_ether1_variables.scss
- apps/block_scout_web/assets/css/theme/_variables.scss
- apps/block_scout_web/assets/static/images/ether1_logo.svg
* add Ether-1 SVG logo
* add Ether-1 theme variables
> Add assets for Ether-1

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
- load data async on addresses page
> load data async on addresses page

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/async_listing_load.js
- apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- enable prev buttons for addresses page
- remove `JSON` parameter  when rendering a page
- hide navigation elements if a page has no items for all pages
> addresses page improvements

- CHANGELOG.md
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/js/lib/card_tabs.js
- apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_tabs.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
Closes #1995 
To fix when a second click to a selected tab causes the other tabs to hide.
- Fixed a bug triggered when a second click to a selected tab caused the other tabs to hide.
> (fix) wrong tabs behavior

- CHANGELOG.md
- apps/block_scout_web/config/dev.exs
Closes https://github.com/poanetwork/blockscout/issues/2004
> Use PORT env variable in dev config

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_dropdown.scss
We need to update _dropdown.scss
> Header nav. dropdown active element color issue

- CHANGELOG.md
we forgot to attach CHANGELOG entry for https://github.com/poanetwork/blockscout/pull/2012
- add CHANGELOG entry for async pagination
> add CHANGELOG entry for async pagination

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/mix.exs
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex
- apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
- apps/explorer/priv/repo/migrations/20190513134025_add_refetch_needed_to_block.exs
- apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
- mix.lock
A part of https://github.com/poanetwork/blockscout/issues/2057
> LUKSO 1.3.15

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_log-search.scss
We need to update _log-search.scss
> Fixed length of logs search input

- CHANGELOG.md
- docs/README.md
- docs/index.html
Resolves https://github.com/poanetwork/blockscout/issues/1968
Consolidation of docs for Blockscout project
- the static docs page generator is added
The page will be available in GitHub pages after merging
> Docsify integration: static docs page generation

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_footer.scss
Issue - https://www.loom.com/share/d1ac0f25b6124954929f65d62541e1fa
Now:
> Footer links and socials focus color issue

- CHANGELOG.md
- bin/install_chrome_headless.sh
CI is failing for the latest chromedriver version `75.0.3770.8`. So we should use the previous release
- change chromedriver version
> change chromedriver version

- CHANGELOG.md
- apps/indexer/lib/indexer/block/realtime/fetcher.ex
fixes https://github.com/poanetwork/blockscout/issues/2117
- fix map interpolation in the logger
> fix map logging

- .circleci/config.yml
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
fixes https://github.com/poanetwork/blockscout/issues/2122
introduced in https://github.com/poanetwork/blockscout/pull/1840
- fix coin percentage view
> fix coin percentage view

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination_container.html.eex
after https://github.com/poanetwork/blockscout/commit/e4c876d5529d3989232f263afafaa2abd5443a82 navigation was broken
- fix navigation
> fix navigation

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination_container.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/page_not_found/index.html.eex
> RSK 2.0.0 updates

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/assets/css/theme/_base_variables.scss
> Contract creation tile color changed

- CHANGELOG.md
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
> fix net version test

- docker/Dockerfile
> fix docker build error

- apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Parity changed an error message.
- fix parity test
> fix parity test

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/eth_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api_docs_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Waiting on: https://github.com/poanetwork/blockscout/pull/2146
* Displays the available endpoints and their notes on an api documentation page.
> feat: document eth rpc api mimicking endpoints

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_transaction.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
1) Changed design
2) Now we have only one button at the bottom
Now:
> New 'download csv' button design

- apps/block_scout_web/assets/css/theme/_variables.scss
- apps/block_scout_web/lib/block_scout_web/templates/active_pools/_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/inactive_pools/_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/validators/_table.html.eex
* Fixed error with importing POSDAO CSS variables
* Updated pagination's template name in the stakes' templates
> Replace posdao css variables by dai

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_stakes.scss
- apps/block_scout_web/assets/css/components/_stakes_table.scss
- apps/block_scout_web/assets/css/theme/_dai_variables.scss
- apps/block_scout_web/lib/block_scout_web/templates/active_pools/_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/inactive_pools/_table.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_table.html.eex
1) Added padding for pagination
2) Duplicated pagination to top
3) Changed white color to transparent white for stat borders at the top panel
4) Changed checkbox hover color at the table, checkbox color for banned rows
5) "Banned until block #345345 (15 May 2020)" aligned to the right
6) Theme colors issues (https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/348397546)
After:
> Staking page colors, gaps, and pagination issues

- apps/block_scout_web/assets/js/lib/modals.js
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/config/config.exs
- apps/block_scout_web/lib/block_scout_web/controllers/pools_controller.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/pools/_rows.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/pools/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
- apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex
- apps/block_scout_web/test/block_scout_web/controllers/pools_controller_test.exs
- apps/explorer/lib/explorer/staking/pools_reader.ex
#1709
**Merge after [PR#2221](https://github.com/poanetwork/blockscout/pull/2221)**
Added functionality to become a candidate
* Sending a transaction to become a candidate
* Prevalidation before sending a transaction
* Async updating of user data and pools list after success transaction
> Become a candidate

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_navbar.scss
> Header logo aligned to the center properly

- CHANGELOG.md
- bin/install_chrome_headless.sh
it looks like https://github.com/keathley/wallaby/issues/432 was fixed in chromedriver
- use the latest version of chromedriver
> use the latest version of chromedriver

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_modal_status.scss
- apps/block_scout_web/assets/css/theme/_dai_variables.scss
1) Checkbox color green instead of blue
2) Removed purple outline and border on input focus
3) Dark button in modal dialog instead of green
4) Border-radius issue in modal dialog
5) Success color changed to green instead of dark
After 3,4,5
6) Tooltips aligned properly to the center
> Staking colors issues, staking modal issues

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_network_selector.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Description for networks selector

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
As part of https://github.com/poanetwork/blockscout/pull/2193 some links in docs weren't fixed  
- remove port in docs
> remove port in docs

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_card.scss
- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
- apps/block_scout_web/assets/css/components/_stakes_table.scss
- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
- apps/indexer/config/dev/parity.exs
- apps/indexer/config/dev/rsk.exs
2.0.1+ (support of Nethermind)
> Rinkeby 2.0.1+

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
> Footer grid fix for md resolution

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_card.scss
- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
- apps/block_scout_web/assets/js/pages/chain.js
- apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/recent_transactions_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/test/support/conn_case.ex
- apps/block_scout_web/test/support/feature_case.ex
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/import/runner/transactions.ex
- apps/explorer/lib/explorer/chain/supply/rsk.ex
- apps/explorer/lib/explorer/chain/transactions_cache.ex
- apps/explorer/test/explorer/chain/supply/rsk_test.exs
- apps/explorer/test/explorer/chain/transactions_cache_test.exs
- apps/explorer/test/explorer/chain_test.exs
- apps/explorer/test/support/data_case.ex
- apps/indexer/lib/indexer/block/fetcher.ex
- apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Part of #2287 
POA Mainnet release v2.0.1
> Mainnet v2.0.1

- CHANGELOG.md
- apps/explorer/lib/explorer/market/market.ex
- apps/explorer/test/explorer/market/market_test.exs
fixes https://github.com/poanetwork/blockscout/issues/2339
- do not override existing market records
> do not override existing market records

- docs/ansible-deployment.md
- docs/env-variables.md
- docs/index.html
- docs/manual-deployment.md
Clarify deployment instructions
- Updated instructions and links to additional resources
- Added Note and Important highlights
- Additional spacing and text cleanup
> Updated deployment docs with additional information, styles, links

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/eth_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
- add parameters example for eth rpc
> add parameters example for eth rpc

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
part of https://github.com/poanetwork/blockscout/issues/2320
- add two columns of smart contract info
> add two columns of smart contract info

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_stakes_table.scss
- apps/block_scout_web/assets/css/components/_tile.scss
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/loaders/_table-loader.eex
- apps/block_scout_web/lib/block_scout_web/templates/loaders/_tile-loader.eex
- apps/block_scout_web/priv/gettext/default.pot
> Added templates for table loader and tile loader

- apps/block_scout_web/assets/js/app.js
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
- apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
- apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/channels/stakes_channel_test.exs
- apps/explorer/lib/explorer/chain/events/subscriber.ex
- apps/explorer/lib/explorer/staking/contract_state.ex
Top panel is entirely rendered on server-side using a dedicated controller function for proper gettext support and reduced fiddling with jQuery.
Reducer is simplified and made pure as per Redux guidelines.
> Refresh staking page top panel when new blocks arrive

- apps/indexer/config/config.exs
- apps/indexer/config/dev/geth.exs
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
-Reduce batch size and concurrency for internal transactions fetcher
-Increase memory limit and timeout for indexers
> Goerli 2.0.1+

- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/js/pages/stakes/become_candidate.js
- apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_empty_content.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Show "Become a Candidate" modal window

- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/js/pages/stakes/remove_pool.js
It's just a question and a simple contract call, actually.
> Show "Remove my Poll" modal window

- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/js/pages/stakes/make_stake.js
- apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_stake.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Show "Make Stake" modal window

- apps/block_scout_web/assets/css/components/_modal_bottom_disclaimer.scss
- apps/block_scout_web/assets/css/components/_modal_stake.scss
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/js/pages/stakes/move_stake.js
- apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_move.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
Modal window HTML is re-rendered each time target pool is changed.
> Show "Move Stake" modal window

- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js
- apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_withdraw.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_claim.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
If there is available ordered withdraw for claiming, we generate both withdraw and claim modal windows, and present user a question modal.
> Add "Withdraw stake" and "Claim withdraw" modal windows

- CHANGELOG.md
- docker/Dockerfile
- mix.exs
fixes https://github.com/poanetwork/blockscout/pull/2494
- use a major version of elixir
> use major version of elixir

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/supply/rsk.ex
- apps/explorer/test/explorer/chain/supply/rsk_test.exs
- fix rsk total supply for empty exchange rate
> fix rsk total supply for empty exchange rate

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
- apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs
- fix slash before not empty path in docs
> fix slash before not empty path in docs

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address_transaction_csv_exporter.ex
- do not fetch emission rewards for transactions csv exporter
> do not fetch emission rewards for transactions csv exporter

- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_title.html.eex
- apps/explorer/lib/explorer/chain.ex
> Implement filters for staking pool tables

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
@vbaranov  
Hello Victor. I've re-created this PR and closing #2673 with the same update, but with unresolved merge conflict. Finally, I've the resolved merge conflicts in my local repo, and will never push anything to master anymore:
:
Bug with dashboard banner must be resolved.
Fixed jumping bug with dashboard banner on main Blockscout page.
> Dashboard Banner Fix. 

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
@vbaranov 
Hello Victor.
I've fixed issue with dashboard-banner-chart-legend bottom items incorrect rendering.  
Changed display value for dashboard-banner-chart-legend class from flex to grid. Changed right padding for dashboard-banner-chart-legend-item. Chart legend Items should be rendered as it's expected now.
> Dashboard banner fix.

- apps/block_scout_web/assets/css/components/_card.scss
- apps/block_scout_web/assets/css/components/_stakes_table.scss
- apps/block_scout_web/assets/css/components/stakes/_stakes_empty_content.scss
- apps/block_scout_web/assets/js/lib/async_listing_load.js
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex
Some remain issues related to pool filters
https://github.com/poanetwork/blockscout/pull/2292#issuecomment-531745134
About 16.09.2019-3. "should be animation on items disappearing on Inactive pools table?"
- I can't reproduce an issue or not sure what part we talk about or @vbaranov
> Fix issues in Staking Dapp related to pool filters

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/cache/uncles.ex
- apps/explorer/lib/explorer/chain/import/runner/blocks.ex
- apps/explorer/test/explorer/chain/cache/uncles_test.exs
- apps/indexer/lib/indexer/block/fetcher.ex
- apps/indexer/lib/indexer/fetcher/uncle_block.ex
- apps/indexer/lib/indexer/temporary/uncles_without_index.ex
> Add cache for first page of uncles

- CHANGELOG.md
- README.md
Keep 1 version of docs for maintainability
- Removed project table and adding link to table in docs
*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or …
> Remove supported instances and link to doc version

- CHANGELOG.md
- README.md
- Update README to reflect current hosted chains
*If you have any Incompatible Changes in the above Changelog, outline how users of …
> update info and links

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/token_transfer.ex
Remove unused clause in  `address_to_unique_tokens` query
- fix address_to_unique_tokens query
> fix address_to_unique_tokens query

- .circleci/config.yml
- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/explorer/package-lock.json
- apps/explorer/package.json
Node js 12.13.0 (latest LTS release) support
- Upgrade of Circle CI images of Node js
- Upgrade of `keccak` and `node-saas` packages
> Node js 12.13.0 (latest LTS release) support

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/etherscan.ex
resolves https://github.com/poanetwork/blockscout/issues/2732
- add verify contract rpc doc
> add verify contract rpc doc

- apps/block_scout_web/assets/css/components/_dashboard-banner.scss
- apps/block_scout_web/assets/js/lib/market_history_chart.js
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
Closes https://github.com/poanetwork/blockscout/issues/2705
> Improve displaying of chart loading

- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/explorer/chain_test.exs
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
*If you have any Incompatible Changes in the above …
> Remove old internal transactions with the same primary key

- .circleci/config.yml
- CHANGELOG.md
Disable Parity WebSockets tests since we closed access to the archive node
Change circle CI config
> Disable Parity websockets tests

- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/import/runner/blocks.ex
- apps/explorer/test/explorer/chain_test.exs
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
optimize removal of pending ops
- remove pending ops on invalidation
> remove pending ops on invalidation

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
- apps/explorer/lib/explorer/chain/cache/address_sum.ex
- apps/explorer/test/explorer/chain/cache/address_sum_test.exs
- apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs
Reverts poanetwork/blockscout#2901
> Revert "fix address sum cache"

- apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
> Missing function clause for set_constructor_arguments

- .circleci/config.yml
- CHANGELOG.md
Upgrade Circle CI Postgres Docker image up to version `10.10`, that is used on hosted Blockscout instances.
> Upgrade Circle CI postgres Docker image

- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
Vulnerable NPM deps
Fix them with `npm audit fix`
> Fix vulnerable NPM deps

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/verification_form.js
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/poanetwork/blockscout/issues/2367
Refine UX of contracts verification
- Compiler nightly builds as an option
- Optimization is enabled by default
- Optimization runs are hidden if optimization is disabled
> Refine UX of contracts verification

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/router.ex
Continuation of https://github.com/poanetwork/blockscout/pull/2993
> Contract verification fix

- .circleci/config.yml
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- upgrade `node-sass` dependency to `4.13.1`
- upgrade npm version in CircleCI config to `12.15.0`
> npm audit fix

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/router.ex
Reverts poanetwork/blockscout#2999
> Revert "Contract verification fix"

- apps/block_scout_web/config/test.exs
This change fixes tests in master branch
> fix checksum redirect tests

- apps/indexer/config/dev/ganache.exs
- apps/indexer/config/dev/geth.exs
- apps/indexer/config/dev/parity.exs
- apps/indexer/config/dev/rsk.exs
- apps/indexer/config/prod/ganache.exs
- apps/indexer/config/prod/geth.exs
- apps/indexer/config/prod/parity.exs
- apps/indexer/config/prod/rsk.exs
Rename `ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT` env var to `ETHEREUM_JSONRPC_TRANSPORT`
> Rename ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT env var

- .dialyzer-ignore
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
- apps/explorer/config/config.exs
*If you have any Incompatible Changes in the above …
> Fix default values for ENV vars

- CHANGELOG.md
- apps/explorer/config/test.exs
- apps/explorer/config/test.secret.exs.example
> Support DB URL in test env

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
> Rescue for SUPPORTED_CHAINS env var parsing

- apps/explorer/config/config.exs
This config is not used anywhere.
> Remove unused index_internal_transactions_for_token_transfers config

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
- apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/recent_transactions_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/poanetwork/blockscout/issues/2970
BlockScout displays `Token Transfer` in tiles and transaction page even if it was minting or burning of a token.
Change the title of tile or transaction page in case of token burning/minting:
> Show proper title of the tile or container for token burnings/mintings instead of "Token Transfer"

- CHANGELOG.md
- apps/explorer/lib/explorer/smart_contract/reader.ex
Fixes https://github.com/poanetwork/blockscout/issues/3096
> Fix contract reader decoding

- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
> Update npm packages

- apps/explorer/priv/repo/migrations/20200521170002_create_token_transfers_token_contract_address_hash_token_id_block_number_index.exs
Addition to https://github.com/poanetwork/blockscout/pull/3119
Modified to DESC directions for block_number and token_id columns in index
> Modified direction in index

- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
https://github.com/poanetwork/blockscout/issues/3163
https://github.com/poanetwork/blockscout/pull/3174
> eip1967 update: handle different size response from eth_getStorageAt for implementation address

- .github/workflows/config.yml
- CHANGELOG.md
- README.md
- apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
https://github.com/poanetwork/blockscout/issues/3200
Not all current token balances are updated
Change clause to update current token balances in indexer: update also if inserting block number matches existed block number in DB and inserting value is not null and existed value_fetched_at is null
> Fix current token balances fetcher

- apps/block_scout_web/assets/js/lib/awesomplete-util.js
Searching contract/token by name now is a 3-step process:
- type part of the name/symbol
- select target contract in the appearing dropdown
- hit enter
This PR eliminates the last step.
https://www.loom.com/share/b0e91508163d4ef9bf3b50b26a521605
Open `/search?q=${address_hash}` page if target item is selected in dropdown
> Search tokens/contracts in one click

- .dialyzer-ignore
- .github/workflows/config.yml
- CHANGELOG.md
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/css/components/_external_link.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/config/config.exs
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/bridged_token.ex
- apps/explorer/lib/explorer/chain/token.ex
- apps/explorer/priv/repo/migrations/20200806125649_token_add_bridged_column.exs
- apps/explorer/priv/repo/migrations/20200807064700_bridged_tokens_table.exs
- apps/indexer/config/config.exs
- apps/indexer/lib/indexer/set_bridged_status_for_tokens.ex
- apps/indexer/lib/indexer/supervisor.ex
Distinguishing of bridged tokens from others
- `bridged` column is added to tokens table
- `bridged_tokens` table is created
```
CREATE TABLE public.bridged_tokens (
foreign_chain_id numeric NOT NULL,
foreign_token_contract_address_hash bytea NOT NULL,
home_token_contract_address_hash bytea NOT NULL,
inserted_at timestamp without time zone NOT NULL,
updated_at timestamp without time zone NOT NULL
);
```
- *SetBridgedStatusForTokens* indexer is added
- `MULTI_TOKEN_BRIDGE_MEDIATOR` environment variable is introduced. Providing this variable enables the aforementioned process and changes to tokens table view in order to display bridged status and to a token overview page in order to display link to the original token.
> Distinguish bridged tokens

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_verification_view.ex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/priv/repo/migrations/20200812143050_add_addresses_contract_code_index.exs
Resolves https://github.com/poanetwork/blockscout/issues/3181
Show metadata of verified contract at an unverified contract with the same bytecode and simplify verification of the latter.
- display the link to verified contract - twin (contract with the same bytecode)
- display metadata at an unverified contract page from verified twin
- show a notice to user about contract metadata is taken from twin
- automatically substitute values from the verified contract at the verification page of the unverified contract
- Verification form automatically fills with the metadata from the verified contract which has the same bytecode if any
> Easy verification of contracts which have verified twins (the same bytecode)

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/assets/css/theme/_dai_variables.scss
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tokens_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
xDai links, search hover color, "token is bridged" text, handle token name at token page if name/symbol is empty
> Style fixes

- CHANGELOG.md
- apps/ethereum_jsonrpc/config/config.exs
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case.ex
Finalization of https://github.com/poanetwork/blockscout/pull/3019
> Eliminate occurrences of obsolete env variable ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dai_variables.scss
Fix of https://github.com/poanetwork/blockscout/pull/3240 implementation
> xDai: do not apply link style for buttons

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/bridged_tokens_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/lib/block_scout_web/views/bridged_tokens_view.ex
- apps/block_scout_web/lib/block_scout_web/web_router.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
Extract bridged tokens to a separate table
> Bridged tokens table

- apps/block_scout_web/assets/css/theme/_dai_variables.scss
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
> Fix invisible token name at transfer page (xDai)

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
> Actualize names of default chains

- .github/workflows/config.yml
- .tool-versions
- CHANGELOG.md
- docker/Makefile
Elixir *1.10.4*
Docker Postgres image *12.4*
Node js *12.18.4*
> Fixate latest stable release of Elixir, Node, Postgres

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_navbar.scss
> Eliminate horizontal scroll

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_custom_tooltips.scss
- apps/block_scout_web/assets/css/components/_label.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
> Dark theme improvements

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/history_chart.js
> Chart smooth lines

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/assets/css/_code.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Fix mobile styles for contract code tab

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dai_variables.scss
> Fix xDai buttons hover color

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
https://github.com/poanetwork/blockscout/issues/2647
> Fix Staking dapp dark mode styles

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_card.scss
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/transfer/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Improve all lists header container

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/address.js
- apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
- apps/explorer/config/config.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/counters/address_gas_usage_counter.ex
Display total gas usage counter at address page
> Address total gas usage

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/css/theme/custom_contracts/_dark-forest-theme.scss
- apps/explorer/lib/explorer/chain/cache/gas_usage.ex
> Fix DF, night mode styles

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
- apps/explorer/lib/explorer/chain/transaction/history/historian.ex
- apps/explorer/lib/explorer/chain/transaction/history/transaction_stats.ex
- apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
- apps/explorer/lib/explorer/exchange_rates/source.ex
- apps/explorer/priv/repo/migrations/20201026093652_transactions_stat_add_gas_usage_column.exs
- apps/explorer/test/explorer/chain/transaction/history/historian_test.exs
- apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
Gather gas usage per day stats
> Collect and display gas usage per day at the main page

- .dialyzer-ignore
- CHANGELOG.md
- apps/explorer/lib/explorer/exchange_rates/source.ex
- apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
- apps/explorer/lib/explorer/known_tokens/source.ex
- apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
Blockscout can parse not all possible requests from CoinGecko which can cause application outage
Handle all available HTTP state codes in CoinGecko requests.
> Refactor Coingecko interaction

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_erc721_token_image_container.scss
- apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
- apps/block_scout_web/lib/block_scout_web/csp_header.ex
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/inventory_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/tokens/instance/overview_view_test.exs
https://github.com/poanetwork/blockscout/issues/3392
Add mp4 files support for NFTs
> Adding mp4 files support for NFTs

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_erc721_token_image_container.scss
- apps/block_scout_web/assets/css/components/_inventory_token_instance_image_container.scss
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tokens/inventory_view.ex
Support of mp4 media files at NFTs Inventory tab
> Inventory mp4 support

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
- apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
- apps/explorer/lib/explorer/chain.ex
Add read/write proxy tabs for Gnosis safe contracts
Extract implementation address which is stored in masterCopy storage pointer for Gnosis safe.
> Enable read/write proxy tabs for Gnosis safe proxy contract

- CHANGELOG.md
- docker/Makefile
Fixes #3436
Fixed postgres docker container.
Set the POSTGRES_HOST_AUTH_METHOD environment variable to trust on the postgres docker container so that it can run without any password.
> Fixed postgres docker container

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/js/lib/history_chart.js
> Dark mode color fixes (search, charts)

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
https://github.com/poanetwork/blockscout/issues/3488
Finalization of https://github.com/poanetwork/blockscout/pull/3494
> Fix tuple array output in contract interaction

- CHANGELOG.md
- apps/explorer/package-lock.json
- apps/explorer/package.json
Update `solc` npm package to the latest version
> Update solc version in explorer folder

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_card.scss
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Finalization of https://github.com/poanetwork/blockscout/pull/3507
> Finalize fixing tx mobile view: left margin

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Show total balance of Circles at Circles user account's address page
> CRC total balance

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/smart_contract/functions.js
Write contract page array input data processing still doesn't work for some cases.
> Finalize fixing write contract array input data processing

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
If DF contracts are not specified, DF theme applied to all address and transactions pages.
> Fix DF theme applying

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_custom_tooltips.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/js/pages/layout.js
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Add a keyboard shortcut to quickly focus on the search field.
Focus to search field with a forward slash key:
> Focus to search field with a forward slash key

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/stakes/_stakes-btn-close-alert.scss
- apps/block_scout_web/assets/css/stakes.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_learn-more.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
Add a link to learning resources related to Staking Dapp
> Staking welcome message

- apps/block_scout_web/assets/css/components/stakes/_stakes-btn-close-alert.scss
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_title.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_warning.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Staking Dapp warning message

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
- apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
Finalization of https://github.com/poanetwork/blockscout/pull/3592
> Fix contract reader

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
- apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
> Process :bool, :string types in contract together with  string representations

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_navbar.scss
Fix compressed top logo on some screen resolutions.
> Fix logo size

- CHANGELOG.md
- apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
Wrong price for SURF.Finance token at xDai
> Correct exchange rate for SURF.finance token

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
Current Twitter link goes to the wrong account
Change Twitter link to https://twitter.com/blockscoutcom
> Change Twitter handle

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/stakes/_stakes.scss
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_btn_external_link.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Add links to HoneySwap and Bridge from Staking Dapp
> Staking Dapp new buttons: swap, bridge

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_label.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
- apps/explorer/lib/explorer/chain.ex
> Display Sushiswap pools data

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_base_variables.scss
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/bridged_tokens_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/tokens_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_table-loader.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/bridged_tokens_view.ex
- apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
Show bridged tokens Tokens Locked Value in USD in bridged tokens table
> Bridged tokens TLV in USD

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Bridged status doesn't appear for some tokens bridged with Binance Smart Chain
> BSC bridged tokens detection fix

- CHANGELOG.md
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
Get different fixes from chain branches to master branch
> Miscellaneous minor fixes

- .github/workflows/config.yml
- .tool-versions
- CHANGELOG.md
Update `.tool-versions` to the latest versions of tools available
> Update tool versions

- CHANGELOG.md
- docker/Dockerfile
Run Docker setup on Elixir 1.11.3
> Update alpine-elixir-phoenix 1.11.3

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_info.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_minimal_proxy_pattern.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_learn-more.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/stakes/_warning.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
Resolves https://github.com/blockscout/blockscout/issues/3716
Missing Read/Write functionality for unverified contracts which follow minimal proxy contract pattern (EIP-1167)
> Minimal proxy pattern support (EIP-1167)

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
https://blockscout.com/xdai/mainnet/tx/0x99ac8deb9fdcaa762f6dfda7f666d782e36f15a09ad96174b3b8c8ff698806b4/internal-transactions
> Decoded contract method input tuple reader fix

- CHANGELOG.md
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
Update `fontawesome` NPM package to the latest version
> Update fontawesome NPM package

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- apps/block_scout_web/assets/package.json
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/mix.exs
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/lib/explorer/token/metadata_retriever.ex
- apps/explorer/mix.exs
- apps/explorer/package.json
- apps/indexer/README.md
Reflect changes in Github organization.
> Update repo organization

- apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_btn_copy.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_btn_qr_code.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_qr_code.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- Transaction page refactoring
- Create templates for copy / qr code buttons
> Tx page refactoring, copy/qr code buttons templates

- apps/indexer/lib/indexer/fetcher/token_balance.ex
> fix typo in doc: they -> them

- apps/block_scout_web/assets/js/lib/currency.js
- apps/explorer/lib/explorer/chain/supply/token_bridge.ex
- apps/explorer/lib/explorer/counters/bridge.ex
- total_coins_from_token_bridge -> get_total_coins_from_token_bridge
- total_coins_from_token_b -> total_coins_from_token_bridge
- return N/A usd value if input value isNaN or === '0'
- `if total_market_cap_from_omni do` -> `if Decimal.cmp(total_market_cap_from_omni, 0) == :gt do`
> Token bridge supply small refactoring

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_label.scss
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain/transaction.ex
Display decoded method name or method id, if decoding failed on tx tile
> Method name in tx tile

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_tile.scss
> Add left/right paddings in tx tile

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain/transaction.ex
> Do not display 4bytes signature in the tx tile for contract creation

- apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
Fixes https://github.com/blockscout/blockscout/issues/4145
> Coin balance history chart display fix

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/transaction/history/historian.ex
- apps/explorer/lib/explorer/chain/transaction/history/transaction_stats.ex
- apps/explorer/priv/repo/migrations/20210527093756_transaction_stats_add_total_fee_column.exs
- apps/explorer/test/explorer/chain/transaction/history/historian_test.exs
Add calculation of total fee to validators per day for future API endpoint
> Calculate total fee to validators per day

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Mobile view fix: transaction tile tx hash overflow

- .github/workflows/config.yml
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/etherscan.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
Resolves #3847 
- Added new api endpoint `api?module=contract&action=verify_via_sourcify`
Example of using this method (python3 script):
```
import requests
file_name_source = "contract.sol"
file_name_metadata = "metadata.json"
response = requests.post("https://blockscout.com/poa/sokol/api?module=contract&action=verify_via_sourcify", files=
{'files[0]':(file_name_source, open(file_name_source, 'rb'), 'application/json'),
'files[1]':(file_name_metadata,open(file_name_metadata, 'rb'), 'application/json')},
data={'addressHash':'0x0000000000000000000000000000000000000000'})
```
Response example:
```
{
"message": "OK",
"result": {
"ABI": "[{\n\"type\":\"event\",\n\"inputs\": [{\"name\":\"a\",\"type\":\"uint256\",\"indexed\":true},{\"name\":\"b\",\"type\":\"bytes32\",\"indexed\":false}],\n\"name …
```
> Add API endpoint: contract verification via Sourcify

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/token/search.js
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex
Close #4275 
- Fixed bug in updating list with the search results on `/tokens` page
> Fix token search

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4296 
- Contract Byte Code -> Deployed Contract Byte Code on contract's page.
- Added contract creation code field on contract's page.
> Add creation contract code

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- fix bug on `address/transaction` page for validators addresses
> Fix txs page for validators

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
Close #4344 
- Fix internal server error on raw-trace page for pending transaction
> fix raw trace bug

- CHANGELOG.md
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/assets/css/components/_search.scss
- apps/block_scout_web/lib/block_scout_web/templates/layout/_search.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Increase the visibility of search input field for mobile devices
> Place search outside of burger in mobile view

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/async_listing_load.js
- apps/block_scout_web/assets/js/pages/token_counters.js
- apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #862 
- Add live reload on the token holders page
> Token holders page: add live reload

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/blockscout/blockscout/issues/4365
> Add "Token ID" label onto token-trasfers page

- CHANGELOG.md
- apps/indexer/lib/indexer/pending_transactions_sanitizer.ex
Close #4427 
- Fix PendingTransactionsSanitizer for non-consensus blocks
> Complete fix pending sanitizer

- apps/block_scout_web/assets/js/lib/ad.js
- apps/block_scout_web/assets/js/lib/autocomplete.js
- apps/block_scout_web/assets/js/lib/text_ad.js
- apps/block_scout_web/assets/webpack.config.js
- apps/block_scout_web/lib/block_scout_web/templates/advertisement/text_ad/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
> In-house text ad

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/autocomplete.js
> Fix Cannot read property toLowerCase of undefined

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/assets/css/_mixins.scss
- apps/block_scout_web/assets/css/components/_btn_copy.scss
- apps/block_scout_web/assets/css/components/_i_tooltip.scss
- apps/block_scout_web/assets/css/components/_i_tooltip_2.scss
- apps/block_scout_web/assets/css/components/_label.scss
- apps/block_scout_web/assets/css/components/_transaction.scss
- apps/block_scout_web/assets/css/non-critical.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/js/lib/clipboard_buttons.js
- apps/block_scout_web/assets/js/lib/transaction_input_dropdown.js
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip_2.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_status_icon.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_total_transfers_from_to.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
- apps/explorer/lib/explorer/chain.ex
Make the transaction page more recognizable for most of the users.
> Tx page facelifting

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
- apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
- apps/explorer/lib/explorer/smart_contract/reader.ex
Close #4393 
- Added names to smart-contract's outputs
Before:
After:
> Added names to smart-contract's outputs

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_label.scss
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4490 
- Add `Position` field to the transaction's page
> Add transaction's index

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4502 
- Updated tooltips on transaction page
> Update txn page tooltips

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
- apps/explorer/config/dev/arbitrum.exs
- apps/explorer/config/prod/arbitrum.exs
- apps/explorer/config/test/arbitrum.exs
- apps/explorer/lib/explorer/chain.ex
- apps/indexer/config/dev/arbitrum.exs
- apps/indexer/config/prod/arbitrum.exs
- apps/indexer/config/test/arbitrum.exs
This adds basic support for Arbitrum
> Add arbitrum support

- apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
The contract verification controller takes the first json file it finds in the response from sourcify, whilst the application logic is expecting the format from the `metadata.json` file. This fails when there are multiple json files in the response and the wrong one is chosen (like from this contract https://repo.sourcify.dev/contracts/partial_match/42220/0x31EFa3ea696F91E751ec5fA6c93B876E7270D77B/)
This patch explicitly searches for a file named `metadata.json` in the sourcify response and processes that.
> Search for metadata.json file in sourcify response.

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/smart_contract/write.js
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
- Add step and min value for txValue input
- Fix js: fix bug with metamask which appears in case when aforementioned field is empty
> Add step and min value for txValue input

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4563 
- Add separator for contract function's outputs
> Fix solid outputs on contract read page

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_btn_no_border.scss
- apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Block Details page: Improved style of transactions button

- CHANGELOG.md
- apps/block_scout_web/assets/css/main-page.scss
Close #4604 
- Add `token_tile_view_more.css` to `the main-page.css`
> Add `token_tile_view_more.css` to the `main-page.css`

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Close #4504 
- Hide error selector in the contract's functions list
> Hide error selector in the contract's functions list

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_btn_no_border.scss
- Change alpha of transactions button's background
> Change alpha of transactions button's background

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4411 
- Add implementation link to the overview of proxy contracts
> Contract address page:  Add implementation link to the overview of proxy contracts

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4643 
- Convert Burnt Fee to ether and add price in USD
> Convert Burnt Fee to ether and add price in USD

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/etherscan.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
- apps/explorer/lib/explorer/chain/smart_contract.ex
- apps/explorer/lib/explorer/smart_contract/publisher.ex
- apps/explorer/priv/repo/migrations/20210916194004_add_file_path_for_sourcify_contracts.exs
Close #4651 
- Save Sourcify path instead of filename
- Add `FileName` field to the API response of `getsourcecode` method
> Add path for sources from sourcify

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_btn_no_border.scss
- apps/block_scout_web/assets/css/theme/_dark-theme.scss
Close #4666 
- Fix css for dark theme
> Fix css for dark theme

- apps/block_scout_web/assets/css/components/_transaction.scss
Closes #4670 
Removed duplicate entry for `.transaction-bottom-panel`
Removed duplicate entry for `.transaction-bottom-panel`
> fix duplicate entry

- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Fix token creation section on transaction overview page difference from other section.
> fix transaction overview token creation section

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4702 
In addition to the requirments in #4702, I've removed carryover of the phrase `Bridged from Ethereum`
> Top navigation: Move Accounts to Tokens

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4722 
- Fix hardcoded coin name on transaction's and block's page
> Fix hardcoded strings

- CHANGELOG.md
- apps/indexer/lib/indexer/empty_blocks_sanitizer.ex
Refactoring of empty blocks sanitizer
> Empty blocks sanitizer refactoring

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/etherscan.ex
- apps/block_scout_web/lib/block_scout_web/views/api/rpc/token_view.ex
- apps/block_scout_web/lib/block_scout_web/views/bridged_tokens_view.ex
- apps/explorer/lib/explorer/chain.ex
https://github.com/blockscout/blockscout/issues/4986
Add API endpoint which returns the list of the bridged tokens
The API endpoint as others is available through `/api-docs` playground in `Token` module.
Request URL example: `/api?module=token&action=bridgedTokenList&chainid=99&page=1&offset=1000`
Response example:
```
{
"message": "OK",
"result": [
{
"foreignChainId": "99",
"foreignTokenContractAddressHash": "0xd2cfbcdbdf02c42951ad269dcffa27c02151cebd",
"homeContractAddressHash": "0x9fe3864f9ae7cfb5668dae90c0e20c4c3d437664",
"homeDecimals": "18",
"homeHolderCount": "38",
"homeName": "Wrapped POA from POA",
"homeSymbol": "WPOA",
"homeTotalSupply": "1540909.647356829365428416",
"homeUsdValue": "0"
},
{
"foreignChainId": "99",
"foreignTokenContractAddressHash": …
```
> Bridged tokens list API endpoint

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Finalization of https://github.com/blockscout/blockscout/pull/4979
> address_to_gas_usage_count function fix for nil incoming transactions gas usage count

- CHANGELOG.md
- apps/block_scout_web/config/dev.exs
- apps/block_scout_web/config/prod.exs
- apps/block_scout_web/lib/block_scout_web/controllers/api/api_logger.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/supply_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
- apps/explorer/mix.exs
- config/config.exs
- mix.exs
> API endpoints logger

- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
Resolves https://github.com/blockscout/blockscout/issues/4967
> Resolve npm vulnerabilities via npm audix fix

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_navbar.scss
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Add capability to not provide logo in the header and footer.
> Capability to leave an empty logo

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/smart_contract/interact.js
Closes https://github.com/blockscout/blockscout/pull/5012
Finalization of https://github.com/blockscout/blockscout/pull/5012
> At contract write use wei precision

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address_token_transfer_csv_exporter.ex
- apps/explorer/lib/explorer/chain/token_transfer.ex
- apps/explorer/lib/explorer/paging_options.ex
- apps/explorer/test/explorer/chain/address_token_transfer_csv_exporter_test.exs
Close #5021 
- Add token-transfers bounding by date
- Fix csv-export pagination
> Fix token transfer csv export

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_table.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/search/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/search/results.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_token_icon.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Add separate column for token icons

- .dialyzer-ignore
- CHANGELOG.md
- apps/explorer/lib/explorer/smart_contract/reader.ex
- apps/explorer/test/explorer/smart_contract/reader_test.exs
Close #5062 #5064 
- Add additional check if method_id is not null
> Fix read contract page bug

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/search/_empty_td.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/search/_name_td.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/search/_tile.html.eex
> Refactor search page template

- CHANGELOG.md
- apps/explorer/package-lock.json
```
cd apps/explorer && npm install; cd -
up to date, audited 27 packages in 1s
2 packages are looking for funding
run `npm fund` for details
1 high severity vulnerability
```
> Resolve vulnerable npm dep in ./apps/explorer

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_token-balance-dropdown.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_token_icon.html.eex
> Fix wallet style

- apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
> Fix typo in layout_view_test.exs

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_pagination_container.scss
- apps/block_scout_web/assets/js/lib/random_access_pagination.js
- apps/block_scout_web/assets/js/pages/transactions.js
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/common_components/_rap_pagination_container.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
#4498 
- Add new type of pagination supported
- Adapted `async_lysting_load.js` to `random_access_pagination.js`
- New type of pagination launched on `/txs` page
In code '**rap**' means '**r**andom **a**ccess **p**agination'
Desktop view: 
Mobile view:
> Improve pagination

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Duplicate `<li>` in _topnav template
> Fix top navigation template

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
Inventory controller refactoring
> Inventory controller refactoring

- .github/workflows/config.yml
- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
webpack: `^5.44.0` -> `^5.67.0`
webpack-cli: `^4.7.2` -> `^4.9.2`
> Webpack minor update

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Replace Gitter link with Discord, Support -> Forum
> Discord link instead of Gitter

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
> Token price row name fix

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/stakes.js
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/webpack.config.js
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
> Fix Staking Dapp styles

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/decode_error.ex
> Hide request url in exceptions message

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
- apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
> Add empty view for new addresses

- CHANGELOG.md
- docker/Makefile
Docker setup Makefile improvements.
Add tasks for adding tags to Docker image, publishing of images to Docker hub
> Docker setup Makefile release/publish tasks

- docker-compose/docker-compose-no-build-geth.yml
1. Block Transformer should be clique in docker-compose of geth
> Block Transformer should be clique when using geth

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Close #5210 
- Drop gas_used from first_trace
> Drop gas_used from first_trace

- CHANGELOG.md
- apps/block_scout_web/assets/css/_code.scss
- apps/block_scout_web/assets/css/app.scss
- apps/block_scout_web/assets/css/components/_api.scss
- apps/block_scout_web/assets/css/components/_btn_add_to_mm.scss
- apps/block_scout_web/assets/css/components/_btn_swap.scss
- apps/block_scout_web/assets/css/components/_button.scss
- apps/block_scout_web/assets/css/components/_fontawesome_icon.scss
- apps/block_scout_web/assets/css/components/_verify_other_explorers.scss
- apps/block_scout_web/assets/css/export-vars-to-js.module.scss
- apps/block_scout_web/assets/css/main-page.scss
- apps/block_scout_web/assets/css/theme/_base_variables.scss
- apps/block_scout_web/assets/css/theme/custom_contracts/_circles-theme.scss
- apps/block_scout_web/assets/css/theme/custom_contracts/_dark-forest-theme.scss
- apps/block_scout_web/assets/js/lib/history_chart.js
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/block_scout_web/assets/webpack.config.js
https://github.com/blockscout/blockscout/issues/5168
Update `css-loader` NPM package 3 -> 5
> Major update of css-loader npm package

- CHANGELOG.md
- docker/Makefile
> Improve Docker Makefile: unify Blockscout docker image naming for all tasks

- .github/workflows/config.yml
- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Close #5215 
- Add accounting for block rewards in `getblockreward` api method
> Add accounting for block rewards in `getblockreward` api method

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
- apps/explorer/lib/explorer/chain.ex
Close #5247 
- Prevent flaky bug with absence primary names for contract; 
- Add fallback in case of absence primary name
> Fix bug with name absence for contract

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/smart_contract/helper.ex
- apps/explorer/test/support/factory.ex
Finalize https://github.com/blockscout/blockscout/pull/5248
> Fix verified smart-contract bytecode twins feature

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/tokens/instance/overview_view_test.exs
Finalizes https://github.com/blockscout/blockscout/pull/5296
> Token instance page: general video improvements

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Finalizes https://github.com/blockscout/blockscout/pull/5126
> Add specific tx receipt fields for the GoQuorum client

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Finalizes https://github.com/blockscout/blockscout/pull/5293
> Allow specific block keys for sgb/ava

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4928 
- Fix flash on reload in dark mode
> Fix flash on reload in dark mode

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_read_proxy_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_write_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/address_write_proxy_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/explorer/chain/log_test.exs
- apps/explorer/test/explorer/chain/transaction_test.exs
- apps/explorer/test/explorer/chain_test.exs
#5292 
- Add OpenZeppelin proxy storage slot
> Add OpenZeppelin proxy storage slot

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #5336 
- Specify general default parameter for `media_src`
> Fix 500 error on NF token page with nil metadata

- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
- apps/explorer/package-lock.json
npm audit reports vulnerability which can be fixed with `npm audit fix`
> Resolve Prototype Pollution in minimist dependency

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
- apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
Apply refactoring from the implementation of SourcifyFilePathBackfiller https://github.com/blockscout/blockscout/pull/5152
> Refactoring from SourcifyFilePathBackfiller

- CHANGELOG.md
- apps/indexer/lib/indexer/fetcher/pending_transaction.ex
Close #5308 
- Add case clauses
> Fix pending txs fetcher

- apps/explorer/lib/explorer/repo/config_helper.ex
> Fix typo in config_helper.ex

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/address/transactions.js
> Fix reload transactions button

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
> Fix Jason encode error

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
Add logging of errors in publishing of smart-contracts.
> Logging error in publishing of smart-contract

- CHANGELOG.md
- apps/indexer/lib/indexer/block/realtime/fetcher.ex
- apps/indexer/lib/indexer/fetcher/coin_balance.ex
Follow DRY principe in daily coin balance fetcher.
> Refactor daily coin balances fetcher

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
> Split long contract output to multiple lines

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
> Fix array displaying in decoded constructor args

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/etherscan/contracts.ex
Close #4566 
- Add name for the proxy implementation on address page
- Add name for contracts to logs on transaction page
> Add name for the proxy implementation on address page

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js
- apps/explorer/lib/explorer/smart_contract/reader.ex
- apps/explorer/test/explorer/smart_contract/reader_test.exs
> Fix params encoding for read contracts methods

- CHANGELOG.md
- apps/block_scout_web/config/config.exs
- apps/explorer/config/config.exs
- apps/indexer/config/config.exs
- apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Enhance config files for all applications a bit by removing repeating parts and defining variables for default values.
> Refactor config files

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
> Fix internal tx's tile bug

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/transaction.js
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/show_internal_transactions.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/show_token_transfers.html.eex
- apps/block_scout_web/lib/block_scout_web/views/tab_helpers.ex
- apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
Scroll to tab's data after clicking to the tab.
> Tx page: scroll to selected tab's data

- CHANGELOG.md
- apps/block_scout_web/assets/css/components/_dropdown.scss
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/_token_icon.html.eex
> Fix token dropdown

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/erigon.ex
- apps/explorer/config/dev/erigon.exs
- apps/explorer/config/prod/erigon.exs
- apps/explorer/config/test/erigon.exs
- apps/indexer/config/dev/erigon.exs
- apps/indexer/config/prod/erigon.exs
- apps/indexer/config/test/erigon.exs
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Erigon archive node type support
Support 
```
export ETHEREUM_JSONRPC_VARIANT=erigon
```
> Erigon archive node support

- CHANGELOG.md
- docker/Dockerfile
Closes https://github.com/blockscout/blockscout/pull/5542
Finalization of https://github.com/blockscout/blockscout/pull/5542
> Add jq to Dockerfile

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/resolvers/transaction.ex
- apps/block_scout_web/lib/block_scout_web/schema/scalars.ex
- apps/block_scout_web/lib/block_scout_web/schema/types.ex
- apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
- apps/explorer/lib/explorer/graphql.ex
- apps/explorer/test/explorer/graphql_test.exs
Closes https://github.com/blockscout/blockscout/pull/5345
Finalization of https://github.com/blockscout/blockscout/pull/5345 (rebase to masterb branch)
> graphql: add user-selected ordering to transactions for address

- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
Bump eth-net-props npm dependency
> Bump eth-net-props

- .github/workflows/publish-docker-image-every-push.yml
- .github/workflows/publish-docker-image-release.yml
- CHANGELOG.md
Add e2e tests + fix job "Merge 'master' to specific branch after release"
> Add e2e tests

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
Resolves https://github.com/blockscout/blockscout/issues/5735
Fix flickering tooltip
> Fix flickering token tooltip

- CHANGELOG.md
- docker-compose/docker-compose-no-build-ganache.yml
- docker-compose/docker-compose-no-build-geth.yml
- docker-compose/docker-compose-no-build-hardhat-network.yml
- docker-compose/docker-compose-no-build-no-db-container.yml
- docker-compose/docker-compose-no-build-open-ethereum-nethermind.yml
- docker-compose/docker-compose.yml
- docker/Makefile
Update Postgres version
Update Postgres version in Makefile for Docker setup and in docker-compose configs 13.6 -> 14
> Update target Postgres version in Docker: 13 -> 14

- CHANGELOG.md
- mix.exs
> Disable compile env validation

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/verification_form.js
Wrong behavior of verification page
- Fix nightly solidity versions filtering UX
> Fix nightly solidity versions filtering UX

- .github/workflows/config.yml
- CHANGELOG.md
- apps/block_scout_web/assets/js/view_specific/address_contract/code_highlighting.js
Resolves https://github.com/blockscout/blockscout/issues/5899
Fix ace editor appearance
Check if `#code_viewer_main` object exists before initializing ace editor.
> Fix ace editor appearance

- .github/workflows/config.yml
- CHANGELOG.md
- apps/block_scout_web/mix.exs
- bin/install_chrome_headless.sh
> Update chromedriver version

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/page_not_found/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/index.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/6008
> Hide copy btn if no raw trace

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/6007
> Fix address checksum on transaction page

- README.md
- config/runtime.exs
Added Blockscout Discord tag
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and …
> Discord badge and updated permalink

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
Close #5549 
- add missing preload
> Add preload for :created_contract_address

- CHANGELOG.md
- docker-compose/README.md
Add docker compose config for Erigon archive node
> Docker compose: add config for Erigon

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/smart_contract.ex
```
** (FunctionClauseError) no function clause matching in Explorer.Chain.SmartContract.merge_twin_vyper_contract_with_changeset/2
(explorer 4.1.8) lib/explorer/chain/smart_contract.ex:448: Explorer.Chain.SmartContract.merge_twin_vyper_contract_with_changeset(%Explorer.Chain.SmartContract{__meta__: #Ecto.Schema.Metadata<:loaded, "smart_contracts">, abi: [%{"inputs" => [], "payable" => false, "stateMutability" => "nonpayable", "type" => "constructor"}, %{"anonymous" => false, "inputs" => [%{"indexed" => true, "internalType" => "address", "name" => "owner", "type" => "address"}, %{"indexed" => true, "internalType" => "address", "name" => "spender", "type" => "address"}, %{"indexed" => false, "internalType" => "uint256", "name" => "value", "type" => "uint256"}], "name" => "Approval", "type" …
```
> Add missing clause for merge_twin_vyper_contract_with_changeset function

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
- config/runtime.exs
Finalization of https://github.com/blockscout/blockscout/pull/6155
> Fix runtime definition of ETHEREUM_JSONRPC_VARIANT variable

- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex
- apps/explorer/lib/explorer/chain.ex
`/blocks/`
`/blocks/{block_hash_or_number}`
`/blocks/{block_hash_or_number}/transactions`
> BS API V2: Blocks

- apps/block_scout_web/assets/css/theme/_dark-theme.scss
- apps/block_scout_web/assets/css/theme/_opcraft_variables.scss
- apps/block_scout_web/assets/js/lib/history_chart.js
- apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
> Fix opcraft style

- apps/indexer/lib/indexer/fetcher/token_instance.ex
- apps/indexer/lib/indexer/supervisor.ex
- config/runtime.exs
> Fix DISABLE_TOKEN_INSTANCE_FETCHER env

- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/config_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/models/get_address_tags.ex
- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/config_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/block_scout_web/lib/block_scout_web/views/block_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs
- apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
- apps/explorer/lib/explorer/account/tag_transaction.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/lib/explorer/chain/wei.ex
- apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex
- apps/explorer/lib/explorer/market/market.ex
- `/addresses/{address_hash}`
- `/addresses/{address_hash}/token-balances`
- `/addresses/{address_hash}/transactions`
- `/addresses/{address_hash}/token-transfers`
-  `/config/json-rpc-url`
- added tags for addresses and txs
- changed format of token info (added token name)
- transaction -> coin_transfer
- added `method` and `type` fields to the transaction body
- added `gas_limit` field for internal txs
- fix `block_type` in some cases
- changed type for returning big numbers to string
- changed token values to raw number with decimals
> BS core API V2: addresses + some fixes

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain.ex
Close #4564
Close #6220 
Close #6260 
- Add tooltip for unknown contract creator
- Checksum address in tx overview
- Fix search bug
> Fix UI bugs

- CHANGELOG.md
- apps/explorer/lib/explorer/smart_contract/rust_verifier_interface.ex
Finalization of https://github.com/blockscout/blockscout/pull/6133 (rebased original PR)
> Fix logger truncate rust verifier

- CHANGELOG.md
- apps/block_scout_web/assets/js/pages/address/logs.js
- apps/block_scout_web/lib/block_scout_web/templates/address_logs/index.html.eex
Fixes #6295 
- Fix double request
- Fix cancel search button
- Add dynamic search and search by enter
> Fix and refactor address logs page and search

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
> Fix transactions response

- .github/workflows/e2e-tests.yml
- .github/workflows/publish-docker-image-every-push.yml
- CHANGELOG.md
Fix errors in docker build and e2e tests workflows
> Fix docker build and e2e tests workflows

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controller.ex
Finalization of https://github.com/blockscout/blockscout/pull/6357
> Fix double slash in the path

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Close #4773
- move filtering to base_query
> Fix address logs search

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_yul_contracts_switcher.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_multi_part_files/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_write_contract/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_verification_via_flattened_code_view.ex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_verification_via_multi_part_files_view.ex
- apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/explorer/lib/explorer/chain/smart_contract.ex
- apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
- apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex
- apps/explorer/priv/repo/migrations/20221114113853_remove_not_null_constraint_from_abi.exs
- Add support for yul verification via rust microservice (required [smart-contract-verifier](https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier) >=5.0.0)
- Fix bug in `apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex`. Before fix was a problem on a contract details tab when contract creation bytecode disapeared after inserting creation internal transaction
- Delete unused and stale `contract-read-write.js` import
> Add support for yul verification via rust microservice

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
- apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
- apps/explorer/priv/repo/migrations/20221117075456_modify_address_token_balances_indexes.exs
- apps/explorer/priv/repo/migrations/20221117080657_modify_address_current_token_balances_indexes.exs
Related to https://github.com/blockscout/blockscout/pull/6476
> Fix token balances migrations

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_state/_state_change.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/transaction_state_controller_test.exs
Fix #6442 
Add handling of `nil` `address`  in template
Moved address hash from comment to `<tr>` tag attribute
> Fix state changes for contract creation transactions

- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/main_page_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/main_page_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- `/tokens/{address_hash}`
- `/tokens/{address_hash}/counters`
- `/tokens/{address_hash}/transfers`
- `/tokens/{address_hash}/holders`
- `/addresses/{address_hash}`
- `/addresses/{address_hash}/counter` - changed to plural
- `/main-page/indexing-status`
> BS core API V2: /tokens, /main-page/indexing-status

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
- apps/explorer/config/test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/log.ex
- apps/explorer/lib/explorer/chain/smart_contract.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/lib/explorer/etherscan/contracts.ex
- apps/explorer/lib/explorer/smart_contract/reader.ex
- apps/explorer/priv/repo/migrations/20220527131249_add_implementation_fields.exs
- apps/explorer/test/explorer/chain/smart_contract_test.exs
- apps/explorer/test/explorer/chain_test.exs
- config/runtime.exs
Close #5553 
`smart_contracts` table changes: 
- add implementation_address_hash
- add implementation_fetched_at
- Use changeset on updating implementation name to prevent rewrite the same name to the DB
- Add storing of the implementation address in DB
- Now we are waiting for `implementation_data_fetching_time_out` milliseconds to get implementation address from node and if no response then returning value from DB
- Add handling exception on invalid response from node
- Changed signature of `get_implementation_address_hash`, `proxy_contract?` and `get_implementation_address_hash`
- Aforementioned and some others method was moved to the `Explorer.Chain.SmartContract` module
> Improve working with contracts implementations

- CHANGELOG.md
- apps/explorer/priv/repo/migrations/20220919105140_add_method_id_index.exs
Close #6528 
- `CREATE` -> `CREATE IF NOT EXISTS`
> Fix index creation migration

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/priv/repo/migrations/20221126103223_add_txs_indexes.exs
Continuation of https://github.com/blockscout/blockscout/pull/6502
> Split ordering cases for txs

- apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
- apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
> Store ERC-721 token balances in aggregated form

- CHANGELOG.md
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
> Vacuum package-lock.json

- .github/workflows/publish-docker-image-every-push.yml
- CHANGELOG.md
Add latest image build for frontend-main with specific build-args (SESSION_COOKIE_DOMAIN)
> Add latest image for frontend-main

- apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
- Wrong h1 closing tag on api docs eth_rpc
> Fix wrong h1 closing tag

- apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
> Apply fix to tracer.js

- .github/workflows/config.yml
- apps/indexer/config/test.exs
> Decrease future_check_interval for tests

- CHANGELOG.md
- apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
- apps/indexer/test/indexer/block/catchup/fetcher_test.exs
> Fix MissingRangesCollector initial state

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- Add `/tokens`
- Add `/addresses`
> Add `/tokens` and `/addresses` endpoints

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
- Fix couple of internal server errors
> Fix bugs in smart contracts API v2

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/tokens.ex
> Fix tokens deadlock

- CHANGELOG.md
- docker/Dockerfile
Move the `jq` command to the real running image, fix the PR #5773
> Add `jq` in docker image

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/history_chart.js
- apps/block_scout_web/assets/js/pages/dark-mode-switcher.js
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/assets/package.json
- apps/block_scout_web/lib/block_scout_web/templates/csv_export/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/explorer/package.json
- config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/6718
With runtime ENV variable `PERMANENT_DARK_MODE_ENABLED=true` it is now possible.
Docs update https://github.com/blockscout/docs/pull/109.
> Permanent UI dark mode

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_tabs.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/lib/block_scout_web/views/nft_helpers.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/support/factory.ex
- Add endpoints:
- `/tokens/{address_hash}/instances`
- `/tokens/{address_hash}/instances/{token_id}`
- `/tokens/{address_hash}/instances/{token_id}/transfers`
- `/tokens/{address_hash}/instances/{token_id}/transfers-count`
- Change names of verification methods in `/smart-contracts/verification/config`
- Add `is_yul_contract` field to `/smart-contracts/verification/via/flattened-code`
> API v2: `/tokens/0x../instances`

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Close #5803 
Close #6822 
Repeat https://github.com/blockscout/blockscout/pull/6028 since this change was accidentally dropped
> Contracts interaction: from networkID to chainID for chain detection

- CHANGELOG.md
- apps/block_scout_web/assets/static/503.html
Update 503 page for Cloudflare
> Fix 503 page

- CHANGELOG.md
- apps/indexer/lib/indexer/transform/transaction_actions.ex
Previous code didn't properly handle incorrect Uniswap pool, so it led to fetcher work interruption.
> Fix pool checker in tx actions fetcher

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/transaction.ex
> Fix Internal Server Error on tx input decoding

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/autocomplete.js
Close #6939 
- Sanitize search query
> Sanitize search query before displaying

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
> Fix wss connect

- CHANGELOG.md
- apps/indexer/lib/indexer/fetcher/token_instance.ex
Resolves #6950 
Set `poll: true` for `Indexer.Fetcher.TokenInstance` so it poll for new records when all records are processed.
> Set poll: true for TokenInstance fetcher

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/csv_download.js
- apps/block_scout_web/assets/js/lib/dark_mode.js
- apps/block_scout_web/assets/package-lock.json
- apps/block_scout_web/lib/block_scout_web/templates/csv_export/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
reCAPTCHA doesn't apply dark mode, if it is enabled on the UI
> reCAPTCHA dark mode

- CHANGELOG.md
- apps/indexer/lib/indexer/fetcher/token_instance.ex
> Increase TokenInstance fetcher flush_interval

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Finalization of https://github.com/blockscout/blockscout/pull/6937
> Fix indexed_ratio_blocks

- CHANGELOG.md
- apps/block_scout_web/assets/js/lib/add_chain_to_mm.js
- apps/block_scout_web/assets/js/lib/autocomplete.js
- apps/block_scout_web/assets/js/lib/path_helper.js
- apps/block_scout_web/assets/js/pages/address/logs.js
- apps/block_scout_web/assets/js/pages/layout.js
- apps/block_scout_web/assets/js/pages/transaction.js
Finaliztion of https://github.com/blockscout/blockscout/pull/6954
> Update NETWORK_PATH env usage to use runtime env

- CHANGELOG.md
- docker/Dockerfile
Update bitwalker/alpine-elixir-phoenix: 1.13 -> 1.14
> Update bitwalker/alpine-elixir-phoenix: 1.13 -> 1.14

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/address/coin_balances_daily.ex
- apps/indexer/lib/indexer/block/realtime/fetcher.ex
> Fix updating coin balances with empty value

- CHANGELOG.md
- apps/block_scout_web/assets/js/socket.js
Use path_helper.js in order to define custom path
> Refactor socket.js

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/cldr_helper/number.ex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
Small refactoring: Use `alias BlockScoutWeb.Cldr.Number`
> Use alias BlockScoutWeb.Cldr.Number

- CHANGELOG.md
- apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Finalization of https://github.com/blockscout/blockscout/pull/7031
> fetch_json mock requests in tests

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex
> Deduplicate second degree relations before insert

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/authenticate_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/fallback_controller.ex
- config/runtime.exs
- Add  `/account/v1/authenticate`
- [docs PR](https://github.com/blockscout/docs/pull/125)
> Add authenticate endpoint 

- .github/workflows/publish-docker-image-every-push.yml
- .github/workflows/publish-docker-image-release.yml
- CHANGELOG.md
- docker/Dockerfile
Finalization of [#7119](https://github.com/blockscout/blockscout/pull/7119)
> Config helper path fix in docker container

- .github/workflows/e2e-tests.yml
- CHANGELOG.md
- docker-compose/docker-compose-no-rust-services.yml
- docker-compose/docker-compose.yml
`docker compose up --build` failed with:
```
blockscout               | {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Code.LoadError',file=><<"/app/releases/5.1.2/config_helper.exs">>,message=><<"could not load /app/releases/5.1.2/config_helper.exs. Reason: enoent">>,reason=>enoent},[{'Elixir.Code','find_file!',2,[{file,"lib/code.ex"},{line,1807}]},{'Elixir.Code',eval_file,2,[{file,"lib/code.ex"},{line,1184}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/5.1.2/runtime.exs"},{line,5}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,298}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,288}]},{'Elixir.Module.Paralle …
```
> Fix build from Dockerfile

- CHANGELOG.md
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Added one more error case for reorg block internal transactions requesting
> Add not found transaction error case

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_json/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_multi_part_files/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_standard_json_input/new.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/blockscout/blockscout/issues/7444
Navbar buttons are unresponsive on the verification form page.
> Resolve unresponsive navbar in verification form page

- CHANGELOG.md
- apps/explorer/lib/explorer/utility/missing_block_range.ex
- apps/indexer/lib/indexer/block/catchup/fetcher.ex
- apps/indexer/lib/indexer/block/catchup/missing_ranges_manipulator.ex
- apps/indexer/lib/indexer/block/catchup/supervisor.ex
- apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
- apps/indexer/test/indexer/block/catchup/fetcher_test.exs
Related to https://github.com/blockscout/blockscout/pull/7469
> Fix missing block ranges clearing

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_balances.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_beneficiaries.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_codes.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/trace_replay_block_transactions.ex
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Resolves #5726
Resolves https://github.com/blockscout/blockscout/issues/7211
> Handle empty id in json rpc responses

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Resolves https://github.com/blockscout/blockscout/issues/6711
> Fix created_contract_address_hash detection

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Reverts blockscout/blockscout#7598
> Revert "Fix created_contract_address_hash detection"

- CHANGELOG.md
- apps/explorer/priv/repo/migrations/20230606091935_fix_contract_creation_transactions.exs
Reverts data affected by https://github.com/blockscout/blockscout/pull/7598
> Fix contract creation transactions

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Add search by labels in the query
> Search label query

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/lib/block_scout_web/templates/verified_contracts/index.html.eex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
- apps/block_scout_web/lib/block_scout_web/views/verified_contracts_view.ex
- apps/block_scout_web/priv/gettext/default.pot
- apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/verified_contracts_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
Close #6460 
- Add yul filter for smart contracts list
- Add "language" field for single smart contract response, the same as for list smart contract response
> Add yul filter and "language" field for smart contracts

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex
Close #7730 
- Add search by public tag support to API v2 SearchView
> Add search by public tag support to API v2 SearchView

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
- apps/explorer/lib/explorer/tags/address_tag.ex
- apps/explorer/test/support/factory.ex
> Add test for label search

- CHANGELOG.md
- apps/indexer/config/dev/besu.exs
- apps/indexer/config/dev/erigon.exs
- apps/indexer/config/dev/nethermind.exs
- apps/indexer/config/dev/rsk.exs
- apps/indexer/config/prod/besu.exs
- apps/indexer/config/prod/erigon.exs
- apps/indexer/config/prod/nethermind.exs
- apps/indexer/config/prod/rsk.exs
Added missing `method_to_url` parameters for transactions tracing requests.
> Add missing method_to_url params for trace transactions

- CHANGELOG.md
- apps/indexer/test/indexer/block/catchup/missing_ranges_collector_test.exs
Related to https://github.com/blockscout/blockscout/pull/7724
> Fix missing ranges collector test

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
- Add /api/v1/health/liveness 
- Add /api/v1/health/readiness
> Add /api/v1/health/liveness and /api/v1/health/readiness

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/smart_contract.ex
Close #7818 
- Add logging for unknown error verification result
> Add logging for unknown error verification result

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/import_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/test/explorer/exchange_rates/token_exchange_rates_test.exs
- apps/explorer/test/support/factory.ex
Close #7795
- Add `is_smart_contract_verified` for contracts, addresses, labels and tokens
- Add `token_type`, `exchange_rate`, `total_supply` for tokens
- Add `timestamp` for transactions and blocks
> Search improvements: Add new fields, light refactoring

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/endpoint.ex
- apps/block_scout_web/lib/block_scout_web/plug/redis_cookie.ex
Close #7862 
- Add TTL for sessions
> Add TTL for account sessions

- CHANGELOG.md
- apps/indexer/lib/indexer/memory/monitor.ex
Finalization https://github.com/blockscout/blockscout/pull/7890
> Fix "Elixir.Indexer.Memory.Monitor",{{badkey,limit}

- .github/workflows/config.yml
- bin/install_chrome_headless.sh
Related to https://github.com/blockscout/blockscout/pull/7928
> Fix install chrome headless

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/rolling_window.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
- apps/indexer/lib/indexer/fetcher/block_reward.ex
Remove Logger requirements, where it is not used anymore.
> Small refactoring

- apps/indexer/lib/indexer/block/fetcher.ex
Remove withdrawals from coin balance request to decrease amount of requests
> Remove withdrawals from coin balance request

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/withdrawal.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/withdrawals.ex
- apps/explorer/priv/repo/migrations/20230801170524_withdrawals_from_gwei_to_mgno.exs
> Fix gwei to mGNO

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/schema/types.ex
https://github.com/blockscout/blockscout/issues/7976
extend GraphQL schema with new field for existing objects (address, block, transaction, internal transaction)
> GraphQL: extend schema with new fields for existing objects

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
Close #8117 
- Handle negative holders count: return 0 in case of negative count
> Handle negative holders count

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/indexer/lib/indexer/fetcher/token_balance.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
https://github.com/blockscout/blockscout/issues/8157
Import unfetched token balances during TokenBalanceOnDemand process as well
> Include unfetched balances in TokenBalanceOnDemand fetcher

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Related to https://github.com/blockscout/blockscout/pull/8158
> Remove query filters for TokenBalanceOnDemand fetcher

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
- apps/block_scout_web/lib/block_scout_web/endpoint.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
- apps/explorer/lib/explorer/chain/events/publisher.ex
- apps/explorer/lib/explorer/chain/events/subscriber.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
#8157 
- Now Indexer.Fetcher.TokenBalanceOnDemand sends batch requests
- Add broadcast of updated address_current_token_balances
>  Indexer.Fetcher.TokenBalanceOnDemand improvements

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/import_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/token.ex
- apps/explorer/priv/repo/migrations/20230809134253_add_is_verified_via_admin_panel.exs
- apps/explorer/test/support/factory.ex
Сlose #8155 
Сlose #8138 
- Add `is_verified_via_admin_panel` field to `tokens` table
- Add `is_verified_via_admin_panel` field to API v2 search response 
- Add sorting by aforementioned new field in search
> Add is_verified_via_admin_panel property to tokens table

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/explorer/lib/explorer/chain/address/counters.ex
Close #8136 
- Add `/api/v2/addresses/:address_hash/tabs-counters`
> API v2: Add tabs counters endpoint

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
Closes #8219 
- Fix address encoding
> Fix API v2 broken tx response

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/withdrawal_controller.ex
- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
Close #8239 
- Refactor and fix paging params in API v2
> Refactor and fix paging params in API v2

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs
- apps/explorer/lib/explorer/chain/smart_contract.ex
- apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
- apps/explorer/lib/explorer/smart_contract/solidity/publisher_worker.ex
- apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex
- apps/explorer/lib/explorer/smart_contract/vyper/publisher_worker.ex
Resolves https://github.com/blockscout/blockscout/issues/7985
Scarce logging on the backend side in the process of smart-contract verification.
Add step-by-step logging of the sc verification process between the sending request to the microservice and broadcasting results of verification.
> API v2 smart-contract verification extended logging

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- Add ranking of NFTs to the Indexer.Fetcher.TokenInstance.Retry
> Add ranking of NFTs to the Indexer.Fetcher.TokenInstance.Retry

- CHANGELOG.md
- docker/Dockerfile
```
/bin/sh: curl: not found
```
in the resulting image
Add curl into 2nd stage of multi-stage building of Docker image.
> Add curl into resulting Docker image

- .tool-versions
- apps/explorer/lib/explorer/chain/search.ex
> Fix merge branch artifacts

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/priv/repo/migrations/20230831122819_drop_current_token_balances_tokens_foreign_key.exs
Drop address_current_token_balances tokens foreign-key for performance reasons and to prevent deadlocks.
> Drop current token balances tokens foreign key

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/robots_controller.ex
- apps/block_scout_web/lib/block_scout_web/endpoint.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/templates/robots/robots.txt.eex
- apps/block_scout_web/lib/block_scout_web/templates/robots/sitemap.xml.eex
- apps/block_scout_web/lib/block_scout_web/views/robots_view.ex
- apps/explorer/lib/explorer/chain.ex
- cspell.json
Close #8334 
- update `/robots.txt`
- add `/sitemap.xml`
> Add sitemap.xml

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/address/token_balance.ex
- apps/explorer/priv/repo/migrations/20230905085809_drop_token_balances_tokens_foreign_key.exs
Related to https://github.com/blockscout/blockscout/pull/8362
> Drop token balances tokens foreign key

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- CHANGELOG.md
> New issue template

- .github/ISSUE_TEMPLATE/config.yml
- CHANGELOG.md
Finalization of https://github.com/blockscout/blockscout/pull/8536
> Disable blank issues creation

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Finalization of https://github.com/blockscout/blockscout/pull/8536
Apply new issue template to the footer
> Apply new issue template to the footer

- CHANGELOG.md
- apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
- apps/explorer/lib/explorer/market/history/cataloger.ex
- apps/explorer/lib/explorer/market/history/source/market_cap.ex
- apps/explorer/lib/explorer/market/history/source/market_cap/coin_gecko.ex
- apps/explorer/lib/explorer/market/history/source/market_cap/coin_market_cap.ex
- apps/explorer/lib/explorer/market/history/source/price/coin_gecko.ex
- apps/explorer/lib/explorer/market/history/source/price/crypto_compare.ex
- apps/explorer/test/explorer/market/history/cataloger_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8560
Get historical market data for native coin from CoinGecko API
> Get historical market cap data from CoinGecko

- CHANGELOG.md
- apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
- apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
Adjustment to https://github.com/blockscout/blockscout/pull/8561
> Coin id definition fix

- CHANGELOG.md
- docker-compose/docker-compose-no-build-erigon.yml
- docker-compose/docker-compose-no-build-external-backend.yml
- docker-compose/docker-compose-no-build-external-frontend.yml
- docker-compose/docker-compose-no-build-ganache.yml
- docker-compose/docker-compose-no-build-geth-clique-consensus.yml
- docker-compose/docker-compose-no-build-geth.yml
- docker-compose/docker-compose-no-build-hardhat-network.yml
- docker-compose/docker-compose-no-build-nethermind.yml
- docker-compose/docker-compose-no-build-no-db-container.yml
- docker-compose/docker-compose.yml
- docker-compose/envs/common-blockscout.env
- docker-compose/services/docker-compose-backend.yml
- docker-compose/services/docker-compose-db.yml
- docker-compose/services/docker-compose-frontend.yml
- docker-compose/services/docker-compose-nginx.yml
- docker-compose/services/docker-compose-redis.yml
- docker-compose/services/docker-compose-sig-provider.yml
- docker-compose/services/docker-compose-smart-contract-verifier.yml
- docker-compose/services/docker-compose-stats.yml
- docker-compose/services/docker-compose-visualizer.yml
Resolves https://github.com/blockscout/blockscout/issues/7837
- run DBs (blockscout/stats) via non-root user: add db init container wich changing owner of the db folder to the user with id 2000
- add DBs (blockscout/stats) healthcheck
- add custom users to DBs (blockscout/stats)
- Add new frontend and microservices build to docker-compose/docker-compose-no-build-erigon.yml
> Refactor docker-compose config

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
> Fix `nil` `"structLogs"`

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/nft_helper.ex
Finalization of https://github.com/blockscout/blockscout/pull/8579
> Public IPFS gateway URL for frontend

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/polygon_tracer.ex
Close #8485
Fix #8241  
- Add fallback to 0 in case of `nil` `input_length`
- Add handling of additional fields in stack
> Fix polygon tracer

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
Close #8497 
- Fix is_verified for /addresses and /smart-contracts
> Fix is_verified for /addresses and /smart-contracts

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/import_controller.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/import_controller_test.exs
Close #8691
- Support `tokenSymbol` and `tokenName` in `/api/v2/import/token-info`
> Support tokenSymbol and tokenName in /api/v2/import/token-info

- CHANGELOG.md
- apps/explorer/lib/explorer/smart_contract/solidity/publish_helper.ex
Close #8675
Close #8697 
- Fix sourcify enabled flag
> Fix sourcify enabled flag

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
- apps/explorer/lib/explorer/chain/log.ex
- apps/explorer/lib/explorer/chain/token.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/lib/explorer/helper.ex
Close #8650 
- add `stability_fee` field to tx response:
```
"stability_fee": {
"dapp_address": {
"hash": "0xafa081C766383bAbdAC47AE46394423541606561",
"implementation_name": null,
"is_contract": false,
"is_verified": null,
"name": null,
"private_tags": [],
"public_tags": [],
"watchlist_names": []
},
"dapp_fee": "0",
"token": {
"address": "0xDc2B93f3291030F3F7a6D9363ac37757f7AD5C43",
"circulating_market_cap": null,
"decimals": "18",
"exchange_rate": null,
"holders": "10",
"icon_url": null,
"name": "Stability Gas",
"symbol": "GAS",
"total_supply": "10000000000000000000000000",
"type": "ERC-20"
},
"total_fee": "0",
"validator_address": {
"hash": "0x59024dD6932bbbBCEAb416873874d733D5B3A84C",
"implementation_name": null,
"is_contract": false,
"is_verified": null,
"name": null,
"private_tags": …
```
> Add stability_fee for CHAIN_TYPE=stability

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
Close #8663 
- Add address name updating on contract re-verification
> Add address name updating on contract re-verification

- CHANGELOG.md
- apps/explorer/test/explorer/account/notifier/notify_test.exs
> Fix flaky account notifier test

- CHANGELOG.md
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Related to https://github.com/blockscout/blockscout/pull/8695
> Fix internal transaction error

- CHANGELOG.md
- apps/explorer/lib/explorer/token_instance_owner_address_migration/supervisor.ex
- apps/explorer/lib/explorer/token_instance_owner_address_migration/worker.ex
- config/runtime.exs
Close #8729 
- Add `TOKEN_INSTANCE_OWNER_MIGRATION_ENABLED` env
https://github.com/blockscout/docs/pull/193
> Add TOKEN_INSTANCE_OWNER_MIGRATION_ENABLED env

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/chain.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- apps/explorer/config/test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/lib/explorer/chain/token/instance.ex
- apps/explorer/lib/explorer/helper.ex
- apps/explorer/test/support/factory.ex
Close #8231 
- Add filter to `/api/v2/tokens/{address_hash}/instances?holder_address_hash={holder_address}`
- Add `/api/v2/addresses/{address_hash}/nft` and `/api/v2/{address_hash}/nft/collections`
> API v2: address nft

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/ethereum_jsonrpc/config/runtime/test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/indexer/lib/indexer/fetcher/optimism.ex
- apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
- apps/indexer/lib/indexer/fetcher/optimism_output_root.ex
- apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
- apps/indexer/lib/indexer/fetcher/optimism_withdrawal.ex
- apps/indexer/lib/indexer/fetcher/optimism_withdrawal_event.ex
- apps/indexer/lib/indexer/fetcher/polygon_edge.ex
- apps/indexer/lib/indexer/helper.ex
- apps/indexer/test/indexer/block/realtime/fetcher_test.exs
This is complete change for the issue mentioned in https://github.com/blockscout/blockscout/pull/8822
> Return all OP Withdrawals bound to L2 transaction

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
Since `eth_call` timeouts are common, it's reasonable to disable incrementing error counter for them so other requests won't be affected.
> Disable error counter for eth_call

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/authenticate_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/email_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/fallback_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/tags_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/user_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
- apps/block_scout_web/lib/block_scout_web/views/account/api/v2/account_view.ex
- apps/block_scout_web/lib/block_scout_web/views/account/api/v2/tags_view.ex
- apps/block_scout_web/lib/block_scout_web/views/account/api/v2/user_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
Complete migration to account v2 paths
- Remove /api/account/v1 path
> Remove /api/account/v1 path

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/geth/mox.ex
Resolves https://github.com/blockscout/blockscout/issues/8920
Handle lowercase call type as well.
> Allow call type to be in lowercase

- CHANGELOG.md
- apps/explorer/lib/explorer/token_instance_owner_address_migration/helper.ex
- Token Instance Owner migration stopped on some instances
- Skip failed instances
> Skip failed instances

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/notifier.ex
Refactor transactions preloads to use one db query instead of multiple
> Refactor transactions event preloads

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/application.ex
- apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
- apps/block_scout_web/lib/block_scout_web/smart_contract_realtime_event_handler.ex
Resolves https://github.com/blockscout/blockscout/issues/8913
> Add SmartContractRealtimeEventHandler

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/token/instance.ex
- apps/explorer/test/explorer/chain_test.exs
Closes #8995 
- Optimize NFT owner preload
> Optimize NFT owner preload

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
- apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex
Closes #8385 
Closes #7655
- Handle Postgrex errors on NFT import
> Handle Postgrex errors on NFT import

- CHANGELOG.md
- apps/indexer/lib/indexer/block/fetcher.ex
- apps/indexer/lib/indexer/transform/token_transfers.ex
Related to https://github.com/blockscout/blockscout/pull/6893
Update existing tokens with a higher priority type from its transfers
> Update existing tokens type if got transfer with higher type priority

- .dialyzer-ignore
- .github/workflows/config.yml
- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
- apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
- apps/indexer/lib/indexer/fetcher/optimism_withdrawal.ex
- apps/indexer/test/indexer/block/realtime/fetcher_test.exs
- cspell.json
Relates to https://github.com/blockscout/blockscout/pull/9000.
> Fixes in Optimism due to changed log topics type

- .dialyzer-ignore
- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/indexer/lib/indexer/fetcher/polygon_edge/deposit_execute.ex
- apps/indexer/lib/indexer/fetcher/polygon_edge/withdrawal.ex
Small but important fixes for log topics handling for Suave and Polygon Edge modules. Relates to https://github.com/blockscout/blockscout/pull/9000.
> Fix some log topics for Suave and Polygon Edge

- CHANGELOG.md
- apps/explorer/lib/explorer/etherscan.ex
Add filter by `block_hash is not null` to support previous inner join with blocks logic
> Add missing filter to txlist query

- CHANGELOG.md
- apps/explorer/lib/explorer/market/history/cataloger.ex
- config/runtime.exs
> Add `MARKET_HISTORY_FETCH_INTERVAL` env

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
- apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
- apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
- apps/explorer/lib/explorer/exchange_rates/token.ex
- apps/explorer/lib/explorer/helper.ex
- apps/explorer/lib/explorer/market/market.ex
- apps/explorer/lib/explorer/market/market_history_cache.ex
- apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
- apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
- apps/explorer/test/support/fakes/one_coin_source.ex
Resolves https://github.com/blockscout/blockscout/issues/9025
Cache native coin image together with price.
Save native coin image from CoinGecko API to ETS.
> Fetch token image from CoinGecko

- CHANGELOG.md
- apps/block_scout_web/.sobelow-conf
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/utils_controller.ex
- apps/block_scout_web/lib/block_scout_web/utils_api_v2_router.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/utils_controller_test.exs
Close #9033 
- Add `/api/v2/utils/decode-calldata` endpoint
> Add /api/v2/utils/decode-calldata endpoint

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/token/instance.ex
Close #9179 
- Fix Internal Server Error on request for nonexistent token instance
> Fix 500 response on token id which is not in DB

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/account_abstraction_controller.ex
`is_verified` is null for `entry_point`:
https://eth-goerli.blockscout.com/api/v2/proxy/account-abstraction/operations/0x7b19441a9390fea80cb8ca96a1e32890f016d1e519a858b12a901d537df562bf
- Add smart contract and names preload
> Add smart contract and names info to AA response

- .github/actions/setup-repo-and-short-sha/action.yml
- .github/actions/setup-repo/action.yml
- .github/workflows/config.yml
- .github/workflows/prerelease.yml
- .github/workflows/publish-docker-image-every-push.yml
- .github/workflows/publish-docker-image-for-core.yml
- .github/workflows/publish-docker-image-for-eth-goerli.yml
- .github/workflows/publish-docker-image-for-eth-sepolia.yml
- .github/workflows/publish-docker-image-for-eth.yml
- .github/workflows/publish-docker-image-for-filecoin.yml
- .github/workflows/publish-docker-image-for-fuse.yml
- .github/workflows/publish-docker-image-for-gnosis-chain.yml
- .github/workflows/publish-docker-image-for-immutable.yml
- .github/workflows/publish-docker-image-for-l2-staging.yml
- .github/workflows/publish-docker-image-for-lukso.yml
- .github/workflows/publish-docker-image-for-optimism.yml
- .github/workflows/publish-docker-image-for-polygon-edge.yml
- .github/workflows/publish-docker-image-for-rootstock.yml
- .github/workflows/publish-docker-image-for-stability.yml
- .github/workflows/publish-docker-image-for-suave.yml
- .github/workflows/publish-docker-image-for-zkevm.yml
- .github/workflows/publish-docker-image-for-zksync.yml
- .github/workflows/publish-docker-image-staging-on-demand.yml
- .github/workflows/release-additional.yml
- .github/workflows/release.yml
- CHANGELOG.md
Github actions workflows use equal steps to setup repo and those steps are repeated in the each workflow.
Extract configuration of repo steps in the workflows into separate file.
> Create repo setup actions

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/explorer/lib/explorer/account/notifier/summary.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/csv_export/address_token_transfer_csv_exporter.ex
- apps/explorer/lib/explorer/chain/csv_export/address_transaction_csv_exporter.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/lib/explorer/chain/transaction/state_change.ex
- apps/explorer/test/explorer/account/notifier/notify_test.exs
- apps/explorer/test/explorer/account/notifier/summary_test.exs
- apps/explorer/test/explorer/chain_test.exs
Close #9298
- Add fallback effective gas price calculation
> Add fallback effective gas price calculation

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
- apps/indexer/lib/indexer/fetcher/internal_transaction.ex
- cspell.json
Resolves https://github.com/blockscout/blockscout/issues/9368
Docs update: https://github.com/blockscout/docs/pull/236
> Filter non-traceable transactions for zetachain

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/bridged_token.ex
We do not filter out empty values before token update
> Filter empty values before token update

- .github/workflows/config.yml
- CHANGELOG.md
* Bump cache action in CI to fix the deprecation warnings
> chore: bump actions/cache to v4

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex
- apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex
- Do not send a request to Solidityscan API, if SOLIDITYSCAN_CHAIN_ID or SOLIDITYSCAN_API_TOKEN is empty.
- Do not send a request to Solidityscan API, if the smart contract is not verified.
> Solidityscan integration enhancements

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/search.ex
> Fix quick search bug

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/blob_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/blob_view.ex
* Show proper not found view for unknown blob hashes
> Fix not found page for unknown blobs

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/address/counters.ex
- apps/explorer/lib/explorer/chain/cache/addresses_tabs_counters.ex
Closes #8952 
- Refactor code and eliminate the bug
> Fix tabs counter cache bug

- CHANGELOG.md
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
Closes #9341 
- Fix decoding error in `format_args/2` (`apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex`)
> Fix no function clause matching in Integer.parse/2

- CHANGELOG.md
- apps/explorer/priv/repo/migrations/20240227115149_add_smart_contracts_name_text_index.exs
Reduced search performance after filling DB with a numerous smart contracts
- Add tsvector index on smart_contracts.name
> Add tsvector index on smart_contracts.name

- CHANGELOG.md
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
- apps/explorer/lib/explorer/smart_contract/helper.ex
- apps/explorer/lib/explorer/smart_contract/reader.ex
Closes #9175.
Regression test for Bug fix
> Fix duplicate read methods

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transport.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket.ex
- apps/explorer/lib/explorer/graphql.ex
> chore: remove repetitive words

- CHANGELOG.md
- apps/explorer/lib/explorer/chain/block/second_degree_relation.ex
> chore: fix some comments

- CHANGELOG.md
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/smart_contract.ex
Finalization of https://github.com/blockscout/blockscout/pull/9518
> Find a single creation tx for smart-contract

- README.md
> chore: Bump floki from 0.36.0 to 0.36.1

- CHANGELOG.md
- README.md
- cliff.toml
> feat: Super-mega-important-feature

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/_card_body.html.eex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
- apps/explorer/lib/explorer/access_helper.ex
- apps/explorer/lib/explorer/account/custom_abi.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/bridged_token.ex
- apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
- apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
- apps/explorer/lib/explorer/chain/search.ex
- apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
- apps/explorer/lib/explorer/tags/address_to_tag.ex
- apps/explorer/lib/explorer/token/balance_reader.ex
- apps/indexer/lib/indexer/block/fetcher.ex
- apps/indexer/lib/indexer/fetcher/beacon/client.ex
- apps/indexer/lib/indexer/fetcher/polygon_zkevm/bridge.ex
- apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
- apps/indexer/lib/indexer/transform/transaction_actions.ex
Enhance Enum usage could gain performance hits for example `!Enum.empty?(list)` has a constant time.
Improve Enum usage
> refactor: `Enum.count` to `Enum.empty?`

- CHANGELOG.md
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/notifier.ex
- apps/explorer/lib/explorer/chain.ex
Closes #9402 
Closes #8839 
- Add missing preloads
- Refactor `flat_1155_batch_token_transfers/2`
> fix: Add missing preloads

- apps/block_scout_web/lib/block_scout_web.ex
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/csv_export_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/rpc/token_view.ex
- apps/block_scout_web/lib/block_scout_web/views/currency_helper.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
- apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
- apps/block_scout_web/test/block_scout_web/views/currency_helper_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/lib/explorer/chain/csv_export/helper.ex
- apps/explorer/lib/explorer/chain/currency_helper.ex
- apps/explorer/test/explorer/chain/currency_helper_text.exs
Closes #9580 
- Add /api/v2/tokens/:address_hash_param/holders/csv endpoint
> feat: Add /api/v2/tokens/:address_hash_param/holders/csv endpoint

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/account_abstraction_controller.ex
- apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
Support for fields introduced in https://github.com/blockscout/blockscout-rs/pull/817
> feat: support for internal user operation calldata decoded by microservice

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
> fix: Apply quantity_to_integer/1 to effectiveGasPrice

- apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
- apps/explorer/lib/explorer/utility/address_contract_code_fetch_attempt.ex
- apps/explorer/test/support/fixture/smart_contract/ERC677.sol
> chore: fix some typos in comments

- apps/explorer/lib/explorer/account/notifier/summary.ex
In the 1st token transfer token has no metadata yet. If the participated in the token transfer address hash is in the watchlist, then an email about the token transfer will be sent without taking into account decimals and token ticker.
This PR mitigates uncertainty in the email:
- displays "Unknown" instead of empty ticker
- fixes decimals divider: before this change in the mentioned case, we divided the number of tokens to 10. With this PR: to 1.
> chore: Improve email template for token transfer without token metadata (ticker, decimals)

- apps/indexer/lib/indexer/memory/monitor.ex
Related to https://github.com/blockscout/blockscout/pull/9870
> fix: Expand memory only if it was shrunk

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
> fix: `coin_price_change_percentage` calculation

- apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex
- apps/explorer/test/explorer/chain/cache/gas_price_oracle_test.exs
Fix #9942
Omit the limit and use `GAS_PRICE_ORACLE_NUM_OF_BLOCKS` to calculate the proper from_block for where condition in query instead
> fix: `GAS_PRICE_ORACLE_NUM_OF_BLOCKS` calculation

- apps/block_scout_web/lib/block_scout_web/views/nft_helper.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
- cspell.json
> fix: Fix incorrect image_url parsing from NFT meta

- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
- apps/explorer/lib/explorer/chain/search.ex
- apps/explorer/lib/explorer/helper.ex
Closes #7641.
A regression test for Bug fix.
Add function for safe integers parsing
> fix: search for long integers

- apps/indexer/lib/indexer/application.ex
Closes #9874
- Update hackney pool size: add new fetchers and disabled fetcher accounting
> chore: Update hackney pool size: add new fetchers accounting

- apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
These changes are required to get rid of warning messages appearing when the project is compiled with the chain type different from `:arbitrum`.
* Instead of using the form `entity.item` for the chain specific fields, the construction `Map.get(entity, :item)` is used.
> fix: hide Arbitrum specific fields to get rid of warnings

- apps/explorer/lib/explorer/chain.ex
- apps/indexer/test/indexer/fetcher/token_instance/helper_test.exs
Closes #10128 
- Fix condition in SQL query, which leaded to overflow of retries count
- Tune fragment in `token_instance_metadata_on_conflict/0` in order to avoid exception in linked issue
> fix: Fix Retry NFT fetcher

- apps/block_scout_web/lib/block_scout_web.ex
- apps/block_scout_web/lib/block_scout_web/api_router.ex
- apps/block_scout_web/lib/block_scout_web/router.ex
- apps/block_scout_web/lib/block_scout_web/routers/account_router.ex
- apps/block_scout_web/lib/block_scout_web/web_router.ex
- apps/block_scout_web/test/block_scout_web/controllers/account/custom_abi_controller_test.exs
- apps/block_scout_web/test/support/conn_case.ex
Related to https://github.com/blockscout/blockscout/pull/10032
> fix: Move auth routes to general router

- apps/explorer/lib/explorer/chain/csv_export/address_internal_transaction_csv_exporter.ex
- apps/explorer/lib/explorer/chain/transaction.ex
- apps/explorer/test/explorer/chain/csv_export/address_internal_transaction_csv_exporter_test.exs
Close #10035 
- Add Fee column to Internal transactions CSV export
> feat: Add Fee column to Internal transactions CSV export

- apps/explorer/lib/explorer/token/metadata_retriever.ex
Related to https://github.com/blockscout/blockscout/pull/10187
Fixed fetched metadata overriding for `ERC-1155` tokens.
> fix: ERC-1155 tokens metadata retrieve

- apps/explorer/lib/explorer/chain/smart_contract/proxy/verification_status.ex
> fix: Fix possible unknown UID bug

- .github/actions/setup-repo/action.yml
- .github/scripts/select-builder.sh
`Error: Unable to process file command 'env' successfully.
Error: Invalid format '18.188.25.128'`
> Fix ci setup repo error

- apps/indexer/lib/indexer/fetcher/beacon/blob.ex
> fix: set blob fetcher timeout in seconds

- apps/explorer/test/explorer/market/history/cataloger_test.exs
https://github.com/blockscout/blockscout/actions/runs/9549326068/job/26318651611?pr=10261
Increase sleep time
> fix: flaky market test

- apps/indexer/lib/indexer/fetcher/arbitrum/rollup_messages_catchup.ex
- apps/indexer/lib/indexer/fetcher/arbitrum/workers/historical_messages_on_l2.ex
During the synchronization of the ArbitrumOne node, it was found that `arbitrum_bridge_l2_catchup` does not halt when the indexer's first block is reached and continues to parse lower blocks unnecessarily.
The fetcher's code has been changed to rely on the configured indexer first block (or `0` by default) rather than assuming that the end of the chain is always at block `0`.
> fix: indexer first block usage to halt Arbitrum missed messages discovery

- .github/actions/setup-repo/action.yml
- .github/workflows/publish-docker-image-for-eth.yml
We don't need rootless connection on isolated builder
> Update buildkit builders

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex
> fix: empty revert reasons in geth variant

- apps/block_scout_web/test/block_scout_web/controllers/api/v2/stats_controller_test.exs
https://github.com/blockscout/blockscout/issues/9347
Fix exchange rate flickering test:
```
2) test /stats/charts/market get empty data (BlockScoutWeb.API.V2.StatsControllerTest) Error: test/block_scout_web/controllers/api/v2/stats_controller_test.exs:40 Assertion with == failed code: assert response["chart_data"] == [] left: [ %{ "closing_price" => "2.5", "date" => "2024-07-05", "market_cap" => "0.0", "tvl" => nil }, %{ "closing_price" => "1", "date" => "2024-07-04", "market_cap" => "0", "tvl" => nil }, %{ "closing_price" => "1", "date" => "2024-07-03", "market_cap" => "0", "tvl" => nil }, %{ "closing_price" => "1", "date" => "2024-07-02", "market_cap" => "0", "tvl" => nil }, %{ "closing_price" => "1", "date" => "2024-07-01", "market_cap" => "0", "tvl" => nil }, %{ "closing_price" => …
```
> fix: Fix exchange rate flickering test

- apps/indexer/lib/indexer/memory/monitor.ex
Related to https://github.com/blockscout/blockscout/pull/9984
> feat: Add memory metrics for OnDemand fetchers

- apps/indexer/lib/indexer/memory/monitor.ex
Related to https://github.com/blockscout/blockscout/pull/10425
> fix: Fix on-demand fetchers metrics

- apps/explorer/mix.exs
- mix.exs
Related to https://github.com/blockscout/blockscout/pull/10486
> Move recon to explorer

- apps/explorer/lib/explorer/chain/csv_export/address_internal_transaction_csv_exporter.ex
- apps/explorer/test/explorer/chain/csv_export/address_internal_transaction_csv_exporter_test.exs
Closes #10494 
- Add nil gas_used handling
> fix: Error on internal transactions CSV export

- apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex
Since the batch 0 does not contain any rollup blocks associated it makes sense to skip its handling.
> fix: skip the batch 0 on Arbitrum chains

- apps/explorer/lib/explorer/etherscan.ex
Fixed a bug where `token_type` was taken from token instead of token transfer even if `token_transfers` denormalization is finished
> fix: Use token_type from tt instead of token

- apps/explorer/lib/explorer/chain/arbitrum/reader.ex
- apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex
The recent implementation of the historical cross-chain messages fetcher does not work on the instances where there are lots of rollup transactions like Arbitrum One, Arbitrum Nova, and Arbitrum Sepolia. The DB query identifying the rollup block of the latest missing cross-chain message cannot be executed in the default timeout and crashes:
```
GenServer Indexer.Fetcher.Arbitrum.RollupMessagesCatchup terminating
** (DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
(ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
(ecto 3.11.2) lib/ecto/repo/queryable.ex:232: …
```
> fix: limited usage of infinite timeout in Arbitrum related DB queries

- apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
In order to increase transparency for the end users, it makes sense to extend the `arbitrum` section in the response of `/api/v2/transactions/{txHash}` with an L1 transaction associated with the cross-chain message if the rollup transaction contains either an 'incoming' or 'outgoing' message. For an incoming message, the new field `message_related_l1_transaction` will contain a hash of an L1 originating transaction; for an outgoing message, the field will contain a hash of an L1 completion transaction. 
The function `BlockScoutWeb.API.V2.ArbitrumView.extend_if_message`, called during the preparation of transaction data as part of rendering it in response to `/api/v2/transactions/{txHash}`, was modified to include information about the L1 transaction associated with the message. If the …
> feat: L1 tx associated with Arbitrum message in /api/v2/transactions/{txHash}

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/metadata_controller.ex
- apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/proxy/metadata_view.ex
- apps/explorer/lib/explorer/microservice_interfaces/metadata.ex
Closes #9976 
-  Add `/api/v2/proxy/metadata/addresses endpoint`
> feat: Add /api/v2/proxy/metadata/addresses endpoint

- config/config_helper.exs
Related to https://github.com/blockscout/blockscout/pull/10631
Docs update: https://github.com/blockscout/docs/pull/314
> fix: Change mode env name

- apps/explorer/lib/explorer/chain/mud.ex
* Fix decoding issues caused by zero fields, i.e. https://explorer.garnetchain.com/api/v2/mud/worlds/0x00E38DC13bBCBd0F83d32d5D763407b5966a5506/tables/0x74620000000000000000000000000000436861726163746572426174746c6500/records
> fix: decoding of zero fields in mud

- apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex
During indexing of historical entities by a Blockscout instance for Arbitrum One, two issues were identified:
1. The process of discovering missing batches did not properly handle situations where several transactions committing subsequent batches were included in the same L1 block. The mechanism identifying block ranges to discover missing batches skipped blocks where transactions committing already indexed batches were included.
2. The historical batches discovery process started from the block preceding the one where the earliest discovered transaction committing a batch was included. However, since multiple batch-committing transactions can occur in one block, this approach could lead to some batches not being discovered.
This PR refines two functions in the …
> fix: revisited approach to choose L1 blocks to discover missing Arbitrum batches

- apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
- apps/indexer/lib/indexer/fetcher/celo/epoch_block_operations.ex
Add missing symbols
*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade …
> chore: Add missing symbols

- apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
Resolves https://github.com/blockscout/blockscout/issues/10672
> feat: Retry ERC-1155 token instance metadata fetch from baseURI + tokenID

- apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Related to https://github.com/blockscout/blockscout/pull/9862
> chore: Support non-unique log index for rsk chain type

- apps/explorer/config/config.exs
- apps/explorer/config/runtime/test.exs
- apps/explorer/lib/explorer/application.ex
- apps/explorer/lib/explorer/migrator/reindex_internal_transactions_with_incompatible_status.ex
- apps/explorer/test/explorer/migrator/reindex_internal_transactions_with_incompatible_status_test.exs
Resolves https://github.com/blockscout/blockscout/issues/10547
> chore: Reindex incorrect internal transactions migration

- .dialyzer-ignore
- apps/explorer/lib/explorer/chain/cache/celo_core_contracts.ex
- apps/indexer/lib/indexer/application.ex
Fix dialyzer warning that arose after #10284.
> fix: dialyzer warning

- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
> feat: Support CoinMarketCap's format in token supply endpoint

- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Resolves https://github.com/blockscout/blockscout/issues/10789
> fix: Fix get current user in app template

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/mud_controller.ex
- apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
- apps/block_scout_web/lib/block_scout_web/views/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/mud_view.ex
- apps/explorer/lib/explorer/chain/mud.ex
- apps/explorer/lib/explorer/chain/smart_contract/proxy.ex
Add API for fetching MUD world systems and their implementation ABI.
> feat: api for querying mud systems abi

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_transfer_controller.ex
- apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
- apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/advanced_filter_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/stability_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_transfer_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_transfer_controller_test.exs
- apps/explorer/lib/explorer/chain/token_transfer.ex
Resolves https://github.com/blockscout/blockscout/issues/10717
Development of API v2 endpoint for the list of token transfers. 
GET `api/v2/token-transfers` API v2 endpoint is added.
It supports keyset pagination in the form:
`?block_number=6715325&index=24&items_count=50` which is taken from `next_page_params` param of the response for the 1st page:
```
"next_page_params": {
"block_number": 6715322,
"index": 254,
"items_count": 100
}
```
Sample response:
```
{
"items": [
{
"block_hash": "0x36606ce63df214e78ca6fc391997b3f608934039caac6415e8aed0ff80b13def",
"block_number": "6788861",
"from": {
"ens_domain_name": null,
"hash": "0x0000000000000000000000000000000000000000",
"implementations": [],
"is_contract": false,
"is_scam": true,
"is_verified": false,
"metadata": {
"tags": [
{
"meta": …
```
> feat: Token transfers list API endpoint

- .github/workflows/publish-docker-image-for-celo.yml
Add shrinking of internal transactions for Celo chain type.
> chore: Add shrink int txs docker image build for Celo chain type

- .github/workflows/publish-docker-image-for-celo.yml
> fix: add missing build arg to celo workflow

- README.md
Minor docu fix.
Updated dead doc link to env. variables.
> doc: correct link to env. variables in README.md

- apps/block_scout_web/lib/block_scout_web/views/api/v2/proxy/metadata_view.ex
- apps/explorer/lib/explorer/microservice_interfaces/metadata.ex
snake_case in metadata service
- Support snake_case in metadata service
> feat: Support snake_case in metadata service

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/filecoin_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
- apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
- apps/explorer/lib/explorer/chain/address.ex
Closes #10884 
- Add missing filecoin robust addresses
> feat: Add missing filecoin robust addresses

- apps/explorer/lib/explorer/repo/config_helper.ex
- apps/explorer/priv/account/migrations/20231207201701_add_watchlist_id_column.exs
- apps/explorer/priv/repo/migrations/20191203112646_internal_transactions_add_to_address_hash_index.exs
- apps/explorer/priv/repo/migrations/20220919105140_add_method_id_index.exs
Resolves https://github.com/blockscout/blockscout/issues/10916
Alternative `search_path` may be provided via query string in all database urls
> feat: Allow to provide DB schema other than public

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/advanced_filter_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/advanced_filter_controller_test.exs
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/advanced_filter.ex
- apps/explorer/priv/repo/migrations/20240806124402_add_internal_transaction_to_address_hash_index.exs
Related to https://github.com/blockscout/blockscout/issues/9034
> perf: optimize advanced filters

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
- apps/block_scout_web/lib/block_scout_web/templates/account/tag_transaction/index.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/account/tag_transaction/row.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorer.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorer_modal.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorers.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
- apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/advanced_filter_controller_test.exs
- apps/explorer/lib/explorer/account/tag_transaction.ex
> fix: chart API: add compatibility with the current frontend

- apps/explorer/lib/explorer/chain/transaction.ex
> fix: bugs introduced in calldata decoding optimizations 

- apps/block_scout_web/lib/block_scout_web/paging_helper.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- apps/explorer/lib/explorer/chain/transaction.ex
> feat: address transactions block number sorting

- apps/explorer/priv/celo/migrations/20241029131554_modify_collated_gas_price_constraint.exs
- apps/explorer/priv/polygon_edge/migrations/20230731130103_modify_collated_gas_price_constraint.exs
Fix block import problem related to `collated_gas_price` constraint violation.
- Changed path for module migration under Polygon chain type
- Migration
> fix: celo collated gas price issue

- apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/data.ex
- apps/explorer/lib/explorer/chain/smart_contract.ex
- apps/explorer/lib/explorer/smart_contract/helper.ex
- apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
- apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex
- cspell.json
> feat: Support zksync foundry verification

- apps/explorer/lib/explorer/chain/transaction.ex
Fix one more bug introduced in https://github.com/blockscout/blockscout/pull/10842
ABI for non-proxied contracts should be also cached in `combine_proxy_implementation_abi_map`, since its ABI is already fetched from the DB.
> fix: abi cache for non-proxied addresses

- apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
- apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
- apps/explorer/lib/explorer/etherscan.ex
Resolves https://github.com/blockscout/blockscout/issues/11084
`tokennfttx` API v1 endpoint when `transactions` table denomalization finished.
> fix: Fix tokennfttx API v1 endpoint

- apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
- Fix tests for filecoin chain type
> fix: Fix failed filecoin tests

- apps/indexer/lib/indexer/fetcher/optimism.ex
- apps/indexer/lib/indexer/fetcher/polygon_edge.ex
- apps/indexer/lib/indexer/fetcher/shibarium/l1.ex
- apps/indexer/lib/indexer/fetcher/zksync/batches_status_tracker.ex
- apps/indexer/lib/indexer/helper.ex
Related to https://github.com/blockscout/blockscout/pull/10934
> fix: Fix fake json_rpc_named_arguments for multiple urls usage

- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/common_helper.ex
- apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_checker.ex
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
- apps/ethereum_jsonrpc/test/ethereum_jsonrpc/utility/common_helper_test.exs
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/geth/http_websocket.ex
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/nethermind/http_websocket.ex
- apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/http/case.ex
- apps/explorer/lib/explorer/chain/bridged_token.ex
- apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
- apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
Related to https://github.com/blockscout/blockscout/pull/10934
> fix: Multiple json rpc urls fixes

- apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Resolves https://github.com/blockscout/blockscout/issues/10397
> fix: Check if flash is fetched before getting it in app.html

- apps/explorer/lib/explorer/etherscan/logs.ex
- apps/explorer/test/explorer/etherscan/logs_test.exs
> fix: eth_getLogs paging

- apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
- apps/explorer/lib/explorer/chain/token_transfer.ex
- apps/explorer/lib/explorer/helper.ex
Similar workaround for current token balances as it was done for addresses. (https://github.com/blockscout/blockscout/pull/7811)
> chore: Optimize CurrentTokenBalances import runner

- apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
Closes #10865
- Add request to /cache/{tx_hash} of transaction interpreter
> feat: Add request to /cache/{tx_hash} of transaction interpreter

- apps/block_scout_web/test/block_scout_web/views/api/v2/transaction_view_test.exs
- apps/explorer/lib/explorer/chain/log.ex
Closes #11267 
- store in events_acc not results, but candidates from DB
> fix: Fix log decoding bug

- apps/explorer/lib/explorer/chain.ex
- apps/explorer/lib/explorer/chain/token/instance.ex
- apps/explorer/priv/repo/migrations/20241002125432_add_is_banned_to_token_instances.exs
- apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
- apps/indexer/test/indexer/fetcher/token_instance/helper_test.exs
Close #10825 
- Add `is_banned` to `token_instances` table
> feat: Add is_banned to token_instances table

- docker/Dockerfile
- docker/oldUI.Dockerfile
https://github.com/blockscout/blockscout/actions/runs/12176016585/job/33964017962
> fix: add utils to dockerfile

- config/runtime.exs
After https://github.com/blockscout/blockscout/pull/11130 DISABLE_WEBAPP is actually taken into account and it turned out that config definition for events listener is wrong
> fix: webscoket configuration

- docker/Dockerfile
Finalization of https://github.com/blockscout/blockscout/pull/10675
Docker build failed:
```
#40 1.044 Unchecked dependencies for environment prod:
#40 1.044 * evision (Hex package)
#40 1.044   the dependency is not available, run "mix deps.get"
#40 1.044 * ex_aws_s3 (Hex package)
#40 1.044   the dependency is not available, run "mix deps.get"
#40 1.044 * image (Hex package)
#40 1.044   the dependency is not available, run "mix deps.get"
#40 1.044 * ex_aws (Hex package)
#40 1.044   the dependency is not available, run "mix deps.get"
#40 1.044 * sweet_xml (Hex package)
#40 1.044   the dependency is not available, run "mix deps.get"
#40 1.045 ** (Mix) Can't continue due to errors on dependencies
#40 ERROR: process "/bin/sh -c mix compile" did not complete successfully: exit code: 1
#36 …
```
> fix: Fix docker container build after adding NFT media handler

- apps/explorer/lib/explorer/prometheus/collector/active_db_connections.ex
Resolves https://github.com/blockscout/blockscout/issues/11072
> feat: Add active DB connections metric

- apps/explorer/lib/explorer/chain/log.ex
Finalization of https://github.com/blockscout/blockscout/pull/11956
```
{"time":"2025-02-26T14:49:43.540Z","severity":"error","message":"Ranch listener BlockScoutWeb.Endpoint.HTTP, connection process #PID<0.30481.0>, stream 1 had its request process #PID<0.30482.0> exit with reason {{{%BadMapError{\n     term: nil\n   },\n   [\n     {Explorer.Chain.Log,\n      :\"-decode_events_batch_via_sig_provider/2-fun-2-\",\n      1,\n      [\n        file: ~c\"lib/explorer/chain/log.ex\",\n        line: 481\n      ]},\n     {Enum,\n      :\"-map/2-lists^map/1-1-\",\n      2,\n      [\n        file: ~c\"lib/enum.ex\",\n        line: 1703\n      ]},\n     {BlockScoutWeb.API.V2.TransactionView,\n      :decode_logs,\n      2,\n      [\n        file: …
```
> fix: Fix logs decoding error

- README.md
Finalization of https://github.com/blockscout/blockscout/pull/12097
> chore: replaced the link to the blockscout badge

- apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
Fix [failed tests](https://github.com/blockscout/blockscout/actions/runs/14176214559/job/39717921779) in master branch.
> fix: Fix Rootstock failed tests

- apps/block_scout_web/test/block_scout_web/controllers/api/v1/health_controller_test.exs
- apps/explorer/lib/explorer/chain/health/monitor.ex
Fix unhandled error on /api/health endpoint.
> Fix health endpoint
