CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
- check fetched instance metadata in multiple places
=> check fetched instance metadata in multiple places

apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
internal transaction fetching is triggered in block
fetchers before block insertion. but pending ops are
inserted only during block insertion. So sometimes
internal transactions are being fetched without corresponding
records in pending ops table so these blocks are marked as
non-consensus. This PR removes internal transaction fetching
from block fetchers.
Another possible issue I found is that we mark blocks
invalid if there are no internal txs for some transactions in
these blocks. Some transactions may not have internal txs. This
is also fixed.
- not trigger internal txs in fetchers
=> not trigger internal txs in fetchers

CHANGELOG.md, apps/explorer/priv/repo/migrations/20191018140054_add_pending_internal_txs_operation.exs, apps/explorer/priv/repo/migrations/20191121064805_add_block_hash_and_block_index_to_logs.exs, apps/explorer/priv/repo/migrations/20191122062035_add_block_hash_to_token_transfers.exs
In migration to *block_hash* indexing approach we should clear the DB from possible inconsistencies (cc https://github.com/poanetwork/blockscout/pull/2699 https://github.com/poanetwork/blockscout/pull/2697 https://github.com/poanetwork/blockscout/pull/2695)
1. Before constructing primary key on all tables we should check that there are no rows  with empty `block_hash`
2. We should check for possible duplicates of a pair [`block_hash`, `block_index`] before creating a primary key on them on `internal_transactions` table.
3. Looks like, `create(index(:logs, [:block_number]))` index is unused in the new approach.
=> Mitigate issues in the migration to "block_hash" indexing approach

CHANGELOG.md, apps/explorer/priv/repo/migrations/20191220113006_pending_block_operations_block_hash_partial_index.exs
Improve the performance of int txs importer
One of the parts of indexing is to get block numbers which need dot be fetched. 2Mb partial index on `pending_block_operations` table on block's hash *where fetch_internal_transactions=true* increases the speed of that query up to 30 - 40%.
Query plan before:
```
QUERY PLAN
----------------------------------------------------------------------------------------------------
-------------------------------------------------
Gather  (cost=1000.56..170202.03 rows=31829 width=8) (actual time=0.233..113.157 rows=35029 loops=1
)
Workers Planned: 1
Workers Launched: 1
->  Nested Loop  (cost=0.56..166019.13 rows=18723 width=8) (actual time=0.027..100.006 rows=17514
loops=2)
->  Parallel Seq Scan on pending_block_operations p  (cost=0.00..1563.86 …
```
=> Speedup pending block ops int txs to fetch query

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
https://github.com/poanetwork/blockscout/issues/2912
`tokenID` is missing in `tokentx` API endpoint
Add `tokenID` in output for `tokentx` endpoint explicitly in case of ERC-721 token instead to write the value to `value` key
=> Add tokenID for tokentx API action explicitly

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
The query https://github.com/poanetwork/blockscout/blob/da54650a4a559393d29a499a486b51d1477789ef/apps/explorer/lib/explorer/chain.ex#L2969 executes more than 1 hour on ETH Mainnet instance
This PR aims to increase the performance of this query.
Decrease the subset before joining the tables
Before the changes query looked like this:
```
SELECT DISTINCT ON (t0."token_contract_address_hash", t0."token_id") t0."token_contract_address_hash", t0."token_id" FROM "token_transfers" AS t0
INNER JOIN "tokens" AS t1 ON t1."contract_address_hash" = t0."token_contract_address_hash"
LEFT OUTER JOIN "token_instances" AS t2 ON (t0."token_id" = t2."token_id")
AND (t0."token_contract_address_hash" = t2."token_contract_address_hash")
WHERE (((t1."type" = 'ERC-721')
AND t2."token_id" IS NULL) AND NOT …
```
=> Reduce execution time of stream_unfetched_token_instances query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20191218120138_logs_block_number_index_index.exs
Logs tab on address page:
For almost all addresses if there are tons of transactions in the chain like in ETH Mainnet.
1. Replace index on logs table on `block_number` field with a multicolumn index `block_number DESC, index DESC` to be able to sort in logs table
2. Change the query to use this index.
The query is transformed from 
```
SELECT l0.* FROM logs AS l0
INNER JOIN transactions AS t1
ON ((t1.block_hash = l0.block_hash)
AND (t1.block_number = l0.block_number))
AND (t1.hash = l0.transaction_hash)
WHERE (((t1.block_number < 9125388))
OR ((t1.block_number = 9125388)
AND (t1.index > 0))
OR (((t1.block_number = 9125388) AND (t1.index = 0))
AND (l0.index > 0)))
AND ((l0.address_hash = '\xdac17f958d2ee523a2206206994597c13d831ec7')
AND (l0.block_hash = t1.block_hash))
ORDER BY …
```
=> Speedup address to logs query

CHANGELOG.md, apps/indexer/lib/indexer/buffered_task.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/test/support/indexer/fetcher/internal_transaction_supervisor_case.ex
current fetchers do not process new items
when they were added after initial records from
DB were processed.
This PR fixes it.
- fix empty buffered task
=> fix empty buffered task

CHANGELOG.md, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/priv/repo/migrations/20191208135613_block_rewards_block_hash_partial_index.exs
The query https://github.com/poanetwork/blockscout/blob/8c62be450d9a78b4a52ae6c3900f6b383d2b8382/apps/explorer/lib/explorer/chain/block.ex#L118 executes more than **5 hours** on ETH Mainnet instance.
This PR aims to decrease the execution time.
1. Add partial index on `block_rewards` table `block_hash` column where address type is `validator`
2. Decrease subsets of tables before joins, not after.
Before the changes:
```
8740 | 05:36:11.251542 |SELECT b0."hash", b0."consensus", b0."difficulty", b0."gas_limit", b0."gas_used", b0."nonce", b0."number", b0."size", b0."timestamp", b0."total_difficulty", b0."internal_transactions_indexed_at", b0."refetch_needed", b0."inserted_at", b0."updated_at", b0."miner_hash", b0."parent_hash" FROM "blocks" AS b0 LEFT OUTER JOIN "block_rewards" AS b1 ON …
```
=> Speedup of blocks_without_reward_query

CHANGELOG.md, apps/block_scout_web/assets/js/lib/currency.js, apps/block_scout_web/assets/js/pages/chain.js
**Problem:** the same websocket connection is initialized in 2 separate scripts, because both scripts use `lib/currency.js`
**Solution:** moved websocket connection from `lib/currency.js` to `pages/chain.js`
=> Fix duplicate websocket connection

CHANGELOG.md, apps/explorer/priv/repo/migrations/20191018140054_add_pending_internal_txs_operation.exs
If `internal_transactions` is small (< 10,000,000 rows) a better approach is to clear {`block_hash`, `block_index`} duplicates at once rather than to iterate through all blocks.
Change migration script
=> Improve DB migration to "pending_block_operations" indexing approach

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex
RSK chain doesn't have internal transactions. Thus, Blockscout needs to skip filling pending_block_operations table for RSK variant since there blocks with pending internal txs are stored there.
Skip logic inside `new_pending_operations` for `EthereumJSONRPC.RSK` variannt.
=> Prevent filling pending_block_operations table for RSK variant

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
There is no tooltip on UTF-8 tx input
=> utf8 copy tx input tooltip

CHANGELOG.md, apps/explorer/priv/repo/migrations/scripts/20181108205650_additional_internal_transaction_constraints.sql
Actualize `additional_internal_transaction_constraints` script after migration to `pending_block_operations` indexing approach https://github.com/poanetwork/blockscout/pull/2886
=> Actualize additional_internal_transaction_constraints script

CHANGELOG.md, apps/block_scout_web/assets/js/socket.js, apps/block_scout_web/assets/webpack.config.js
Closes https://github.com/poanetwork/blockscout/issues/2948
=> Move socket path to env

CHANGELOG.md, rel/commands/clear_build.sh
Cleaning script removes logs only from `dev` folder
Adding of removal of logs from `test` folder
=> Remove logs from test folder too in the cleaning script

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
https://github.com/poanetwork/blockscout/issues/2907
Read page is broken if `addresses` output is not a list
Check that `addresses` type is an enum
=> Add a guard that addresses is enum in `values` function in `read contract` page

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex, apps/explorer/test/explorer/smart_contract/verifier/constructor_arguments_test.exs
https://github.com/poanetwork/blockscout/issues/2911
Closes https://github.com/poanetwork/blockscout/issues/2968
Contract constructor hexed `require` fallback messages appear in constructor arguments encoded view after contract verification
Add filtering of those hexed messages from constructor arguments encoded view
=> Fix contract constructor require msg appearance in constructor arguments encoded view

CHANGELOG.md, apps/explorer/priv/repo/migrations/20191128124415_remove_duplicate_indexes_token_entities.exs
PGHero found duplicate indexes
```
Details
--
On address_token_balancesaddress_token_balances_block_number_index (block_number) is covered by address_token_balances_block_number_address_hash_index (block_number, address_hash)
On token_instancestoken_instances_token_id_index (token_id) is covered bytoken_instances_pkey (token_id, token_contract_address_hash)
```
=> remove duplicate indexes

CHANGELOG.md, apps/block_scout_web/assets/js/lib/try_eth_api.js, apps/block_scout_web/config/config.exs, apps/block_scout_web/config/dev.exs, apps/block_scout_web/config/prod.exs, apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs
If Blockscot instance is proxied to blockscout.com there are 2 problems exist:
- URL on API docs page doesn't include path on blockscout.com for the instance that confusing developers
- Try it out section doesn't work for ETH RPC API endpoints
`API_PATH` ENV var introduced which indicates the path for API URL. If it is not set, it is `/`.
=> Introduce API_PATH env var

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Styles in the search field are broken in Firefox because `awesomplete.css` is not loaded there
Fix loading of `awesomplete.css`
=> Fix awesomplete lib loading in Firefox

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
"Copy Txn UTF8 input button" copies not decoded input but hex instead.
Fix Copy Txn UTF8 input button action
=> Fix copy UTF8 tx input action

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Export to CSV button returns redirect to not found page. It was broken in #2834
add checksummed hash in `address_id` param for `transactions_csv` method
=> Fix broken export to CSV

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex
`tokenTx` API endpoint returns 504 Gateway timout error even with using of pagination with 10 elements per page. For instance: https://blockscout.com/poa/core/api?module=account&action=tokentx&address=0xcb55fc893000a984a5ad73011f93d1540a5f0895&sort=desc&page=1&offset=10. The issue is because query to get list of token transfers is too long. This PT improves performance of this query.
Original query looks like:
```
SELECT t1.*, t0.*, b3."hash", b3."number", b3."timestamp", t2.*
FROM "transactions" AS t0
INNER JOIN "token_transfers" AS t1 ON ((t1."transaction_hash" = t0."hash")
AND (t1."block_number" = t0."block_number")) AND (t1."block_hash" = t0."block_hash")
INNER JOIN "addresses" AS a4 ON a4."hash" = t1."token_contract_address_hash"
INNER JOIN "tokens" AS t2 ON …
```
=> Speedup token transfers list query

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Reverts #2470
This feature causes real time fetcher to skip blocks and catchup fetcher never processes them causing increasing the number of chain breaks. Noticed on Mainnet instance. In view of that fact and unclear profit from implementing of #2470 (it still tries to index indexed blocks), it is suggested to revert that PR.
=> Revert realtime fetcher small skips feature

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
URL behind QR-code on token instance page leads to 404 page
Add `set_path` parameter to `blockscout_url` method and pass `false` in case of constructing URL for  QR-code
=> Fix token instance QR code data

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/schema/subscription/token_transfers_test.exs, apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs
Continuation of https://github.com/poanetwork/blockscout/pull/3016
=> Fix token instance QR code data when api_path is different from path

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_metatags.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/views/tokens/read_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/transfer_view.ex
Issue caused by #2834
- Some links on token/instances pages are broken
- Checksummed address feature doesn't spread to token/instances pages
=> Fix checksum address feature for tokens pages

apps/block_scout_web/lib/block_scout_web/checksum_address.ex
The issue caused by https://github.com/poanetwork/blockscout/pull/2834
Filters functionality doesn't work: all filters params are ignored because on redirect to checksummed address query string is lost.
Add query string to redirected address if it is not empty.
=> Fix filters functionality

.circleci/config.yml, CHANGELOG.md, apps/explorer/config/dev.exs, apps/explorer/config/prod.exs
The default value of `POOL_SIZE` env var doesn't read in the production environment.
Fix default value reading in prod env
- increase the value up to 50 (what is closer to real production instances)
=> Fix pool size default value in config

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex, apps/explorer/lib/explorer/chain.ex
Continuation of https://github.com/poanetwork/blockscout/pull/3013
Unhandled error response in `trace_replay_transaction_responses_to_first_trace_params` method request
Handle `:error` case of response from `trace_replay_transaction_responses_to_first_trace_params` method
=> Handle error at first trace request

CHANGELOG.md, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Polling period is too long for realtime fetching of blocks.
- decrease minimal safe polling period down to 5 sec
- define the polling period as half of avg block time
=> Decrease polling period value for realtime fetcher

CHANGELOG.md, apps/block_scout_web/assets/__tests__/pages/chain.js, apps/block_scout_web/assets/js/pages/chain.js
if fewer blocks or txs on the page than it can contain than new items rewrite existing instead of adding to the list.
=> Fix transactions and blocks appearance on the main page

CHANGELOG.md, apps/explorer/config/dev/ganache.exs, apps/explorer/config/dev/geth.exs, apps/explorer/config/dev/parity.exs, apps/explorer/config/dev/rsk.exs, apps/explorer/config/prod/ganache.exs, apps/explorer/config/prod/geth.exs, apps/indexer/config/dev/ganache.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/dev/parity.exs, apps/indexer/config/dev/rsk.exs, apps/indexer/config/prod/ganache.exs, apps/indexer/config/prod/geth.exs
Archive node websockets are not required for Blockscout. Thus, we need to remove default valued from config
Remove default values in the config for websockets
=> Remove default websockets URL from config

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex, apps/explorer/lib/explorer/chain.ex
There is an error when someone opens raw trace page with Ganache, for instance
Handle `:ignore` case in response in case of unsupported variants
=> Ignore case for first trace response

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Indexing status alert at the top of the main page appears for Ganache variant. Though, ganache doesn't' support tracing methods. Thus, the alert will never disappear.
Hide this alert from Ganache variant
=> Remove indexing status alert for Ganache variant

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex, apps/explorer/lib/explorer/smart_contract/reader.ex
Read methods which are defined in ABI as `"stateMutability":"view"` are not recognized
Add check of `"stateMutability":"view"` in ABI parser
=> Support stateMutability=view to define reading functions in smart-contracts

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/explorer/lib/explorer/chain/address.ex
address_counters endpoint experiences infinite redirects due to redirect to checksummed address:
Convert query param to this endpoint into the checksummed address
=> Fix checksum in query parameter of address_counters endpoint

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
Buttons at verified contract page have different colors
Apply equal styles to the buttons on that page
=> Make buttons color at verification page consistent

apps/explorer/config/dev.exs
Set default hostname and database in dev mode
=> Return default hostname and database in dev mode

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
The currently implemented query is slow because it doesn't use current indexes effectively. Current query execution plan:
```
explain select * from transactions where block_hash is null and error is null order by inserted_at desc, hash desc limit 50;
QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------
Limit  (cost=7535181.93..7535182.05 rows=50 width=398)
->  Sort  (cost=7535181.93..7541132.96 rows=2380414 width=398)
Sort Key: inserted_at DESC, hash DESC
->  Bitmap Heap Scan on transactions  (cost=107203.94..7456106.29 rows=2380414 width=398)
Recheck Cond: ((block_hash IS NULL) AND (error IS NULL))
->  Bitmap Index Scan on transactions_block_hash_error_index  (cost=0.00..106608.84 rows=2380414 width=0)
Index …
```
=> Speedup pending txs list query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/events/listener.ex, apps/explorer/test/explorer/chain_test.exs
Addition to https://github.com/poanetwork/blockscout/pull/3025
We should also extract hostname from DB URL provided in order to make a splitting couple: indexer - web app work.
`extract_db_host(db_url)` function is introduced
=> Extract host name for split couple of indexer and web app

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_table-loader.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/common_components_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
There is a division by zero in coin market cap percentage calculation on `/accounts` page for coins with zero market cap from CoinGecko.
Check total_supply before division
=> Prevent division by zero on /accounts page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
Caused by https://github.com/poanetwork/blockscout/pull/2944
Fix missing conn in eex template
```
2020-03-11T13:07:34.253 [error] GenServer #PID<0.1858.0> terminating
** (ArgumentError) assign @conn not available in eex template.
Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.
Available assigns: [:transaction, :view_module, :view_template]
(phoenix_html) lib/phoenix_html/engine.ex:133: Phoenix.HTML.Engine.fetch_assign!/2
(block_scout_web) lib/block_scout_web/templates/transaction/_tile.html.eex:79: BlockScoutWeb.TransactionView."_tile.html"/1
(phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
(phoenix) lib/phoenix/view.ex:406: …
```
=> Fix missing conn in eex template

CHANGELOG.md, apps/explorer/lib/explorer/chain/supply/token_bridge.ex
Block reward contract address is hardcoded in TokenBridge supply module
Extract Block reward contract address from `blockRewardContract` property of TokenBridge contract
=> Automatically define Block reward contract address in TokenBridge supply module

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
Closes https://github.com/poanetwork/blockscout/issues/3015
There is no link to a token page from token instance page
Link to token page is added
=> ERC-721 token instance page: link to token added

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Closes https://github.com/poanetwork/blockscout/issues/3068
Constructor argument of address type currently is not clickable in decoded view if the decoded argument is correct address.
Add a link to address page for constructor argument of address type
=> Make a link to address page on decoded constructor argument of address type

CHANGELOG.md, apps/explorer/priv/repo/migrations/20200410115841_create_index_address_current_token_balances_token_contract_address_hash_value.exs
https://github.com/poanetwork/blockscout/issues/2644
The last step in the fixing of performance of token page is token holders query. Currently, it cannot be finished in 20 secs causing "Something went wrong, click to reload" error message.
In this PR, an index is creating:
```
CREATE INDEX address_current_token_balances_token_contract_address_hash_value_index ON address_current_token_balances(token_contract_address_hash, value);
```
which significantly improves the performance of token holders query https://github.com/poanetwork/blockscout/blob/abb1157ee5231f082c37ab2451de5063fd8d5479/apps/explorer/lib/explorer/chain/address/current_token_balance.ex#L114:
```
eth2s=> EXPLAIN ANALYZE SELECT a0."id", a0."value", a0."block_number", a0."value_fetched_at", a0."old_value", a0."address_hash", …
```
=> Index creation to blazingly speedup token holders query

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.exs, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/graphql.ex, apps/explorer/priv/repo/migrations/20200410141202_create_index_token_transfers_token_contract_address_hash_block_number.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/graphql_test.exs
https://github.com/poanetwork/blockscout/issues/1408
Closes https://github.com/poanetwork/blockscout/issues/2644
Slow performance of token transfers and inventory queries at token page
Create an index on `token_transfers` table:
```
CREATE INDEX token_transfers_token_contract_address_hash_block_number_index ON token_transfers(token_contract_address_hash, block_number);
```
to increase the speed of retrieving of the list of token transfers
https://github.com/poanetwork/blockscout/blob/4ad6f91459100c5a5f391b8b542492959862c940/apps/explorer/lib/explorer/chain/token_transfer.ex#L146
https://github.com/poanetwork/blockscout/blob/4ad6f91459100c5a5f391b8b542492959862c940/apps/explorer/lib/explorer/chain/token_transfer.ex#L164
*Caveat*: token transfers will not be longer sorted by `log_index` …
=> Speedup list of token transfers per token query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20200421102450_pending_txs.exs
Continuation of https://github.com/poanetwork/blockscout/pull/3042/files
Pending tx list is still not enough fast. This PR finally solves the problem by creating a partial index specific for pending txs list query.
1. Create a partial index: `CREATE INDEX IF NOT EXISTS pending_txs_index ON transactions(inserted_at, hash) WHERE (block_hash IS NULL AND (error IS NULL OR (error != 'dropped/replaced')))`
2. Remove not efficient index: `"transactions_hash_inserted_at_index" btree (hash, inserted_at)`
3. Change the ordering in pending txs list query back to : `[desc: transaction.inserted_at, desc: transaction.hash]`
And index size dramatically decreased:
Before:
public.transactions_hash_inserted_at_index                             | **1715 MB**
After:
public.pending_txs_index …
=> Finally speedup pending tx list

CHANGELOG.md, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod/geth.exs
Continuation of https://github.com/poanetwork/blockscout/pull/2289 https://github.com/poanetwork/blockscout/pull/1778
Websockets are not optional for Geth
Update Geth config
=> Extend optionality of websockets to Geth

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
Solves https://github.com/poanetwork/blockscout/issues/3087
A search of coin price in Coingecko is by coin symbol. However, symbol is not unique. Thus, result of the search can be unexpected if multiple coins with the same symbol are tracked in Coingecko.
Add `COINGECKO_COIN_ID` environment variable in order to open an ability to explicitly set Coinngecko ID of the coin.
=> CoinGecko API coin id environment variable

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
Fixes https://github.com/poanetwork/blockscout/issues/3094
BlockScout doesn't display decoded view for some smart-contracts
=> Fix constructor arguments decoding

CHANGELOG.md, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex, apps/explorer/test/explorer/smart_contract/verifier_test.exs
https://github.com/poanetwork/blockscout/issues/3110 https://github.com/poanetwork/blockscout/issues/3111
- BlockScout doesn't check compiler version on verification
- Contracts compiled with nightly builds cannot be verified
=> Contract verification: check compiler version, verify compiled with nightly builds

CHANGELOG.md, apps/explorer/priv/repo/migrations/20200518075748_create_index_blocks_miner_hash_number_index.exs
Fixes https://github.com/poanetwork/blockscout/issues/3063
"Blocks validated" page is slow
https://github.com/poanetwork/blockscout/issues/3063#issuecomment-629372669
=> Performance fix: index on blocks [miner_hash, number]

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/smart_contract/verifier_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/3108
```
2020-05-18T12:30:39.169 [error] Task #PID<0.9944.1> started from #PID<0.11593.4> terminating
from i0 in Explorer.Chain.InternalTransaction,
where: i0.created_contract_address_hash == ^"0x5933331BB25aAc7fF7BBb22e4E35F65D5882e621",
select: i0.init
(ecto 3.3.1) lib/ecto/repo/queryable.ex:104: Ecto.Repo.Queryable.one/3
(explorer 0.0.1) lib/explorer/chain.ex:2743: Explorer.Chain.smart_contract_creation_tx_bytecode/1
(explorer 0.0.1) lib/explorer/smart_contract/verifier.ex:95: Explorer.SmartContract.Verifier.compare_bytecodes/6
(elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
(explorer 0.0.1) …
```
=> Fix verification of contracts created from factory

CHANGELOG.md, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20200521170002_create_token_transfers_token_contract_address_hash_token_id_block_number_index.exs, apps/explorer/test/explorer/chain/token_transfer_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/3073
Loading of ERC-721 token instances is slow
=> Fix performance of Inventory tab

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Fixes https://github.com/poanetwork/blockscout/issues/3103
https://github.com/poanetwork/blockscout/issues/3103#issuecomment-627220686
Doesn't show balance percentage to market cap for burn address.
=> Exclude balance percentage calculation for burn address on accounts page

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Fixes https://github.com/poanetwork/blockscout/issues/3074
Response from https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash method of Geth client for uncle block doesn't contain `totalDifficulty` param
Add a clause for `elixir_to_params` function with input which doesn't contain `totalDifficulty` param
=> Geth: handle response from eth_getblockbyhash JSON RPC method without totalDifficulty (uncle blocks)

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/coin_balance.ex
=> Fetch balance only for blocks which are greater or equal block with FIRST_BLOCK number

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
=> Take into account FIRST_BLOCK for block rewards fetching

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
```
2020-05-27T13:14:54.939 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32603, data: %{"blockNumber" => 13515086}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13513794}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13513789}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13514436}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13514459}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13514984}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13514814}, message: "Internal error"}, %{code: -32603, data: %{"blockNumber" => 13514759}, message: "Internal error"}, …
```
=> Take into account FIRST_BLOCK in trace_ReplayBlockTransactions requests

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Fixes https://github.com/poanetwork/blockscout/issues/3131
Queries for coin supply endpoints are slow. For instance:
```
select SUM(a0.fetched_coin_balance) from addresses a0;
```
However, `addresses` table has index `"addresses_fetched_coin_balance_index" btree (fetched_coin_balance)` on `fetched_coin_balance` column which excludes empty or zero balances and it is not used by the query. We can modify query adding `where fetched_coin_balance > 0` clause to speed-up it without changing the result of the query.
```
core=> explain analyze select SUM(a0.fetched_coin_balance) from addresses a0 where fetched_coin_balance > 0;
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Fix performance of coin supply API endpoints

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex, apps/explorer/lib/explorer/counters/last_fetched_counter.ex, apps/explorer/priv/repo/migrations/20200527144742_add_counters_table.exs
`coinsupply` API endpoint returns 0 supply for sometime after restart of the application because it retrieved from ETS (in-memory cache), which is cleared on application restart.
In order to provide uninterrupted service for `coinsupply` API endpoint, it is suggested to store last fetched value on cache update for this counter in the DB. And if cache is empty (for instance, on application restart), get that value from DB.
=> Get last value of fetched coinsupply API endpoint from DB if cache is empty

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
https://github.com/rsksmart/rskj/releases/tag/PAPYRUS-2.0.1
happened at block 2,392,700 and causes an error in Blockscout:
```
2020-05-28T12:36:58.685 application=indexer fetcher=block_catchup first_block_number=2393023 last_block_number=2393014 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
(ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"cumulativeDifficulty", "0x2c912722075cffd936"})
(elixir 1.10.2) lib/enum.ex:1320: anonymous fn/4 in Enum.into/3
(stdlib 3.9.2) maps.erl:232: :maps.fold_1/3
(elixir 1.10.2) lib/enum.ex:2127: Enum.into/4
(elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
(ethereum_jsonrpc …
```
=> RSK Papyrus Release v2.0.1 hardfork: cumulativeDifficulty

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex, apps/explorer/test/explorer/chain_test.exs
#1946
Should be merged after https://github.com/poanetwork/blockscout/pull/3125
Balance changing history list (which is under balance history chart) loading at *Coin Balance History* tab is very slow.
Eliminate joining to *Blocks* table in the query to find the list of balance changes by finding min/max blocks in the list and interpolate blocks timestamps using those min and max numbers.
=> Fix performance of the balance changing history list loading

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/coin_balance.ex
https://github.com/poanetwork/blockscout/issues/1946
Last coin balance query is slow
https://github.com/poanetwork/blockscout/blob/02ac0a3ecd2a20be4a00c8ef7381bc05f5d7d25b/apps/explorer/lib/explorer/chain/address/coin_balance.ex#L107-L113
in case of some addresses types. For instance, for emission funds account which balance changes every block https://blockscout.com/poa/sokol/address/0x523B6539Ff08d72A6C8Bb598Af95bF50c1EA839C/coin_balances
The solution is to extract subquery from *address_coin_balances* table to extract target block and then query for its timestamp. It significantly speeds-up the query:
Performance of the query before the changes:
```
sokol=> EXPLAIN ANALYZE SELECT b1."timestamp", a0."value" FROM "address_coin_balances" AS a0
sokol-> INNER JOIN "blocks" AS b1 ON …
```
=> Speed-up last coin balance timestamp query

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex
1. Error is displayed if no balance changes https://blockscout.com/poa/xdai/address/0xf74769d9FFe1Cd17F20b283995CF9e7fA2A262ed/coin_balances
2. Wrong order of items 
- Check if there are balances changes
- Order items in DB query, remove post-ordering
=> Fix coin balance history page: order of items, fix if no balance changes

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/priv/repo/migrations/20200608075122_alter_transactions_add_error_reason.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/test/indexer/fetcher/coin_balance_test.exs
Closes https://github.com/poanetwork/blockscout/issues/2711
Display revert reason of transaction at transaction details page and at *gettxinfo* API endpoint.
- New *revert_reason* field added to *transactions* DB table
- This field added into the output of transaction details page and as *revertReason* field at *gettxinfo* API endpoint
- If the value in DB is empty, it is updated in DB if tx details page or *gettxinfo* is requested. Next times the value is retrieved from the DB.
=> Display and store revert reason of tx on demand

CHANGELOG.md, apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Change compiler version since nightly versions of some older versions was removed
=> Fix contract compilation tests for old versions of compiler

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain_test.exs
https://github.com/poanetwork/blockscout/issues/1151 https://github.com/poanetwork/blockscout/issues/2839
Methods of implementation contract which called on proxy contract are not decoded
If contract's ABI contains "implementation" method and it returns an address of existing on-chain contract Blokcscout will retrieve ABI of implementation from its DB (thus, implementation contract should anyways be verified in the Blockscout) and will try to decode methods using full ABI which comprises from proxy and implementations ABIs.
=> Proxy contracts: methods decoding using implementation ABI

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex
Resolves https://github.com/poanetwork/blockscout/issues/3165
Verification for contracts from genesis block doesn't work
Verification is broken because verification expects transaction/internal transaction to exist. Contracts from genesis block have no any of that. Thus, we should use contract bytecode as a fallback instead of tx input.
=> Fix for verification of contracts from genesis block

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/blockscout/issues/3162
Implementation address is not displayed at read/write proxy tabs
=> Display implementation address at read/write proxy tabs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/lib/explorer/smart_contract/writer.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/explorer/test/explorer/smart_contract/writer_test.exs
https://github.com/poanetwork/blockscout/issues/3163
Blockscout doesn't support retrieving of implementation from storage point defined by EIP-1967
- add `eth_getStorageAt` call support
- get implementation from `0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc` storage pointer of proxy contract if `implementation` getter has `nonpayable` *stateMutability*.
=> EIP-1967 support: transparent proxy pattern

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Resolves https://github.com/poanetwork/blockscout/issues/3177
Resolves https://github.com/poanetwork/blockscout/issues/3176
- Navbar menu is not clickable when any of read/write tabs is active
- Fetching tokens... never disappears at read/write tabs
=> Fix permanent fetching tokens and unavailable navbar menu when read/write proxy tab is active

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
- If smart-contract is verified and someone tries to verify it through API, "Something went wrong while publishing the contract." status is returned
- Kovan is listed in the default chains whereas the instance no more exists
- Return "Smart-contract already verified." in the response of *verify* API endpoint if contract verified.
- Remove Kovan from the list of default chains
=> Return correct status in verify api endpoint if contract verified, remove Kovan from the list of default chains

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex, apps/explorer/lib/explorer/chain/log.ex
If a contract is verified and a transaction to this contract made a call to another contract which is also verified and event emitted in the 2nd contract, Blockscout doesn't decode that event on transaction page of 1st contract.
For instance, https://blockscout.com/poa/xdai/tx/0x3869c26855af7799159e868ff0a80fc254b9fa63b9fd9a351aa5d90764a53533/logs
For any log at the transaction's page for decoding pass an address of a called contract, and not address of a contract to which origin transaction was made
=> Transaction page: decoding logs from nested contracts calls

apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/test/explorer/chain/log_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/3186
Logs are not decoded at address page even if the contract, which produces the logs, is verified
At decoding, pass ABI of a contract which produces the log, and not a contract to which transaction is generated from which that log came from.
=> Address logs decoding fix

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_logs/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/log/_data_decoded_view.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/views/log_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/blockscout/issues/2537
Resolves https://github.com/poanetwork/blockscout/issues/3187
Improve the decoded view. What is annoying for users:
- horizontal scroll
- too many borders, whitespaces
BEFORE:
AFTER:
=> Improve decode log/method view

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/not_found.html.eex
Navbar is non-interactive if "Not found" page is rendered.
Add missing js part to the page.
=> Fix: dropdown menu doesn't open at "not found" page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
No copy button at "raw trace" tab
=> Raw trace copy button

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/publisher.ex, apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex, apps/explorer/lib/explorer/smart_contract/verifier.ex
Resolves https://github.com/poanetwork/blockscout/issues/3198
If compilation is failed at contract verification Blockscout doesn't show the exact reason of failure
Show compilation error
=> Show compilation error at contract verification

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/assets/js/lib/smart_contract/write.js, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/blockscout/issues/3197
=> Connect to Metamask button

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex
Resolves https://github.com/poanetwork/blockscout/issues/3191
Verification of contracts with enabled experimental features doesn't work.
Process a specific additional hex  `6c6578706572696d656e74616cf5 ` added to the bytecode of contract stored in the blockchain if experimental features are enabled.
=> Fix contracts verification with experimental features enabled

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex
https://forum.poa.network/t/querying-core-poa-network-blockchain-via-rpc-graphql/3591
> I’m trying to pull data from POA Core blockchain for analytics (e.g. blocks mined and list of transactions from specific POA address) via RPC and it’s timing out even for a single page with an offset of 1 (i.e. asking for just one item).
Remove grouping by number, timestamp
=> Improve "get mined blocks" query performance

CHANGELOG.md, apps/block_scout_web/assets/css/_helpers.scss, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/explorer/lib/explorer/smart_contract/reader.ex
Error at "Read contract" page if a contract contains bytes array type.
```
blockscout     | Request: GET /smart_contracts?hash=0xe7d982c6554e490ee707144d2f38a1c1ca3ccaae&type=regular&action=read
blockscout     | ** (exit) an exception was raised:
blockscout     |     ** (ArgumentError) argument error
blockscout     |         :erlang.byte_size([<<238, 151, 199, 221, 46, 115, 76, 242, 52, 194, 186, 13, 131, 167, 70, 51, 225, 172, 127, 200, 169, 253, 119, 159, 132, 151, 160, 16, 156, 113, 185, 147>>, <<165, 241, 91, 31, 169, 32, 187, 219, 194, 143, 93, 120, 94, 82, 36, 227, 166, 110, 181, 247, 212, 9, 45, 201, 186, 130, 213, 229, 174, 58, 188, 135>>, <<94, 248, 58, 217, 85, 144, 51, 230, 233, 65, 219, 125, 124, 73, 90, 205, 206, 97, 99, 71, 210, 142, 144, 199, 206, 71, 203, 252, 252, 173, …
```
=> Fix read contract bytes array type output

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/schema/types.ex
Fixes https://github.com/poanetwork/blockscout/issues/3208
Internal server error querying internal transactions at an address if *first*, *last* params are not specified
Add missing *complexity* function clause
=> GraphQL: fix internal server error at request of internal transactions at address

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain/supply/token_bridge_test.exs, apps/explorer/test/explorer/chain_test.exs
Revert reason is not shown for transactions at xDai instance
https://blockscout.com/poa/xdai/tx/0x4600d60565943c10b5486953a406de6e04612f62b2c590a16c4a72af9d658555/internal_transactions
- `gas_price` -> `gasPrice` in *eth_call* request
- parse with "Reverted prefix"
- decode message from response of eth_call
=> Fix revert reason message detection

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block_transaction/404.html.eex
The same issue as here https://github.com/poanetwork/blockscout/pull/3192 but for "Block not found" page.
Add app.js to "Block not found" page.
=> Allow interaction with navbar menu at block-not-found page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/notifier.ex
An error in live update of token transfers notifier
```
2020-08-06T08:22:52.780 [error] GenServer BlockScoutWeb.RealtimeEventHandler terminating
** (Ecto.MultipleResultsError) expected at most one result but got 3 in query:
from t0 in Explorer.Chain.TokenTransfer,
where: t0.transaction_hash == ^%Explorer.Chain.Hash{byte_count: 32, bytes: <<67, 97, 100, 11, 67, 162, 176, 10, 231, 126, 89, 195, 220, 251, 96, 53, 204, 213, 38, 200, 242, 204, 234, 212, 187, 138, 16, 229, 188, 33, 236, 227>>} and t0.token_contract_address_hash == ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<184, 26, 254, 39, 193, 3, 188, 212, 47, 64, 38, 207, 113, 154, 246, 216, 2, 146, 135, 101>>}
(ecto 3.3.4) lib/ecto/repo/queryable.ex:115: Ecto.Repo.Queryable.one/3
(block_scout_web 0.0.1) …
```
=> Fix notifier query for live update of token transfers

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex
- Search by the name with whitespaces is not allowed
- results are not ordered
- Allow searching by several words (in case if name is composite)
- Order search results by holders count in descendant order
- Return `name (symbol)` instead of name in the dropdown
- unlimited searching results (previously, max 10 items)
=> Improve search: allow search with space, order by token holders in descendant order

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex
The compilation is failed for contracts which have constructor arguments, compiled with 0.5.x compilers and experimental features are enabled.
- Refactoring of update introduced in https://github.com/poanetwork/blockscout/pull/3202 for more stable verification
=> Fix for the contract verifiaction for solc 0.5 family with experimental features enabled

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/rpc_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
Probably, caused by Phoenix minor upgrade from 1.4 to 1.5 in https://github.com/poanetwork/blockscout/pull/3143
https://blockscout.com/poa/core/api?module=stats&action=coinsupply returns
```
{
"message": "Something went wrong.",
"result": null,
"status": "0"
}
```
=> Fix coin supply api edpoint

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
Internal server error for reading method if ABI consists of multiple methods with the same name
Replace function_name with method_id to a better search of the target method to call
=> Refine contract method signature detection for read/write feature

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex
https://github.com/poanetwork/blockscout/issues/735
BlockScout displays all tabs at address page even if there are no items under the tab.
Hide next tabs if no items:
- Token Transfers
- Tokens
- Logs
- Blocks Validated
=> Hide address page tabs if no items

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
Incorrect ABI decoding of address in tuple output:
=> Fix incorrect ABI decoding of address in tuple output

CHANGELOG.md, apps/block_scout_web/assets/css/theme/_dai_variables.scss
2nd fix of #3240 implementation
=> Fix for invisible validator address at block page and wrong alert text color at xDai

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
Check, that block is not nil before retrieving timestamp at token transfer tile.
=> Token transfer: check that block exists before retrieving timestamp

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/contract_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block/reward.ex, apps/explorer/lib/explorer/chain/supply/token_bridge.ex, apps/explorer/lib/explorer/chain_spec/poa/importer.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/lib/explorer/staking/epoch_counter.ex, apps/explorer/lib/explorer/staking/pools_reader.ex, apps/explorer/lib/explorer/token/balance_reader.ex, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/lib/explorer/validator/metadata_retriever.ex, apps/explorer/package-lock.json, apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
https://blockscout.com/poa/sokol/address/0xD99dFe5F3253CDACd1C4eCe0Da524187fD9EacF4/contracts
Add method id as key in the list of contract methods instead of function name
=> Contracts read/write: method_id instead function_name as a key

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
*Adress* type output in the contract method call incorrectly decodes if the method contains inputs
Add missing clauses in function for parsing of output - support *:address* atoms
=> Fix encoding of address output if function input exists

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex, apps/indexer/lib/indexer/fetcher/token_updater.ex
Need possibility for requesting new token metadata frequenter than once per hour
Change denomination of *stream_cataloged_token_contract_address_hashes* function's time input from hours to minnutes.
=> Open possibility to set token metadata updater interval less than hour

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
Resolves https://github.com/poanetwork/blockscout/issues/3255
https://github.com/poanetwork/blockscout/issues/3255#issuecomment-683247410
Parse empty input value for array input type in contract interactions
=> Handle empty array type input

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/token_total_supply_on_demand.ex, apps/indexer/lib/indexer/supervisor.ex
Resolves https://github.com/poanetwork/blockscout/issues/3267
Token total supply doesn't update with the new tokens mint/burn
On-demand token metadata update fetcher is added. It triggers when someone opens a token page
=> Token total supply on-demand fetcher

CHANGELOG.md, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/bridged_token.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/indexer/lib/indexer/transform/token_transfers.ex
Total supply doesn't updates through indexing fetchers. Currently, it updates only by on-demand fetcher https://github.com/poanetwork/blockscout/pull/3268.
Add token metadata updater to token transfer parsing method if *to* or *from* of token transfer is *burn_address*. Thus, token supply will be updated with every burn or mint of tokens.
=> Update token metadata at burn/mint events

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block/reward.ex, apps/explorer/lib/explorer/chain/token.ex
Resolves https://github.com/poanetwork/blockscout/issues/3262
Worker missed some tokens to set bridged status for them.
This PR is aimed to increase the fault-tolerance of the worker. *Bridged* status will not be processed until metadata of corresponding transaction or corresponding internal transactions will not appear in the DB.
=> Bridged tokens status fetcher refactoring

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
Nifty.Ink token images are not displayed in Blockscout
Extend parsing function of token instance's metadata fetcher in order to support ipfs URIs
=> Support of fetching of NFT tokens metadata from IPFS

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/assets/js/lib/smart_contract/write.js, apps/block_scout_web/lib/block_scout_web/templates/icons/_inactive_icon.html.eex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Improve UX of contract's write functionality
Display address to which contract's write page currently connected. Also, take into account *accountsChanged* events.
=> Write contract: display currently connected address

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/coin_balance.ex
Current query in *fetch_coin_balance* function causes performance issues.
In order to address the performance of the query replace
```
SELECT a0."block_number", a0."value", a0."value_fetched_at", a0."inserted_at", a0."updated_at", a0."address_hash", value - coalesce(lag(value, 1) over (order by block_number), 0), b1."timestamp" FROM "address_coin_balances" AS a0 INNER JOIN "blocks" AS b1 ON a0."block_number" = b1."number" WHERE (a0."address_hash" = '\...') AND (a0."block_number" <= ...) ORDER BY a0."block_number" DESC LIMIT 1;
```
with
```
SELECT c."block_number", c."value", c."value_fetched_at", c."inserted_at", c."updated_at", c."address_hash", value - coalesce(lag(value, 1) over (order by block_number), 0) from (select a0."block_number", a0."value", a0."value_fetched_at", …
```
=> Fix fetch_coin_balance query: coin balance delta

CHANGELOG.md, apps/indexer/config/dev/besu.exs, apps/indexer/config/dev/ganache.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/dev/parity.exs, apps/indexer/config/dev/rsk.exs, apps/indexer/config/prod/besu.exs, apps/indexer/config/prod/ganache.exs, apps/indexer/config/prod/geth.exs, apps/indexer/config/prod/parity.exs, apps/indexer/config/prod/rsk.exs
If *ETHEREUM_JSONRPC_WS_URL* is provided but it is empty, the application still tries to connect via websocket endpoint. Relevant for AWS Marketpace CFT deployment.
If `ETHEREUM_JSONRPC_WS_URL` is an empty string, switch to RPC endpoint polling.
=> Switch to RPC endpoint polling if ETHEREUM_JSONRPC_WS_URL is an empty string

CHANGELOG.md, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/chain/transaction/history/transaction_stats.ex, apps/explorer/lib/explorer/chain/wei.ex, apps/explorer/lib/explorer/exchange_rates/token.ex
The errors of the next types periodically appear:
1. 
```
2020-09-10T09:28:06.463 [error] GenServer #PID<0.2423.0> terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Explorer.ExchangeRates.Token{available_supply: #Decimal<279261188.720888>, btc_value: #Decimal<0.000002396024029452239812522812910>, id: "poa-network", last_updated: ~U[2020-09-10 09:24:20.408Z], market_cap_usd: #Decimal<6824341>, name: "POA Network", symbol: "POA", total_supply: #Decimal<279261188.720888>, usd_value: #Decimal<0.02459655>, volume_24h_usd: #Decimal<551215>} of type Explorer.ExchangeRates.Token (a struct), Jason.Encoder protocol must always be explicitly implemented.
If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON: …
```
=> Eliminate protocol Jason.Encoder not implemented for... error

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/besu/fetched_beneficiaries.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
```
2020-09-11T10:37:28.429 application=indexer fetcher=block_catchup first_block_number=11937842 last_block_number=11937840 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.FetchedBeneficiaries.get_address_type/2
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:172: EthereumJSONRPC.Parity.FetchedBeneficiaries.get_address_type("external", 21)
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:156: EthereumJSONRPC.Parity.FetchedBeneficiaries.trace_to_params_set/3
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:132: anonymous fn/3 in EthereumJSONRPC.Parity.FetchedBeneficiaries.traces_to_params_set/2
(elixir 1.10.3) lib/enum.ex:3383: anonymous fn/3 in Enum.reduce/3 …
```
=> Support unlimited number of external rewards

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
Eliminate error like this
```
Request: GET /tokens/0x7D37700d88D5258e6Ca100D2694dD87A49101412/instance/3/token-transfers
** (FunctionClauseError) no function clause matching in String.Break.trim_leading/1
(elixir 1.10.3) lib/elixir/unicode/properties.ex:298: String.Break.trim_leading(nil)
(elixir 1.10.3) lib/string.ex:1177: String.trim/1
(block_scout_web 0.0.1) lib/block_scout_web/views/tokens/instance/overview_view.ex:51: BlockScoutWeb.Tokens.Instance.OverviewView.external_url/1
(block_scout_web 0.0.1) lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex:66: BlockScoutWeb.Tokens.Instance.OverviewView."_details.html"/1
(block_scout_web 0.0.1) lib/block_scout_web/templates/tokens/instance/transfer/index.html.eex:2: …
```
=> Token instance: check if external_url is not null before trimming

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
https://github.com/poanetwork/blockscout/pull/3236
some pages of unverified contracts are not opened on tie due to long request for searching of verified contract twins
Replace left join with inner join in the target query
=> Address contract twins feature performance

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/publisher.ex, apps/explorer/lib/explorer/smart_contract/solc_downloader.ex, apps/explorer/lib/explorer/smart_contract/solidity/compiler_version.ex, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/test/explorer/smart_contract/verifier_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/3300
Blockscout doesn't store actual compiler version for a verified contract if it was verified with the `latest` compiler version option.
function `get_strict_compiler_version/1` is added, which replaces `latest` with the current latest version of the compiler
Chore:
- If `latest` option selected, download compiler even if `latest.js` was already downloaded before because it can represent the previous version of the compiler.
- Do not try to verify with different EVM versions if selected compiler version doesn't match version stored in the bytecode or if contract name is wrong: return from array reducing instead from the first try.
- Fix verification for some `nightly` compiler versions.
=> Replace "latest" compiler version with the actual one

CHANGELOG.md, apps/explorer/lib/explorer/chain/supply/token_bridge.ex
"POA20" -> "POA"
"yDAI+yUSDC+yUSDT+yTUSD" -> "yCurve"
=> Replace symbol for some tokens to be able to find price in CoinGecko for OmniBridge balance

CHANGELOG.md, apps/block_scout_web/assets/css/theme/_dai_variables.scss
Invisible tokens dropdown on address page
Fix color of the tokens dropdown link in case of xDai
=> Fix xDai styles: invisible tokens on address

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/css/theme/_dai_variables.scss, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
CoinGecko returns nil `last_updated` property from some coins. We should handle it.
Handle nil values in the properties from the response on the request of the price of any token from CoinGecko.
=> Handle nil values from response of CoinGecko price API

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/counters/bridge.ex
Absence of allowability to easily disable bridge market cap updater
`DISABLE_BRIDGE_MARKET_CAP_UPDATER ` introduced
=> Environment variable to disable Bridge market cap updater

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Extended processing of unexpected responses from the archive node fore Balancer-like bridged token custom metadata processor.
=> Safer balancer like token custom metadata extraction

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/etherscan/logs.ex
- The response of logs list api endpoint doesn't contain `0x` prefix
- *blockNumber* returns *transactionIndex* and vise-versa
Example:
https://blockscout.com/poa/xdai/api?module=logs&action=getLogs&fromBlock=11262794&toBlock=latest&address=0x481c034c6d9441db23Ea48De68BCAe812C5d39bA&topic0=0x3c798bbcf33115b42c728b8504cff11dd58736e9fa789f1cda2738db7d696b2a&topic1=0x00000000000000000000000050d967fd81ad09befb6ff11e8ac6062a3ce11eb1&topic0_1_opr=and
```
{"address":"0x481c034c6d9441db23ea48de68bcae812c5d39ba","blockNumber":"1","data":"0x00000000000000000000000000000000000000000000001f2bba5d84f99c0000","gasPrice":"0","gasUsed":"27D04","logIndex":"1","timeStamp":"5BBBA539","topics":["0x3c798bbcf33115b42c728b8504cff11dd58736e9fa789f1cda2738db7d696b2a","0x00000000000000000000000050d967fd81ad09befb6f …
```
=> Fix logs list API endpoint response

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/coin_balance_daily.ex, apps/explorer/lib/explorer/chain/import.ex, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod/geth.exs, apps/indexer/lib/indexer/fetcher/coin_balance.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/transform/address_coin_balances_daily.ex
Multiple errors if run Blockscout with non-archive Ethereum node
Catching of various errors
=> Handle various indexer fetchers errors in setup with non-archive node

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/bridged_tokens_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex
An error like this on loading of bridged tokens list with the length > *page_size*:
```
blockscout-xdai    | Request: GET /bridged-tokens?type=JSON
blockscout-xdai    | ** (exit) an exception was raised:
blockscout-xdai    |     ** (FunctionClauseError) no function clause matching in BlockScoutWeb.Chain.paging_params/1
blockscout-xdai    |         (block_scout_web 0.0.1) lib/block_scout_web/chain.ex:215: BlockScoutWeb.Chain.paging_params([%Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, bridged: true, cataloged: true, contract_address: %Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: %Explorer.Chain.Data{bytes: <<96, 128, 96, 64, 82, 96, 4, 54, 16, 96, 62, 87, 99, 255, 255, 255, 255, 124, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
```
=> Fix pagination for bridged tokens list page

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/counters/address_transactions_counter.ex
1. Address transactions counter query is slow.
2. If there are more than 10_000 transactions, UI displays `>= 10000` instead of exact number
- Add caching of transactions counter at the address.
- Remove 10_000 query limit.
- A cache is expired if it was updated more than 1 hour ago by default.
- `ADDRESS_TRANSACTIONS_CACHE_PERIOD` env var is introduced to manage address transactions counter cache update period (in seconds).
=> Caching of address transactions counter, remove query 10_000 rows limit

CHANGELOG.md, apps/explorer/lib/explorer/counters/bridge.ex
The appearance of error like this
```
Request: GET /
** (ArgumentError) argument error
(stdlib 3.12.1) :ets.insert(:bridges_market_cap, {"current_market_cap_from_omni_bridge", #Decimal<0E-18>})
(explorer 0.0.1) lib/explorer/counters/bridge.ex:152: Explorer.Counters.Bridge.update_total_omni_bridge_market_cap_cache/0
(explorer 0.0.1) lib/explorer/chain/supply/token_bridge.ex:60: Explorer.Chain.Supply.TokenBridge.market_cap/1
(block_scout_web 0.0.1) lib/block_scout_web/templates/chain/show.html.eex:66: BlockScoutWeb.ChainView."show.html"/1
(phoenix 1.5.4) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
(phoenix 1.5.4) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
(phoenix 1.5.4) lib/phoenix/controller.ex:776: …
```
=> MarketCap calculation: check that ETS tables exist before inserting new data or lookup from the table

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
=> Fix validated transactions visibility page

CHANGELOG.md, apps/block_scout_web/mix.exs, mix.lock
Websocket subscription to Ethereum node doesn't work
Downgrade *websocket_client* dependency down to *1.3.0* (from *1.4.2*)
=> Repair websocket subscription

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/solc_downloader.ex
`https://ethereum.github.io/solc-bin/bin/soljson-#{version}.js` URL to download Solc binary doesn't work for the version of compiler >= 0.7.2
Change Solc compiler download URL to `https://solc-bin.ethereum.org/bin/soljson-#{version}.js`. It is officially supported primary way https://gitter.im/ethereum/solidity-dev?at=5f8418f402e81701b017f522.
=> Change Solc binary downloader path to official primary supported path

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
Too much white space on (Bridged) Token's list page's header:
=> Make (Bridged) Tokens' list page's header more compact

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address/logs.js
Address' page logs search doesn't work causing `Failed to load resource: net::ERR_TOO_MANY_REDIRECTS`
Set checksummed address as a value for *address_id* param for `/search-logs` endpoint
=> Fix logs search on address page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
ERC-721 inventory pages 1+ failed to open
Do not apply checksum to checksummed address for pagination of inventory
=> Fix inventory tab pagination

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
Wrong encoding of *bytes* output
=> Contract interaction: fix encoding of bytes output

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/bridged_tokens_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/tokens_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs, apps/explorer/lib/explorer/chain.ex
- Some tokens are missing on the 2nd page of bridged tokens list
- Numeration of the items starts with 1 on every page (tokens list, bridged tokens list, addresses list)
- Fix pagination query filtering by ordered token name
- Add items count on the previous pages in the query for the next page to account it in numeration
=> Fix tokens list pagination

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Caused by the implementation of https://github.com/poanetwork/blockscout/pull/3333
Eliminate permanent all pages' dark body background together with eliminating of flickering at transactions page of Dark forest contract
=> Fix dark body background

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/_coin_balances.html.eex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex
Users ask ability to drill down to transaction details from coin balance history page
https://discord.com/channels/502416149343109121/502432256011272195/763889220887904326
=> Tx hash in EOA coin balance history

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/notifier.ex
Fix errors like this:
```
2020-10-15T15:27:31.081 [error] GenServer BlockScoutWeb.RealtimeEventHandler terminating
from t0 in Explorer.Chain.TokenTransfer,
where: t0.transaction_hash == ^%Explorer.Chain.Hash{byte_count: 32, bytes: <<110, 29, 80, 134, 186, 27, 182, 59, 198, 16, 180, 207, 190, 124, 60, 247, 170, 147, 92, 7, 10, 117, 1, 68, 75, 74, 82, 59, 168, 25, 239, 184>>} and t0.token_contract_address_hash == ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 2, 60, 205, 31, 246, 242, 4, 92, 51, 9, 118, 142, 173, 158, 104, 249, 120, 246, 225>>} and t0.log_index == ^3
(ecto 3.3.4) lib/ecto/repo/queryable.ex:115: Ecto.Repo.Queryable.one/3
(block_scout_web 0.0.1) lib/block_scout_web/notifier.ex:144: anonymous …
```
=> Fix token transfer realtime fetcher

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/assets/js/pages/admin/tasks.js, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Endless
Change condition to show dropdown in *loadTokenBalance* function
=> Fix tokens dropdown appearance

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
Caused by changing of implementation of Contract reader for Staking Dapp
=> Contract reader: Address output fix

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan_test.exs
There are some tests which are unstable in Github Actions CI
=> Stabilize tests execution in Github Actions CI

CHANGELOG.md, apps/block_scout_web/assets/css/components/_new_smart_contract.scss, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
Width of Loading button is less than *Verify & Publish*:
=> Fix Verify contract loading button width

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex
Some contracts cannot be verified because of unmatched constructor arguments
Improve procedure to find constructor arguments
=> Improve contracts verification: refine constructor arguments extractor

CHANGELOG.md, apps/block_scout_web/assets/css/theme/custom_contracts/_dark-forest-theme.scss
Dark background applied for opened modal window.
Apply dark background for modals only for Dark forest game theme
=> Eliminate dark background except Dark forest theme

CHANGELOG.md, apps/block_scout_web/assets/css/_helpers.scss, apps/block_scout_web/assets/css/components/_label.scss, apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
Horizontal scroll in Tokens table if a long token name appears in the list
=> Fix horizontal scroll in Tokens table

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
An error like this:
```
2020-10-20T12:47:04.925 [error] #PID<0.629.6> running BlockScoutWeb.Endpoint (connection #PID<0.628.6>, stream id 1) terminated
Server: 147.135.46.163:80 (http)
Request: GET /address/0x0B02534634092077Fbf73431867DB83A7B008084/coin-balances?type=JSON
from b0 in Explorer.Chain.Block,
where: b0.number == ^12609315,
select: b0.timestamp
(ecto 3.3.4) lib/ecto/repo/queryable.ex:115: Ecto.Repo.Queryable.one/3
(explorer 0.0.1) lib/explorer/chain.ex:4390: Explorer.Chain.address_to_coin_balances/2
(block_scout_web 0.0.1) lib/block_scout_web/controllers/address_coin_balance_controller.ex:23: BlockScoutWeb.AddressCoinBalanceController.index/2
(block_scout_web …
```
=> Fix find block timestamp query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Prevent terminating of tokens/contracts process
```
Request: GET /token-autocomplete?q=https%3A%2F%2Fcircles.garden%2Fprofile0x4625d7b6ba483734f629d2f2d95d6b589dba4cd3
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error in tsquery: "https://circles.garden/profile0x4625d7b6ba483734f629d2f2d95d6b589dba4cd3:*"
(ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5
(ecto 3.3.4) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
(ecto 3.3.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
(block_scout_web 0.0.1) lib/block_scout_web/controllers/chain_controller.ex:101: BlockScoutWeb.ChainController.token_autocomplete/2 …
```
=> Prevent terminating of tokens/contracts process

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
Transformation of nested inputs like array from an array into form' view in contract method cause application Internal server error
Handling of nested input types
=> Fix contract nested inputs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
There are no links to contract libraries. Its hash
is plain text
=> Add links to contract libraries

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Organize Tokens header and top pagination in one line
Chore:
Token transfers tab: replace list header from "Transactions" with "Token transfers"
=> Make tokens list header compact

CHANGELOG.md, apps/explorer/lib/explorer/known_tokens/known_tokens.ex
Eliminate error like this:
```
Request: GET /address/0xA6452911d5274e2717BC1Fa793b21aB600EC9133/token-balances
** (ArgumentError) argument error
(stdlib 3.12.1) :ets.lookup(:known_tokens, "CRC")
(explorer 0.0.1) lib/explorer/known_tokens/known_tokens.ex:97: Explorer.KnownTokens.lookup/1
(explorer 0.0.1) lib/explorer/market/market.ex:25: Explorer.Market.get_known_address/1
(explorer 0.0.1) lib/explorer/market/market.ex:55: Explorer.Market.add_price/1
(explorer 0.0.1) lib/explorer/market/market.ex:65: Explorer.Market.add_price/1
(elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
(elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
(block_scout_web 0.0.1) lib/block_scout_web/controllers/address_token_balance_controller.ex:13: …
```
=> Check ets table exists for known tokens

.dialyzer-ignore, CHANGELOG.md, apps/explorer/config/config.exs
Finalization of https://github.com/poanetwork/blockscout/pull/3384
=> Fix gas price usage counter

CHANGELOG.md, apps/block_scout_web/assets/css/components/_custom_tooltips.scss, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
Total txs info icon is not vertically centred in mobile view:
=> Fix total tx info icon placement in mobile view

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/exchange_rates/source.ex, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
Eliminate error and process terminating when exchange rates request is throttled:
```
** (FunctionClauseError) no function clause matching in Access.get/3
(elixir 1.10.3) lib/access.ex:284: Access.get("Throttled\n", "error", nil)
(explorer 0.0.1) lib/explorer/exchange_rates/source.ex:36: Explorer.ExchangeRates.Source.fetch_exchange_rates_request/2
(explorer 0.0.1) lib/explorer/chain/supply/token_bridge.ex:191: Explorer.Chain.Supply.TokenBridge.get_current_price_for_bridged_token/1
(explorer 0.0.1) lib/explorer/counters/bridge.ex:193: anonymous fn/1 in Explorer.Counters.Bridge.consolidate/0
(elixir 1.10.3) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
(elixir 1.10.3) lib/enum.ex:783: Enum.each/2
(explorer 0.0.1) lib/explorer/counters/bridge.ex:192: …
```
=> Handle exchange rates request throttled

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex
Export of token transfers to CSV is broken at *Tokens* tab of address page
Replace address with the checksummed address in `/token-transfers-csv` request
=> Fix Token transfers CSV export

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
If a block has multiple transactions and block's first transaction is failed Blockscout marks all internal transactions in that block as failed too even if their parent transactions are not failed.
Fix function of searching failed parent trace to mark child traces as failed.
=> Fix procedure of marking internal transactions as failed

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http/httpoison.ex
Eliminate error:
```
2020-10-27T10:30:05.660 fetcher=block_catchup [error] Task Indexer.Block.Catchup.BoundIntervalSupervisor started from #PID<0.739.0> terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.HTTPoison.json_rpc/3
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http/httpoison.ex:11: EthereumJSONRPC.HTTP.HTTPoison.json_rpc(nil, ["{\"", [[] | "id"], "\":", "0", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34, [[] | "eth_getBlockByNumber"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "latest"], 34], 44, "false", 93], 125], [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]])
(ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/http.ex:29: EthereumJSONRPC.HTTP.json_rpc/2 …
```
=> Add EthereumJSONRPC.HTTP.HTTPoison.json_rpc function clause when URL is null

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
https://github.com/poanetwork/blockscout/issues/3395
Incorrect difficulty display: zeros at the end
Convert from Decimal to Integer before formatting
=> Fix difficulty display

CHANGELOG.md, apps/explorer/lib/explorer/chain/events/publisher.ex, apps/explorer/lib/explorer/chain/events/subscriber.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/test/explorer/staking/contract_state_test.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex
This PR adds an additional `:last_block_number` chain event which notifies subscribers about a new block immediately as soon as the block appears (using the existing `eth_subscribe` subscription).
This hotfix is mainly for Staking DApp that used `:blocks` chain event before. The `:blocks` is only broadcasted when a block is written to DB, so when there is a load to DB, the `:blocks` event appears with time delays. Due to that, the staking app may skip blocks which might lead to bugs in its UI. Since the Staking DApp doesn't use the block info from DB, it should receive a notification about the new block number immediately once the block appears through `eth_subscribe`.
These changes were successfully tested locally.
Add `last_block_number` to `@allowed_events` and …
=> Add :last_block_number realtime chain event

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Closes https://github.com/poanetwork/blockscout/issues/1555
Manage other explorers in the footer via env var
OTHER_EXPLORERS env var added and parsing of it.
Example of set:
`export OTHER_EXPLORERS='{"Etherscan": "https://etherscan.io/", "EtherChain": "https://www.etherchain.org/", "Bloxy": "https://bloxy.info/"}'`
=> Manage list of other explorers in the footer via env var

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex
Add functionality to display a link to Gnosis Safe app
=> Functions to enable GnosisSafe app link

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
https://github.com/poanetwork/blockscout/issues/3418
Contract reader: process tuple type input
=> Fix contract reader: tuple type

CHANGELOG.md, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/assets/css/theme/_dai_variables.scss, apps/block_scout_web/assets/css/theme/_dark-theme.scss, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_total_transfers.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/poanetwork/blockscout/issues/2526 https://github.com/poanetwork/blockscout/issues/2474
Display short NFT id if it is longer than 30 digits.
=> Fix display of long NFT IDs

CHANGELOG.md, apps/block_scout_web/assets/js/lib/token_balance_dropdown.js, apps/block_scout_web/assets/js/lib/token_balance_dropdown_search.js, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
https://github.com/poanetwork/blockscout/issues/1994
Tokens search functionality doesn't work in address tokens dropdown
=> Fix address tokens search

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs, apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs
Closes https://github.com/poanetwork/blockscout/issues/2536
Standardize token name definition if there is no name:
"0x" + "left::binary-size(6)" + "-" + "right::binary-size(6)"
An example: *0x8a55f3-b3b9a5*
=> Standardize token name definition, if name is empty

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Some transactions are marked with error status. Though, they are successful.
Check block_number in the process of setting the error from parent trace for the child traces.
=> Fix unnecessary tx error status

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/token_controller.ex, apps/block_scout_web/lib/block_scout_web/views/access_helpers.ex, apps/block_scout_web/test/block_scout_web/controllers/tokens/token_controller_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfers_counter.ex
Implement cache for token transfers counter since the request is periodically timing out in production.
`TOKEN_HOLDERS_COUNTER_CACHE_PERIOD` and `TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD` env variables introduced to identify cache invalidation period.
=> Token transfers counter cache

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex
Closes https://github.com/poanetwork/blockscout/issues/3324
Constructor arguments autodetection in API verify endpoint
=> Constructor arguments autodetection in API verify endpoint

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/block_count.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/transaction_count.ex
Default cache invalidation interval is too small for counters on the main page and request is dropped after 1 minute
Increase default cache invalidation interval up to 15 minutes, set an infinite timeout for counters queries.
=> Set infinity timeout and increase cache invalidation period for counters on the main page

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Function to find missing blocks ranges in given range misses some ranges.
For instance, current implementation of *missing_block_number_ranges* function returns empty range for this range `Explorer.Chain.missing_block_number_ranges(12859384..12859386)` even though _4 is not consensus block, _5 is missing.
```
dai=# select consensus, number from blocks where number in (12859383, 12859384, 12859385, 12859386);
consensus |  number
-----------+----------
t         | 12859383
f         | 12859384
t         | 12859386
(3 rows)
```
Fully rewrite the query and add tests which don't work with the previous algorithm.
=> Rewrite missing blocks range query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex
Token counters queries were timed out time to time
Set infinite timeouts for counters
=> Inifinite timeout for token counters

CHANGELOG.md, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/test/explorer/counters/average_block_time_test.exs
The current average block time calculation procedure doesn't account whether there are some missing blocks in the range causing an increase in average block time.
Current calculation function assumes that each block in the range is present and calculates the duration between those blocks. For instance, if we have block A and next block C with the _number_C_ = _number_A_ + 2 and block B is missing (or non-consensus) with the number = _number_A_ + 1, then the duration between A and C _duration_A_C_ ~= 2 * _duration_A_B_ which gives increasing in total duration.
In order to fix that it is suggested to divide the duration between two blocks into the diff between blocks numbers. It will allow avoiding increasing of avg block time if blocks are missing in the range.
=> Correct avg time calculation

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/js/lib/queue.js, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex, apps/block_scout_web/lib/block_scout_web/staking_event_handler.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/channels/stakes_channel_test.exs, apps/explorer/lib/explorer/chain/events/publisher.ex, apps/explorer/lib/explorer/chain/events/subscriber.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex
This improves blocks handling in the Staking DApp. Now the app can correctly handle possible block gaps and delays both on the client and server sides. Also, it should speed up the server side of the app as it now uses a separate thread for handling the `:staking_update` message (now it is handled by the `StakingEventHandler` instead of the `RealtimeEventHandler`).
These changes relate to https://github.com/poanetwork/blockscout/pull/3400 and https://github.com/poanetwork/blockscout/pull/3434.
=> Improve blocks handling in Staking DApp

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/assets/js/lib/smart_contract/write.js, apps/block_scout_web/assets/js/pages/address/logs.js
MetaMask will discontinue injecting `window.web3` object to the page https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3. We should handle this change.
Replace injected `window.web3` object with `window.ethereum`
Chore:
- refactor write contract functionality
=> Replace window.web3 with window.ethereum

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/claim_reward.js, apps/block_scout_web/assets/js/pages/stakes/constants.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/assets/js/pages/stakes/utils.js
There are MetaMask breaking changes: https://docs.metamask.io/guide/provider-migration.html
This PR uses the latest changes for Staking DApp JavaScript code.
=> Update Staking DApp scripts due to MetaMask breaking changes

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
Identifier of a token transfer tile is not unique since several transfers could be inside a single transaction. This causes an issue in the update of the token transfers list:
https://github.com/poanetwork/blockscout/blob/84741f3db5aba428c7820153579840f2aa4e790a/apps/block_scout_web/assets/js/lib/list_morph.js#L35
Add `log_index` to the identifier of a token transfer tile for token view.
=> Fix display of token transfers list at token page (fix unique identifier of a tile)

.tool-versions, CHANGELOG.md, apps/block_scout_web/assets/css/theme/_dai_variables.scss, apps/block_scout_web/assets/js/lib/async_listing_load.js, apps/block_scout_web/assets/js/lib/coin_balance_history_chart.js, apps/block_scout_web/assets/js/lib/history_chart.js, apps/block_scout_web/assets/js/lib/transaction_input_dropdown.js, apps/block_scout_web/assets/js/pages/favorites.js, apps/block_scout_web/assets/js/pages/layout.js, apps/block_scout_web/assets/js/pages/network-search.js, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/assets/package.json, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Fixes https://github.com/poanetwork/blockscout/issues/3456
Broken Firefox styles. Originally, the fix was introduced here https://github.com/poanetwork/blockscout/commit/b65d4672f12f12ed6e3e9d93a0db49fa79642819#diff-55e55e74851b2d314637173c23930a2fc6958746ad35d4da53b2271baf628aa7 but was lost during the manual merging of conflicts while rebasing Staking Dapp branch.
- Fix Firefox styles
- Node@14 as a default version
- var -> let, const
=> Client-side fixes: fix Firefox styles, Node@14, var -> let, const

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes.js
If MetaMask/Nifty wallet is not installed or not connected to xDai chain and someone opens Staking Dapp page, a warning appears. Let's remove it and leave it only on the buttons' click in order to not prevent to see validators list.
Add an additional input parameter `checkSupportedNetwork` for function `setNetwork` which enables/disables check of the supported network.
=> Do not check supported networks on application loading page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/smart_contract/solc_downloader.ex, apps/explorer/lib/explorer/smart_contract/solidity/compiler_version.ex, apps/explorer/test/explorer/chain_test.exs
https://github.com/poanetwork/blockscout/issues/3447
Contracts verification is broken for contracts from the genesis block.
If transaction and internal transaction are absent for a contract then use the contract's bytecode for verification.
=> Fix contract verification of precompiled contracts

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/explorer/lib/explorer/chain.ex
1. Call of a contract's fallback function returns an alert
2. Calls of GnosisProxy contract functions with parameters return the error:
```
2020-11-17T16:50:13.031 [error] #PID<0.6835.0> running BlockScoutWeb.Endpoint (connection #PID<0.6713.0>, stream id 9) terminated
Request: GET /smart-contracts/0x52a0110990C2047B1354b53Ef576f93f471D124F?function_name=isOwner&method_id=2f54bf6e&args%5B%5D=0xBDFdb9F56e7E11D51DB3c80604D09970C97445Fa
** (MatchError) no match of right hand side value: nil
(explorer 0.0.1) lib/explorer/smart_contract/reader.ex:353: Explorer.SmartContract.Reader.query_function/3
(block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:95: BlockScoutWeb.SmartContractController.show/2
(block_scout_web 0.0.1) …
```
=> Fix broken call of fallback function and call of Gnosis contract methods with parameters

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/token_exchange_rate.ex, apps/explorer/lib/explorer/chain/currency_helpers.ex, apps/explorer/lib/explorer/chain/supply/token_bridge.ex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/explorer/lib/explorer/counters/bridge.ex
Display sum USD value of tokens on the token holder's address page
`ADDRESS_TOKENS_USD_SUM_CACHE_PERIOD` env variable added for managing of cache invalidation period for USD value sum of tokens. The default value is 1 hour.
=> Display sum of tokens' USD value at tokens holder's address page

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Resolves https://github.com/poanetwork/blockscout/issues/3453
Add support of Autonity network
Whitelist additional block output parameters:
- `committedSeals`
- `committee`
- `pastCommittedSeals`
- `proposerSeal`
- `round`
=> Support of Autonity network

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/assets/js/pages/stakes/move_stake.js, apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js, apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex
Some Staking DApp code incorrectly worked with big numbers: it returned a number with scientific notation instead of a long number (as a string) in some cases.
=> Fix working with big numbers in Staking DApp

.github/workflows/config.yml, CHANGELOG.md, docker/Dockerfile, docker/Makefile
Resolves https://github.com/poanetwork/blockscout/issues/2852
Update Docker setup to be compatible with Erlang OTP 23
- install `rustc` for `ex_keccak` dependency
- python -> python3
- Postgres 12.4 -> 12.5
- Run migrations with `start` command even if Postgres container exists/started
=> Docker setup update to be compatible with Erlang OTP 23

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js
https://github.com/poanetwork/blockscout/issues/3486
Finalization of https://github.com/poanetwork/blockscout/pull/3494
=> Fix representation of contract write call input values before making a call

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/priv/contracts_abi/posdao/Token.json, apps/explorer/test/explorer/staking/contract_state_test.exs
I recently [updated](https://github.com/poanetwork/posdao-contracts/commit/40dea4e6adcd9f3980ba9bece0d315288a364912) the [StakingAuRa](https://github.com/poanetwork/posdao-contracts/blob/master/contracts/StakingAuRa.sol) contract so that it supports staking with `transferAndCall` function along with the `stake` function. We need this to switch POSDAO from the [non-bridged](https://blockscout.com/poa/xdai/tokens/0xAb84415fBB0D35abc08dee250356F19Bc37aBaeA/) STAKE token contract to the [bridged](https://blockscout.com/poa/xdai/tokens/0xb7D311E2Eb55F2f68a9440da38e7989210b9A05e/) one.
~Please, don't merge this until we switch the StakingAuRa contract to the new implementation. I'll let you know when that happens.~ Done: https://github.com/poanetwork/posdao-contracts/releases/tag/v0.1.9
=> Make Staking DApp work with transferAndCall function

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/block/rewards.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/indexer/lib/indexer/token_balances.ex
Closes https://github.com/poanetwork/blockscout/issues/3334
Eliminate deadlocks of 3 kinds on rows insertion to the next tables:
1. TokenBalances
Application logs:
```
2020-11-03T08:28:20.676 [error] Task Indexer.Block.Realtime.Fetcher started from #PID<0.23370.336> terminating
** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected
hint: See server log for query details.
Process 10575 waits for ShareLock on transaction 29941763; blocked by process 11516.
Process 11516 waits for ShareLock on transaction 29941630; blocked by process 10575.
(ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:521: Ecto.Adapters.SQL.insert_all/8
(ecto 3.3.4) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6 …
```
=> Token balances and rewards tables deadlocks elimination

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/explorer/package-lock.json
Fix for https://github.com/poanetwork/blockscout/pull/3497
A warning appears at contract's write function call without parameters
=> Fix write call without params

CHANGELOG.md, apps/block_scout_web/assets/js/lib/async_listing_load.js, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
Currently, when loading the Staking DApp it makes an async call (request) to load items several times because of duplicated `firstPageLoad` calls in `apps/block_scout_web/assets/js/lib/async_listing_load.js`. This PR adds an ability to not call the `firstPageLoad` when we don't need it. It can be turned on by a separate HTML attribute `data-no-first-loading` in a `div` with `data-async-load` attr for any module. This PR turns this on only for the `staking` module.
Without this PR we observe the pool list disappearing when using any tab within the Staking DApp UI because of the excess calls. They visually disappear until the next block arrives.
I think this also relates to other modules but propose to optimize it in separate PRs by removing excess requests when using the …
=> Fix Staking DApp first loading

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
https://github.com/poanetwork/blockscout/issues/2396
Overlapping of to/from address and value of token transfer inside a tile
=> Fix token trasfer's tile styles: prevent overlapping of long names

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
The left margin of balance's container is excessive in the mobile view.
Remove excessive left margin.
=> Fix left margin of balance card in mobile view

CHANGELOG.md, apps/block_scout_web/assets/js/lib/loading_element.js, apps/block_scout_web/assets/js/lib/modals.js, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/assets/js/pages/token_counters.js, apps/block_scout_web/assets/js/pages/verification_form.js
Fix QR code tooltip appearance in mobile view
The tooltip shouldn't appear in the mobile view
Manage the appearance of tooltip through Javascript
=> Fix QR code tooltip appearance in mobile view

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/explorer/lib/explorer/smart_contract/reader.ex
https://github.com/poanetwork/blockscout/issues/3486
1. https://gitter.im/poanetwork/blockscout?at=5fcdf6f567bf4438e12d0a52 internal server error when calling a method with multiple inputs
2. Square brackets are not allowed for an array input type. In order to provide the same experience for Remix users, it is suggested to allow square brackets.
1. Fix input data processing
2. Allow square brackets for an array input type
=> Allow brackets for arrays for contract input data, fix decoding for multiple inputs

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
```
Request: GET /smart-contracts?hash=0x47ed323d03cd3fff423f1200af2e2e3d823e8d0a&type=regular&action=read
blockscout     | ** (exit) an exception was raised:
blockscout     |     ** (Protocol.UndefinedError) protocol Enumerable not implemented for "" of type BitString. This protocol is implemented for the following type(s): Indexer.BoundQueue, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Flow, Map, MapSet, Function, HashDict, IO.Stream, File.Stream, List, Stream, Range, HashSet, Date.Range, GenEvent.Stream
blockscout     |         (elixir 1.10.4) lib/enum.ex:1: Enumerable.impl_for!/1
blockscout     |         (elixir 1.10.4) lib/enum.ex:141: Enumerable.reduce/3
blockscout     |         (elixir 1.10.4) lib/enum.ex:3383: …
```
=> Read contract: fix internal server error for method with empty output array

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex, apps/indexer/lib/indexer/supervisor.ex
Address page in some cases shows stale tokens balance.
As a patch (not a solid solution of the issue) on-demand token balance fetcher is introduced. With default stale balance window 24hrs.
=> Address token balance on demand fetcher

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
https://github.com/poanetwork/blockscout/issues/3523
Pools with the same stake are not ordered
Add descending order by stakes ration and ascending order by staking_address_hash in DB query
=> Order staking pools

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/explorer/package-lock.json, apps/explorer/package.json
Blockscout returns `odd-length string error` if a user provides trailing/leading whitespaces in input data when interacts with contract's reading methods.
Allow trailing/leading whitespace in input data of read-only methods of contracts
=> Allow trailing/leading whitespaces for inputs for contract read methods

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js
Closes https://github.com/poanetwork/blockscout/issues/3486
Double quotes re not allowed in input data of contract methods
=> Allow double quotes in input data of contract methods

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/css/components/_dropdown.scss, apps/block_scout_web/assets/css/theme/_dark-theme.scss, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Simplifying of procedure of adding trailing zeroes to (unsigned) integer input type.
=> Contract interaction: an easy setting of precision for integer input

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Finalization of https://github.com/poanetwork/blockscout/pull/3525
Run token balance on-demand fetcher in parallel non-blocking process via `Task. start_link`
=> Run token balance on-demand fetcher in parallel

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/contract_test.exs, apps/explorer/test/explorer/token/balance_reader_test.exs
Display revert reason in the result of the contract method call.
=> Revert reason in the result of contract's method call

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/css/theme/custom_contracts/_dark-forest-theme.scss, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/page_not_found_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_custom_view_df_title.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- DarkForest theme is not intended to be applied to token's instance page
- Support (0.4, 0.5) versions of DarkForest
=> DarkForest: apply theme to token instance, differentiate versions of DF

CHANGELOG.md, apps/block_scout_web/assets/css/components/stakes/_stakes.scss, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_title.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Display total number of delegators and total staked amount in Staking dApp
=> Staking dapp stats: total number of delegators, total staked amount

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
Method `getArtifact ` of DarkForest NFT contract returns internal server error:
```
2021-01-04T11:19:45.103 [error] #PID<0.1431.0> running BlockScoutWeb.Endpoint (connection #PID<0.1248.0>, stream id 10) terminated
Server: localhost:4000 (http)
Request: GET /smart-contracts/0x5cFbC3e179C48ccB3B3d35bAD6361972F2C5603B?function_name=getArtifact&method_id=8465ad44&args%5B%5D=80655615332912814281286268613438042255103875506825830758019774624527142298860
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for {80655615332912814281286268613438042255103875506825830758019774624527142298860, 996040386519514455547369964248641440971718171905442664266757499782684832, 2, 1, 1609747540, <<101, 112, 77, 187, 192, 10, 168, 130, 225, 223, 247, 185, 210, …
```
=> Fix contract's method's output of tuple type

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
3 menu items related to Staking Dapp:
The idea is to replace with a single menu item
=> Single Staking menu

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Display error if staking dapp is unhealthy (including a partial case of archive node is unhealthy).
Display error message if epoch_end_block is equal to 0.
=> Staking dapp: unhealthy state message

CHANGELOG.md, apps/block_scout_web/assets/css/components/_btn_dropdown_line.scss, apps/block_scout_web/assets/js/lib/async_listing_load.js, apps/block_scout_web/assets/js/pages/address/internal_transactions.js, apps/block_scout_web/assets/js/pages/address/token_transfers.js, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/assets/js/pages/address/utils.js, apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination_container.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/poanetwork/blockscout/pull/3559
Force to show a filter at filtered items list page if the items list is empty. It improves UX: users don't need anymore to refresh the page in order to see all items.
=> Force to show filter at the page where filtered items list is empty

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
Incorrect price of UNI token in xDai instance because of multiple tokens exist with UIN symbol from CoinGecko API list.
Create a mapping to correct token id for UNI token.
=> Correct UNI token CoinGecko ID

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex, apps/explorer/lib/explorer/chain/events/subscriber.ex, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex, apps/explorer/priv/contracts_abi/posdao/StakingAuRa.json, apps/explorer/priv/contracts_abi/posdao/ValidatorSetAuRa.json, apps/explorer/test/explorer/staking/contract_state_test.exs
Staking DApp requests information about pools and delegators (and rewrites the corresponding DB tables) on every block even when there are no changes in StakingAuRa and ValidatorSetAuRa contracts. This PR makes DApp only do that when some changes occurred. For that purpose, it uses the `lastChangeBlock` field from the contracts introduced in https://github.com/poanetwork/posdao-contracts/commit/ef9ccff0f11f09cf7671982ed6a035f7a9ce1e62
Also, this PR comments out the warning added in https://github.com/poanetwork/blockscout/pull/3576 (but doesn't remove it completely).
=> Reduce RPC requests and DB changes by Staking DApp

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/token_view.ex, apps/explorer/lib/explorer/chain.ex
Resolves https://github.com/poanetwork/blockscout/issues/3566
Lack of token holders API endpoint
A new token holders API endpoint with pagination added
An example of GET request:
`/api?module=token&action=getTokenHolders&contractaddress=0xB81AFe27c103bcd42f4026CF719AF6D802928765&page=1&offset=3`
An example of a response:
```
{"message":"OK","result":[{"address":"0xd0b6b13546f28ad8a083fcbaa3dc174ffbc46b75","value":"10000000000000000000000000"},{"address":"0x0039f22efb07a647557c7c5d17854cfd6d489ef3","value":"13237500999979000000000"},{"address":"0x9602686bf53a17baed60c48ba34ed4219a532381","value":"10100000000000000000000"}],"status":"1"}
```
=> Token holders API endpoint

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
Nested tuple outputs cause 500 server error.
- Process method call output recursively
- Add formatting of nested output types
=> Contract interaction: fix nested tuples in the output view, add formatting

CHANGELOG.md, apps/explorer/lib/explorer/validator/metadata_importer.ex
If validator's name is not from the metadata contract (hardcoded in DB), it wipes with empty name on the next scheduled update of metadata
Do not update metadata if name in contract's is empty
=> Prevent update validator metadata with empty name from contract

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/chain/cache/token_exchange_rate.ex, apps/explorer/lib/explorer/counters/address_gas_usage_counter.ex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/explorer/lib/explorer/counters/address_transactions_counter.ex, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfers_counter.ex, apps/explorer/lib/explorer/market/market_history_cache.ex
Fixes https://github.com/poanetwork/blockscout/issues/3544
Currently, the application should be recompiled after changing ETS cache period variables for various of caching processes.
```
ADDRESS_TOKENS_USD_SUM_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
ADDRESS_TRANSACTIONS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
MARKET_HISTORY_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
TOKEN_EXCHANGE_RATE_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
TOKEN_HOLDERS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
AVERAGE_BLOCK_CACHE_PERIOD (def 30min)
```
Allow redefining ETS cache period variables at …
=> Allow re-define cache period vars at runtime

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Closes https://github.com/poanetwork/blockscout/issues/3538
Contract method output parameters names are not displayed at the read page:
=> Display method output parameter name at contract read page

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex, apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/test/explorer/staking/contract_state_test.exs
This adds a new feature to Staking DApp to display `Annual Percentage Yield`. It will be shown in UI by separate columns (in the `Validators` tab and in the `Delegators` popup). For example (it is test screens without real values):
The `Delegators` popup will also display an approximate expected reward which will be accrued in tokens at the end of the current staking epoch.
The feature doesn't require any additional fields in the database.
=> Show APY for delegators in Staking DApp

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/priv/contracts_abi/posdao/StakingAuRa.json
This is a small refactoring PR that reflects the changes made in https://github.com/poanetwork/posdao-contracts/commit/2994441358329e2e725edd0c4dccf6812e8fbea0. It is part of big refactoring in POSDAO contracts to add there an ability for changing pool's stakingAddress/miningAddress. We'll be making the changes step-by-step in small portions like this one.
Please, don't merge and publish Blockscout release with these changes until we upgrade the `StakingAuRa` contract to apply [the changes](https://github.com/poanetwork/posdao-contracts/commit/2994441358329e2e725edd0c4dccf6812e8fbea0). I'll let you know once that happens.
=> POSDAO refactoring: use 'getDelegatorPools' getter instead of 'getStakerPools' in Staking DApp

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/smart_contract/publisher.ex
For some contracts, the max limit of 5 libraries for verification is not enough.
Increase max number of libraries up to 10 in contracts verification
=> Contracts verification up to 10 libraries

CHANGELOG.md, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex, apps/explorer/test/explorer/staking/contract_state_test.exs
This is a small refactoring PR that reflects the changes made in https://github.com/poanetwork/posdao-contracts/commit/73e04a44e74c4289c240d577d9cb6db2931e47c2 and https://github.com/poanetwork/posdao-contracts/commit/0f8bf7f61782abfadcebe0a5cc26e99305050894. It is part of big refactoring in POSDAO contracts to add there an ability for changing pool's stakingAddress/miningAddress. We'll be making the changes step-by-step in small portions like this one.
Please, don't merge and publish Blockscout release with these changes until we upgrade the `StakingAuRa` and `BlockRewardAuRa` contracts to apply the changes mentioned above. I'll let you know once that happens.
=> POSDAO refactoring: use zero address instead of staker address for certain cases

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
Resolve Internal server error caused by Int(x) type "0" value in the output of the contract method
=> Contract reader: fix int type output

CHANGELOG.md, apps/explorer/lib/explorer/counters/bridge.ex
```
2021-02-10T09:46:14.726 [error] GenServer Explorer.Counters.Bridge terminating
** (FunctionClauseError) no function clause matching in Explorer.Counters.Bridge.handle_info/2
(explorer 0.0.1) lib/explorer/counters/bridge.ex:92: Explorer.Counters.Bridge.handle_info({:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.2302>, :tls_connection, :undefined}, [#PID<0.10152.0>, #PID<0.10150.0>]}}, %{consolidate?: true})
(stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
(stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
(stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.2302>, :tls_connection, :undefined}, [#PID<0.10152.0>, #PID<0.10150.0>]}}
State: %{consolidate?: true}
```
Add default function clause for …
=> Ignore unrecognized messages in bridge counter processes

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex, apps/block_scout_web/test/block_scout_web/views/abi_encoded_value_view_test.exs
Error rendering view inn transactions decoding view.
=> Fix transaction decoding view: support tuple types

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js
Some old/legacy browsers don't support replaceAll method. For instance, [the native Android browser](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll).
Use regular expression mimicking `replaceAll` function if it is not supported.
=> Handle absence of replaceAll function in some old/legacy browsers

CHANGELOG.md, apps/explorer/lib/explorer/chain/supply/token_bridge.ex
Tokens with more holders should get the price first from CoinGecko. Requests of the price for other tokens may be rate-limited by CoinGecko.
=> Order bridged tokens in descending order by tokens holder for Omni bridge cap calculation

apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_table-loader.html.eex
Improve some of Elixir templates
- missing closing tag in `bridged_tokens/_tile.html.eex`
- check whether @total_supply param passed into `_table-loader.html.eex`
=> Improve templates

CHANGELOG.md, apps/explorer/lib/explorer/chain/bridged_token.ex, apps/explorer/lib/explorer/chain/cache/token_exchange_rate.ex, apps/explorer/lib/explorer/chain/supply/token_bridge.ex, apps/explorer/lib/explorer/counters/bridge.ex, apps/explorer/lib/explorer/market/market.ex, apps/explorer/priv/repo/migrations/20210226154732_add_exchange_rate_column_to_bridged_tokens.exs
Bridge market cap updater can not get token price reliably from CoinGecko for the whole bridged tokens list
Save exchange rate of token to the DB and gets old value from DB, if it is nil or 0 at CoinGecko scheduled update.
=> Store bridged token price in the DB

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Images from IPFS doesn't show on the token instance page
=> Token instance image IPFS link display fix

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
=> Reorganize staking buttons

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_table-loader.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex
Fix tokens list page table loader: number of columns in loader should match the number of columns in the table
=> Table loader fix

CHANGELOG.md, apps/indexer/lib/indexer/calc_lp_tokens_total_liquidity.ex, apps/indexer/lib/indexer/set_omni_bridged_metadata_for_tokens.ex
Increase lp tokens calc process re-check interval from 1 minute to 10 minutes
Increase omni bridge metadata imported process re-check interval from 10 minutes to 20 minutes
=> Increase LP tokens calc process re-check interval

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/endpoint.ex
>2021-03-16T08:44:03.648 application=ethereum_jsonrpc fetcher=coin_balance count=7 [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.
>2021-03-15T18:06:00.692 application=ethereum_jsonrpc fetcher=block_realtime block_number=15027643 [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.
Increase acceptable max length of the request up to 20Mb. The default is 8Mb (https://hexdocs.pm/plug/Plug.Parsers.html#module-options)
=> Fix 413 Request Entity Too Large returned from single request batch

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/bridged_tokens_controller.ex
>Request: GET /bridged-tokens
** (ArgumentError) assign @destination not available in eex template.
=> Missing @destination in bridged-tokens template

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_warning.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Closes https://github.com/poanetwork/blockscout/issues/1609
Manage Blockskout alerts
Enables explorer alert managing through ENV variables:
`SHOW_MAINTENANCE_ALERT` - true/false enables announcement at the top of explorer
`MAINTENANCE_ALERT_MESSAGE` - Message text of the alert
Enables staking dapp alert managing through ENV variables:
`SHOW_STAKING_WARNING` - true/false enables announcement inside Staking Dapp
`STAKING_WARNING_MESSAGE` - Message text of the alert
Chore:
Add env var `DISABLE_POS_STAKING_IN_MENU` for management of enabling/disabling of Staking Dapp in the menu
=> Application alerts management: whole explorer, staking dapp

apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
We faced method handler crashed error in Kotti
```
[%{code: -32000, data: %{block_number: 1743966, transaction_hash: "0x0e439d91608cfcd2ff89ca9345bb8a93a4f1522fe82a0666e21f02afa7011848", transaction_index: 0}, message: "method handler crashed"}]
```
I found similar issues but there is no solution yet
https://github.com/poanetwork/blockscout/issues/3234
https://github.com/poanetwork/blockscout/issues/2445
But I found that in our case in Kotti this transactions is contact creation tx. But tx doesn't has input (so no contract code). 
```
{
"jsonrpc": "2.0",
"method": "eth_getTransactionByHash",
"params": ["0x0e439d91608cfcd2ff89ca9345bb8a93a4f1522fe82a0666e21f02afa7011848"],
"id": 83
}
{
"jsonrpc": "2.0",
"id": 83,
"result": {
"blockHash": …
```
=> Fix trace internal transactions for create contract without code

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/indexer/config/dev.exs, apps/indexer/config/prod.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/pending_transactions_sanitizer.ex, apps/indexer/lib/indexer/supervisor.ex, config/config.exs
Resolves https://github.com/poanetwork/blockscout/issues/3665
During the restart of the application, ongoing block import could result in the appearing of block with 0 transactions when actually it contains transactions. 
In order to eliminate the consequences of broken import, `Indexer.PendingTransactionsSanitizer` process is added which starts every 3 hours. It gets the list of pending transactions from the DB. It requests the archive node for each transaction hash from the list and if a transaction already included in the block, the process invalidates that block in Blokcsocut DB in order to re-fetch it. The process also removes pending transactions from the DB if they are dropped from the node.
=> Pending transactions sanitizer process

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex, apps/explorer/priv/contracts_abi/posdao/BlockRewardAuRa.json, apps/explorer/priv/contracts_abi/posdao/README.md, apps/explorer/priv/contracts_abi/posdao/StakingAuRa.json, apps/explorer/priv/contracts_abi/posdao/ValidatorSetAuRa.json, apps/explorer/test/explorer/staking/contract_state_test.exs
`1.` This is a refactoring PR that continues https://github.com/poanetwork/blockscout/pull/3612 and https://github.com/poanetwork/blockscout/pull/3616 and reflects the changes made in https://github.com/poanetwork/posdao-contracts/compare/0f8bf7f61782abfadcebe0a5cc26e99305050894...79803fdb40c5e106f60ab4b200d0cdf9a1714859.
It is a final part of big refactoring in POSDAO contracts to add there an ability for changing pool's staking address and/or mining address.
The `changeStakingAddress` and `changeMiningAddress` features weren't added to Staking UI, so this is refactoring only.
This PR doesn't change the DB structure.
Please, don't merge and publish Blockscout release with these changes until we upgrade POSDAO contracts to apply the changes. I'll let you know once that happens.
`2.` Also, …
=> POSDAO refactoring: use pool ID instead of staking address

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
From Discord:
> Hey frens, anyone know what this is showing?
https://blockscout.com/poa/xdai/api?module=stats&action=ethprice
Rename `ethprice` API endpoint to `coinprice` in order to eliminate confusion
=> Rename ethprice API endpoint

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/wei_ether_converter.js, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Resolves https://github.com/poanetwork/blockscout/issues/3654
Fix losing of value digits between wei conversions
=> Fix losing digits at value conversion back from WEI

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
Accept quoted numbers as an input for (u)int arrays inputs.
=> Allow double quotes for (u)int arrays inputs during contract interaction

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
>2021-03-21T15:36:54.476 application=block_scout_web request_id=Fm5llsNt_47yDO4AAEYE [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (UndefinedFunctionError) function nil.last_updated/0 is undefined\n    nil.last_updated()\n    (block_scout_web 0.0.1) lib/block_scout_web/views/api/rpc/stats_view.ex:31: BlockScoutWeb.API.RPC.StatsView.prepare_rates/1\n    (block_scout_web 0.0.1) lib/block_scout_web/views/api/rpc/stats_view.ex:23: BlockScoutWeb.API.RPC.StatsView.render/2\n    (phoenix 1.5.6) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n    (phoenix 1.5.6) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4\n    (block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/stats_controller.ex:1: …
=> Coinprice api endpoint: handle nil rates

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
> 2021-03-21T20:59:51.783 [error] GenServer Indexer.Fetcher.TokenBalanceOnDemand terminating
** (FunctionClauseError) no function clause matching in Decimal.new/1
(decimal 1.9.0) lib/decimal.ex:1181: Decimal.new(nil)
(indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:94: anonymous fn/3 in Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/4
(elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
(elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
(indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:78: Indexer.Fetcher.TokenBalanceOnDemand.fetch_and_update/4
(indexer 0.1.0) lib/indexer/fetcher/token_balance_on_demand.ex:53: Indexer.Fetcher.TokenBalanceOnDemand.handle_cast/2
(stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
(stdlib …
=> Token on-demand balance fetcher: handle nil balance

CHANGELOG.md, apps/explorer/config/config.exs
> 2021-03-21T19:39:34.473 [error] GenServer Explorer.Counters.AverageBlockTime terminating
** (ArgumentError) argument error
:erlang.send_after(nil, #PID<0.1135.0>, :refresh_timestamps)
(explorer 0.0.1) lib/explorer/counters/average_block_time.ex:59: Explorer.Counters.AverageBlockTime.handle_info/2
(stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
(stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
(stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :refresh_timestamps
Set 10 mins default period for average block time counter refresh interval
=> Set default period for average block time counter refresh interval

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/pending_transaction.ex
> 2021-03-21T20:59:55.941 fetcher=pending_transaction [error] Task #PID<0.13429.13> started from Indexer.Fetcher.PendingTransaction terminating
** (CaseClauseError) no case clause matching: {:error, {:bad_gateway, "https://xdai-archive-df.xdaichain.com"}}
(indexer 0.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
(elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
(stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.24088951/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
Args: []
Handle `{:error, {:bad_gateway, _}}` response in pending transactions fetcher
=> Handle bad gateway at pending transactions fetcher

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex
This PR removes some code temporarily added in https://github.com/poanetwork/blockscout/pull/3712 and adds a fix for `Explorer.Staking.ContractState` module which makes the module restart snapshotting procedure if there were `ChangedMiningAddress` or `ChangedStakingAddress` event emitted. The re-snapshotting is required to re-fill `snapshotted_*` fields in `staking_pools` and `staking_pools_delegators` tables after pool's address is changed.
=> POSDAO: fix snapshotting and remove temporary code

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex, apps/indexer/lib/indexer/supervisor.ex
Memory leak in Token balance on demand fetcher
Re-write Token balance on-demand fetcher as ordinary Module instead of Genserver process
Chore:
- Fix the issue when rendering of tokens dropdown at address page is called 6 times on the page: use checksummed address in the URI and ignore NaN balance in the state
=> Token balance on demand fetcher memory leak fix

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js
Finalization of https://github.com/blockscout/blockscout/pull/3736
Allow spaces and quotes for tuple input
=> Write contract: allow quotes and spaces in tuple input

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/explorer/lib/explorer/smart_contract/reader.ex
> 2021-03-22T04:47:48.893 [error] #PID<0.16672.7> running BlockScoutWeb.Endpoint (connection #PID<0.16671.7>, stream id 1) terminated
Server: 35.173.81.59:80 (http)
Request: GET /smart-contracts/0x6093AeBAC87d62b1A5a4cEec91204e35020E38bE?function_name=getAmountsIn&method_id=1f00ca74&args%5B%5D=4008815907250056140062&args%5B1%5D%5B%5D=0x712b3d230f3c1c19db860d80619288b1f0bdd0bd&args%5B1%5D%5B%5D=0xe91d153e0b41518a2ce8dd3d7944fa863463a97d
** (FunctionClauseError) no function clause matching in Integer.parse/2
(elixir 1.11.3) lib/integer.ex:232: Integer.parse({"1", ["0x712b3d230f3c1c19db860d80619288b1f0bdd0bd", "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d"]}, 10)
(explorer 0.0.1) lib/explorer/smart_contract/reader.ex:412: …
=> Contract reader fix when there are multiple input params including an array type

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/staking/contract_state.ex
Missing token name and symbol of MKR in Sushiswap LP token
MKR token and symbol getters have `byte32` type, unlike others. This PR enables support in metadata fetcher for Sushiswap LP tokens which have `bytes(n)` type for symbol and token getters in token contract.
=> Fix Sushiswap LP tokens custom metadata fetcher: bytes(n) symbol and name support

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/staking/stake_snapshotting.ex, apps/explorer/test/explorer/staking/contract_state_test.exs
Staking DApp sends big batch JSON RPC requests to the archive node in some cases (especially, when reading info about delegators). This PR refactors DApp's server side code, limits the length of batch requests splitting them into chunks, and optimizes the code of the `StakeSnapshotting` module so snapshotting procedure takes a few seconds instead of a few tens of seconds.
=> Refactor and optimize Staking DApp

CHANGELOG.md, apps/block_scout_web/assets/js/lib/try_eth_api.js, apps/explorer/lib/explorer/eth_rpc.ex
https://github.com/blockscout/blockscout/issues/3746
Null topic causes Internal server error in `eth_getLogs` API endpoint
Filter out not null topics before processing in `eth_getLogs` API endpoint
=> Skip null topics in eth_getLogs API endpoint

CHANGELOG.md, apps/block_scout_web/assets/js/lib/try_api.js, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/block_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/block_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Implement API endpoint to get nearest block number by timestamp
`?module=block&action=getblocknobytime×tamp={blockTimestamp}&closest={before/after}`
=> getblocknobytime block module API endpoint

apps/block_scout_web/assets/css/components/_transaction.scss, apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
Token transfer title: token name is out of borders in mobile view
Set `white-space: nowrap !important;` everytime except mobile view. Currently it is applied for each view.
=> Fix mobile styles for tx tile

CHANGELOG.md, apps/explorer/lib/explorer/chain/token_transfer.ex
The DB query for Inventory tab is slow for the next pages after 1st page.
https://github.com/blockscout/blockscout/pull/3773/files#diff-6be189f964972cc8407ceeb151c7a685c5aefa3c662a1082ca7e32f54b2821f9L296-R296
Query performance before the fix:
```
dai=> EXPLAIN ANALYZE (SELECT DISTINCT ON (t0."token_id") t0."amount", t0."block_number", t0."log_index", t0."token_id", t0."from_address_hash", t0."to_address_hash", t0."token_contract_address_hash", t0."transaction_hash", t0."block_hash", t0."inserted_at", t0."updated_at", t1."token_id", t1."metadata", t1."error", t1."token_contract_address_hash", t1."inserted_at", t1."updated_at"
dai(> FROM "token_transfers" AS t0
dai(> LEFT OUTER JOIN "token_instances" AS t1
dai(> ON (t0."token_contract_address_hash" = t1."token_contract_address_hash") AND …
```
=> Inventory pagination query performance improvement

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
"Confirmed by 0 blocks". If transaction confirmed, the number of confirmations should start from 1.
=> Fix number of confirmations

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/helper.ex
Contract methods with `stateMutability: pure` are not displayed in Read contract tab.
Enable contract methods with `StateMutability: pure` in Read contract tab
=> Read contract: enable methods with StateMutability: pure

CHANGELOG.md, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
In the [previous PR](https://github.com/blockscout/blockscout/pull/3758) I forgot to add pool metadata setting into `Become a Candidate` popup. This PR extends that.
=> Extend Become a Candidate popup in Staking DApp

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Resolves https://github.com/blockscout/blockscout/issues/3776
A new field type is returned from `eth_getTransactionReceipt` method. We should allow such transaction receipts.
```
2021-04-20T05:42:27.287 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0x999fdedac3fb63e77d4054951382e8d70a14c4f747c6fef4f53ce27e0f0f5e36\", \"blockNumber\" => \"0x13dc146\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0xaaf0\", \"error\" => \"\", \"from\" => \"0xdad49e6cbde849353ab27dec6319e687bfc91a41\", \"gas\" => 2500000, \"gasUsed\" => \"0xaaf0\", \"logs\" => [], \"logsBloom\" => \"0x0000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> Process type field in eth_getTransactionReceipt response

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/current_token_balance.ex
https://github.com/blockscout/blockscout/issues/3809
getTokenHolders API endpoint pagination is broken
=> Fix getTokenHolders API endpoint pagination

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Availability to manage token balance on-demand fetcher update threshold via env var
`TOKEN_BALANCE_ON_DEMAND_FETCHER_THRESHOLD_MINUTES `
=> Manage token balance on-demand fetcher threshold via env var

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_logs/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_read_proxy/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_write_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_write_proxy/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_read_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Some contracts, which following EIP-1967 proxy pattern are not displayed in Blockscout as Proxy contracts because of the fact, that application expects them to have implemetation` function, but it doesn't required in EIP-1967.
=> EIP-1967 contract proxy pattern detection fix

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_view.ex
Display 6 symbols instead of 4 in the short address view
=> Increase the number of left symbols in trimmed address hash

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
Metadata failed to fetch from requests to URIs with status code 301.
Process the response if the status code is 301.
=> Get NFT metadata from URIs with status_code 301

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
`tokenlist` API endpoint in  `Account` module returns all tokens, that once was owned by address. The endpoint should return current tokens with a positive balance.
Change `token_list` query to use `address_current_token_balances` instead of `address_token_balances` and add a clause to return only tokens with balance > 0.
=> Fix tokenlist API endpoint return only tokens with positive balance

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex
Fixes #3988.
* Fixed bug that sometimes lead to incorrect ordering of token transfers
=> Fixed bug that sometimes lead to incorrect ordering of token transfers

CHANGELOG.md, apps/explorer/test/explorer/etherscan_test.exs, apps/explorer/test/support/factory.ex
Finalize https://github.com/blockscout/blockscout/pull/3989
Fix tests for `list_token_transfers` method based on this comment:
> During testing I also found that the tests related to token transfer ordering are broken. The list of found token transfers appears to be empty
https://github.com/blockscout/blockscout/issues/3988#issue-884209375
=> Fix tests for list_token_transfers function

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
https://github.com/blockscout/blockscout/issues/4029
Internal server error on the address page of the verified contract.
Add clause for abi_decode_address_output/1 when is_nil(address)
=> Add clause for abi_decode_address_output/1 when is_nil(address)

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex, apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/market/market.ex, apps/explorer/test/explorer/chain/address/current_token_balance_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Blockscout  doesn't display USD value of LP tokens in tokens dropdown
Add USD value of LP tokens into token dropdown at the address page. This RP also adds display of LP tokens custom metadata in the tokens dropdown for differentiating them.
=> Display LP tokens USD value and custom metadata in tokens dropdown at address page

CHANGELOG.md, apps/explorer/lib/explorer/chain/address.ex
Fixes https://github.com/blockscout/blockscout/issues/4078
```
** (RuntimeError) cannot encode association :smart_contract_additional_sources from Explorer.Chain.Address to JSON because the association was not loaded.
You can either preload the association:
Repo.preload(Explorer.Chain.Address, :smart_contract_additional_sources)
Or choose to not encode the association when converting the struct to JSON by explicitly listing the JSON fields in your schema:
defmodule Explorer.Chain.Address do
@derive {Jason.Encoder, only: [:name, :title, ...]}
schema ... do
(ecto 3.5.5) lib/ecto/json.ex:4: Jason.Encoder.Ecto.Association.NotLoaded.encode/2
(explorer 0.0.1) lib/explorer/chain/address.ex:87: Jason.Encoder.Explorer.Chain.Address.encode/2
(jason 1.2.2) lib/encode.ex:172: Jason.Encode.map_naive/3 …
```
=> Exclude smart_contract_additional_sources from JSON encoding in address schema

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction/history/historian.ex
Resolves https://github.com/blockscout/blockscout/issues/4202
Create API endpoint which returns total fees paid to validators per day
An example of a Request URL:
`http://localhost:4000/api?module=stats&action=totalfees&date=2021-05-27`
Successful response example:
```
{
"message": "OK",
"result": {
"total_fees": "75411956011480008034"
},
"status": "1"
}
```
=> Total transactions fees per day API endpoint

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
- Added drop-down list widget
- Updated tests
- Added env variable `MAX_SIZE_UNLESS_HIDE_ARRAY`. _If amount of elements in array in output greater than `MAX_SIZE_UNLESS_HIDE_ARRAY`, then it will hide under the spoiler._
=> Hide long arrays in smart-contract's output

CHANGELOG.md, apps/explorer/lib/explorer/chain/transaction/history/historian.ex
Min and max block numbers for transactions statistics are calculated in separate queries:
https://github.com/blockscout/blockscout/blob/058b596b0c049fc22f3cc04ae3a16e3fa713995d/apps/explorer/lib/explorer/chain/transaction/history/historian.ex#L28-L46
Combine min and max block numbers into one query.
=> Transactions stats: get min/max blocks in one query

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Improve `get_token_balance` function
Instead of `address_token_balances` table use `address_current_token_balances` table
=> Get token balance query improvement

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Block numbers are not deduplicated before executing the query for acquiring of block hashes https://github.com/blockscout/blockscout/blob/74dab4deedbbddaffb94ee6d80ff3aaf70e36001/apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex#L217.
Add deduplication of block numbers before querying in `acquire_blocks` function.
=> Deduplicate block numbers in acquire_blocks function

.github/workflows/config.yml, CHANGELOG.md, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/block_number.ex, apps/explorer/lib/explorer/chain/cache/min_missing_block.ex, apps/explorer/priv/repo/migrations/20210524165427_min_missing_block_number.exs, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex
Query to get all chain breaks works ~15 seconds on average.
Find min missing block number in the background and save it into DB in `last_fetched_counters` table. Use this min value for the fetcher in order to narrow down the range of blocks for the query.
=> Speedup procedure of finding missing block numbers for catchup fetcher

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/explorer/lib/explorer/smart_contract/publisher.ex, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/test/explorer/smart_contract/publisher_test.exs
Finalization of https://github.com/blockscout/blockscout/pull/4236
Replace `contructor` with `constructor` in variables names
=> Typo: constructor instead of contructor

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js
- added additional check in `apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js` `prepareMethodArgs()`
=> Fix bug with empty array in write contract page

CHANGELOG.md, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
Do not reload the whole main page on click to "More transactions have come in"
=> Reload transactions on the main page without reloading of the whole page

CHANGELOG.md, apps/block_scout_web/assets/css/components/_new_smart_contract.scss, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_json_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
Resolves issue #4155 
- Added functionality to fetch smart-contracts metadata via [Sourcify](https://sourcify.dev)
- In `sourcify.ex`: checkByAddresses _(deprecated)_ -> check-by-addresses
=> Extend Sourcify smart-contract verification: fetch smart contract metadata from Sourcify repo if it has been already verified there

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_flattened_code_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_json_controller.ex
To prevent user's useless actions to verify already verified smart-contract
Now before rendering page, performs check if the smart-contract verified. And if verified, then user will redirected to smart-contract page
=> Аdded check in web if a contract already verified

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/4291
Images are not displayed for inks kinda `ipfs://<IPFS_ID>`
=> Fix for composing IPFS URLs for NFTs images

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
`https://blockscout.com/xdai/mainnet/address/%5D/contract_verifications/new` page open causes internal server error
Check if `address_hash_str` is valid in smart_contract_verified?/1 function
=> Fix internal server error on contract verification options page

CHANGELOG.md, apps/block_scout_web/assets/js/lib/coin_balance_history_chart.js, apps/block_scout_web/assets/js/lib/history_chart.js, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- Logo flickers on page refresh
- Chart font family is different from that is used on the rest of the application
- Prevent logo redirection by setting the current path from conn object
- Set default font-family for Chart objects
=> Fix logo URL redirection, set font-family defaults for chart.js

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
```
{"error":{"initial_call":null,"reason":"** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)\n    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5\n    (ecto 3.5.5) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4\n    (ecto 3.5.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3\n    (ecto 3.5.5) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3\n    (explorer 0.0.1) lib/explorer/chain.ex:2687: Explorer.Chain.fetch_min_missing_block_cache/0\n    (explorer 0.0.1) lib/explorer/chain/cache/min_missing_block.ex:28: …
```
=> Set infinite timeout for fetch_min_missing_block_cache method DB query

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss
Refactoring of `app.scss`
Replace `node_modules/` with short equivalent definition `~`
=> Replace node_modules/ with ~ in app.scss

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
If you try to access https://blockscout.com/xdai/mainnet/address/0x587aC2b6D8B49C8Df77C14fbec926A4Fed3695f3/decompiled-contracts you will get 500 HTTP error response
- added additional clauses for `last_decompiled_contract_version` method
=> Fix decompiled contracts bug

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs, apps/explorer/lib/explorer/chain.ex
*Fix fall on search token-autocomplete by non-latin characters*
*Fix search token-autocomplete by multiple words"
This PR fixes https://github.com/blockscout/blockscout/issues/4274
No breaking changes IMHO
I don't know exactly is it possible to tokens be in non-latin characters. @vbaranov please check this point
This PR not fix search by, for example, "лучшие токены" - this search string will be treat as empty string.
=> [4274] Fix/improve search token-autocomplete

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/explorer/lib/explorer/chain.ex
Resolves #4207 
- Now you will get sources of other contracts in the following form ```"AdditionalSources":[{"Filename":"filename.sol","SourceCode":"contract source code"}]```
Example: response on `api?module=contract&action=getsourcecode&address=0x0000...000`
```{"message":"OK","result":[{"ABI":"abi","AdditionalSources":[{"Filename":"2_Owner.sol","SourceCode":"source code"}],"CompilerVersion":"v0.7.5+commit.eb77ed08","ContractName":"Storage","EVMVersion":"istanbul","OptimizationUsed":"false","SourceCode":"source code","Address":"0x0000...000"}],"status":"1"}```
=> Fix getsourcecode bug

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/paging_options.ex, apps/explorer/test/explorer/chain_test.exs
Close #4147 
- Added displaying pending txs on `/address/${address_hash}/transactions` page
=> Add displaying pending transactions

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex
- Remove dropped/replaced txs from address transactions page
=> Remove dropped/replaced txs from address transactions page

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Closes https://github.com/blockscout/blockscout/issues/4335
`effectiveGasPrice` property in transaction receipt causes termination of fetching transaction receipts.
Allow `effectiveGasPrice` property in receipt
=> Support effectiveGasPrice property in tx receipt (Geth specific)

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_flattened_code_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_via_json_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/config/config.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/publisher.ex, apps/explorer/lib/explorer/third_party_integrations/sourcify.ex, apps/explorer/priv/repo/migrations/20210701084814_support_partial_match.exs, apps/explorer/test/explorer/chain_test.exs
Closes #4317 
- If smart-contract verified via Sourcify Blockscout will fetch it automatically
- Added support for partially verified contracts via Sourcify
=> Add support for partially verified via sourcify contracts 

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
Do not redirect to 404 page with empty string in the search field
=> Do not redirect to 404 page with empty string in the search field

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
Close #4387 
- Added check if sourcify integration is enabled in `BlockScoutWeb.AddressContractVerificationController.check_and_verify/1`
=> Fix sourcify bug

.tool-versions, CHANGELOG.md
In ASDF's `.tool-version` OTP version Elixir compiled with should match Erlang OTP version.
elixir version 1.11.4 mean 1.11.4-otp-21
=> Fix elixir version in .tool-versions

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
- Now addresses in nested tuples in transaction's input are also links 
- Add :tuple clause for `apps\block_scout_web\lib\block_scout_web\views\abi_encoded_value_view.ex -> do_copy_text/2`
- Fix render bug in transaction's input
Before: 
After:
=> Fix render bug in transaction's input

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4362 
- Add batched transactions on the `address/{addressHash}/transactions` page
=> Add batched txs at address page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
Loading of page with transactions are long. Because there are many useless requests to the server which takes 1-6 secs
- Moved line with using of `token-transfers-toggle.js` to more general place to decrease amount of requests.
=> moved token-transfers-toggle.js

CHANGELOG.md, apps/indexer/lib/indexer/pending_transactions_sanitizer.ex
Close #4348 
- Added else branch in `pending_transactions_sanitizer.ex/invalidate_block`
- Pending txs included in reorg blocks will marked as `dropped/replaced` via sanitizer
=> Fix false pending txs

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Example 500 reponse on the [page]( https://blockscout.com/poa/sokol/address/0xE8DDc5c7A2d2F0D7a9798459c0104fDf5E987ACA/transactions)
- Fix internal server error on the validator's txs page
=> Fix internal server error on validator's transactions page

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
https://github.com/blockscout/blockscout/issues/4407
Contracts in the search results are unordered
Add ordering by `[desc: inserted_at]` in the search query
=> Order contracts in the search by inserted_at in descending order

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Fixes https://github.com/blockscout/blockscout/issues/4409
0 results with the full word
Use default text search config in `to_tsvector` text-search function
=> Fix empty search results for the full-word search criteria

CHANGELOG.md, apps/block_scout_web/assets/js/lib/autocomplete.js, apps/explorer/lib/explorer/chain.ex
https://github.com/blockscout/blockscout/issues/4379
Add display of category to which search result belongs
=> Display search results categories

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/holder_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/holder_view_test.exs
Close #4425 
- Added clause for `total_supply_percentage/2`
- Added test for zero total supply case
=> Fix zero total supply bug

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
On-demand token balance fetcher failed to update token balances in some cases.
The issue is because the update query in the DB is failing. It is failing because the updated object doesn't contain `token_type` property. This PR adds `token_type` to the updated object.
=> Fix current token balance on-demand fetcher

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/holder_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/holder_view_test.exs
Close #4425 
- Added clause for `total_supply_percentage/2`
- Added test for zero total supply case
=> Fix bug zero total supply

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/current_token_balance.ex
- Now all token holders with the same amount of tokens are displaying
=> Token page: fix displaying of token holders with the same amount

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
In some cases Revert response in contract's output did non printed
- Added separate case for error mesages from smart-contract
=> Fix error response in contract's output

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, bin/install_chrome_headless.sh
Closes https://github.com/blockscout/blockscout/issues/4445
Escaping of `\x` blocks decoding of UTF-8 encoded string in contract string type output.
Add `unescape` function taken from https://elixirforum.com/t/how-to-properly-convert-this-octal-encoded-utf16-be-string-to-utf8/33220/11 and implement it in the case of `string` output type.
=> Unescape characters for string output type in the contract response

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://github.com/blockscout/blockscout/issues/4441
URLs for media assets are not properly encoded and might contain whitespaces and thus not all assets are displayed on the inventory tab or on the instance page:
Add URL encoding before rendering an image or other media asset on the page.
=> URL encoding for NFT media files URLs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
```
Request: GET /smart-contracts?hash=0xb538938335f8f79a5879c6ce6682fc72de08c630&type=regular&action=read
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, "(-32015) VM execution error. (Reverted 0x6c61737444617465206d75737420626520626967676572207468616e20666972737444617465)"} of type Tuple. This protocol is implemented for the following type(s): Indexer.BoundQueue, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Flow, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
(elixir 1.11.4) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.11.4) lib/enum.ex:141: Enumerable.reduce/3
(elixir 1.11.4) …
```
=> Fix contract read page error

CHANGELOG.md, apps/block_scout_web/assets/js/lib/autocomplete.js, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/explorer/lib/explorer/chain.ex
Autocomplete displays 0 search result if searching by full address, tx or block hash:
Add search by full tx/block/address hash to populate autocomplete.
=> Search autocomplete fix for address/block/tx hash

CHANGELOG.md, apps/block_scout_web/assets/js/lib/autocomplete.js
Broken link to address/tx/block in autocomplete
=> Fix autocomplete links to txs, blocks, addresses

CHANGELOG.md, apps/explorer/lib/explorer/counters/token_transfers_counter.ex
There was a typo in `apps\explorer\lib\explorer\counters\token_transfers_counter.ex` . Names of caches in `token_transfers_counter.ex` and `token_holders_counter.ex` were the same.
=> Fix copy-paste typo in token_transfers_counter.ex

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
```
Request: GET /tx/0x3cda07757d638cff3ea49003ae2c491d0afb0dafaf12d37a19480e0fc4340a94
blockscout-xdai    | ** (exit) an exception was raised:
blockscout-xdai    |     ** (ArgumentError) cannot convert nil to param
blockscout-xdai    |         (phoenix 1.5.6) lib/phoenix/param.ex:67: Phoenix.Param.Atom.to_param/1
blockscout-xdai    |         (block_scout_web 0.0.1) BlockScoutWeb.WebRouter.Helpers.address_path/4
blockscout-xdai    |         (block_scout_web 0.0.1) lib/block_scout_web/templates/transaction/overview.html.eex:218: BlockScoutWeb.TransactionView."overview.html"/1
blockscout-xdai    |         (block_scout_web 0.0.1) lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex:2: BlockScoutWeb.TransactionInternalTransactionView."index.html"/1
blockscout-xdai …
```
=> Tx page: handle empty to_address

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
This will parse blocks from RPC which are expected ot have a base fee field post London hard fork (EIP1559). Without this blocks will not parse.
This does not add base fee field to database or surface it to the Transaction view as that is out of scope for this PR, doing so would require language additions of "Base Fee" as well as View/Database updates and some integration/functional tests. I left that for the blockscout team after initially trying (and failing) due to not understanding how to integrate a new field into the database. I am sure I can figure it out if needed as I can learn it but I am new to the codebase and the coded language here so I left it out.
Related to #4480
=> parse base fee from eth RPC

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
```
Request: GET /address/0xB06e22E06C5Cc68011f8901A7F1F543d0A7adF8B/contracts
** (FunctionClauseError) no function clause matching in BlockScoutWeb.AddressContractView.creation_code/1
(block_scout_web 0.0.1) lib/block_scout_web/views/address_contract_view.ex:122: BlockScoutWeb.AddressContractView.creation_code(%Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: %Explorer.Chain.Data{bytes: ""}, contracts_creation_internal_transaction: nil, contracts_creation_transaction: nil, decompiled: false, decompiled_smart_contracts: #Ecto.Association.NotLoaded<association :decompiled_smart_contracts is not loaded>, fetched_coin_balance: #Explorer.Chain.Wei<0>, fetched_coin_balance_block_number: 22171247, …
```
=> Fix 500 response on empty contract's code page

CHANGELOG.md, apps/explorer/lib/explorer/validator/metadata_retriever.ex, apps/explorer/test/explorer/validator/metadata_retriever_test.exs
Error response from `fetch_validators_list` method is not handled.
=> Handle error in fetch_validators_list method

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex
If you will try [here](https://blockscout.com/xdai/mainnet/tokens/0xf26594f585de4eb0ae9de865d9053fee02ac6ef1/instance/2/token-transfers) to switch to the page 2 you will met the error
=> Fix incorrect next page url

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Close #4491 
- changed order of transations in `Explorer.Chain.block_to_transactions/2`
=> Change order of transations in block's view

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/indexer/test/indexer/temporary/uncataloged_token_transfers_test.exs
https://github.com/blockscout/blockscout/issues/4522
Query for `uncataloged_token_transfer_block_numbers` method is slow (> 60 mins on some application instances).
- Remove join with `transactions` table since `block_hash` column is directly available at `logs` table.
- Replace `LEFT JOIN  / IS NULL` approach for finding records in table A, that do not exist in table B, with `NOT EXISTS` approach, which should be faster in Postgres.
`EXPLAIN ANALYZE` for the query before the changes:
```
EXPLAIN ANALYZE SELECT DISTINCT
ON (t1."block_number") t1."block_number"
FROM "logs" AS l0 INNER JOIN "transactions" AS t1 ON t1."hash" = l0."transaction_hash"
LEFT OUTER JOIN "token_transfers" AS t2 ON (t2."transaction_hash" = l0."transaction_hash") AND (t2."log_index" = l0."index")
WHERE …
```
=> Uncataloged token transfers query performance improvement

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/fetcher/block_reward.ex, apps/indexer/lib/indexer/transform/address_coin_balances_daily.ex, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs, apps/indexer/test/indexer/fetcher/block_reward_test.exs
Coin balance daily fetcher makes extra requests to archive node to get block timestamps. However, those timestamps are already fetched in the previous steps.
Eliminate extra `eth_getBlockByNumber` requests in coin balance daily fetcher, use previously fetched data.
=> Indexer performance update: refactor coin balance daily fetcher

CHANGELOG.md, apps/indexer/lib/indexer/transform/token_transfers.ex
With parsing token transfers, Blockscout updates token's data (name, symbol, decimals, totalSupply) in the DB from the blockchain. But it makes requests to the archive node for each token in the token transfers batch even if there are repeating tokens. Blockscout should make as requests for the tokens data as the number of unique tokens in that batch. It should reduce the number of requests to the node and the number of writes to the DB.
Request tokens' data on token transfer only for unique tokens in the batch.
=> Indexer performance update: Eliminate multiple updates of the same token while parsing mint/burn token transfers batch

apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
When trying to fetch token balances the token type is being retrieved from `Explorer.Chain.Address.CurrentTokenBalance` which fails, as the property is on it's `Explorer.Chain.Token` field, rather than directly on the object proper. This results in the following error.
```
Task #PID<0.26535.4> started from #PID<0.26534.4> terminating
** (KeyError) key :token_type not found in: %Explorer.Chain.Address.CurrentTokenBalance{__meta__: #Ecto.Schema.Metadata<:loaded, "address_current_token_balances">, address: #Ecto.Association.NotLoaded<association :address is not loaded>, address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<170, 150, 63, 201, 114, 129, 217, 99, 45, 150, 112, 10, 182, 42, 77, 19, 64, 249, 162, 138>>}, block_number: 6810831, id: 192377275, inserted_at: ~U[2021-05-06 …
```
=> Access token type from token object.

CHANGELOG.md, apps/indexer/lib/indexer/transform/token_transfers.ex
In the catchup block indexer resulting set of tokens before the update in the DB is not unique.
Deduplicate tokens set before update in the DB.
=> Indexer performance update: Deduplicate tokens in the indexer token transfers transformer

.github/workflows/config.yml, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/rolling_window.ex, mix.exs
Optimises the workflow by aggressively caching dependencies. 
Notably :
* Cache elixir dependencies
* Cache npm node_modules
* Cache dialyzer persistent lookup table (plt)
These caches are keyed on their respective lock files, for npm this is the `package-lock.json` files in `explorer` and `block_scout_web` apps, for dialyzer and elixir dependencies this is `mix.lock`. These caches will be rebuilt upon changes to npm modules or elixir dependencies, which will result in an initially longer build time but will be persisted across test runs.
Initial results seem to show a reduction in test run time from ~23 minutes to around 14 minutes with fully cached dependencies. Currently the test runs are bounded by the `explorer` test suite, specifically smart contract verification functionality. …
=> Optimise github actions (#363)

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/write.js
Close #4561 
- Add `0x` prefix to hex values
=> Fix NaN input in write contract

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Resolves https://github.com/blockscout/blockscout/issues/4533
Navbar menu is non-interactive on Search results page
Enable missing javascript logic on Search results page
=> Enable navbar menu on Search results page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/common_components/_btn_copy_for_table.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_total_transfers_from_to.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Broken floating tooltips 
- Fix floating tooltips on the token transfer family blocks
=> Fix floating tooltips on token transfer block

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4560 
Close https://github.com/blockscout/blockscout/issues/4559
- Type of input field for transaction value changed to `number`
- Now input fields resized according to length of its placeholder
- Power selector edited to more intuitive manner
- Add tooltip for transaction's value
=> Write contract page: Resize inputs; Improve multiplier selector

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- Add status for txs have no block
=> Add status to Position pane

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/block_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/chain/wei.ex, apps/explorer/lib/explorer/counters/block_burned_fee_counter.ex, apps/explorer/lib/explorer/counters/block_priority_fee_counter.ex, apps/explorer/priv/repo/migrations/20210811140837_add_1559_support.exs
Close #4327 
- new env variable `ENABLE_1559_SUPPORT`
- new fields in DB
- support eip-1559 on transaction's page
- support eip-1559 on block's page
- Burnt Fees and Priority Fees for blocks are calculating at the runtime and storing in ets
=> EIP-1559 support

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
Endless "Fetching tokens..." warning on empty addresses. For instance, https://blockscout.com/xdai/mainnet/address/0x8c461F78760988C4135e263a87DD736F8b671ff0/transactions
Change the condition to load dropdown with tokens
=> Fix endless Fetching tokens... message on empty addresses

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4565 
- Now entities of Smart Contract such as `receive` and `fallback` fucntions are marked as `receive` and `fallback` respectively
=> Fix empty contract's function names

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
HTML tags are not supported in the message applied to the whole explorer
=> Support HTML tags in alert message

CHANGELOG.md, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
=> Token page: fixes in mobile view

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js, apps/block_scout_web/assets/js/lib/smart_contract/write.js, apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_status.html.eex
Close #4506 
- Cut error message in case of reverted tx
- Change title of popup message
=> Refine view of popup for reverted tx

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
- Rename burned to burnt at transaction page
=> Transaction page: Rename burned to burnt

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
In some cases there is possibility of Internal Server Error
- Change `@burn_address` to string `0x0000000000000000000000000000000000000000`
=> Change burn address to string

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/web_router.ex, apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
Resolves https://github.com/blockscout/blockscout/issues/4455
Closes https://github.com/blockscout/blockscout/pull/4576
Support `/block/{number_or_hash}` `/token/{hash}` paths
Makes `/block/{number_or_hash}` `/token/{hash}` are default paths.
`/blocks/{number_or_hash}` `/tokens/{hash}` are still supported, but no links to those paths from the application from this point.
=> EIP-3091 support

apps/block_scout_web/lib/block_scout_web/templates/common_components/_tenderly_link.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/4652
Add Open in Tenderly button to transaction
There are 2 new ENV variables introduced:
- `SHOW_TENDERLY_LINK` - if `true`, button is displayed on transaction
- `TENDERLY_CHAIN_PATH` - chain path to the transaction in Tenderly. For instance, for transactions in xDai, Tenderly link looks like this `https://dashboard.tenderly.co/tx/xdai/0x...`, then  `TENDERLY_CHAIN_PATH =/xdai`
=> Open in Tenderly button

CHANGELOG.md, apps/block_scout_web/assets/js/pages/transaction.js, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #4610 
- Add expand/collapse button for long contract method data
- Add env variable `MAX_STRING_LENGTH_WITHOUT_TRIMMING` which is responsible for appearing aforementioned button
=> Transaction Page: Add expand/collapse button for long contract method data

CHANGELOG.md, apps/block_scout_web/assets/js/lib/from_now.js
Was lost timestamp on the Block Details page
- Change `from_now.js` according to changes done in #4655
=> Fix timestamp for blocks pages

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
An internal error on the block pages when Blockscout connected to Aurora JSON RPC.
```
2021-09-23T18:07:34.632 [error] GenServer #PID<0.2260.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
(block_scout_web 0.0.1) lib/block_scout_web/templates/block/_tile.html.eex:71: BlockScoutWeb.BlockView."_tile.html"/1
(phoenix 1.5.6) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
(phoenix 1.5.6) lib/phoenix/view.ex:479: Phoenix.View.render_to_string/3
(block_scout_web 0.0.1) lib/block_scout_web/channels/block_channel.ex:24: BlockScoutWeb.BlockChannel.handle_out/3
(phoenix 1.5.6) lib/phoenix/channel/server.ex:328: Phoenix.Channel.Server.handle_info/2
(stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.15.1) gen_server.erl:771: …
```
=> Block page: check gas limit value before division

apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Check constraint violation on transactions update from internal transactions:
`
2021-09-22T10:02:11.556 application=indexer fetcher=internal_transaction step=update_transactions count=10 error_count=10 [error] failed to import internal transactions for blocks: %{exception: %Postgrex.Error{connection_id: 26245, message: nil, postgres: %{code: :check_violation, constraint: "status", detail: "Failing row contains (null, null, 250000, 89602868567, null, \\xd9b74fd8f9e69ff45a1f7e07cc3106d6b1fa3b3ff616d407ea3861902e165c..., null, \\x, 36879668, 2491383878535995488279521215521881858038120066050117420264006418..., 5488171561368591118540607534447152719879393889735935592636586416..., 1, 1, 81442603985372310, 2021-08-21 13:05:26.847668, 2021-09-22 09:59:50.922441, null, null, …
=> Internal transactions indexer: fix issue of some pending transactions never become confirmed

CHANGELOG.md, apps/block_scout_web/assets/static/manifest.webmanifest, apps/block_scout_web/lib/block_scout_web/csp_header.ex
Finalization of #4596
Kudos to @carterqw2 for the catch
=> CSP fix: allow only Trustwallet assets repo from Github

.dialyzer-ignore, .github/workflows/config.yml, .tool-versions, CHANGELOG.md, apps/explorer/lib/explorer/chain/bridged_token.ex, apps/explorer/lib/explorer/chain/token/instance.ex, apps/explorer/lib/explorer/smart_contract/writer.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/explorer/chain_spec/parity/importer_test.exs, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex, docker/Dockerfile
Update to Erlang/OTP 24
- Erlang/OTP 24 pinned
- bitwalker/alpine-elixir-phoenix:1.12.2 -> bitwalker/alpine-elixir-phoenix:1.12.3
=> Update to Erlang/OTP 24

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/paging_options.ex
Close #4664 
- Fix pagination on the Transactions tab for the Block Details page
=> Block Details page: Fix pagination on the Transactions tab

CHANGELOG.md, apps/block_scout_web/assets/js/lib/autocomplete.js, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json
Missing sanitization of search field input data
Add `xss` NPM package and sanitize input by using it.
=> Search input field: sanitize input

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Resolves https://github.com/blockscout/blockscout/issues/4716
When Blockscout finds a creation transaction for a contract, it doesn't check the status of the transaction but expects one result in the response. However, multiple failed transactions can presence in the DB at the same time.
Add check of the tx status in the query for finding contract creation transaction.
=> Contract verification fix: check only success creation tx

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block/reward.ex, apps/explorer/lib/explorer/chain/supply/token_bridge.ex, apps/explorer/lib/explorer/chain_spec/poa/importer.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/lib/explorer/validator/metadata_retriever.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
Close #4844 
- Fix a bug linked with last update of functions response decoding
- Changed signatures of some funcions: 
- - `Reader.query_contract`
- - `Reader.query_verified_contract`
- - `Reader.query_verified_contract_inner`
- - `Reader.query_contract_and_link_outputs`
- - `Reader.query_function_inner`
- - `Reader.query_function`
- - `Reader.query_function`
- - `Reader.fetch_current_value_from_blockchain`
=> Fix read contract page

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close #4770 
- Added support for BeaconProxy smart-cotract pattern
> If some smart-contract (BeaconProxy) has address (pointing to the Beacon) at the storage slot `bytes32(uint256(keccak256('eip1967.proxy.beacon')) - 1`, then we call `implementation()` method from the Beacon. We consider address returned by `implementation()` at the Beacon contract as address of the implementation of BeaconProxy. If call for some reason failed, we return address of the Beacon as the implementation.
=> Add support for BeaconProxy pattern

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
Resolves https://github.com/blockscout/blockscout/issues/4845
`200` is hardcoded for Optimizations runs at `/verify` API endpoint in case of input is bitstring
Process bitstring input: if input can be parsed, use that value. Otherwise, use 200.
=> Allow custom optimizations runs for contract verifications via API

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
=> Fix infinite gas usage count loading

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/transactions.ex
Cumulative gas used is indicated twice in the update query for transactions import
=> Remove cumulative gas used update duplicate

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Set explicit ascending order by hash in acquire transactions query of internal transactions import
=> Set explicit ascending order by hash in acquire transactions query of internal transactions import

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close #4839 
- Set by default `block_index` to `-1` for internal transactions If there are some unpredictable issues and it is impossible to find raw-trace's tx hash between block's internal txs.
=> Add default value for block_index

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex
Some DB columns in different tables are not updated in UPDATE query when conflict arises on INSERT query.
- add `updated_at` into update when importing addresses
- add `token_type` into update when importing token balances history and current token balances
- add `earliest_processing_start`, `revert_reason`, `max_priority_fee_per_gas`, `max_fee_per_gas`, `type` into update when importing transactions
=> Add missing columns updates when INSERT ... ON CONFLICT DO UPDATE ... happens

CHANGELOG.md, apps/explorer/priv/repo/migrations/20211018073652_add_token_balances_contract_address_hash_index.exs, apps/explorer/priv/repo/migrations/20211018074058_add_internal_transactions_block_number_from_address_hash_hash_transaction_hash_index.exs, apps/explorer/priv/repo/migrations/20211018164843_transactions_block_number_index.exs, apps/explorer/priv/repo/migrations/20211018170533_add_address_token_balances_address_hash_token_contract_address_hash_block_number_index.exs, apps/explorer/priv/repo/migrations/20211018170638_add_logs_address_hash_transaction_hash_index.exs, apps/explorer/priv/repo/migrations/20211029085117_drop_block_rewards_block_hash_partial_index.exs
Observation of helpful indices in PGAnalyze index advisor to sped up slow queries.
PGAnalyze suggestions to add new indices:
- `CREATE INDEX ON public.address_token_balances USING btree (address_hash, token_contract_address_hash, block_number);` - for `derive_address_current_token_balances` method
- `CREATE INDEX ON public.transactions USING btree (block_number);` - for txs per day chart collection
- for `list_internal_transactions` method:
```
CREATE INDEX ON public.internal_transactions USING btree (block_number, from_address_hash, transaction_hash);
CREATE INDEX ON public.internal_transactions USING btree (block_number, to_address_hash, transaction_hash);
CREATE INDEX ON public.internal_transactions USING btree (block_number, created_contract_address_hash, transaction_hash);
```
- …
=> PGAnalyze index suggestions

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex, apps/explorer/lib/explorer/chain.ex
Change ordering `fetch_top_tokens` in query from `holder_count DESC` to `holder_count DESC NULLS LAST`
=> Fix fetch_top_tokens method: add nulls last for token holders desc order

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
There are bug, when Sourcify disabled in ENV, Verify & Publish button refer to the flattened source code verification
- Change button link to the verification type selection page
=> Change button link to the verification type selection page

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address_token_transfer_csv_exporter.ex
Resolves https://github.com/blockscout/blockscout/issues/4972
Exporting of tokens transfers on address accounts only those which sent from or to account. Thus, if someone requests transfers of token address itself, an empty list of token transfers will be returned.
Complement `to_address_hash` and `from_address_hash` clauses with `token_contract_address_hash` clause for the list of token transfers to export.
=> Export token transfers on address: include transfers on contract itself

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/pending_transaction.ex
Eliminate pending transactions fetcher termination:
```
2021-12-03T10:18:28.379 fetcher=pending_transaction [error] Task #PID<0.26811.31> started from Indexer.Fetcher.PendingTransaction terminating
** (CaseClauseError) no case clause matching: {:error, :econnrefused}
(indexer 0.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
(elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
(stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.38596988/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
Args: []
```
=> Handle :econnrefused in pending transactions fetcher

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
Close #4933 
- Fix displaying of nested arrays for contracts read
[Test contract](https://blockscout.com/poa/sokol/address/0x0EC925Cf5d65c2ad8Ae7fb26957EF1b8e9D73a0C/read-contract) with differrent examples of arrays
=> Fix displaying of nested arrays for contracts read

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/counters/address_gas_usage_counter.ex, apps/explorer/lib/explorer/counters/address_token_transfers_counter.ex, apps/explorer/lib/explorer/counters/address_transactions_counter.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfers_counter.ex, apps/explorer/priv/repo/migrations/20211204184037_address_add_gas_used.exs, apps/explorer/priv/repo/migrations/20211206071033_modify_address_gas_used_bigint.exs
Query to get total `gas_used` on address is quite long and for a huge number of transactions is executing more than 60secs resulting in 0 `gas_used` in UI because the calculation is synchronous.
Together with updating of `gas_used` on address cache, update the value in the DB. For this aim, the `gas_used` column is added to the `addresses` table. And use the value from the table as a fallback if the cache was not updated in time.
=> Store total gas_used in addresses table

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
https://github.com/blockscout/blockscout/issues/4986
If page number/size is not set, the endpoint returns internal server error.
Add handlers of empty page size or/and number
=> Improve bridged tokens list API endpoint: add handler for empty page number and page size

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/rpc_translator_test.exs
Refactor API routing for code-readability and disable routes like `/api/anything`, leave only `/api/v1` and `/api` routes available
=> API router refactoring

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/assets/js/pages/address/coin_balances.js, apps/block_scout_web/assets/js/pages/address/internal_transactions.js, apps/block_scout_web/assets/js/pages/address/token_transfers.js, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/assets/js/pages/address/validations.js, apps/block_scout_web/assets/js/pages/blocks.js, apps/block_scout_web/assets/js/pages/pending_transactions.js, apps/block_scout_web/assets/js/pages/token/token_transfers.js, apps/block_scout_web/assets/js/pages/token_counters.js, apps/block_scout_web/assets/js/pages/transactions.js, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_json/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_vyper/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_channel_disconnected_message.html.eex, apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Alert appears when page reloading/switching to the another
- Add check if the page is loading/updating or not
- Add reusable component to render `Connection lost` alert block
=> Fix falsy Connection Lost on reload page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
Resolves https://github.com/blockscout/blockscout/issues/5007
Extend decimals cap in token balance format function up to 24 since some tokens have more than 18 decimals. For instance, Near token hash 24 decimals.
=> Extend decimals cap in format_according_to_decimals up to 24

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Ganache returns empty adress as `0x0`, but blockscout shows `0x0` as te correct implementation addresss
- Add clause for `0x0`
=> Fix 0x0 implementation address

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_changed_bytecode_warning.html.eex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_read_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/priv/repo/migrations/20211115164817_add_check_for_bytecode_actuality.exs, apps/explorer/test/explorer/chain/log_test.exs
- Add `is_changed_bytecode` and `bytecode_checked_at` fields to the `smart_contracts` table
- Add daily bytecode verifcation to prevent metamorphic contracts vulnerablity
- Warning message in case of changed bytecode
=> Add daily bytecode verifcation to prevent metamorphic contracts vulnerablity

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex
Resolves https://github.com/blockscout/blockscout/issues/4934
Fixing an error of kind:
```
2021-12-14T21:04:16.957 [error] GenServer #PID<0.735.406> terminating
** (Ecto.Query.CastError) apps/explorer/lib/explorer/chain/address/current_token_balance.ex:191: value `%{}` in `where` cannot be cast to type Explorer.Chain.Hash.Address in query:
from c0 in Explorer.Chain.Address.CurrentTokenBalance,
where: c0.token_contract_address_hash == ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<183, 211, 17, 226, 235, 85, 242, 246, 138, 148, 64, 218, 56, 231, 152, 146, 16, 185, 160, 94>>},
where: c0.address_hash == ^%{},
select: c0.value
(elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
(elixir 1.12.2) lib/enum.ex:1704: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(elixir 1.12.2) …
```
=> Fix fetch_last_token_balance function termination

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/4935
Eliminate error of kind:
```
Request: GET /token/0x906d56d114ef1bb430a1c450dc6b24df22d3e759/instance/22/token-transfers
** (FunctionClauseError) no function clause matching in URI.encode/2
(elixir 1.12.2) lib/uri.ex:366: URI.encode(["https://5cryptos.com/wp-content/uploads/2021/06/Shiba-Inu-Grain-NFT-004.png"], #Function<1.66049009/1 in URI."-fun.char_unescaped?/1-">)
(block_scout_web 0.0.1) lib/block_scout_web/views/tokens/instance/overview_view.ex:159: BlockScoutWeb.Tokens.Instance.OverviewView.retrieve_image/2
(block_scout_web 0.0.1) lib/block_scout_web/views/tokens/instance/overview_view.ex:34: BlockScoutWeb.Tokens.Instance.OverviewView.media_src/1
(block_scout_web 0.0.1) …
```
=> Token instance image display imrovement

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/smart_contract/reader.ex
Close #4874 
Add view for parse errors (appears in cases when input ABI type is `tuple[]`)
- Fix emtpy method_id for cases when ABI type is `tuple[]` but actual type more complex
=> Add parse input errors view; fix empty method_id

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
In order to support `truffle-plugin-verify` we should improve verification
Add new steps to the verification pipeline:
- - Validate JSON input before processing it to the compiler
- - Replace `outputSelection` parameter in JSON input files
=> Add validation for the JSON input

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
Close #4863 
- Add check if method parsed correctly by ABI library
=> Fix 500 response when ABI method was decoded as nil

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex, apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
Close #4849 
- If input too long and part of it hidden then we do not show addresses inside it as links
- Increase default value in case of bad integer in ENV: `0` -> `2040`
=> Fix broken functions input

apps/block_scout_web/lib/block_scout_web/templates/bridged_tokens/_tile.html.eex
Closes #5059 
Fix typo. SHould be `class`
Fix typo
=> fix typo on class

CHANGELOG.md, apps/block_scout_web/assets/__tests__/lib/smart_contract/common_helpers.js, apps/block_scout_web/assets/js/lib/smart_contract/common_helpers.js
Tuple and bytes as well as arrays of tuple and bytes input types are not processing correctly on the Write contract page.
Missing tests were added.
=> Fix write contract page input data processing (tuple, bytes)

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
https://github.com/blockscout/blockscout/issues/5068
There is no ability to disable InternalTransactions fetcher
Add disabled? option for internal transaction fetcher in config
=> Internal transactions fetcher disabled? config parameter

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/counters/address_token_transfers_counter.ex, apps/explorer/lib/explorer/counters/address_transactions_counter.ex, apps/explorer/priv/repo/migrations/20220111085751_address_add_counters.exs
To improve the display of transactions/token transfers counters. Sometimes constantly 0 is returned when the counter value is huge.
Store address transactions/token transfers in `addresses` table together with `gas_used` which previously added in https://github.com/blockscout/blockscout/pull/4979.
=> Store address transactions/token transfers in the DB

CHANGELOG.md, apps/block_scout_web/assets/.babelrc, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json
core-js: `^2.6.12` -> `^3.20.2`
@babel/core: `^7.14.6` -> `^7.16.12`
@babel/preset-env: `^7.14.7` -> `^7.16.11`
@babel/polyfill is remove as deprecated
=> Babel minor and core-js major updates

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/token_controller.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfers_counter.ex
First token counters fetching always leaded to infinity loading (only in UI; actually server just sent nil response)
- Fetch token counters from ets cache sequentially, not in parallel, because it already handled in `TokenController`
- Change timeout, as in hexdocs stated, that `yield_many` expect timeout in ms
=> Fix token counters bug

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5143
`get_implementation_abi_from_proxy/2` method doesn't return implementation ABI in case EIP 1967 proxy pattern.
=> Fix get_implementation_abi_from_proxy/2 implementation

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Wrong hint on "Blocks Validated" field
=> Fix blocks validated hint

CHANGELOG.md, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/js/view_specific/address_contract/code_highlighting.js, apps/block_scout_web/assets/js/view_specific/raw-trace/code_highlighting.js, apps/block_scout_web/assets/js/view_specific/raw_trace/code_highlighting.js, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
Finalization of https://github.com/blockscout/blockscout/pull/4701
Staking-related js removed from the common js file, which is used on most of the pages, and moved to staking dapp page.
=> Reducing the size of JS bundles

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
Resolves https://github.com/blockscout/blockscout/issues/5121
`from: nil` param in `eth_call` request can cause problems on some types of archive nodes
Remove `from` param from the `eth_call` request, if it is null
=> eth_call method: remove from param from the request, if it is null

CHANGELOG.md, apps/block_scout_web/assets/css/_mixins.scss, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #5141 #5158 
- Add tooltips:
- Center copy buttons on the block details page
- Fix the following bug (font size in the second column is 12 px) which appears when ENV variable `DISPLAY_TOKEN_ICONS` disabled
=> Fix several UI bugs; Add tooltip to the prev/next block buttons

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/events/listener.ex, apps/explorer/lib/explorer/repo.ex, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/repo/config_helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5180
Resolves https://github.com/blockscout/blockscout/issues/5130
Resolves https://github.com/blockscout/blockscout/issues/3849
Closes https://github.com/blockscout/blockscout/issues/3840
Closes https://github.com/blockscout/blockscout/issues/4736
`DATABASE_URL` env variable params are not used by `Explorer.Repo` in some combinations with other environment variables.
=> Fix DATABASE_URL config parser

CHANGELOG.md, apps/explorer/config/config.exs
=> Add Berlin, London to the list of default EVM versions

CHANGELOG.md, apps/block_scout_web/assets/css/components/_i_tooltip_2.scss, apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/priv/repo/migrations/20211217201759_add_has_error_in_iternal_txs_field_to_transaction.exs, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
=> Add view for internal transactions error

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Close #4834 
- Fix an order of internal txs
=> Fix internal txs pagination

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #5035 
- Fix bug with stucked together outputs
- Add name and type to the function outputs
=> Fix contract functions outputs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
Close #5211 
- Add token-transfers-toggle.js to the block_transaction index.html
=> Add token-transfers-toggle.js to the `block_transaction/index.html.eex`

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_btn_swap.scss, apps/block_scout_web/assets/css/main-page.scss, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json, apps/block_scout_web/assets/webpack.config.js, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/advertisement/text_ad/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip_2.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_status_icon.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Update `fontawesome` package 5 -> 6
- "@fortawesome/fontawesome-free": "^5.15.3" -> "^6.0.0-beta3"
Chore:
- "postcss": "^8.3.5" -> "^8.4.6"
- "postcss-loader": "^4.3.0" -> "^6.2.1"
- "sass-loader": "^12.3.0" ->  "^12.6.0"
- "webpack": "^5.67.0" -> "^5.69.1"
- Add GC related missing swap button icons
=> Migrate fontawesome 5 -> 6

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/etherscan/contracts.ex
Close #3691 
- Add `IsProxy` and `ImplementationAddress` fields to the success response of `getsourcecode` and `verify` api methods
- `ImplementationAddress` field presents only if `IsProxy` is `true`
=> Add info about proxy contracts to api methods response

.gitignore, CHANGELOG.md, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/repo/config_helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5234
After https://github.com/blockscout/blockscout/pull/5192 it is disallowed to use a hyphen in the hostname.
Change DB hostname regex pattern in order to allow hyphen.
=> Fix DB hostname Regex pattern

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/smart_contract/reader.ex
Close #5043 
- Add functions overloading support
=> Add functions overloading support

.github/workflows/config.yml, CHANGELOG.md, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_contract_address_field.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_address.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_name.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_json/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_standard_json_input/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_vyper/new.html.eex, apps/block_scout_web/lib/block_scout_web/web_router.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher_worker.ex
- "Contract Address" is re-used from `_contract_address_field.html.eex` template In all contract verification forms
- `_library_address.html.eex` and `_library_name.html.eex` templates created and re-used
- `get_address_verified_twin_contract` - check, that address hash is valid, added
- an additional param `verification_type` is added to the request `/verify_smart_contract/contract_verifications`: [`json:metadata`, `json:standard`, `vyper`]
Chore:
- Erlang OTP version updated to `24.2.2` in GithubActions workflow config
- Commented code removed from the router
- Fix typos in the naming
=> Contract verification forms refactoring

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_read_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_write_proxy_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs, apps/block_scout_web/test/block_scout_web/schema/query/addresses_test.exs, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs, apps/block_scout_web/test/block_scout_web/views/tokens/overview_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/helper.ex, apps/explorer/priv/repo/migrations/20220303083252_smart_contracts_contract_code_md5.exs, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/explorer/test/explorer/smart_contract/writer_test.exs, apps/explorer/test/support/factory.ex
Some unverified contracts pages are not opened due to reaching timeout because of the slow query of checking verified contracts bytecode twins.
https://blockscout.com/poa/sokol/address/0x2D455d3bb60B37c88d25e7a8BB2B7f271317baB2/transactions
Add storage of md5(contract_code) in `smart_contracts` in order to remove join with `addresses` table in the query of finding verified smart-contracts bytecode twins.
=> Speedup query for getting verified smart-contract bytecode twin

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/coin_balance.ex
Close #4904 
- Add check if block is `consensus` and just in case `limit: 1` in resulting query with join
=> Fix coin-balances/by-day bug

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
Not aligned implementation address: 
- Align implementation address
=> Fix implementation address align

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
Close #4428 
- Fix bug with 500 response on partial sourcify status
=> Fix bug with 500 response on `partial` sourcify status

CHANGELOG.md, docker/Makefile
Closes https://github.com/blockscout/blockscout/issues/5284
Makefile definition of runinng container is not stable
Improve finding container function in Makefile by change it to find exact container by name in Makefile in order to define if container exist or started.
=> Makefile: find exact container by name

.github/workflows/publish-docker-image.yml, CHANGELOG.md
Add building and publishing of Docker image to CI pipeline
YML config is added for building and publishing of Docker image on publishing of releases.
=> CI pipeline: build and push Docker image to Docker Hub on every release

CHANGELOG.md, apps/explorer/config/test.exs, apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex, apps/explorer/test/explorer/smart_contract/solidity/publisher_test.exs, apps/explorer/test/explorer/smart_contract/solidity/verifier_test.exs
It was not possible to verify contract if json file had `"bytecodeHash": "none"` parameter
- Add ability to verify bytecode without bytecode hash
- Increase `ownership_timeout` to prevent tests fail
=> Add ability to verify bytecode without bytecode hash

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/besu.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/besu/trace.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/besu/traces.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
Finalizes https://github.com/blockscout/blockscout/pull/4895
=> Besu: revertReason support in trace

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/instance/overview_view_test.exs
Inspired by https://github.com/blockscout/blockscout/pull/5300#issuecomment-1065037029
Display low quality media files in inventory tab and high quality media files - on the token instance page.
Implement `high_quality_media?` flag in order to choose from which property get the asset's media file link:
`animation_url` - is for high quality media files
=> Display low-quality media assets in inventory tab, and high-quality - on instance page

CHANGELOG.md, apps/block_scout_web/assets/js/chart-loader.js
Replace Jquery  import with VanillaJS selectors in chart-loader.js
=> Eliminate Jquery import from chart-loader.js

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Empty blocks sanitizer init query is extremely slow on database with huge amount of transactions/blocks.
After implementation:
```
EXPLAIN ANALYZE SELECT b0.number, b0.hash FROM blocks AS b0 LEFT OUTER JOIN transactions AS t1 ON b0.number = t1.block_number WHERE (t1.block_number IS NULL) AND (b0.is_empty IS NULL) AND (b0.consensus = TRUE) ORDER BY b0.number DESC LIMIT 400;
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------
Limit  (cost=1.01..1410.08 rows=400 width=41) (actual time=0.083..17411.425 rows=400 loops=1)
->  Nested Loop Anti Join  (cost=1.01..48819091.63 rows=13858518 width=41) (actual time=0.082..17411.283 rows=400 loops=1)
->  Index Scan …
```
=> Empty blocks sanitizer performance improvement

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/empty_blocks_sanitizer.ex
The current query for finding blocks that should be refetched is still slow
Separate working process into 2 queries:
- 1st one - finds blocks that have transactions and null `in_empty` flag. The worker sets `is_empty=false` flag for those blocks.
- 2nd one - finds blocks that have no transactions and null `in_empty` flag. The worker sets `is_empty=true` flag for those blocks.
Decrease restart of the worker to 1 minute.
=> Empty blocks sanitizer refactoring

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_compiler_field.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_standard_json_input/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_vyper/new.html.eex
Description of tooltips are wrong for Vyper contracts verification:
=> Fix Vyper smart-contract verification form tooltips

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Closes https://github.com/blockscout/blockscout/issues/5343
Pass `blockExtraData` and `extDataHash` in block data response.
=> Block data for Avalanche: pass blockExtraData, extDataHash params

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Close #5304 
- Change `tokenlist` method. Now method returns all instances of ERC-1155.
Example: 
```
{
"message": "OK",
"result": [
{
"balance": "1",
"contractAddress": "0xed1efc6efceaab9f6d609fec89c9e675bf1efb0a",
"decimals": "",
"id": "106",
"name": "SNAFU",
"symbol": "SNAFU",
"type": "ERC-1155"
},
{
"balance": "1",
"contractAddress": "0xed1efc6efceaab9f6d609fec89c9e675bf1efb0a",
"decimals": "",
"id": "28",
"name": "SNAFU",
"symbol": "SNAFU",
"type": "ERC-1155"
},
{
"balance": "2",
"contractAddress": "0xed1efc6efceaab9f6d609fec89c9e675bf1efb0a",
"decimals": "",
"id": "169",
"name": "SNAFU",
"symbol": "SNAFU",
"type": "ERC-1155"
}
],
"status": "1"
}
```
=> Return all ERC-1155's token instances in tokenList api endpoint

apps/indexer/config/config.exs, apps/indexer/lib/indexer/fetcher/coin_balance.ex
Add ability to disable next fetchers:
- updater of cataloged tokens metadata
- coin balance
- block reward
The ability to switch off the last 2 fetchers is actual when explorer is connected to a non-archive node.
=> Ability to disable block reward, coin balance, token updater fetchers

CHANGELOG.md, apps/indexer/lib/indexer/block/realtime/fetcher.ex
```
** (stop) exited in: GenServer.call(Indexer.Block.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
** (EXIT) time out
(elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
(indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:156: Indexer.Block.Realtime.Fetcher.subscribe_to_new_heads/2
(indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:74: Indexer.Block.Realtime.Fetcher.handle_continue/2
(stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
(stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
=> Handle exited realtime fetcher

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close #5409 
- Add check: if revert reason is valid UTF-8 string then leave as UTF-8, otherwise save as raw hex string
=> Fix character_not_in_repertoire error for tx revert reason

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex, apps/indexer/lib/indexer/supervisor.ex, config/runtime.exs
- Add ability to disable empty blocks sanitizer
- Configure batch size of empty block sanitizer via env variable in runtime.
- `INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE` - a new environment variable to manage the batch size of empty block sanitizer
- `INDEXER_DISABLE_EMPTY_BLOCK_SANITIZER` - a new environment variable to manage enabling/disabling of empty block sanitizer
=> Empty blocks sanitizer improvements

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/gas.ex
Tx revert reason doesn't appear in the case of Geth-like archive node.
=> Geth: display tx revert reason

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
An error like this on smart-contract verification with wrong data:
```
2022-04-12T13:51:39.560 application=block_scout_web request_id=FuUqcBSo6HEjK1cAADtS [error] Something went wrong while publishing the contract.{:error, #Ecto.Changeset<action: :insert, changes: %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<55, 208, 237, 37, 143, 55, 169, 102, 243, 59, 117, 181, 174, 116, 134, 145, 122, 10, 230, 20>>}, compiler_version: "0.8.13+commit.abaa5c0e", contract_source_code: "pragma solidity ^0.8.0; contract Example { }", is_vyper_contract: false, name: "Example", optimization: false, optimization_runs: 200}, errors: [contract_source_code: {"There was an error compiling your contract.", []}, contract_code_md5: {"can't be blank", [validation: :required]}], data: …
```
=> Fix unverified_smart_contract function: add md5 of bytecode to the changeset

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Closes https://github.com/blockscout/blockscout/issues/5436
Allow custom Ethereum clients with extended block data to work with Blockscout from the box.
Ignore arbitrary field in the response of block's data.
=> Ignore arbitrary block details fields for custom Ethereum clients

CHANGELOG.md, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Decrease min safe polling period for realtime fetcher from _5 sec_ to _1 sec_ in order to mitigate realtime fetcher skips blocks.
=> Decrease min safe polling period for realtime fetcher

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/interact.js, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
Close #4870 
Close #5478 
- Split multiple functions arguments to separate query args:
- - add `args_count` parameter
- - other parameters has name like `arg_{x}`
=> Split multiple functions arguments to separate query args

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
Prevent broadcasting new block if previous one wasn't indexed yet. The fix is aimed to prevent situation like on this screenshot:
- Store last broadcasted block number in in-memory cache (ETS).
- If block to be broadcasted has number > cached last broadcasted number + 1, broadcast function waits until previous blocks broadcasted by periodically requesting cached last broadcasted block number value every 0.5 sec.
- In case of 4 blocks gap, which is the maximum number of blocks on the main page, broadcast is allowed again.
=> Sequential blocks broadcast on the main page

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex
Finalization of https://github.com/blockscout/blockscout/pull/5327
Deduplicate addresses and coin balances before insert operation into the DB.
=> Deduplicate addresses and coin balances before inserting to the DB

CHANGELOG.md, apps/block_scout_web/assets/package-lock.json, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
`TRACE_FIRST_BLOCK` environment variable is ignored in case of `ETHEREUM_JSONRPC_VARIANT=geth`. This PR extends action of this env varirable to all kinds of archive nodes including Geth.
=> Extend TRACE_FIRST_BLOCK env var to use with Geth-like node

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
Resolves https://github.com/blockscout/blockscout/issues/5499
If `TRACE_FIRST_BLOCK` environment variable is set, Blockscout continues to fill `pending_block_operations` table below that block height, which it shouldn't do because internal transactions will not be fetched for those blocks.
Prevent filling `pending_block_operations` table with blocks, which numbers lower than `TRACE_FIRST_BLOCK`.
=> Do not fill pending blocks ops with block numbers below TRACE_FIRST_BLOCK

docker/Dockerfile
Resolves https://github.com/blockscout/blockscout/issues/5512
Coin symbol customized not in all pages with Docker setup by means of `COIN` environment variable.
Apply `COIN` env variable to `ETH` localization string in default.po and default.pot files.
=> Set localization for "ETH" in Dockerfile in addition to "Ether"

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/fetcher/token_balance_test.exs, apps/indexer/test/indexer/token_balances_test.exs
If token balance fething failed, retry of fetching work only with restart of the application.
Retry fetching of failed token balances on-fly in `TokenBalance.run/2` up to 3 times. It should mititgate the issue with empty current token balances.
=> Token balances fetcher retry

CHANGELOG.md, apps/block_scout_web/assets/js/pages/transaction.js, apps/block_scout_web/lib/block_scout_web/application.ex, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
Increase the number of restarts of the explorer and block_scout_web applications from default 3 to 1000.
=> Increase max_restarts to 1_000 (from 3 by default) for explorer, block_scout_web supervisors

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close #5550 
- Add fallback clauses to `string_to_address_hash` `string_to_block_hash` `string_to_transaction_hash` functions
=> Add clauses to string_to_*_hash functions

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Incorrect burnt fees and priority fees calculation for legacy transactions. Currently, fees from legacy transactions are not included into total burnt fees.
Include legacy transactions into burnt fees
Change priority fees calculation, taking into account, that for legacy transactions:
```
transaction.max_priority_fee_per_gas = transaction.gas_price
transaction.max_fee_per_gas = transaction.gas_price
```
=> Burn fees for legacy transactions

CHANGELOG.md, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_standard_json_input/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_vyper/new.html.eex, apps/explorer/lib/explorer/chain/smart_contract.ex
Close #5521 
Close #5589 
- `apps/block_scout_web/assets/js/pages/verification_form.js`:
- - set `newForm` to null after the first use of it
- - remove unused `beyondPageOne` and other variables
- elixir side:
- - always set `address_hash` to `checksum(address_hash)` in smart_contract address_hash field
=> Fix failing verification attempts

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source.ex, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/repo/config_helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5608
Hyphen is not allowed in the DB password
Allow hyphen in DB password since it is not prohibited on DB connection level.
=> Allow hyphen in DB password

CHANGELOG.md, apps/block_scout_web/lib/phoenix/param.ex, apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
urls for fetching transaction (and other) pages returned by backend contains non checksummed address hash. It leads to redirect when clients fetch page and as the consequence larger waiting time 
- change Phoenix.Param implementation. Now it returns checksummed address_hash for address
=> Get rid of some redirects to checksummed address url

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
For empty addresses (aren't presented in DB) coin balance displayed as empty field:
=> Fix empty coin balance for empty address

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain_test.exs
Improper ordering of token transfers
- add order by `ASC: log_index` 
- fix pagination for `transaction/token-transfers`
=> Fix token transfers order

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs, apps/explorer/test/explorer/chain/cache/uncles_test.exs, apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/supply/token_bridge_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/explorer/test/explorer/smart_contract/solidity/verifier_test.exs, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/fetcher/block_reward_test.exs, apps/indexer/test/indexer/fetcher/internal_transaction_test.exs, apps/indexer/test/indexer/fetcher/uncle_block_test.exs
During test runs generates a lot of different warnings, some of them are consequence of incorrect test's, some of them just flood the output.
- get rid of warnings except:
- - some warns in `block_scout_web` module related to csv transaction export implementation: `warning: using Enum.into/2 for conn is deprecated, use Plug.Conn.chunk/2 and Enum.reduce_while/3 instead (see the Plug.Conn.chunk/2 docs for an example)` [code](https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex#L171)
- - some others related to `Supervisor`
=> Fix warnings in tests

CHANGELOG.md, apps/block_scout_web/assets/js/lib/history_chart.js, apps/block_scout_web/config/config.exs, apps/explorer/config/config.exs
- Make txs count chart visible on the main page by default, because it is a natural blockchain property
- Make price and market cap chart disabled by default since it makes sense to show it only for mainnets and if a coin is tracked by CoinGecko.
- Add a title for mono charts. If only market or transaction data is chosen, show the chart title.
=> Display txs count chart by default, disable price chart by default, add chart titles

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
Close #5631 
Some times sourcify for some reasons don't return metadata.json for verified contract: [example](https://repo.sourcify.dev/contracts/partial_match/77/0x43Cf33aa82383C33F064165881b484B5A7e206C9/)
- Add handling for cases when sourcify returns invalid data
=> Add handling for invalid Sourcify response

docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-build-open-ethereum-nethermind.yml
Fixes yaml syntax for Compose [environment:](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment) block supports two syntaxes.
* updated syntax to fix invalid data type bug during docker compose.
=> fixes yaml syntax for docker compose

CHANGELOG.md, apps/block_scout_web/assets/js/pages/token_counters.js, apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
Hot refresh of token holders makes the token holders' page blink over time when the there is much activity with the token
Cherry-pick from Celo fork https://github.com/celo-org/blockscout/pull/669
=> Disable token holder refreshing

CHANGELOG.md, apps/indexer/lib/indexer/transform/blocks.ex
Finalizes https://github.com/blockscout/blockscout/pull/5669
fixes #5380, fixes #2775, fixes #5065
=> Fix wrong miner address shown for post EIP-1559 block for clique network

CHANGELOG.md, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_show_address_transactions.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/views/tab_helpers.ex, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
Close #5641 
- add scrolling to tabs on address page
=> Address page: scroll to selected tab's data

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/chain/cache/token_exchange_rate.ex, apps/explorer/lib/explorer/counters/helper.ex, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex, apps/explorer/test/explorer/exchange_rates/source/token_bridge_test.exs
Close #5658 
Close #5646 
https://github.com/blockscout/docs/pull/55
- handle 404 response from CoinGecko
- add `EXCHANGE_RATES_FETCH_BTC_VALUE` env variable
- add `CACHE_EXCHANGE_RATES_PERIOD` env variable
=> Add clause for 404 response from CoinGecko; Disable fetching btc_value by default

CHANGELOG.md, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/repo/config_helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5688
Complex passwords with a set of different special characters are not allowed in DB URL parser.
Change the regexp pattern to support [#!%^&$] special characters except `@`.
=> Allow special characters for password in DB URL parser

.github/workflows/config.yml, CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
Resolves https://github.com/blockscout/blockscout/issues/5678
Requests to CoinGecko are made through PRO API endpoint by default and no options to switch to the basic one. If API key for CoinGecko is not provided, we should switch to the basic API endpoint.
Switch to basic (non-pro) API endpoint for Coingecko requests, if API key is not provided.
=> Switch to basic (non-pro) API endpoint for Coingecko requests, if API key is not provided

apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex, config/runtime.exs
Links in the footer are hardcoded
Add abiblity to manage footer links via env vars. New env vars introduced:
`FOOTER_CHAT_LINK`, `FOOTER_FORUM_LINK`, `FOOTER_GITHUB_LINK`
=> Footer links management

CHANGELOG.md, apps/explorer/lib/explorer/chain/data.ex
Close #5711 
- Add nil clause for Data.to_string/1
=> Add nil clause for Data.to_string/1

CHANGELOG.md, apps/block_scout_web/assets/css/components/_label.scss, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
The ability to add Testnet label right after the logo in navbar
New env vars added: `SHOW_TESTNET_LABEL`, `TESTNET_LABEL_TEXT`
=> Manage testnet label (right to the navbar logo)

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/config/config.exs, apps/explorer/lib/explorer.ex
Resolves https://github.com/blockscout/blockscout/issues/5763
"xDai" is hardcoded in balance tooltip
Define coin name in tooltip via `COIN_NAME` or `COIN` env variables
=> Define coin name in balance tooltip via variable

CHANGELOG.md, apps/block_scout_web/assets/css/components/_token-balance-dropdown.scss, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
Close #5707 
#5658 
- fix token balances dropdown view
- fix double requests to `/token-balances`, `/internal-transactions` and `/token-transfers`
- fix redirects on loading data for coin-balance chart (replace address hash with checksummed one)
=> Fix double requests; Fix token balances dropdown view

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close https://github.com/blockscout/blockscout/pull/5547
Fixes https://github.com/blockscout/blockscout/issues/5544
Add limit for the query to find missing block numbers (init query for catchup fetcher). The main idea of the change to #5547 is fetcher should start with the recent 500k blocks than first 500k blocks because the direction of catchup indexer is from head to tail.
=> Outstanding rows limit for missing blocks query (catchup fetcher)

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
previous PR #5737 was not complete
- fix layout for usd value
=> Move usd value to separate row

CHANGELOG.md, docker/Dockerfile
Resolves #5793 
Npm module `solc` is used directly on host machine via `node` command. Since we are using `mix release` on building, we don't have explorer npm modules in docker image anymore. So it is necessary to include packages like this to docker image.
Added copying of explorer's node_modules to result docker image.
=> Fix Cannot find module solc

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/explorer/test/explorer/counters/addresses_tokens_usd_sum_counter_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5794
The bug introduced while remomving bridged tokens functionality in https://github.com/blockscout/blockscout/pull/5703
=> Fix address_tokens_usd_sum function

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
commits from https://github.com/blockscout/blockscout/pull/5786 
Some requests didn't use full path with network subpath. It leaded to redirects
- Replace `current_path` with `Controller.current_full_path` in `BlockScoutWeb.Tokens.Instance.HolderController` and ` BlockScoutWeb.TransactionController`
=> Mofhusseini fix/transactions do not add subpath

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip_2.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_status_icon.html.eex, apps/block_scout_web/mix.exs, apps/ethereum_jsonrpc/mix.exs, apps/explorer/mix.exs, apps/explorer/package.json, apps/indexer/mix.exs, mix.exs
- Update CHANGELOG
- Revert update of css-loader (fontawesome icons are broken with 6+ version)
- Rename fontawesome icons selectors in order to match v6.1.2
=> Update CHANGELOG; revert update of css-loader; rename fontawesome icons selectors

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_tabs.html.eex
If a token instance has `nil` metadata we displaying `Metadata` tab. But this tab will lead to 404 page ([example](https://blockscout.com/xdai/optimism/token/0xC3EEc2E9CD1D777A04e9F1fa2ae2576754144f22/instance/41/token-transfers))
- Add condition to prevent displaying `Metadata` tab for token instance with `nil` metadata
=> Add check for nil metadata to avoid empty tab

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex, config/runtime.exs
- 5 mins block delay is hardcoded in the response of `/api/v1/health` API endpoint.
- HEALTHY_BLOCKS_PERIOD is not correctly parsed.
- Parse HEALTHY_BLOCKS_PERIOD to milliseconds
- Use HEALTHY_BLOCKS_PERIOD in the response of `/api/v1/health` api endpoint
=> Enhance health API endpoint: better parsing HEALTHY_BLOCKS_PERIOD and use it in the response

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
Resolves #5517 
Since `Chain.import` uses `Task.async` under the hood and `CoinBalanceOnDemand` uses `Chain.import`, `CoinBalanceOnDemand` receives messages about tasks completion it doesn't expect.
Added stub `handle_info`s so messages like these are not unexpected.
=> Fix unexpected messages in CoinBalanceOnDemand

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address_internal_transaction_csv_exporter.ex, apps/explorer/test/explorer/chain/address_internal_transaction_csv_exporter_test.exs, apps/explorer/test/explorer/chain/address_token_transfer_csv_exporter_test.exs, apps/explorer/test/explorer/chain/address_transaction_csv_exporter_test.exs
Resolves https://github.com/blockscout/blockscout/issues/5643
Resolves https://github.com/blockscout/blockscout/issues/5535
Fix 
- error in CSV export of internal transactions
- warning in general CSV export
We shouldn't use union joins in address to internal transactions query because limit is applied on each  joining part (not at the joint query) and breaking the logic of pagination.
=> Fix CSV export of internal transactions

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/5685
=> Fix address overview.html.eex in case of nil implementation address hash

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
New version of Erigon `"erigon/2022.08.2/linux-amd64/go1.18.3"` returns `"timestamp":"0x0"` for every log item in `logs` param in the response of `eth_getTransactionReceipt`.
Allow `timestamp` param in `logs` key.
=> Allow timestamp param in the log of eth_getTransactionReceipt method

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex
Estimated address counter is not triggered at explorer restart causing 0 value for this counter until the exact counter is not returned from DB. And it can take tens of minutes to query exact counter.
=> Fix display of estimated  addresses counter on the main page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
https://github.com/blockscout/blockscout/issues/5803
Use `CHAIN_ID` env variable for comparison with wallet's chain ID on contract contract write page.
=> Contracts interaction: from networkID to chainID for chain detection

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan/addresses.ex
Resolves https://github.com/blockscout/blockscout/issues/6023
Results of `accountlist` API endpoint are non-deterministic.
Add ascending sorting by `address.hash` together with `address.inserted_at` in order making results deterministic.
=> Sort by address.hash column in accountlist API endpoint

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex
Resolves https://github.com/blockscout/blockscout/issues/5986
Unordered internal transactions in txlistinternal API endpoint
Add resulting order on block number respecting sorting direction and index of the log.
=> Fix order of results in txlistinternal API endpoint

CHANGELOG.md, apps/explorer/priv/repo/migrations/20220902083436_extend_token_name_type.exs
Resolves https://github.com/blockscout/blockscout/issues/5682
Resolves https://github.com/blockscout/blockscout/issues/5934
Token names can be longer than 255 symbols, which is the current limit of token name type in the DB
Modify `tokens` table name column type from `character varying(255)` to `text`
=> Extend token name from string to text type

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/tokens/instance/transfer_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/tokens/instance_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20220902103213_create_index_token_transfers_token_ids.exs, apps/explorer/priv/repo/migrations/20220902103527_create_indexes_token_instances_token_contract_address_hash_token_id.exs
Resolves #4369 #5929
Functions that fetch token transfers from db uses condition on `token_id` field while ERC-1155 tokens uses `token_ids` field so they are filtered out.
Updated functions that fetch token transfers from db so they use `token_ids` field as well.
=> Fix ERC-1155 tokens fetching

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/metadata_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/tokens/instance/transfer_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token/instance.ex
There is no need to fetch `TokenTransfer` along with the `Token.Instance` in cases where we only need an instance.
Got rid of fetching a `TokenTransfer` in places where this is not necessary.
=> Fix token instance fetching

CHANGELOG.md, ISSUE_TEMPLATE.md, apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Re-use _btn_copy.html for raw trace page
Also, issue template extended with the question about archive node type & version.
=> Re-use _btn_copy.html for raw trace page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
Close #5749 
- Fix inconsistent behaviour of getsourcecode method
- For all cases method will return at least `Address` field (for unverified and non-existing in DB addresses response will be: `{"message":"OK","result":[{"Address":"0xc57de7d1771549b56bdad1a55aae776e43fe090a"}],"status":"1"}`)
=> Fix inconsistent behaviour of getsourcecode method

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/fetcher/token_instance.ex
Token instance fetchers operates only the `token_id` field of token transfer entity while ERC-1155 tokens uses `token_ids` field which means that token instance fetcher just ignores them.
Updated token instance fetcher algorithm so it fetches ERC-1155 token instances as well.
=> Fix token instance fetcher for ERC-1155

.github/workflows/config.yml, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
- Add tags to fallback render of coin balance history
=> Add tags to fallback render of coin balance history

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/mix.exs, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #5857 
- Replace `get` method with `head` in order to optimize fetching file type
- Add support for `data:` url
=> Improve fetching media type for NFT

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/token_balance.ex
Condition in `TokenBalance.unfetched_token_balances` function will never be true for ERC-721 tokens, so `Indexer.Fetcher.TokenBalance` will always ignore them.
Fixed condition so it works correctly for ERC-721 tokens.
=> Fix unfetched token balances

CHANGELOG.md, apps/indexer/lib/indexer/application.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/prometheus/instrumenter.ex, apps/indexer/lib/indexer/prometheus/pending_block_operations_collector.ex
Added following metrics for Prometheus:
- `block_full_processing_duration_microseconds` - time needed to fully fetch and import a block
- `block_import_duration_microseconds` - time needed to import a block to the database
- `block_batch_fetch_request_duration_microseconds` - time needed to perform a batch `eth_getBlockByNumber` request
- `missing_block_count` - the number of missing blocks in the database
- `delay_from_last_node_block` - the delay from the last block on the node in seconds
- `import_errors_count` - the number of errors while importing blocks to the database
- `pending_block_operations_count` - the number of records in pending_block_operations table
=> Add Prometheus metrics to indexer

CHANGELOG.md, apps/explorer/priv/repo/migrations/20220926122620_extend_token_symbol_type.exs
```
2022-09-26T12:03:33.059 [error] Task #PID<0.1157.39> started from Indexer.Fetcher.Token terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
(ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
(ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
(explorer 4.1.8) lib/explorer/chain.ex:4853: anonymous fn/5 in Explorer.Chain.update_token/2
(ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
(elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
(ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
(ecto_sql 3.7.1) …
```
=> Extend token symbol type varchar(255) -> text

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
Expected behaviour: rate limit logs appears on application start.
Real behaviour: rate limit logs appears on each request.
Moved rate limit logs to `BlockScoutWeb.Application.start/2`.
=> Move rate limit logs to application start

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_owner_reader.ex, apps/indexer/lib/indexer/fetcher/token_instance.ex, apps/indexer/test/indexer/fetcher/token_instance_test.exs
As an improvement of current token balances relevance, token instance fetcher can check info about token instance owner and update corresponding current token balance.
Token instance fetcher now checks the owner of instance and update its current token balance.
=> Update token balances in token instance fetcher

CHANGELOG.md, apps/block_scout_web/assets/js/lib/indexing.js, apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
This message appears on the main page while Blockscout fetches internal transactions. However, it doesn't take into account, that when `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true` is provided, the internal transactions fetcher is disabled. Thus, the message will never disappear.
Hide mentioned message, if `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`.
As a side note: before this PR, the message claimed: "Indexing Tokens ...". It would be fairer to indicate, that we index internal transactions at this time. Thus, the message changed to "Indexing Internal Transactions ...".
Docs update PR https://github.com/blockscout/docs/pull/77
=> Hide Indexing Internal Transactions message, if INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true

CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-verification.yml, docker-compose/docker-compose.yml
Docker compose Redis DB config improvements
- add `redis_db` container name
- add persistent volume on the host machine at `./redis_data`
=> Docker compose configs improvements: Redis container name and persistent storage

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_libraries_other.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_address.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_first.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_name.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_multi_part_files/new.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex, config/runtime.exs
Repeating code in the rendering of contract libs at verification page.
- Define several .eex templates for contract libs inputs rendering in order to prevent repeating pieces of code.
- Add `CONTRACT_VERIFICATION_MAX_LIBRARIES` to manage max number of supported libraries in the runtime environment.
Docs update PR https://github.com/blockscout/docs/pull/79
=> Refactor contract libs render, CONTRACT_VERIFICATION_MAX_LIBRARIES

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
"Indexing blocks" alert at the top doesn't appear in case of blocks are still indexing if `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER` env var is set.
=> Fix Blocks Indexing message appearance

CHANGELOG.md, apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
https://github.com/blockscout/blockscout/blob/68209fffe81ef511ee24ea14b15202785db392f5/apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs#L118-L124
This test now is incorrect and fails randomly due to the fact that order of the test is random ([`:seed` option](https://hexdocs.pm/ex_unit/1.12/ExUnit.html#configure/1)) and that happens that this test runs first (i.e. `on_exit` callback hadn't been called yet), so `:explorer, :coin` env var hadn't been set to "POA", thus test fails, because default value for this env is "ETH".
Now we set `:explorer, :coin` env var to "POA" in this test and it checks whether "POA" refers to "poa-network" as in other tests. Seems like there is no default logic in `CoinGecko` module, so there is no sense to test such default behavior.
=> Fix coin_id test

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/coin_balances_daily.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/block/rewards.ex, apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/logs.ex, apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/prometheus/instrumenter.ex
Add new Prometheus metric:
`block_import_stage_runner_duration_microseconds` - metric shows running time of each step of each runner in each stage of block import
=> Add metrics for block import stages, runners, steps

CHANGELOG.md, apps/block_scout_web/assets/js/pages/blocks.js
Close #5701 
In case of /blocks page recieves blocks from backend with a significant difference between min and max block numbers, page freezes and browser crashes. It happens because of `withMissingBlocks` function in `apps/block_scout_web/assets/js/pages/blocks.js`
- add limit on min and max block numbers difference
=> Fix /blocks page freezing in case of large blocks numbers gaps

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/models/get_address_tags.ex, apps/block_scout_web/lib/block_scout_web/models/get_transaction_tags.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_labels.html.eex, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, config/runtime.exs
- copy missed part of public tags functionality from xdai branch
new envs:
- `NEW_TAGS`
-  example: `NEW_TAGS='[ {"tag": "tag_name", "title": "name to display"} ]'`
- `CUSTOM_CONTRACT_ADDRESSES_${tag_name}` 
- example:  `CUSTOM_CONTRACT_ADDRESSES_TAG_NAME=0x0000000000000000000000000000000000000001,0x0000000000000000000000000000000000000000`
Addresses should exist in `addresses` table
Result of setting example envs:
[PR](https://github.com/blockscout/docs/pull/85) to docs
=> Copy public tags functionality to master

.gitignore, CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-verification.yml, docker-compose/docker-compose.yml
Blockscout logs are not persistent between container restarts.
Add a persistent folder for Blockscout logs on the host machine.
=> Docker-compose persistent logs

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Fixes #6337 
Add search string processing to ts query
=> Fix token search with space

CHANGELOG.md, apps/block_scout_web/assets/js/pages/token/search.js
Fixes #6296 
Add short delay to send request when user stops typing, and not for every button click
=> Fix sending request on each key in token search

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/fetcher/coin_balance.ex, config/runtime.exs
The Forum menu item is enabled by default in the footer and there is no env var to manage its visibility.
`FOOTER_ENABLE_FORUM_LINK` - env var to manage forum link in the footer visibility (disabled by default).
Docs update PR https://github.com/blockscout/docs/pull/86
=> Env var to enable forum menu item in the footer

CHANGELOG.md, apps/block_scout_web/assets/js/socket.js, apps/block_scout_web/config/config.exs, apps/block_scout_web/config/prod.exs, apps/block_scout_web/lib/block_scout_web/controllers/account/auth_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex, apps/explorer/lib/explorer/repo/config_helper.ex, config/runtime/dev.exs
Absence or presence of trailing slash could cause incorrect generation of paths based on NETWORK_PATH, API_PATH, SOCKET_ROOT env variables.
Handle trailing "/" in NETWORK_PATH, API_PATH, SOCKET_ROOT env variables.
=> Fix definitions of NETWORK_PATH, API_PATH, SOCKET_ROOT: process trailing slash

apps/explorer/priv/repo/migrations/20220919105140_add_method_id_index.exs
`method_id` index creation took more than an hour on Sokol instance. In other more capable Blockscout instance, it will take longer, and index creation on `transactions` table blocks the indexing as a whole. The suggestion is to create that index concurrently. The drawback is that functionality, which depends on the index, will be broken at the time of index building, but the index creation will not block the indexing of blocks.
Add `CONCURRENTLY` for method_id index creation.
=> Create method_id index concurrently

apps/explorer/config/dev.exs, apps/explorer/config/prod.exs, apps/explorer/config/test.exs, apps/explorer/priv/repo/migrations/20220919105140_add_method_id_index.exs
Concurrent index creation doesn't work in the `api` branch
=> Fix for concurrent index creation

CHANGELOG.md, apps/block_scout_web/assets/js/pages/transaction.js, apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_state/_metatags.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_state/_state_change.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_state/_token_balance.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_state/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_state_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/lib/block_scout_web/web_router.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/transaction_state_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/test/explorer/chain/address/token_balance_test.exs
https://github.com/blockscout/blockscout/issues/5583
Add tab with state changes to transaction page that show how balances changed. Some examlpes below:
- [tx](https://blockscout.com/xdai/mainnet/tx/0xfeacfd6eaa41ad529e29d9779fb4d4a8d9e74c22001d40bba66defb815bb4dc2)
- [tx](https://blockscout.com/poa/sokol/tx/0xf2b1c231ff1af2ba4be2282fdc5fb53c2217ca3aa0fc05fbed168d3c81a1dcb7)
In case of multiple transfers of unique tokens of the same contranct all of them diaplayed in one change
- [tx](https://blockscout.com/xdai/mainnet/tx/0x92d6f2f5798d8104c337c55e25dfae50194dcc81f930c94bea32a57bc9425506)
Here balance of contract(0x09C131) is unknown, so it isn't displayed
=> Add transaction state changes feature

CHANGELOG.md, apps/block_scout_web/assets/js/lib/indexing.js, apps/block_scout_web/config/config.exs, apps/block_scout_web/config/test.exs, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/counters/internal_transactions_indexed_counter.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/blockscout/blockscout/issues/933
Add indexed ratio for internal transactions indexing stage.
=> Indexed ratio for int txs fetching stage

CHANGELOG.md, apps/explorer/priv/repo/migrations/20221114121811_drop_internal_transactions_order_index.exs
Resolves https://github.com/blockscout/blockscout/issues/6132
Queries that fetch internal transactions for address uses this index in priority of specialized partial indexes (`internal_transactions_to_address_hash_partial_index`, `internal_transactions_from_address_hash_partial_index` and `internal_transactions_created_contract_address_hash_partial_ind`), which slows down such queries.
=> Drop internal transactions order index

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Since the consensus of a block can go from true to false, finding the minimum missing block from the previous one is incorrect.
The lower search limit for min missing block query is set to zero.
=> Search min_missing_block_number from zero

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Close #6392 
- add support for base64 encoded NFT metadata
https://blockscout.com/poa/core/token/0x8098a8B08919E02768b826015523E4e39377F0b1/token-transfers (screen of local run)
=> Add support for base64 encoded NFT metadata

CHANGELOG.md, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/explorer/token/metadata_retriever_test.exs
Since some unicode graphemes consist of more than one byte, we need to handle cases when we cut token name on such long graphemes
=> Fix token name with unicode graphemes shortening

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/priv/repo/migrations/20221117075456_modify_address_token_balances_indexes.exs, apps/explorer/priv/repo/migrations/20221117080657_modify_address_current_token_balances_indexes.exs, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs, apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs
Currently, we are using double unique indexes for token balances tables because the field `token_id` presented in this index might be NULL or not NULL. In terms of performance, it's more useful to have one such index.
In addition, there is an inconsistency in token balances import logic. According to the current algorithm, we are collecting balances to be updated in the block fetcher pipeline, but the actual update happens only in async mode after the block is processed by fetcher. But, according to the current logic of actions on conflict in token balance update, we are updating token balance only if the new balance value is not null. So we won't store the information about balances to be update for tokens for which the address already has a balance and therefore we won't update such …
=> Update token balances indexes

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
After last PR merging /transactions endpoint give 504 timeout error on POA 
- Remove caching for api v2 txs
=> Remove caching for api v2 txs

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_compiler_field.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_fetch_constructor_args.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_include_nightly_builds_field.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_libraries_other.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_address.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_first.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_library_name.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_common_fields/_yul_contracts_switcher.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_flattened_code/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_multi_part_files/new.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification_via_standard_json_input/new.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/rust_verifier_interface.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex, apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex, apps/explorer/lib/explorer/third_party_integrations/sourcify.ex, apps/explorer/priv/repo/migrations/20221120184715_add_json_compiler_settings.exs
Close #5675 
Close #6463 
Close #5746 
Close #4571
- Refactor smart contract verification form
- Add support for smart contract verification without creation bytecode (with [smart contract verifier](https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier))
- Add compiler settings for smart contracts verified via standard JSON input or Sourcify 
- Add `compiler_settings` field to `smart_contracts` table
- Add verified twin name as fallback name for unverified contract
=> Smart contract verification improvements

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
- After https://github.com/blockscout/blockscout/pull/5561 `get_implementation_address_hash` function has changed
- Fix `get_implementation_address_hash` call
=> Fix get_implementation_address_hash call

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth/call_test.exs, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/priv/repo/migrations/20221125074820_drop_required_output_constraint.exs
Close #5950 
Close #5566 
- change constraint for `output` field in internal_transactions
=> Fix internal txs indexing

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Sorting in internal transactions query doesn't use any index which slows down internal transactions page loading especially for addresses that have a lot of internal transactions. However, there are several partial indexes that have the same sorting, so we can refactor this query to use these indexes and therefore speed it up.
Split internal transactions query into parts that use their partial indexes.
=> Fix internal transactions query

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/test/explorer/chain/smart_contract_test.exs, apps/explorer/test/support/factory.ex
Close #6548 
- Fix bug with proxy for twins
=> Fix bug with proxy for twins

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/test/indexer/fetcher/internal_transaction_test.exs
For cases when some transactions in block may be missing (node bug or smth else), it's necessary to have a functionality to reindex such blocks. Otherwise, it may cause endless foreign_key_violation errors on internal transactions import.
Set block consensus to false when we face such error, so catchup indexer will reindex this block.
=> Set consensus: false for blocks on int transaction foreign_key_violation

CHANGELOG.md, apps/explorer/priv/repo/migrations/20221209123459_drop_unfetched_token_balances_index.exs
Since we have `fetched_token_balances` unique index which is an extended version of `unfetched_token_balances` unique index and there are no inserts that uses `unfetched_token_balances` index, there is no need to keep the second unique index on the same fields.
`unfetched_token_balances` unique index deleted.
=> Drop unfetched_token_balances index

apps/explorer/config/dev/geth.exs, apps/explorer/config/prod/geth.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod/geth.exs
Bypass expired SSL certificates on some nodes.
Manage insecure HTTP connection via `ETHEREUM_JSONRPC_HTTP_INSECURE` env variable. Docs update in https://github.com/blockscout/docs/pull/99.
=> Allow and manage insecure HTTP connection to the archive node

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/pending_block_operation.ex, apps/explorer/priv/repo/migrations/20221212093406_change_index_for_pending_block_operations.exs, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/test/indexer/fetcher/internal_transaction_test.exs, apps/indexer/test/indexer/pending_ops_cleaner_test.exs
https://github.com/blockscout/blockscout/issues/6561
`fetch_internal_transactions` column in `pending_block_operations` table always has `true` value. There is no place in the logic where it is changed to another value.
Remove `fetch_internal_transactions` column from `pending_block_operations` table, which should simplify the number of indexes on the table.
=> pending_block_operations table: remove fetch_internal_transactions column

CHANGELOG.md, apps/block_scout_web/assets/js/lib/history_chart.js, apps/block_scout_web/assets/js/pages/dark-mode-switcher.js, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/lib/block_scout_web/templates/csv_export/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Since we plan to use hybrid mode for explorer (new UI + old UI) we need to synchronize how we dark mode changer works.
The dark mode switcher is changed to use `chakra-ui-color-mode` cookie instead of `current-color-mode` local storage.
=> Dark mode switcher localStorage to cookie in order to support new UI
