CHANGELOG.md, apps/block_scout_web/assets/js/lib/add_chain_to_mm.js
Resolves https://github.com/blockscout/blockscout/issues/6482
Wrong explorer URL if `NETWORK_PATH` env variable is not set.
=> Add to MM button explorer URL fix

apps/indexer/lib/indexer/block/fetcher.ex
Resolves https://github.com/blockscout/blockscout/issues/6598
Fix the division if is 0.
Trying resolve the issue #6598.
Handle zero division on fetcher of indexer
=> Unhandled division by 0

CHANGELOG.md, apps/explorer/config/dev/arbitrum.exs, apps/explorer/config/dev/besu.exs, apps/explorer/config/dev/erigon.exs, apps/explorer/config/dev/ganache.exs, apps/explorer/config/dev/nethermind.exs, apps/explorer/config/dev/rsk.exs, apps/explorer/config/prod/arbitrum.exs, apps/explorer/config/prod/besu.exs, apps/explorer/config/prod/erigon.exs, apps/explorer/config/prod/ganache.exs, apps/explorer/config/prod/nethermind.exs, apps/explorer/config/prod/rsk.exs
Finalization of https://github.com/blockscout/blockscout/pull/6574
Extending ETHEREUM_JSONRPC_HTTP_INSECURE env variable usage to than Geth clients.
=> Expand ETHEREUM_JSONRPC_HTTP_INSECURE env variable usage to other than Geth clients

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Add ignore rule for Metis RPC
```
curl -X POST 'https://andromeda.metis.io/?owner=1088' -H 'Content-Type: application/json' --data-raw '{
"id": "1",
"jsonrpc": "2.0",
"method": "eth_getTransactionReceipt",
"params": ["0x931d5f82512a2116cde0963f6747022353260c6958f990c1ca5472b2f4290938"]
}'
```
```json
{
"jsonrpc": "2.0",
"id": "1",
"result": {
"blockHash": "0xe24f003576c40c17237df00c9f4193d80b63894df708082c974acd6816335351",
"blockNumber": "0x3fca00",
"contractAddress": null,
"cumulativeGasUsed": "0x5208",
"from": "0xc519c75cf9de75311e6797cb3a3c641a01bdb1d5",
"gasUsed": "0x5208",
"l1Fee": "0x0",
"l1FeeScalar": "8",
"l1GasPrice": "0x0",
"l1GasUsed": "0x1256",
"logs": [],
"logsBloom": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> ignore some receipt fileds for metis

apps/explorer/lib/explorer/chain/events/listener.ex
Closes #6621 
When we have a haproxy architecture with 2 instances for web + 1 database + 1 indexer this we got scalability in terms of api and availability (the only failure point is the indexer) plus remove the issue of verifying the same smart contract in 2 databases behind the load balancer.
In new version 4.1.8-beta i got the following errors: 
- Fix postgres notifications when try delete a notification in stale state
=> Handling stale error when try delete notification

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/min_missing_block.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/utility/missing_block_range.ex, apps/explorer/priv/repo/migrations/20221219151744_create_missing_block_ranges.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/config/config.exs, apps/indexer/config/test.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/catchup/helper.ex, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex, apps/indexer/lib/indexer/block/catchup/supervisor.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/block/catchup/missing_ranges_collector_test.exs, config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/6566
Currently, catchup indexer tries to fetch all missing block ranges at the start. That can cause performance issues if there is a large amount of total blocks. 
Moved missing ranges tracking to a separate GenServer and split missed ranges query into batches.
Docs update: https://github.com/blockscout/docs/pull/100
=> Missing ranges collector

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/pending_block_operation.ex, apps/explorer/priv/repo/migrations/20221223151234_add_block_number_to_pending_block_operations.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/fetcher/pending_block_operations_sanitizer.ex, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/test/indexer/fetcher/internal_transaction_test.exs, apps/indexer/test/indexer/fetcher/pending_block_operations_sanitizer_test.ex, apps/indexer/test/indexer/pending_ops_cleaner_test.exs
Resolves #6561 
Currently we are fetching pending block operations block numbers via joining it with `blocks` table and filtering by consensus. But there is no need to store non-consensus block info in `pending_block_operations` since they are gonna be refetched anyway. Also, it's useful to add some denormalization to `pending_block_operations` so we don't need to join it with blocks and therefore there will be improvement of performance.
- Do not store non-consensus blocks info to `pending_block_operations`
- Added `block_number` field to `pending_block_operations`
=> Pending block operations update

CHANGELOG.md, apps/block_scout_web/.sobelow-conf, apps/block_scout_web/assets/js/lib/smart_contract/functions.js, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/smart_contracts_api_v2_router.ex, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/support/factory.ex
Close #6571 
- add fetching of wallet address from MM before fetching read smart contract methods (can be fetched if you are logged in metamask)
- `/addresses/{address_hash}/tokens`
- `/v2/smart-contracts/{address_hash}`
- `/v2/smart-contracts/{address_hash}/methods-read` (+custom abi)
- `/v2/smart-contracts/{address_hash}/methods-write` (+custom abi)
- `/v2/smart-contracts/{address_hash}/methods-read-proxy`
- `/v2/smart-contracts/{address_hash}/methods-write-proxy`
- `/v2/smart-contracts/{address_hash}/query-read-method` (+custom abi)
- changed messages format in websockets: internal_transactions, token transfers, transactions
- now /addresses returns 404 if address is not in DB
=> BS api v2: smart contracts

CHANGELOG.md, apps/block_scout_web/assets/css/components/_errors.scss
This looks not very good
Now it looks like this
=> Add vertical padding to error pages

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
Optimism Goerli will update 12th January 2023: BedRock release will be activated. There are L1 transaction fields on tx page:
- L1 Gas Used by Transaction
- L1 Gas Price
- L1 Fee Scalar
We need to continue displaying them after BedRock release.
=> L1 tx fields fix for Goerli Optimism BedRock update

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
- Add json rendering for result of contracts reading
- Now, if no value was fetched for the read function because the function has arguments, then no value field is added for output
- Remove from response constructor args if them was fetched from twin
=> API v2: Fix smart contract bug

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/search_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/block_scout_web/lib/block_scout_web/paging_helper.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/chain/transaction.ex
- Add `/search/check-redirect`
- Add `type` query parameter to `/tokens` in order to filter by token type
- Add `/addresses/{address_hash}/token-transfers?token={token_address_hash}`
- Add `method`, `block_hash` and `log_index` fields to token transfers
- Add `tx_hash` field to logs
- Add `coin_balance` to address in `/addresses`
=> API v2: new methods

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs, apps/indexer/test/indexer/block/catchup/missing_ranges_collector_test.exs
There is no need to delete internal transactions before insert since we have on_conflict policy
=> Remove internal transactions deletion

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
```
Request: GET /tokens?type=JSON
** (ArgumentError) errors were found at the given arguments:
* 1st argument: not a number
:erlang.abs(nil)
(ex_cldr_numbers 2.29.0) lib/cldr/number/formatter/decimal_formatter.ex:145: Cldr.Number.Formatter.Decimal.absolute_value/4
(block_scout_web 5.0.0) lib/cldr/number/backend/decimal_formatter.ex:1: BlockScoutWeb.Cldr.Number.Formatter.Decimal.to_string/3
(ex_cldr_numbers 2.29.0) lib/cldr/number.ex:431: Cldr.Number.to_string/3
(block_scout_web 5.0.0) lib/block_scout_web/views/currency_helpers.ex:18: BlockScoutWeb.CurrencyHelpers.format_integer_to_currency/1
(block_scout_web 5.0.0) lib/block_scout_web/templates/tokens/_tile.html.eex:40: BlockScoutWeb.TokensView."_tile.html"/1
(phoenix 1.5.13) lib/phoenix/view.ex:472: …
```
=> Add nil clause for format_integer_to_currency/1

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Fix #6730 
Instead of returning count from `reltuples` return `max(count, 0)`
https://github.com/blockscout/blockscout/blob/f83c27f84159483952f3924db6111e2d72037b11/apps/explorer/lib/explorer/chain.ex#L194-L197
the reason for this is that `reltuples` is equal to `-1` in fresh new table
=> Fix address counter on empty chain

docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose.yml
Force to update `latest` tags of Docker images.
Set `pull_policy: false` for containers which use `latest` tag by default.
=> Set docker-compose pull_policy to always

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/transaction.ex, apps/explorer/test/explorer/chain/cache/transaction_test.exs
Fix #6768 
Same as #6746
Also, add terminating gen server in test to eliminate connection not closed error.
=> Fix transaction count on empty chain

CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml
https://github.com/blockscout/blockscout/issues/6787
`latest` image tag is set as a fallback image for `sig-provider` service in docker-compose setup, but such tag doesn't exist.
Change `latest` to `main` tag as a fallback option for sig-provider service in docker-compose setup.
=> Change sig-provider default image tag to main

.credo.exs, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/plug/redis_cookie.ex, apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex, apps/explorer/lib/explorer/account/notify.ex, apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex, apps/explorer/lib/explorer/chain/contract_method.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex, apps/explorer/lib/explorer/smart_contract/vyper/verifier.ex, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/fetcher/replaced_transaction.ex, apps/indexer/lib/indexer/transform/token_transfers.ex
Closes #6762 
Example error before:
```
2023-01-30T20:20:44.907 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %FunctionClauseError{module: EthereumJSONRPC.Geth, function: :parse_call_tracer_calls, arity: 4, kind: nil, args: nil, clauses: nil}
```
after:
```
2023-01-30T20:21:39.989 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.parse_call_tracer_calls/4
(ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc/geth.ex:233: EthereumJSONRPC.Geth.parse_call_tracer_calls({%{"from" => "0x0a70c7294f9deffe389e437347ba1b6de531d16c", "gas" => "0xeef6c", "gasUsed" => …
```
=> Refactor `try rescue` statements to keep stacktrace

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
Add ignoring unknown call types and notifying about them in logs.
=> Fix handling unknown calls from `callTracer`

CHANGELOG.md, apps/indexer/lib/indexer/transform/transaction_actions.ex
We had the following error when handling nil `log.first_topic`:
```
2023-02-07 12:34:31	
{"log":"    Args: []\n","stream":"stdout","time":"2023-02-07T09:34:31.242592344Z"}
2023-02-07 12:34:31	
{"log":"Function: #Function\u003c2.49978846/0 in Indexer.Fetcher.TransactionAction.handle_info/2\u003e\n","stream":"stdout","time":"2023-02-07T09:34:31.242590148Z"}
2023-02-07 12:34:31	
{"log":"    (indexer 5.0.0) lib/indexer/fetcher/transaction_action.ex:115: Indexer.Fetcher.TransactionAction.task/1\n","stream":"stdout","time":"2023-02-07T09:34:31.242587972Z"}
2023-02-07 12:34:31	
{"log":"    (elixir 1.13.1) lib/enum.ex:4136: Enum.reduce_range/5\n","stream":"stdout","time":"2023-02-07T09:34:31.242586044Z"}
2023-02-07 12:34:31	
{"log":"    (indexer 5.0.0) …
```
=> Transaction actions fix

CHANGELOG.md, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
When new blocks arriving from websocket we update "total blocks" counter on the main page as `coming_block_number + 1`. This presumes that the chain is running from the block `0`. We should also take into account `FIRST_BLOCK`, if it is set.
This PR fixes this: it takes into account `FIRST_BLOCK` env variable in total blocks calculation, if it is set.
=> Take into account FIRST_BLOCK in "Total blocks" counter on the main page

CHANGELOG.md, apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
Resolves #6638 
There is a similar [issue](https://github.com/ethereum/go-ethereum/issues/25169) and its [solution](https://github.com/ethereum/go-ethereum/pull/25213/files#diff-782cb2b41601eeac10ef98a1f0aba25685bf93bfd0e8caf4e141ece7e2acf96dR573) in go-ethereum repo which are not yet included in any release, so we can apply this fix on our side for now.
If the tracer tries to access memory beyond the available limit, we limit it to the end of the memory.
=> Fix geth transaction tracer

CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-services.yml, docker-compose/docker-compose.yml, docker-compose/services/docker-compose-db.yml, docker-compose/services/docker-compose-redis.yml, docker-compose/services/docker-compose-sig-provider.yml, docker-compose/services/docker-compose-smart-contract-verifier.yml, docker-compose/services/docker-compose-visualizer.yml
In docker-compose configs for different RPC clients we repeat the same services: sc-verifier, visualizer, sig-provider etc.
Extract repeating services into separate docker-compose configs.
=> Extract Docker-compose services into separate files

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/transaction_action.ex
Sometimes the indexing task interrupts with timeout error when reading `log` table, and then starts from the block which already was handled. This PR fixes both issues.
=> Fix task restart in transaction actions fetcher

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/csp_header.ex
Resolves https://github.com/blockscout/blockscout/issues/6236
> When setting JSON_RPC env we are getting CSP browser errors after connecting the wallet.
Add value of `JSONRPC` env var to CSP header.
Chore: remove obsolete code lines from `.dialyzer-ignore`
=> Add JSON_RPC to CSP header

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_add_chain_to_mm.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/6477
Some chains don't need "Add to MM button", e.g. default MM chains, and hiding this button shouldn't break smart-contract interaction.
`DISABLE_ADD_TO_MM_BUTTON` introduced. If `true`, "Add to MM button" doesn't appear. Smart-contract interaction still works since `chain_id` and `json_rpc` hidden inputs moved to `app.html.eex`. Docs update https://github.com/blockscout/docs/pull/113.
=> Add env variable to hide Add to MM button

CHANGELOG.md, apps/indexer/lib/indexer/application.ex, apps/indexer/lib/indexer/supervisor.ex
In a setup when the indexer and the web app are running in separate instances, web app cannot trigger OnDemand fetchers because indexer supervisor is disabled, so some data may be inaccurate. It's reasonable to move those fetchers from indexer supervisor so they are started every time regardless of whether the indexer is disabled.
Moved OnDemand fetchers from `Indexer.Supervisor` to `Indexer.Application`.
=> Move OnDemand fetchers from indexer supervisor

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/reader.ex
Close #6710 
- Cut `from` param from query contract request if it's empty
=> Cut 'from' param from query contract request if it's empty

CHANGELOG.md, apps/indexer/lib/indexer/transform/token_transfers.ex, apps/indexer/test/indexer/transform/token_transfers_test.exs
Resolves #6483 
- Token type in the database is the precedence type
- If there are two or more transfers with different token types, the highest priority type will be selected for all
=> Fix token type definition for multiple interface tokens

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/rust_verifier_interface.ex
Some heavy contracts consume more than 30 seconds for verification.
- Increase verification timeout to 120 seconds
=> Increase verification timeout to 120 seconds

CHANGELOG.md, docker-compose/services/docker-compose-sig-provider.yml, docker-compose/services/docker-compose-smart-contract-verifier.yml, docker-compose/services/docker-compose-visualizer.yml
Resolves https://github.com/blockscout/blockscout/issues/6910
Exposed ports for sc-verifier and visualiser services are the same.
Expose different ports for Rust microservices.
=> Docker compose fix exposed ports

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs, apps/explorer/lib/explorer/smart_contract/solidity/publish_helper.ex
There was some bugs in API v2 `/verification`:
1. Missed `String.downcase()` in sourcify verification
2.  
```
2023-02-16T10:52:42.834 [error] #PID<0.1751.0> running BlockScoutWeb.Endpoint (connection #PID<0.1750.0>, stream id 1) terminated
Server: localhost:80 (http)
Request: POST /api/v2/smart-contracts/0x030f7c7dbd472864220bcf9e37ede1b8a3125970/verification/via/sourcify
** (KeyError) key :content_type not found in: "". If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(explorer 5.1.0) lib/explorer/smart_contract/solidity/publish_helper.ex:97: anonymous fn/1 in Explorer.SmartContract.Solidity.PublishHelper.get_one_json/1
(elixir 1.14.3) lib/enum.ex:4197: Enum.filter_list/2
(explorer 5.1.0) …
```
=> Fix bugs in verification API v2

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex, apps/explorer/test/explorer/chain_test.exs, config/runtime.exs
https://github.com/blockscout/blockscout/issues/6899
Inaccurate calculation of indexed blocks.
Rely on  actual `BlockCache.estimated_count()` in calculation rather than `max - min` since not all blocks can be indexed in the range.
=> Fix indexed blocks value in "Indexing tokens" banner

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Indexing banner displays 99% of indexed blocks.
Take into account if min block already indexed. This means that initial index down to the tail of the chain finished.
=> Fix 99% on indexing banner

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/6934
`CACHE_BLOCK_COUNT_PERIOD` is not actually period of update of "Block counter" cache because of higher `ttl_check_interval`.
Reduce `ttl_check_interval` to 1 sec for all cache modules, where it is set to > 1 min.
=> Reduce ttl_check_interval for cache modules

CHANGELOG.md, config/runtime.exs
It's not obvious that value of `INDEXER_MEMORY_LIMIT` must be a single number (https://discord.com/channels/973915550965174292/992040622254997566/1072857553622540399)
Added possibility to set `INDEXER_MEMORY_LIMIT` with suffixes like `gb`, `g`, `mb`, `m` independently of letter case. With no suffix interpreted as gb as it was.
=> Extend `INDEXER_MEMORY_LIMIT` env parsing

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-services.yml, docker-compose/docker-compose.yml
Resolves #4975 
Fetchers import blocks by stages and every stage is running in a separate transaction. So if fetcher was working on some blocks and the application stopped, some stages will not be completed, and most likely it will be the transaction stage which is most often the longest one.
- Added `trap_exit` flag to realtime and catchup fetchers so stopping application will wait until they are done with current fetch
- Added `shutdown_after` parameter to realtime and catchup fetch tasks
- Reordered application supervision tree so catchup fetcher is the first one to stop on application shutdown and the realtime fetcher is the second one
=> Fetchers graceful shutdown

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/transaction_action.ex
The current implementation doesn't allow setting `INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK` to the block that is not yet indexed. This PR fixes it.
=> Change tx actions warning importance

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Different token instance fetcher errors in the logs:
- error kind 1:
`12:11:36.604 [debug] failed to fetch token instance metadata for {"0xe513ca43714e13ba611750a001b8d099d970e282", 2084}: {:error, "ipfs resolve -r /ipfs/bafkreigvdbls327yodd77iinrijqdfhyrtvfav6xwl2i3r7pjl6q4qmqgm/2084.json: func called on wrong kind: \"LookupBySegment\" called on a bytes node (kind: bytes), but only makes sense on map or list\n"}`
- error kind 2: HTTP status code 301 redirect in token URI handled improperly
- Cryptokitties case handled improperly
- Process ipfs link, when after UID, custom path is added.
- Add handling of HTTP status code 301: find redirect location and request metadata from it.
- Properly add handling of Cryptokitties contract.
=> Token instance fetcher fixes

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/nft_helpers.ex, apps/block_scout_web/test/block_scout_web/views/nft_helpers_test.exs, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Multiple token instance metadata fetching errors
New fetching token instances covered:
- parse IPFS links, if protocol is in diverse case (IPFS://, IpFs:// etc)
- fetch URI, if token URI directly passed to `fetch_json/2`
- fetch URI, if token URI in quotes directly passed to `fetch_json/2`
- fetch URI, if CIDv0 IPFS id directly passed to `fetch_json/2`
- process an error, if whatever response code returned, but error message contains `execution reverted` text
- process an error, if whatever response code returned, but error message contains `VM execution error` text
=> Extend token instance metadata parsing functionality

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js
Closes https://github.com/blockscout/blockscout/pull/7015
ES linter warning:
>   81:9  warning  Unexpected var, use let or const instead  no-var
=> Resolve "Unexpected var, use let or const instead"

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, cspell.json
forma*t*ing should be forma*tt*ing
=> Fix `formating` in spell check

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/helper.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex
Define common function for calculation estimated rows count from Postgres DB, which is used by caching functionality.
=> Define common function for "reltuples" query

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/interact.js
Add path_helper in interact.js in order to display custom path in popup messages appeared from interact.js
=> Add path_helper in interact.js

CHANGELOG.md, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Add mocks for external URLs requests in instance metadata retriever tests
=> Instance metadata retriever mocks

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs, apps/explorer/test/test_helper.exs
Failing test: `test/explorer/token/instance_metadata_retriever_test.exs:471`
- Wrap HTTPoison in order to add possibility to mock it in tests
=> Mock HTTP fetch metadata requests

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex
Currently, `Indexer.Fetcher.TokenUpdater` collects tokens to be updated based on `updated_at` field. But if there are no actual changes for token, such an 'empty' update doesn't affect the `updated_at` field, which means that this token will be recognised as not updated on the next check and, therefore, there will be additional `eth_call`s even if this token was checked recently.
Set `updated_at` field manually on `Explorer.Chain.update_token/2` so empty updates will be 'stored' in `updated_at` field.
=> Set updated_at on token update even if there are no changes

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/block.ex
Resolves https://github.com/blockscout/blockscout/issues/7032
On application restart ETS cache is empty and blocks indexed ratio is based on estimated count from `reltuples` from `pg_class` query. Thus indexing banner may appear on every restart. We need to keep status of indexing in the DB as well.
On every calculated from DB count of blocks from `Explorer.Chain.Cache.Block` module, save the counter value in `last_fetched_counters` table and use it, if ETS cache is empty.
=> Save block count in the DB when calculated in Cache module

CHANGELOG.md, docker-compose/docker-compose-no-build-geth-clique-consensus.yml
Create a separate docker compose config for Geth with clique consensus.
=> Add a separate docker compose for geth with clique consensus

CHANGELOG.md, apps/block_scout_web/assets/js/lib/smart_contract/functions.js
If you will try to access any custom ABI tab you will see only infinite loader 
- Fix `loadFunctions()` usage
=> Fix custom ABI loading

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/main_page_controller.ex, apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex, apps/block_scout_web/lib/block_scout_web/counters/internal_transactions_indexed_counter.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
https://blockscout.com/poa/sokol/
Check value of `DISABLE_INDEXER` in `finished_indexing?/2` function
=> Hide indexing alert, if indexer disabled

CHANGELOG.md, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/repo/config_helper_test.exs
Now we cannot have special symbols like `#` in `DATABASE_URL`. If we leave it as it is ecto struggling to parse `DATABASE_URL`, if we encode it like `%23` ecto parses it fine, but config helper adds it to the password as is. For instance we can encode password `pass#` in `DATABASE_URL` like `pass%23` ecto wil decode it as `pass#` but config helper will parse `pass%23` thus in some places we will get authentication error.
Add `URI.decode()` before parsing in config helper
=> Allow URI special symbols in `DATABASE_URL`

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction/history/historian.ex
Tx stats chart sometimes stops to show new data (0 txs on the chart for current and some previous days).
Set infinity timeout timestamp_to_block_number query
=> Set infinity timeout in timestamp_to_block_number query

.github/workflows/publish-docker-image-every-push.yml, .github/workflows/publish-docker-image-release.yml, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Add release link or commit hash to generated by CI docker images
=> Add release link or commit hash to docker images

CHANGELOG.md, config/config_helper.exs
If env variable is set to an empty string, it doesn't use the default value which may cause unpredictable behaviour.
Use default value if env variable is set to an empty string.
=> Treat "" as empty value while parsing env vars

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Alert about indexing internal transactions shouldn't apperar, if INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true is set.
Take into account INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER for indexing alert.
=> Hide indexing alert if internal transactions indexer disabled

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/fetcher/uncle_block.ex, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Resolves #7125 
Currently realtime fetcher schedules next poll only after the current one is done, which may cause delays on new blocks detecting and reorgs missing.
- Changed realtime fetcher logic to schedule next run immediately
- Added a test to check if realtime fetcher handles reorg correctly
- Invalidate block consensus if internal transactions fetcher encounters the associated error
=> Block reorg fixes

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/cache/transaction_action_tokens_data.ex, apps/explorer/lib/explorer/chain/cache/transaction_action_uniswap_pools.ex, apps/explorer/lib/explorer/chain/import/runner/transaction_actions.ex, apps/indexer/lib/indexer/transform/transaction_actions.ex, config/runtime.exs
This PR does two things:
1. Removes `DELETE FROM` sql requests if tx actions transformer is called by realtime or catchup indexer. In this case already existing actions will be rewritten using primary key conflicting.
2. Moves ETS cache from tx actions module to a separate GenServer module like it's done for other modules. It's needed to prevent losing the cache when the module is restarted (as ETS is destroyed if its parent process dies).
=> Tx actions: remove excess `delete_all` calls and remake a cache

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
- set 404 on reorg response added in https://github.com/blockscout/blockscout/pull/7148
=> Set 404 on blocks which lose consensus

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
Resolves #6975 #7217 
Set `MissingRangesCollector` max block number to 0 if node is not responding.
=> Fix MissingRangesCollector max block number fetching

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/explorer/lib/explorer/chain.ex
This PR adds the following fields to transaction in API v2:
- L1 fee
- L1 fee scalar
- L1 gas price
- L1 gas used by Txn
These fields are contained in `eth_getTransactionReceipt` response. If some field doesn't exist, it won't be included into API v2 response.
Also, this PR adds `L1 fee` to the `fee` so that `fee` equals to `l2_execution_fee + l1_data_fee` as described in https://community.optimism.io/docs/developers/build/transaction-fees/. For L1 chains `L1 fee` will be zero and the fee will be calculated as usual, so this change is backward compatible.
=> Output L1 fields in API v2 for transaction and fix transaction fee calculation

CHANGELOG.md, config/runtime.exs
At the moment we have 0 default `TOKEN_EXCHANGE_RATE_REFETCH_INTERVAL` value that can cause exhausting coin gecko api use
Set default `1h` for `TOKEN_EXCHANGE_RATE_REFETCH_INTERVAL`
=> Fix default `TOKEN_EXCHANGE_RATE_REFETCH_INTERVAL`

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
99% of indexed internal transactions top banner may never disappear.
Convert 99+% into 100% in order to disable top indexin banner.
=> Convert 99+% of int txs indexing into 100% in order to hide top indexing banner

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves https://github.com/blockscout/blockscout/issues/7065
Dropped/replaced tx displays confirmed status
Display `dropped/replaced` status in that case.
=> Fix status for dropped/replaced tx

CHANGELOG.md, apps/explorer/priv/repo/migrations/20230417093914_allow_nil_tx_gas_price.exs
Resolves https://github.com/blockscout/blockscout/issues/6672
Resolves https://github.com/blockscout/blockscout/issues/6644
Erigon node returns empty gas price for pending txs in the request of `txpool_content` method.
Add new DB migration, which:
- allows null values for `gas_price` column in the `transactions` table
- adds `collated_gas_price` constraint, which claims, that gas_price shouldn't be null for transactions included into the block.
=> Allow nil gas price for pending tx (Erigon node case)

CHANGELOG.md, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json
Resolves https://github.com/blockscout/blockscout/issues/6924
Warning in docker container:
> npm WARN EBADENGINE required: { node: '18.x', npm: '8.x' },
=> => # npm WARN EBADENGINE current: { node: 'v16.13.1', npm: '8.3.0' }
=> Allow Node 16+ version

CHANGELOG.md, apps/explorer/config/dev/geth.exs, apps/explorer/config/prod/geth.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod/geth.exs
Currently we use `ETHEREUM_JSONRPC_TRACE_URL` for tracing methods in case of `nethermind`/`erigon` json rpc variants, but not in case of `geth`.
Use `ETHEREUM_JSONRPC_TRACE_URL` in case of `debug_traceTransaction` method.
=> Use tracing JSONRPC URL in case of debug_traceTransaction method

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
Reset `MissingRangesCollector` `min_fetched_block_number` in order to re-search missing blocks after bottom is reached.
=> Reset MissingRangesCollector min_fetched_block_number

CHANGELOG.md, deploy/testing/eth-goerli/values.yaml
Reduce resource consumption on bs-indexer-eth-goerli environment
=> Optimizing bs-indexer-eth-goerli resource consumption

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/token_controller_test.exs, apps/explorer/lib/explorer/chain/token.ex
Resolves https://github.com/blockscout/blockscout/issues/7315
tokensupply API v1 internal server error on tokens with nil total supply
Handle nil total supply in tokensupply API v1 endpoint.
=> Fix tokensupply API v1 endpoint: handle nil total_supply

CHANGELOG.md, apps/indexer/lib/indexer/transform/transaction_actions.ex, config/config_helper.exs, config/runtime.exs
Transaction actions indexer has hardcoded contract addresses for Uniswap v3. To be able to index Uniswap's actions on Base Goerli, we need to configure the addresses through env variables. This PR adds two new env vars: `INDEXER_TX_ACTIONS_UNISWAP_V3_FACTORY_CONTRACT` and `INDEXER_TX_ACTIONS_UNISWAP_V3_NFT_POSITION_MANAGER_CONTRACT`. They have default values taken from https://docs.uniswap.org/contracts/v3/reference/deployments. Base Goerli chain has [other addresses](https://docs.base.org/contracts/) for those contracts, so now we will be able to define arbitrary addresses if they don't match the default ones.
=> Add configs for Uniswap v3 transaction actions to index them on Base Goerli

.github/workflows/publish-docker-image-every-push.yml, CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth-clique-consensus.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-services.yml, docker-compose/docker-compose.yml, docker-compose/services/docker-compose-sig-provider.yml, docker-compose/services/docker-compose-smart-contract-verifier.yml, docker-compose/services/docker-compose-stats.yml, docker-compose/services/docker-compose-visualizer.yml
https://github.com/blockscout/blockscout/issues/6787
Currently `latest` docker image tag is updated on every push to master branch and every release issuance. But, update from every push to master is built only for linux/amd64 arch whereas release-based images are multi-platform.
- Update `latest` Docker image tag only from release issuance.
- With every push to master branch update `master` Docker image tag.
- Remove platform param from docker-compose configs.
=> Update Docker image tag `latest` with release only

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex
In case when the chain has a lot of empty blocks, fetching internal transactions for each is useless.
Delete pending block operations for empty blocks since they don't have internal transactions.
=> Delete pending block operations for empty blocks

.gitignore, CHANGELOG.md, docker-compose/services/docker-compose-db.yml, docker-compose/services/docker-compose-stats.yml
DB containers doesn't use persistent volumes.
Add volumes for explorer and stats Postgres Docker containers DBs
=> Add volume for Postgres Docker containers

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/7035
`INDEXER_HIDE_INDEXING_PROGRESS_ALERT` runtime env variable is added to manage visibility of indexing status alert.
Docs update in https://github.com/blockscout/docs/pull/148.
=> Manage visibility of indexing progress alert

CHANGELOG.md, apps/explorer/lib/explorer/chain/smart_contract.ex
Resolves https://github.com/blockscout/blockscout/issues/7311
`getImplementation()` getter is not supported for fetching implementation from proxy contract.
Recognize `getImplementation()` getter as a proxy pattern.
=> Proxy pattern with getImplementation()

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
- for some cases type for internal txs was not returned
- in response of `/addresses/{address_hash}/tokens` was no nft info
- Add type to internal transaction
- Add token_instance to response of `/addresses/{address_hash}/tokens`
=> API v2 improvements

CHANGELOG.md, docker-compose/README.md, docker-compose/services/docker-compose-sig-provider.yml, docker-compose/services/docker-compose-smart-contract-verifier.yml, docker-compose/services/docker-compose-stats.yml
https://github.com/blockscout/blockscout/issues/7440
Actualize docker-compose readme and use `latest` tags for Rust microservices instead `main`. Docs update is in https://github.com/blockscout/docs/pull/154.
=> Actualize docker-compose readme and use latest tags instead main

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/fallback_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/main_page_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex
- Add email to unverified email response
- Fix model of watchlist names in watchlist transactions endpoints
=> Minor API v2 fixes

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/withdrawal.ex, apps/explorer/lib/explorer/etherscan.ex, apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex, apps/indexer/lib/indexer/temporary/uncles_without_index.ex
Refactoring for the sake of consistency.
- Use `block` instead `b` in queries
- Set `block.consensus == true` in queries explicitly
=> Refactoring queries with blocks

CHANGELOG.md, apps/block_scout_web/assets/js/lib/csv_download.js
Resolves https://github.com/blockscout/blockscout/issues/7470#issuecomment-1545863177
RE_CAPTCHA_DISABLED is incorrectly parsed in JS.
Convert string into boolean in the parsing of RE_CAPTCHA_DISABLED env variable in JS.
=> Fix RE_CAPTCHA_DISABLED variable parsing

CHANGELOG.md, apps/explorer/lib/explorer/utility/missing_block_range.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex
Currently, catchup fetcher clears the batch of `missing_block_ranges` only after the whole batch has been processed. Since this batch can contain a large amount of blocks, it can take a lot of time for process and, if there will be any error on import (such as db disconnect), the batch will not be cleared, and therefore, the same batch will be processed on the next step.
Clear batch after every successful import
=> Clear missing block ranges after every success import

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/pending_transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/7483
`txpool_content` may return a list instead of a map in the result (LightLink example, see linked issue).
Check if a map is returned from the node in `fetch_pending_transactions_geth` function
=> Fix pending txs is not a map

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/token_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/websocket_v2_test.exs
Close #7202 
- Now websocket v2 groups and sends several updates in one message (for transactions and token transfers)
=> Websocket v2 improvements

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/config_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/config_view.ex
Resolves https://github.com/blockscout/blockscout/issues/7484
```
/api/v2/config/backend-version
```
Response example:
```
{
"backend_version": "v5.1.4-beta"
}
```
=> API v2: Pass backend version to the frontend

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss
Part of #6437 
.png images were shrinking in Safari browser
Changed default `width` value for logo from `100%` to `auto`
before:
after:
=> Fix shrinking logo in safari

CHANGELOG.md, apps/explorer/lib/explorer/repo/config_helper.ex, apps/explorer/test/explorer/repo/config_helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/7504
Fix regexp in order to allow hyphen in DB username.
=> Allow hyphen in DB username

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
Check if cached in memory exchange rate is empty before replacing DB value in stats API.
=> Check if cached exchange rate is empty before replacing DB value in stats API

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/withdrawal/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/withdrawal.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/withdrawals.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/withdrawals_sum.ex, apps/explorer/priv/repo/migrations/20230522130735_withdrawals_gwei_amount_to_wei_amount.exs
Close #7531
Currently withdrawal amount displayed in wei however it returned in gwei from the node
Also, sum counter does not work properly
- Convert withdrawal amount to wei
- Add `withdrawals_count` field to block structure and **_!remove `has_beacon_chain_withdrawals`!_**
- Fix sum counter
=> Withdrawals fixes and improvements 

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/polygon_tracer.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Fix #7090 
It turned out that Polygon edge trace is very different from geth trace, so it does not work now
Added separate tracer for geth to work with polygon.
There are some limitations:
- call ops are very strange in polygon edge, example:
```
{
"pc": 3132,
"op": "CALL",
"gas": 492083345,
"gasCost": 7400,
"depth": 2,
"stack": [],
"memory": [],
"storage": {}
}
```
so, `to` field in these cases is `0x0000000000000000000000000000000000000000`
=> Add polygon edge support

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/withdrawals_sum.ex
```
2023-05-25T17:34:07.299 [error] GenServer Explorer.Chain.Cache.WithdrawalsSum terminating
** (FunctionClauseError) no function clause matching in Explorer.Chain.Wei.to/2
(explorer 5.1.5) lib/explorer/chain/wei.ex:251: Explorer.Chain.Wei.to(nil, :wei)
(explorer 5.1.5) lib/explorer/chain/cache/withdrawals_sum.ex:72: Explorer.Chain.Cache.WithdrawalsSum.consolidate/0
(explorer 5.1.5) lib/explorer/chain/cache/withdrawals_sum.ex:38: Explorer.Chain.Cache.WithdrawalsSum.handle_continue/2
(stdlib 5.0) gen_server.erl:1067: :gen_server.try_handle_continue/3
(stdlib 5.0) gen_server.erl:977: :gen_server.loop/7
(stdlib 5.0) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :ok}
State: %{consolidate?: true}
```
Add handling of nil response from aggregate query
=> Fix withdrawals sum count on empty database

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/smart_contract/helper.ex
https://eth.blockscout.com/address/0xd9db270c1b5e3bd161e8c8503c55ceabee709552?tab=read_contract
Remove `fallback` type from read methods. It should populate Write tab instead.
=> Remove fallback from Read methods

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
return `contract_type` property in API v2 `api/v2/addresses/_hash_` endpoint.
=> Return contract type in address view

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Internal transactions fetcher currently drops first block to fetch from process since genesis block is not traceable. But first block is not always a genesis block, so in that case it shouldn't be dropped.
Drop first block from internal transactions fetcher process only if it is a genesis.
=> Drop genesis block in internal transactions fetcher

CHANGELOG.md, apps/block_scout_web/assets/css/components/_transaction.scss, apps/block_scout_web/assets/css/theme/_dark-theme.scss, apps/block_scout_web/assets/css/theme/custom_contracts/_circles-theme.scss, apps/block_scout_web/assets/css/theme/custom_contracts/_dark-forest-theme.scss, apps/block_scout_web/assets/js/lib/csv_download.js, apps/block_scout_web/assets/js/pages/address/logs.js, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/csv_export_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_csv_export_button.html.eex, apps/block_scout_web/lib/block_scout_web/templates/csv_export/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/csv_export.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/api/v2/main_page_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/csv_export/address_internal_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_log_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_token_transfer_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/helper.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/6041
Applied filters on the items list are not accounted while exporting data to CSV.
Apply selected filters (by address: to/from/created contract or by log topic) to CSV export as well: transactions, token transfers, internal transactions and logs.
=> CSV export filters

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/explorer/lib/explorer/chain.ex
- Pagination fails in case of null or the same token names, holders and market cap
- Nullable fields are not handled correctly
- Add token contract address hash to pagination key for uniqueness 
- Handle each nullable field individually
- Add `circulating_market_cap` field to /api/v2/tokens/ response
=> Fix tokens pagination

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/test/block_scout_web/channels/websocket_v2_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
For single 1155 transfers `total` come as list with single element
- Fix bug
=> Fix single 1155 transfer displaying

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs
Close #7597 
- Add new ipfs clause (now supported `ipfs/{id}` uri)
- Decrease timeout for NFT metadata fetch
=> Add new ipfs clause; Decrease timeout for NFT metadata fetch

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/smart_contract/helper.ex
Continuation of https://github.com/blockscout/blockscout/pull/7562
Receive function was not filtered
- Filter all functions with empty output
=> Fix ABI read functions filter

.github/workflows/publish-docker-image-for-base.yml, .github/workflows/publish-docker-image-for-core.yml, .github/workflows/publish-docker-image-for-eth.yml, .github/workflows/publish-docker-image-for-gc-chiado.yml, .github/workflows/publish-docker-image-for-l2-staging.yml, .github/workflows/publish-docker-image-for-lukso.yml, .github/workflows/publish-docker-image-for-optimism.yml, .github/workflows/publish-docker-image-for-polygon-supernets.yml, .github/workflows/publish-docker-image-for-xdai.yml, CHANGELOG.md
Keep CI for publishing Docker images for prod/staging environments in the master branch.
=> Publish docker images CI for prod/staging branches

.dialyzer-ignore, CHANGELOG.md, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/exchange_rates/source.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex, apps/explorer/lib/explorer/exchange_rates/token_exchange_rates.ex, apps/explorer/test/explorer/exchange_rates/token_exchange_rates_test.exs
Now major part of requests to coin gecko return null as tokens do not have market data
Firstly fetch tokens with market data via `/coins/list` then update only these tokens
=> Optimize exchange rates requests rate

CHANGELOG.md, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/indexer/lib/indexer/transform/token_transfers.ex, apps/indexer/test/indexer/transform/token_transfers_test.exs
Resolves #7652 
Add support for DEPOSIT and WITHDRAW token transfer event in older contracts
=> [FEAT] Add support for DEPOSIT and WITHDRAW token transfer event in older contracts

apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Internal transactions fetcher may update the address contract code so it needs to explicitly define `:on_conflict`
=> Fix address contract code update

CHANGELOG.md, apps/explorer/priv/repo/migrations/20230613181244_address_coin_balances_block_number_index.exs
It should significantly speed up queries like this for stats microservice (coin total supply calculation):
```
SELECT DISTINCT on (address_hash) address_hash, value
FROM address_coin_balances
WHERE last_previous_day_bn < block_number AND block_number <= last_current_day_bn
ORDER BY address_hash, block_number DESC;
```
=> Add block_number index for address_coin_balances table

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Close #7589 
- Replace `raw` function usage with E sigil
=> Fix contract args displaying bug

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs, apps/indexer/test/indexer/block/catchup/fetcher_test.exs
Missing ranges sanitizing may take a while which can lead to a failed launch of `MissingRangesCollector`.
Move sanitizing logic to `handle_continue` so GenServer will start immediately and perform necessary actions after initialization.
=> Move MissingRangesCollector init logic to handle_continue

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
`OptimismTxnBatch` fetcher stops indexing batches due to incorrect transactions ordering when L1 transactions are in the same block.
=> Fix transactions ordering in Indexer.Fetcher.OptimismTxnBatch

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
- Add `block_number` to logs entity
=> API v2: Add block_number to logs

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/addresses.ex
In cases when there are addresses that appears in many blocks, we have a large amount of blocking insert queries when in fact only small part of them will pass the `on conflict` condition. It makes sense to filter them on the app side first selecting them from db. These operations will not block each other.
Add addresses filtration before insertion.
=> Filter addresses before insertion

CHANGELOG.md, docker-compose/proxy/nginx.conf
The UI 2.0 is not working with the current blockscout nginx config - it fails on the websocket giving consistent errors
Done
=> fix nginx config for UI 2.0 websocket

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/email_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/auth_controller.ex
Close #7801 
- Add new invalid_session cookie for users with unverified email
=> Add new invalid_session cookie for users with unverified email

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/addresses.ex
Resolves https://github.com/blockscout/blockscout/issues/7300
Currently on the import of addresses, field `created_contract_code_indexed_at` for transactions is updated every time an address that has a `contract_code` was updated, regardless of whether the contract code was indexed for the first time or not.
Check if `contract_code` was indexed for the first time and update `created_contract_code_indexed_at` only if it is true.
=> Fix created_contract_code_indexed_at updating

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain/transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/7400
Pending txs fetcher throws errors when using Erigon node:
```
errors: [gas_price: {"can't be blank", [validation: :required]}]
```
Allow gas_price to be nil in the `transaction` model.
=> Fix gas price in pending tx

CHANGELOG.md, apps/block_scout_web/assets/js/pages/verification_form.js
Close #6923
- Replace trigger('click') with appropriate function call
- Fix UI bug:
=> Fix twin compiler version

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/explorer/test/explorer/chain/address/current_token_balance_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/addresses_tokens_usd_sum_counter_test.exs, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Close #7860 
- There was a bug in pagination in corner cases, when DB round fiat_value for ctb differently than elixir 
- Put fiat_value calculated in postgres to ctb in order to leave one point of truth
=> Token balances refactoring: put token to preloads; fix pagination bugs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
- Add `block_hash` to logs entity
=> API v2: Add block_hash to logs

.github/workflows/config.yml
https://github.com/blockscout/blockscout/issues/7929
CI failed in Github Actions with the message:
```
After this operation, 295 kB of additional disk space will be used.
Err:1 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy/main amd64 libstdc++6 amd64 13.1.0-2ubuntu2~22.04
404  Not Found [IP: 185.125.190.52 443]
E: Failed to fetch [https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-13/libstdc%2b%2b6_13.1.0-2ubuntu2%7e22.04_amd64.deb](https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-13/libstdc%2b%2b6_13.1.0-2ubuntu2~22.04_amd64.deb)  404  Not Found [IP: 185.125.190.52 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Downgrade to Ubuntu 20.04 in the main CI …
=> Fix fetching libstdc++ in install_chrome_headless.sh

CHANGELOG.md, apps/explorer/lib/explorer/account/notifier/summary.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/smart_contract/vyper/code_compiler.ex, apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex, apps/indexer/lib/indexer/temporary/uncles_without_index.ex
Explicitly set consensus == true in queries (convenient for search)
=> Explicitly set consensus == true in queries (convenient for search)

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/user_controller.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v1/user_view.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v1/user_controller_test.exs, apps/explorer/lib/explorer/account/watchlist_address.ex, apps/explorer/test/support/factory.ex
Close #7887
- Add `tokens_fiat_value`, `tokens_count` and `tokens_overflow` to watchlist address model
=> Add token balances info to watchlist address response

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/api_key_v2_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/api_key_controller.ex, apps/block_scout_web/lib/block_scout_web/views/access_helper.ex
Close #7945 
- Put API v2 rate limit token to cookies
- Change `/api/v2/key` method from GET to POST
=> API v2 rate limit: Put token to cookies & change /api/v2/key method

CHANGELOG.md, apps/explorer/lib/explorer/account/notifier/email.ex
Fixes #7938 
Currently, email notifications on mainnet contain wrong tx address, e.g.:
`https://blockscout.com/tx/0x8ae7becf6abe11ff4eec490537f26e9cac228af37dbc3503e9bc030162e42b79` instead of `https://eth.blockscout.com/tx/0x8ae7becf6abe11ff4eec490537f26e9cac228af37dbc3503e9bc030162e42b79`
The url-building logic contained redundant check for `prod` environment that led to wrong hostname substitution. According to the docs, the environment should have correct value in `BLOCKSCOUT_HOST` ENV variable.
=> Fixed wrong TX url in email notifications for mainnet

CHANGELOG.md, apps/explorer/lib/explorer/account/notifier/email.ex, apps/explorer/test/explorer/account/notifier/email_test.exs, apps/explorer/test/explorer/account/notifier/notify_test.exs, apps/explorer/test/explorer/account/notifier/summary_test.exs
https://github.com/blockscout/blockscout/pull/7951
Enhance tests for `Explorer.Account.Notifier.Email` module
=> Enhance Account Explorer.Account.Notifier.Email module tests

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/tokens_controller.ex, apps/block_scout_web/lib/block_scout_web/paging_helper.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex
Part of #7794 
Added two new query parameters for `api/v2/tokens` endpoint
- `sort` - possible values: `fiat_value`, `holder_count`, `circulating_market_cap`
- `order` - possible values: `asc`, `desc`
Added `fiat_value` to `next_page_params` to be able to sort by `fiat_value`, note that it should _not_ break the new UI
This PR can be tested in the old ui on the https://github.com/blockscout/blockscout/tree/mf-add-tokens-sorting-test branch by adding these new query parameters by hand
=> API v2: Add sorting to tokens page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/csv_export/address_internal_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_log_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_token_transfer_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/address_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/csv_export/helper.ex, apps/explorer/priv/repo/migrations/20230615130940_add_blocks_date_index.exs, apps/explorer/test/explorer/chain/csv_export/address_internal_transaction_csv_exporter_test.exs, apps/explorer/test/explorer/chain/csv_export/address_log_csv_exporter_test.exs, apps/explorer/test/explorer/chain/csv_export/address_token_transfer_csv_exporter_test.exs, apps/explorer/test/explorer/chain/csv_export/address_transaction_csv_exporter_test.exs, apps/explorer/test/explorer/chain_test.exs
Close #5009 
- Change all the paginated quries to query with limit 10_000
- Get rid of useless DB requests on CSV export
- Add new index for blocks table:
plan on goerli after index:
```
Result  (cost=4.13..4.14 rows=1 width=8) (actual time=0.037..0.038 rows=1 loops=1)
InitPlan 1 (returns $0)
->  Limit  (cost=0.44..4.13 rows=1 width=8) (actual time=0.035..0.035 rows=0 loops=1)
->  Index Scan Backward using blocks_date on blocks b0  (cost=0.44..169589.80 rows=45868 width=8) (actual time=0.034..0.035 rows=0 loops=1)
Index Cond: ((date("timestamp") = to_date('2019-01-14'::text, 'YYYY-MM-DD'::text)) AND (number IS NOT NULL))
Planning Time: 0.195 ms
Execution Time: 0.056 ms
```
plan on goerli before index:
```
Result  (cost=26.48..26.49 rows=1 width=8) (actual time=4767.006..4767.007 rows=1 …
```
=> Csv export improve

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_total_supply_updater.ex, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/lib/indexer/transform/token_transfers.ex
Token's `total_supply` update happens on every transfer to or from burn address and since token transfers are indexed concurrently, there may be many updates of the same tokens at the same time.
Added `TokenTotalSupplyUpdater` which accumulates unique tokens to update and updates them together periodically
=> Add TokenTotalSupplyUpdater

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/coin_balance.ex, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Fix #7874 
Batch size of balances that are requested by realtime block fetcher is not limited, so there may be a situation when amount of such requests is larger than requests batch size limit on node, which will lead to the failed block import.
Added separation balances requests by chunks with size equal to batch size of coin balance fetcher to the realtime fetcher.
=> Chunk realtime balances requests

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Currently we delete token balances on block import for every consensus block but it's needed only for reorgs so it's reasonable to delete balances only for blocks that lost consensus.
Changed blocks runner to delete token balances only for blocks that lost consensus
=> Delete token balances only for blocks that lost consensus

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/indexer/lib/indexer/fetcher/empty_blocks_sanitizer.ex, apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Resolves https://github.com/blockscout/blockscout/issues/6755
Resolves https://github.com/blockscout/blockscout/issues/6734
Currently we are using `FOR UPDATE` locks in every lock queries, but there is no need to use this lock type for queries that are not going to delete or modify primary key. In these cases it's better to use `FOR NO KEY UPDATE` to avoid unnecessary locks.
Also, there are several locks that hold data not meant to be updated.
- Change lock type from `FOR UPDATE` to `FOR NO KEY UPDATE` for queries that are not going to delete data or modify PK
- Move tokens lock acquiring from `Blocks` and `CurrentTokenBalances` runners to update token holders function since this lock is only needed for insert ordering
- Upgrade lock acquiring in `EmptyBlockSanitizer` so it doesn't …
=> Improve locks acquiring

CHANGELOG.md, apps/explorer/lib/explorer/eth_rpc.ex, apps/explorer/lib/explorer/etherscan/logs.ex
Resolves https://github.com/blockscout/blockscout/issues/8059
`eth_getLogs` pagination function is broken.
Remove unused in query and expected in paging options `transaction_index`.
=> Fix eth_getLogs API endpoint

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/explorer/lib/explorer/chain/supply/rsk.ex
Resolves https://github.com/blockscout/blockscout/issues/8083
`/api/v2/stats/charts/market` returns 500 error in case of Rootstock supply module (`SUPPLY_MODULE=rsk`)
Correctly parse current available supply in case of Rootstock.
=> Fix Rootstock charts API

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_tag.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/mox_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/test/explorer/chain/cache/gas_price_oracle_test.exs, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
Resolves #6137
Add function `fetch_block_by_tag` to `EthereumJSONRPC` module to check base fee in pending block. 
Take into account EIP-1559 in gas price oracle.
~~I noticed that env var `GAS_PRICE_ORACLE_CACHE_PERIOD` is actually ignored. According to [ConCache docs](https://hexdocs.pm/con_cache/ConCache.html#start_link/1) setting `:ttl_check_interval` to 5 minutes and `:global_ttl` to `GAS_PRICE_ORACLE_CACHE_PERIOD` does not mean to update gas price every `GAS_PRICE_ORACLE_CACHE_PERIOD` seconds, but update it every maximum of `GAS_PRICE_ORACLE_CACHE_PERIOD` seconds and 5 minutes, so we need to set `:ttl_check_interval` to `GAS_PRICE_ORACLE_CACHE_PERIOD` too.~~ was fixed here https://github.com/blockscout/blockscout/pull/6940
=> Add EIP-1559 support to gas price oracle

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain/market_history_chart_controller.ex
Finalization of https://github.com/blockscout/blockscout/pull/8082
`available_supply` is defined twice: in API v2 and in the controller for an old UI.
Define generalized `available_supply` function.
=> Generalize available_supply function across application versions

apps/indexer/lib/indexer/fetcher/rootstock_data.ex
Now fetcher do not start to fetch blocks from node after fetching from database
=> Fix cycle of rootstock fetcher

docker/Dockerfile
Fix error while building Docker image
`Step 29/47 : ADD *.exs .
When using ADD with more than one source file, the destination must be a directory and end with a /`
=> Fix Dockerfile build

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
This is a continuation of https://github.com/blockscout/blockscout/pull/7827 for the cases like this:
```
2023-08-04 16:32:16.666	
State: %{batch_inbox: "0xff00000000000000000000000000000000000010", batch_submitter: "0x6887246668a3b87f54deb3b94ba47a6f63f32985", block_check_interval: 6180, chunk_size: 4, current_channel_id: "", end_block: 17841935, incomplete_frame_sequence: %{bytes: "", l1_transaction_hashes: [], last_frame_number: -1}, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://65.108.234.142:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]]], json_rpc_named_arguments_l2: [transport: EthereumJSONRPC.HTTP, transport_options: [http: …
```
=> Ignore previously handled frame by OP transaction batches module

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
Close #7924 
- Add method_id to write methods in API v2 response
=> Add method_id to write methods in API v2 response

.github/workflows/config.yml, CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs
Close #8139
- Switch sourcify tests from POA Sokol to Gnosis Chiado
=> Switch sourcify tests from POA Sokol to Gnosis Chiado

CHANGELOG.md, apps/explorer/lib/explorer/utility/missing_block_range.ex
Fix missing range insertion logic in case when the inserted range doesn't fall with its bounds into any of the existing. We should delete all ranges between the bounds of new range before inserting.
=> Fix missing range insert

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Resolves https://github.com/blockscout/blockscout/issues/7961
Currently we add every block number that lost consensus on import to `missing_block_ranges` but it's unnecessary for blocks that was imported with `consensus=true` at the same time.
Remove numbers that was just inserted from those that should be refetched.
=> Don't add reorg block number to missing blocks

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
https://github.com/blockscout/blockscout/issues/8062
In some case requested incorrect path in API v1 returns 500 error. Instead, it should return 404.
=> API v1 500 error convert to 404, if requested path is incorrect

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/endpoint.ex
Debug changes was merged accidentially within https://github.com/blockscout/blockscout/pull/8165
- Return timeout for /socket/v2
=> Revert changing /socket/v2 timeout

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
This is a continuation of https://github.com/blockscout/blockscout/pull/7827 for the cases like this:
```
2023-08-15T08:08:43.235 fetcher=optimism_txn_batches [error] GenServer Indexer.Fetcher.OptimismTxnBatch terminating
** (MatchError) no match of right hand side value: {:error, "Invalid frame sequence. Last frame number: 2. Next frame number: 4. Tx hash: 0xafde0199e602cde34fd5d71792abcb971dcfe49309cec61e08f241ab2e21292f."}
(indexer 5.2.1) lib/indexer/fetcher/optimism_txn_batch.ex:173: anonymous fn/9 in Indexer.Fetcher.OptimismTxnBatch.handle_info/2
(elixir 1.14.5) lib/range.ex:392: Enumerable.Range.reduce/5
(elixir 1.14.5) lib/enum.ex:2514: Enum.reduce_while/3
(indexer 5.2.1) lib/indexer/fetcher/optimism_txn_batch.ex:163: Indexer.Fetcher.OptimismTxnBatch.handle_info/2
(stdlib 4.3.1.2) …
```
=> Ignore invalid frame by OP transaction batches module

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
This is a continuation of https://github.com/blockscout/blockscout/pull/7827 for the cases like this:
```
2023-08-16T13:56:52.534 fetcher=optimism_txn_batches [error] GenServer Indexer.Fetcher.OptimismTxnBatch terminating
** (MatchError) no match of right hand side value: {:error, "Invalid RLP in frame sequence. Tx hash of the last frame: 0xdfd9b119af3e28d65a15a29cecee889aa20ec5a086336904ca11e85cc751d693. Compressed bytes of the sequence: 0x78da7c5c555895ed16a4bb43ba414a90ee92ee9f06e9ee0691ee6e9410a4a4bbbb4140ba4b1ae96e693cb7fbbd39e7ee3cf3fcb8bffdbdef5ab36666edd62744a88727d85c04d89f9df0deb405138517be4d6e9eb86e611d5e2835771afd9932ccc8b2c97921f121c6b9128df80cac7911d7d847706f3a55b023df51f1d2a8b99a2e2458f47cf20fb9780935afa18d7f786c6c7dac7b78ac0e26930efd90580e150acdce0295acf1a81a00bf45f1187153c …
```
=> Fix Indexer.Fetcher.OptimismTxnBatch

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs, apps/indexer/lib/indexer/block/fetcher.ex
#8157 
Insert current token balances placeholders along with historical balances so `TokenBalanceOnDemand` fetcher will update balances more accurately
=> Insert current token balances placeholders along with historical

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/coin_balance.ex, apps/explorer/lib/explorer/chain/address/coin_balance_daily.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20230815131151_drop_logs_address_hash_foreign_key.exs, apps/explorer/priv/repo/migrations/20230816061723_drop_token_transfers_and_transactions_address_foreign_key.exs, apps/explorer/priv/repo/migrations/20230817061317_drop_address_foreign_keys.exs, apps/explorer/priv/repo/migrations/20230821120625_drop_rest_address_foreign_keys.exs
Drop address foreign-keys from logs, token transfers, transactions, tokens, token balances, coin balances and internal transactions for performance reasons.
=> Drop address foreign keys

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/web_router.ex
Finalization of #8105
Remove duplicate API endpoints for CSV export and GraphQL.
=> Planned removal of duplicate API endpoints: for CSV export and GraphQL

CHANGELOG.md, docker-compose/docker-compose-no-build-external-frontend.yml, docker-compose/docker-compose-no-build-frontend.yml, docker-compose/docker-compose-no-build-geth-clique-consensus.yml, docker-compose/docker-compose-no-build-geth.yml
Resolves https://github.com/blockscout/blockscout/issues/8277
`ETHEREUM_JSONRPC_TRACE_URL` env variable is not added to docker-compose config with Geth node.
Add  `ETHEREUM_JSONRPC_TRACE_URL`, where it is missing docker-compose configs.
=> Add ETHEREUM_JSONRPC_TRACE_URL for Geth in docker-compose.yml

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/fetcher.ex
Currently, if a range handled by catchup fetcher throws an exception constantly, the sequence will never be empty and therefore catchup fetcher will not fetch other missing blocks.
Removed pushing back to sequence on catchup exception so other missing blocks will be processed even if some of them throws an exception on every try.
=> Don't push back to sequence on catchup exception

CHANGELOG.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-geth-clique-consensus.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose-no-rust-services.yml
Switch to Elixir prod environment in docker-compose.
Add `MIX_ENV: 'prod'` into docker-compose configs
=> Add MIX_ENV: 'prod' to docker-compose

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
`BlockScoutWeb.API.V2.OptimismView` module doesn't take into account null `from` field (in case of L2 transaction is not indexed yet). Because of that there can be errors like this:
```
2023-08-31 14:36:13.496	
(block_scout_web 5.2.2) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.phoenix_controller_pipeline/2
2023-08-31 14:36:13.496	
(block_scout_web 5.2.2) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.action/2
2023-08-31 14:36:13.496	
(phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
2023-08-31 14:36:13.496	
(phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
2023-08-31 14:36:13.496	
(block_scout_web 5.2.2) …
```
=> Fix API v2 for OP Withdrawals

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex
`/api/v2/stats` API endpoint returns 0 market cap:
```
{
"average_block_time": 5020.0,
"coin_price": "1.018",
"gas_prices": {
"average": 1.71,
"fast": 2.07,
"slow": 1.55
},
"gas_used_today": "65263362659",
"market_cap": "0",
"network_utilization_percentage": 11.9133755,
"static_gas_price": null,
"total_addresses": "1117657",
"total_blocks": "473390",
"total_gas_used": "0",
"total_transactions": "1098480",
"transactions_today": "124792"
}
```
Despite market cap extracted from the source and retuned in `/api/v2/stats/charts/market`
```
{
"available_supply": 0,
"chart_data": [
{
"closing_price": "1.018",
"date": "2023-09-05",
"market_cap": "234074505"
}
]
}
```
Take market cap from `market_cap_usd`, if it is returned.
=> Fix market cap in /stats endpoint

docker-compose/proxy/default.conf.template
The locations of favicon.ico move to /public/favicon from /public/static in this pull request (https://github.com/blockscout/frontend/pull/1152), so we should add add routing proxies starting with favicon to FRONT_PROXY_PASS.
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the …
=> Add routing proxies starting with favicon to FRONT_PROXY_PASS

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/token_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/recent_transactions_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex, apps/explorer/lib/explorer/account/notifier/forbidden_address.ex, apps/explorer/lib/explorer/account/notifier/summary.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/block/reward.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/etherscan.ex, apps/indexer/lib/indexer/transform/address_token_balances.ex, apps/indexer/lib/indexer/transform/token_transfers.ex, apps/indexer/lib/indexer/transform/transaction_actions.ex
Burn address is defined multiple times.
Define burn address once and re-use in other modules.
=> Unify burn address definition

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex, apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs, cspell.json
An error arises in native coin market cap calculation when `EXCHANGE_RATES_COINMARKETCAP_COIN_ID` is provided:
```
2023-09-10T03:23:37.990 [error] Task #PID<0.4384.0> started from Explorer.Market.History.Cataloger terminating
** (FunctionClauseError) no function clause matching in Access.get/3
(elixir 1.14.5) lib/access.ex:286: Access.get({"circulating_supply", 0}, "last_updated", nil)
(explorer 5.2.2) lib/explorer/exchange_rates/source/coin_market_cap.ex:145: Explorer.ExchangeRates.Source.CoinMarketCap.get_last_updated/1
(explorer 5.2.2) lib/explorer/market/history/source/price/coin_market_cap.ex:42: Explorer.Market.History.Source.Price.CoinMarketCap.format_data/1
(explorer 5.2.2) lib/explorer/market/history/source/price/coin_market_cap.ex:21: …
```
=> Fix market cap calculation in case of CMC

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs, apps/explorer/lib/explorer/chain/block.ex
https://github.com/blockscout/blockscout/issues/8209
Since blocks can lost consensus not only because there was a reorg (according to application logic), the current reorgs query is not quite correct.
Fix reorgs query so it checks if there is a block with the same number and `consensus: true`
=> Fix reorgs query

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/internal_transaction/type.ex, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs, apps/explorer/test/explorer/chain/internal_transaction_test.exs
Put error in last call on STOP operations + fixed `REVERT` in call tracer calls parser
=> Put error in last call for STOP opcode

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/test/explorer/chain/import/runner/transactions_test.exs
There are cases when a block is imported later than the transactions of its reorg, so transactions related to the reorg will not be cleared and therefore reorg may have non-zero transactions.
Clear transactions of a reorg in transactions runner if there are any.
=> Fix reorg transactions

CHANGELOG.md, docker/Dockerfile
Docker image hasn't been created with the release 5.2.2
Change parent image back to `bitwalker/alpine-elixir-phoenix:1.14`
=> Fix arm docker image build

.github/workflows/publish-docker-image-release.yml, CHANGELOG.md
Automate interal release announcements
- Add release announcement to the Slack
- Disable branches updates on release since it works imperfect
=> Add release announcement in Slack

CHANGELOG.md, docker-compose/README.md, docker-compose/docker-compose-no-build-erigon.yml, docker-compose/docker-compose-no-build-external-frontend.yml, docker-compose/docker-compose-no-build-ganache.yml, docker-compose/docker-compose-no-build-geth-clique-consensus.yml, docker-compose/docker-compose-no-build-geth.yml, docker-compose/docker-compose-no-build-hardhat-network.yml, docker-compose/docker-compose-no-build-nethermind.yml, docker-compose/docker-compose-no-build-no-db-container.yml, docker-compose/docker-compose.yml, docker-compose/envs/common-frontend.env, docker-compose/services/docker-compose-frontend.yml, docker-compose/services/docker-compose-redis.yml, docker-compose/services/docker-compose-sig-provider.yml, docker-compose/services/docker-compose-smart-contract-verifier.yml, docker-compose/services/docker-compose-stats.yml, docker-compose/services/docker-compose-visualizer.yml
Ports from Redis, old UI, microservices are exposed to the outside in the docker-compose setup.
Conceal those ports.
=> Conceal secondary ports in docker compose setup

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
Resolves #8274 
There are cases when transaction's receipt has failed status, but its first trace has successful status, so we override transaction's status to success even if was failed.
Don't override transaction status from first trace
=> Don't override transaction status

CHANGELOG.md, apps/explorer/lib/explorer/chain/transaction.ex
Close #7529 
- Fix the root cause of the warning
=> Handle ':error.types/0 is undefined' error

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
Close #8270 
- Add `block_type` to search results with `type=block`
=> Add block_type to search results

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_checker.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_observer.ex, apps/indexer/lib/indexer/fetcher/optimism.ex, apps/indexer/lib/indexer/fetcher/optimism_deposit.ex, apps/indexer/lib/indexer/fetcher/optimism_output_root.ex, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex, apps/indexer/lib/indexer/fetcher/optimism_withdrawal.ex, apps/indexer/lib/indexer/fetcher/optimism_withdrawal_event.ex
In cases when the node is unavailable, fetchers that make requests in the `init` function will cause the `Indexer.Supervisor` to crash, but the application should start even on an unavailable node.
Move requests to node from `init` to `handle_continue` so `Indexer.Supervisor` won't crash if node is unavailable.
=> Refactor optimism fetchers init

CHANGELOG.md, bin/install_chrome_headless.sh
Currently, `104.0.5112.79` version of Chromedriver is hardcoded.
Get latest version of Chromedriver from `https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json`.
=> Update Chromedriver version

CHANGELOG.md, docker-compose/proxy/default.conf.template
Currently, proxy works in such a way, that it opens all backend paths and proxy specified frontend paths. Since backend paths are rather stable and are no supposed to be changed or extended, but in the other hand, there can bew new paths appeared on the frontend. It is make more sense to switch: use all frontend paths and proxy list of known paths from backend.
Nginx template modification:
- Proxy all frontend paths by default
- Proxy known backend paths
=> Update Nginx to proxy all frontend paths

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/plug/redis_cookie.ex, apps/explorer/lib/explorer/third_party_integrations/auth0.ex
Resolves https://github.com/blockscout/blockscout/issues/8467
Store chain id together with cookie hash as a key in Redis: ${chain_id}_${hash(cookie)}
=> Store chain together with cookie hash in Redis

CHANGELOG.md, apps/explorer/lib/explorer/market/history/cataloger.ex, apps/explorer/test/explorer/market/history/cataloger_test.exs, config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/8535
Setting `DISABLE_EXCHANGE_RATES=true` doesn't disable market history cataloger.
=> Disable market history cataloger fetcher when exchange rates are disabled

CHANGELOG.md, apps/block_scout_web/assets/webpack.config.js
After these changes https://github.com/blockscout/blockscout/commit/917555f092b786bd3e36e048a727247d40f0627a
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#notes
Icons from font awesome are not displayed in the explorer:
With `esModule: false` option icons are displayed correctly:
=> Fix css-loader

CHANGELOG.md, apps/indexer/lib/indexer/block/realtime/fetcher.ex
https://github.com/blockscout/blockscout/issues/8630
Average block times can be high for low-usage rollups (for instance at the beginning of the launch). We should set max JSON RPC poll frequency in order to prevent missing latest blocks when connection to ws endpoint is disabled.
Set max 30sec JSON RPC poll frequency for realtime fetcher when WS is disabled.
=> Set max 30sec JSON RPC poll frequency for realtime fetcher when WS is disabled

.github/workflows/codeql-analysis.yml, .github/workflows/config.yml, .github/workflows/publish-docker-image-every-push.yml, .github/workflows/publish-docker-image-for-core.yml, .github/workflows/publish-docker-image-for-eth-goerli.yml, .github/workflows/publish-docker-image-for-eth.yml, .github/workflows/publish-docker-image-for-fuse.yml, .github/workflows/publish-docker-image-for-immutable.yml, .github/workflows/publish-docker-image-for-l2-staging.yml, .github/workflows/publish-docker-image-for-lukso.yml, .github/workflows/publish-docker-image-for-optimism.yml, .github/workflows/publish-docker-image-for-rsk.yml, .github/workflows/publish-docker-image-for-xdai.yml, .github/workflows/publish-docker-image-for-zksync.yml, .github/workflows/publish-docker-image-release.yml, CHANGELOG.md, docker/Dockerfile
Resolves https://github.com/blockscout/blockscout/issues/8521
Blockscout docker images are failed to run on arm64 platform (macbook m1, m2).
1. Change base image to
```
FROM hexpm/elixir:1.14.5-erlang-24.2.2-alpine-3.18.2
```
*Note*: I was trying to test with Erlang 25, however arm64 docker image hasn't been built in 5+ hours as here https://github.com/blockscout/blockscout/actions/runs/6566570051/job/17837533330, so decided to return to Erlang 24.
2. Remove `docker/setup-qemu-action@v2` GA plugin from workflows, which build docker images.
Chore:
- Update GA plugin versions in all workflows.
=> arm64-compatible docker image

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance.ex
Fixed a TokenBalance fetcher bug that we are ignoring all successfully fetched balances if there is at least one failed
=> Fix TokenBalance fetcher retry logic

CHANGELOG.md, apps/indexer/lib/indexer/transform/address_coin_balances.ex, apps/indexer/test/indexer/transform/address_coin_balances_test.exs
Currently we are updating coin balances for all addresses that present in logs on block import. But token transfers cannot change the coin balance of any address.
Filter token transfer logs from collecting addresses for coin balance update.
=> Filter token transfers on coin balances updates

CHANGELOG.md, apps/explorer/lib/explorer/application.ex, config/runtime/dev.exs, config/runtime/prod.exs
Setting pool size=50 leads to number of connections to DB > 200.
Exclude repos which are supposed to be operated by the same DB (like RSK and PolygonEdge repos) for the application children except tests. Currently, all pool sizes are concatenated, resulting high total pool size.
=> Fix db pool size exceeds Postgres max connections

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/8623
If there is an error in parent internal transactions, all child errors will be the same, which means that if child internal transaction have its own error, it will be overridden.
Put parent's error in child internal transactions only if there is no error yet.
=> Don't override internal transaction error if it's present already

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/explorer/lib/explorer/smart_contract/solidity/publish_helper.ex
Close #8710 
- Add new function that purely go to sourcify, and do not trigger eth_bytecode_db
=> Fix sourcify check

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
The `wrapped` field has been renamed to `requestRecord` in `eth_getTransactionByHash` response on Suave node.
=> Rename `wrapped` field to `requestRecord` for Suave

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Close #8621 
- Extend query condition in `preload_transactions/2`
=> CoinBalanceHistory tab: show also tx with gasPrice & gasUsed > 0

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex
Gas prices update task takes several seconds to complete during which `get_gas_prices()` returns `nil`.
Save prices value as old value before deletion as a fallback for `get_gas_prices()`.
=> Save GasPriceOracle old prices as a fallback

CHANGELOG.md, apps/explorer/lib/release_tasks.ex
Redundant default value `repos_list` for explorer.ecto_repos in Explorer.ReleaseTasks
=> Remove repos_list (default value for ecto repos) from Explorer.ReleaseTasks

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20231025102325_add_op_withdrawal_index.exs
Closes https://github.com/blockscout/blockscout/issues/8598.
We need to display Withdrawal status on transaction page.
=> Add OP withdrawal status to transaction page in API

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex
This small change adds 2-second delay to Indexer.Fetcher.OptimismTxnBatch module when its starting to avoid exceeding Supervisor restart intensity (in case of DB issues).
=> Add delay to Indexer.Fetcher.OptimismTxnBatch module initialization

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Resolves https://github.com/blockscout/blockscout/issues/8737
Fetch implementation from GnosisSafe proxy's `singleton` input.
=> Gnosis safe proxy via singleton input

CHANGELOG.md, apps/explorer/lib/explorer/market/market.ex
Resolves https://github.com/blockscout/blockscout/issues/8764
tvl is not updated for historical dates when `market_history` table is previously filled.
Change update on conflict behavior from DO NOTHING to UPDATE with non-null positive values. This is applied to tvl, market_cap and prices.
=> Fix for tvl update in market history when row already exists

.github/workflows/config.yml, CHANGELOG.md, apps/explorer/test/explorer/token/instance_metadata_retriever_test.exs, apps/indexer/lib/indexer/transform/addresses.ex, bin/install_chrome_headless.sh
`Indexer.Transform.Addresses` module didn't import an address from `to_address_hash` transaction's field when `CHAIN_TYPE` env is not defined as `suave`.
=> Fix Indexer.Transform.Addresses for non-Suave setup

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/explorer/lib/explorer/etherscan/blocks.ex
Resolves https://github.com/blockscout/blockscout/issues/8769
`eth_get_balance` API returns the latest value found in coin balance history for block number equal or less then latest indexed. However, this can be fragile when fetcher of internal transactions didn't finished initial index.
Get balance for a latest tag from `fetched_coin_balance` in `addresses` table for the given address.
=> Fix for eth_getbalance API v1 endpoint when requesting latest tag

.github/workflows/config.yml, CHANGELOG.md, config/runtime.exs
- Enable API v2 by default
https://github.com/blockscout/docs/pull/196
=> Enable API v2 by default

apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/null_round_height.ex, apps/explorer/lib/explorer/utility/missing_block_range.ex, apps/explorer/priv/repo/migrations/20231109104957_create_null_round_heights.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/fetcher/transaction_action.ex
Resolves https://github.com/blockscout/blockscout/issues/8803
- Added `NullRoundHeight` entity that stores non-existent block numbers.
- Fill `NullRoundHeight` with block numbers from requests with error message `requested epoch was a null round`.
- Don't count null rounds as missing blocks.
- Refactored places that use previous or next block number to use it in accordance with possible null rounds.
=> Null round handling

.github/workflows/config.yml, CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
This change fixes the following error:
```
Request: GET /api/v2/transactions/0xc2f1dc7be06c8580bb233e97a736b1fd15cb5cd4274ffd21e1119cf7f3e076d0
from o0 in Explorer.Chain.OptimismWithdrawal,
left_join: b1 in Explorer.Chain.Block,
on: o0.l2_block_number == b1.number,
left_join: o2 in Explorer.Chain.OptimismWithdrawalEvent,
on: o2.withdrawal_hash == o0.hash and o2.l1_event_type == :WithdrawalFinalized,
where: o0.l2_transaction_hash ==
^%Explorer.Chain.Hash{byte_count: 32, bytes: <<194, 241, 220, 123, 224, 108, 133, 128, 187, 35, 62, 151, 167, 54, 177, 253, 21, 203, 92, 212, 39, 79, 253, 33, 225, 17, 156, 247, 243, 224, 118, 208>>},
select: %{hash: o0.hash, l2_timestamp: …
```
=> Consider consensus block only when retrieving OP withdrawal transaction status

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/import_controller.ex, apps/explorer/lib/explorer/chain.ex
We send `already verified` error message on `/api/v2/import/smart-contracts/{address_hash}` if the contract has twin, but desired behavior is to verify such contracts
- do not ignore twin contracts on `/api/v2/import/smart-contracts/{address_hash}`
=> Do not ignore twin contracts on /api/v2/import/smart-contracts/{address_hash}

CHANGELOG.md, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/block_reward.ex, apps/indexer/lib/indexer/fetcher/coin_balance_daily_updater.ex, apps/indexer/lib/indexer/supervisor.ex
Currently, daily coin balances are updated on every new block which may cause a lot of conflicts on insert
Add a separate daily coin balances updater that accumulates unique balances and periodically updates them
=> Add CoinBalanceDailyUpdater

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Optimism [canyon](https://blog.oplabs.co/canyon-hardfork/) upgrade [introduces](https://github.com/ethereum-optimism/op-geth/blob/ed8e9f54ed0a5069e77ea34895ff12a9ac4ca17f/core/state_processor.go#L150-L152) a new depositReceiptVersion field in receipts and blockscout indexing breaks because of the extra field in the receipt.
Ignore depositReceiptVersion field from optimism txs receipts
=> Ignore depositReceiptVersion from optimism receipts

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
This change fixes the following error:
```
Request: GET /api/v2/transactions/0xc2f1dc7be06c8580bb233e97a736b1fd15cb5cd4274ffd21e1119cf7f3e076d0
from o0 in Explorer.Chain.OptimismWithdrawal,
left_join: b1 in Explorer.Chain.Block,
on: o0.l2_block_number == b1.number,
left_join: o2 in Explorer.Chain.OptimismWithdrawalEvent,
on: o2.withdrawal_hash == o0.hash and o2.l1_event_type == :WithdrawalFinalized,
where: o0.l2_transaction_hash ==
^%Explorer.Chain.Hash{byte_count: 32, bytes: <<194, 241, 220, 123, 224, 108, 133, 128, 187, 35, 62, 151, 167, 54, 177, 253, 21, 203, 92, 212, 39, 79, 253, 33, 225, 17, 156, 247, 243, 224, 118, 208>>},
select: %{hash: o0.hash, l2_timestamp: …
```
=> Hotfix for optimism_withdrawal_transaction_status function

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/lib/explorer/chain/address.ex
Close #8730 
- Do not preload smart contract info if address has no contract_code
=> Do not preload smart contract info if address has no contract_code

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/main_page_realtime_event_handler.ex, apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
Resolves https://github.com/blockscout/blockscout/issues/8736
Main page events are the most important of all since they are visible by every user from the very beginning of using app.
Move main page events to a separate handler so they won't be slowed down by other events.
=> Add MainPageRealtimeEventHandler

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance.ex
Queries inserting token balances may be long-running and since they are keeping locks that conflict with queries from block fetchers, it may cause block fetchers to fail because of timeout.
Set an increased but not infinity limit for token balances fetcher.
=> Limit TokenBalance fetcher timeout

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/authenticate_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/email_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/tags_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v1/user_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/views/account/api/v1/account_view.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v1/tags_view.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v1/user_view.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v1/user_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
Reverts blockscout/blockscout#8843
This change is incompatible with release 1.17.0, 1.17.1, 1.18.0-alpha. It should be done, after this issue release on frontend https://github.com/blockscout/frontend/issues/1367. @nikitosing please coordinate internally with frontend team.
=> Revert "Remove /api/account/v1 path"

CHANGELOG.md, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/test/explorer/counters/average_block_time_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8870
- Replaced `DateTime` structs comparison from `&>=/2` to `&Timex.after?/2` since primitive operators aren't accurate for structs
- Removed negative durations from total durations so non-chronological order of blocks won't result in negative avg time
=> Fix average block time

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Resolves https://github.com/blockscout/blockscout/issues/8918
There was a bug that deriving new current token balances after deletion of old ones in blocks runner did not fill out field `token_type` and [therefore](https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex#L225) `token_id`. This bug was fixed [here](https://github.com/blockscout/blockscout/pull/8355).
But affected current token balances that has empty `token_type` and `token_id` still exists. Most of them were deleted by indexing new blocks, but those that were not deleted cause errors in `TokenBalanceOnDemand` fetcher.
Delete current token balances that has empty `token_type` in `TokenBalanceOnDemand` fetcher.
=> Delete invalid current token balances in OnDemand fetcher

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/test/explorer/chain/smart_contract/proxy_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8899
Based on https://github.com/blockscout/blockscout/pull/8882 (current PR should be reviewed after #8882)
Compound proxy pattern is not supported.
Try to fetch implementation from `comptrollerImplementation()`
https://blog.openzeppelin.com/compound-comprehensive-protocol-audit#implementation-used-as-interface
=> Add Compound proxy contract pattern

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8904
The string argument of contract method is incorrectly ABI-encoded before request.
If argument of :string or "string" type convert it to hex first.
=> Fix abi encoded string argument

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/market/market.ex
Fixes #8692 
Currently `EXCHANGE_RATES_COINGECKO_COIN_ID` is ignored at the point of retrieving exchange rate from the ETS in favor of `COIN_NAME`, while it is used to fetch exchange rate from CoinGecko API
Do not take into account `COIN_NAME` while querying ETS as it cannot store more than one entry by design
=> Fix native coin exchange rate with `EXCHANGE_RATES_COINGECKO_COIN_ID`

.dialyzer-ignore, .github/workflows/config.yml, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/smart_contracts_api_v2_router.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/explorer/lib/explorer/account/notifier/forbidden_address.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/exchange_rates/source.ex, apps/explorer/lib/explorer/helper.ex, apps/explorer/lib/explorer/smart_contract/compiler_version.ex, apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex, apps/explorer/lib/explorer/third_party_integrations/sourcify.ex, apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex, config/runtime.exs, cspell.json
Resolves https://github.com/blockscout/blockscout/issues/8907
Adding API V2 endpoint for proxying request of Solidityscan report.
New API v2 endpoint added:
```
api/v2/smart-contracts/#{contract_address_hash}/solidityscan-report
```
Sample success response:
```
{
"scan_report": {
"contract_address": "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
"contract_chain": "eth",
"contract_platform": "blockscout",
"contract_url": "https://eth.blockscout.com/address/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
"contractname": "Unitroller",
"node_reference_id": null,
"scan_status": "scan_done",
"scan_summary": {
"issue_severity_distribution": {
"critical": 0,
"gas": 95,
"high": 1,
"informational": 18,
"low": 31,
"medium": 1
},
"lines_analyzed_count": 2449,
"scan_time_taken": 6,
"score": "4.63", …
```
=> Solidityscan report API endpoint

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_logs/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain/contract_method.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/log_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8892
Methods decoding doesn't work properly, if 3 conditions are satisfied:
- contract emitted event is a proxy contract
- Blockscout didn't recognize it as a proxy
- Implementation is verified
Find method candidates from the DB, if no ABI for such selector in the contract or/and sig-provider microservice is disabled.
=> Enhance method decoding by candidates from DB

CHANGELOG.md, apps/explorer/lib/explorer/account/notifier/notify.ex, apps/explorer/lib/explorer/account/watchlist_notification.ex, apps/explorer/priv/account/migrations/20231207201701_add_watchlist_id_column.exs, apps/explorer/test/explorer/account/notifier/notify_test.exs, config/runtime.exs, cspell.json
- Add `ACCOUNT_WATCHLIST_NOTIFICATIONS_LIMIT_FOR_30_DAYS`
https://github.com/blockscout/docs/pull/206
=> Add ACCOUNT_WATCHLIST_NOTIFICATIONS_LIMIT_FOR_30_DAYS

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/block_reward.ex
Resolves https://github.com/blockscout/blockscout/issues/8954
Daily coin balances updating with placeholders in BlockReward fetcher is not needed since there is call of `CoinBalance.async_fetch_balances/1` after rewards import and daily balances are updated along with coin balances asynchronously.
Remove daily balances updating from BlockReward fetcher.
=> Remove daily balances updating from BlockReward fetcher

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/lib/explorer/chain/token/instance.ex
Closes #8931 
- Decrease amount of NFT in address collection: 15 -> 9
=> Decrease amount of NFT in address collection: 15 -> 9

CHANGELOG.md, apps/explorer/priv/repo/migrations/20231213085254_add_btree_gin_extension.exs, apps/explorer/priv/repo/migrations/20231213090140_add_token_transfers_token_contract_address_token_ids_index.exs, apps/explorer/priv/repo/migrations/20231213101235_drop_token_transfers_token_ids_index.exs
`token_ids` column is used in all queries only in the bundle with token_contract_address_hash. So, instead of gin index on token_ids column, it is a suggestion to create multicolumn index which will include token_contract_address_hash as well.
- add btree_gin extension
- create multicolumn gin index on [token_contract_address_hash, token_ids]
- remove index on token_ids
Queries lke this start to use new multicolumn index:
```
explain analyze select * from token_transfers tt where token_contract_address_hash='\x60eb332bd4a0e2a9eeb3212cfdd6ef03ce4cb3b5' and token_ids @> ARRAY[809316282247589383998263052849978220592970297069::decimal] limit 1;
QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Refine token transfers token ids index

.github/workflows/config.yml, CHANGELOG.md, apps/explorer/priv/repo/migrations/20231215104320_drop_unused_actb_indexes.exs
Unused indexes are detected in `address_current_token_balances` table:
- Remove partial index on `value` column where value is not null in `address_current_token_balances` table.
- Remove multi-column index on `[:address_hash, :block_number, :token_contract_address_hash]` columns in `address_current_token_balances` table.
=> Drop unused indexes on address_current_token_balances table

CHANGELOG.md, apps/explorer/priv/repo/migrations/20231215132609_add_index_blocks_refetch_needed.exs
[Query](https://github.com/blockscout/blockscout/blob/0673e7fd07ae9829bf4d07e0dcf7be85945ba49f/apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex#L53-L59):
```
SELECT b0."hash", count(t1."hash") 
FROM "blocks" AS b0 LEFT OUTER JOIN "transactions" AS t1 ON t1."block_hash" = b0."hash" 
WHERE ((b0."consensus" = true) AND b0."refetch_needed") 
GROUP BY b0."hash" LIMIT 100000;
```
is slow on some instances because of no index which covers `refetch_needed=true` condition.
The suggestion is to add index:
```
CREATE INDEX consensus_block_hashes_refetch_needed ON blocks((1)) WHERE consensus and refetch_needed;
```
Query execution plan without index:
```
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------ …
```
=> Index for block refetch_needed

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/request_coordinator_test.exs
Resolves https://github.com/blockscout/blockscout/issues/8914
Use separate throttleable error count keys based on request method
=> Isolate throttable error count by request method

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
Blockscout now fails to fetch receipts for EIP-4844 transactions that causes poor experience on EIP-4844 chains.
Do we need such restrictions on receipts or maybe we can simply ignore all unknown fields like we do with blocks and transactions?
Add EIP-4844 fields to known fields, but ignore them.
=> Add EIP-4844 compatibility (not full support yet)

.dialyzer-ignore, CHANGELOG.md, apps/block_scout_web/test/block_scout_web/channels/websocket_v2_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20231213152332_alter_log_topic_columns_type.exs, apps/explorer/test/explorer/chain/csv_export/address_log_csv_exporter_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain/smart_contract_test.exs, apps/explorer/test/explorer/chain/token_transfer_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan/logs_test.exs, apps/indexer/lib/indexer/fetcher/polygon_edge/deposit_execute.ex, apps/indexer/lib/indexer/fetcher/polygon_edge/withdrawal.ex, apps/indexer/lib/indexer/helper.ex, apps/indexer/lib/indexer/temporary/uncataloged_token_transfers.ex, apps/indexer/lib/indexer/transform/transaction_actions.ex
To save storage space for `logs` table (which is in top 3 by storage occupied) we can migrate log topics from `character varying(255)` to `bytea`.
Change type `character varying(255)` to `bytea` for the  next columns in `logs` table:
- `first_topic`
- `second_topic`
- `third_topic`
- `fourth_topic`
=> Change log topic type in the DB to bytea

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex
- `decoded_input` was missed in tx summary request for unverified contracts 
- Add address info preload to summary template variable with `type=address`
- Fix tx input decoding in tx summary microservice request
- Light refactoring:
- Add spec for `decoded_input_data`
- Get rid of doubled Enum.reverse in `decode_transactions` (TransactionView API v2)
=> Fix tx input decoding in tx summary microservice request

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
```
Errors:
{:unknown_key, %{key: "gasUsedForL1", value: "0x0"}}
(ethereum_jsonrpc 5.4.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
(elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
(ethereum_jsonrpc 5.4.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
(elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
(elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
(stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
Allow `gasUsedForL1` to be returned in tx receipt for Arbitrum.
=> Arbitrum allow tx receipt gasUsedForL1 field

CHANGELOG.md, apps/explorer/lib/explorer/microservice_interfaces/bens.ex
I fixed bug with empty ens_name in transaction.token_transfer
Updated API of `bens-server` [blockscout-rs/722](https://github.com/blockscout/blockscout-rs/pull/722) to snake_case
Update service at `MICROSERVICE_BENS_URL` to latest version
=> Fix bens integration

apps/explorer/config/config.exs, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/cache/background_migrations.ex, apps/explorer/lib/explorer/migrator/address_current_token_balance_token_type.ex, apps/explorer/lib/explorer/migrator/address_token_balance_token_type.ex, apps/explorer/lib/explorer/migrator/filling_migration.ex, apps/explorer/lib/explorer/migrator/transactions_denormalization.ex, apps/explorer/test/explorer/chain/address/token_balance_test.exs, apps/explorer/test/explorer/migrator/address_current_token_balance_token_type_test.exs, apps/explorer/test/explorer/migrator/address_token_balance_token_type_test.exs, apps/explorer/test/explorer/migrator/transactions_denormalization_migrator_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9023
Moved root logic of denormalization migration to the separate `use`able module, added migrations based on this "interface"
=> Token type filling migrations

CHANGELOG.md, apps/explorer/priv/repo/migrations/20231225113850_transactions_asc_indices.exs, apps/explorer/priv/repo/migrations/20231225115026_logs_asc_index.exs, apps/explorer/priv/repo/migrations/20231225115100_token_transfers_asc_index.exs
Slow execution of queries in ASC direction from the API requests like this:
```
api?module=account&action=tokentx&startblock=0&endblock=670727&offset=7000&page=1&sort=desc&address=0x03709784c96aeaaa9dd38df14a23e996681b2c66
```
Add indices in ascending order similar to existing on the tables `transactions`, `logs`, `token_transfers`.
`internal_transactions` is skipped intentionally, because requests in different diresctions is out of practical usage on this table.
=> Add ASC indices for logs, token transfers, transactions

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source.ex
Such errors are not helpful:
```
{"time":"2024-01-03T09:50:05.404Z","severity":"error","message":"Error while fetching tokens with market data (/coins/list): nil","metadata":{}}
```
Add http code to error tuple
=> Improve exchange rates logging

CHANGELOG.md, apps/explorer/lib/explorer/migrator/filling_migration.ex
First call of migrator's cache would result in `false` even if migration is already finished.
Update cache on migrator init if migration is already finished.
=> Fix migrators cache updating

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/indexer/lib/indexer/fetcher/contract_code.ex
closes: #8800 
I fixed the bug with `status` in `stream_transactions_with_unfetched_created_contract_codes`.
https://etherscan.io/tx/0x5b60f03db1dde242de1f01a6763ee11addc1a8411e4f4feda99ffc6b862c1149
Contracts that failed to be created should be filtered out.
=> Add status in stream_transactions_with_unfetched_created_contract_codes

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/helper.ex, apps/explorer/test/explorer/smart_contract/helper_test.exs, cspell.json
Resolves https://github.com/blockscout/blockscout/issues/9066
Allow payable functions with output to appear in the Read tab of smart-contract.
=> Allow payable function with output appear in the Read tab

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/market/market_history.ex, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
- In `BlockScoutWeb.API.V2.StatsController` try to use data from `Explorer.ExchangeRates` firstly and only then use `Explorer.Market.get_native_coin_exchange_rate_from_db/0`
- Use tvl data from `MarketHistory` when fetching coin exchange rate, so they are available in `Explorer.ExchangeRates`
=> Return current exchange rate in api/v2/stats

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex
```
2024-01-09T09:36:40.309 application=explorer [error] Couldn't update gas used gas_prices** (FunctionClauseError) no function clause matching in Decimal.decimal/1
(decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal([[Decimal.new("1200000"), Decimal.new("8560998"), Decimal.new("8560998"), Decimal.new("1200000"), Decimal.new("1030438"), Decimal.new("16079028"), Decimal.new("1133481"), Decimal.new("6267951"), Decimal.new("1200000"), Decimal.new("1245694"), Decimal.new("63372601"), Decimal.new("6181717"), Decimal.new("1030438"), Decimal.new("11807436"), Decimal.new("16198856"), Decimal.new("63372601"), Decimal.new("8000000"), Decimal.new("1200000"), Decimal.new("6996791"), Decimal.new("35064841"), Decimal.new("1353362"), Decimal.new("14384218"), Decimal.new("6516613"), …
```
=> Fix Explorer.Chain.Cache.GasPriceOracle.merge_fees

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex
`gas_price_updated_in` is a constant, so to get the new gas prices right after the update some calculations should be performed on the client
- Return actual time before the next update in `gas_price_updated_in` field
- Expire only gas prices field in cache in order to not to kill running task and not to loose old gas prices
=> Improve update_in in gas tracker

CHANGELOG.md, apps/explorer/config/test.exs, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/test/explorer/chain/smart_contract_test.exs, config/runtime.exs
Allow us to manage whether should we use average block time for implementation re-fetch or not.
A new runtime env variable is introduced:
`CONTRACT_PROXY_IMPLEMENTATION_TTL_VIA_AVG_BLOCK_TIME` - default is true. If false, implementation re-fetch ttl will be set to 0 meaning it will be refetched every time someone opens the contract page.
=> Allow bypassing avg block time in proxy implementation re-fetch ttl calculation

CHANGELOG.md, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Related to https://github.com/blockscout/blockscout/pull/8575
Currently, in realtime fetcher we fetch coin balances from node for every address we extracted from block data (transactions, token transfers, logs, etc.). But all addresses whose balance could change are already presented in `address_coin_balances` import option. So it's not needed to fetch balances for all of the extracted addresses since their balances couldn't change. This way we can get rid of a large number of unnecessary requests to node.
Removed unnecessary addresses from balance fetching params list.
=> Fetch realtime coin balances only for addresses for which it has changed

CHANGELOG.md, docker-compose/services/db.yml, docker-compose/services/stats.yml
I stumbled upon an issue where the stats data are not stored in the database due to the issue with the shared memory of the PostgreSQL database containers. Database containers report the error similar to the following:
```
FATAL:  could not resize shared memory segment "/PostgreSQL.809456988" to 1048576 bytes: No space left on device
```
This issue was even acknowledged in the official docs of PostgreSQL, [check it out here](https://www.instaclustr.com/blog/postgresql-docker-and-shared-memory/).
The fix for the issue is to specify the size of the shared memory for the database containers, by default the docker assigns 64MB but this is enough in most cases, but it seems …
=> Increase shared memory for PostgreSQL containers

.github/workflows/config.yml, .github/workflows/prerelease.yml, .github/workflows/publish-docker-image-every-push.yml, .github/workflows/publish-docker-image-for-stability.yml, .github/workflows/publish-docker-image-for-suave.yml, .github/workflows/publish-docker-image-staging-on-demand.yml, .github/workflows/release-additional.yml, .github/workflows/release.yml, .tool-versions, docker/Dockerfile, docker/README.md
* Equalize elixir stack version across the local builds, ci and docker images. Use Erlang OTP 25.3.2.8 and Elixir 1.14.5 everywhere.
=> Equalize elixir stack versions

CHANGELOG.md, docker-compose/services/db.yml, docker-compose/services/nginx.yml, docker-compose/services/stats.yml
```
% docker-compose version
Docker Compose version 2.24.1
% docker-compose up -d
service ports services.stats-db.ports.[0] is missing a target port
```
Add compatibility with docker-compose v2.24
=> Compatibility with docker-compose 2.24

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/visualize_sol2uml_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1167.ex, apps/explorer/lib/explorer/chain/smart_contract_additional_sources.ex, apps/explorer/lib/explorer/etherscan/contracts.ex, apps/explorer/test/explorer/chain/smart_contract_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Resolves https://github.com/blockscout/blockscout/issues/9045
Smart-contract page and API don't return additional source codes of verified bytecode twin.
Return all additional sources of bytecode twin implementation in case of smart-contract follows EIP-1167 pattern.
Chore: bind `smart_contract_additional_sources` to `smart_contracts`. Before the changes it was bound to `address`, which is logically incorrect since `smart_contract_additional_sources` may exist only for verified smart contract - all of verified smart_contracts are in `smart_contracts` table.
=> EIP-1167 display multiple sources of implementation

.github/workflows/config.yml, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helper.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/csv_export_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/verification_status.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/lib/explorer/etherscan/contracts.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher_worker.ex, apps/explorer/lib/explorer/tags/address_to_tag.ex, apps/explorer/priv/repo/migrations/20231227170848_add_proxy_verification_status.exs, cspell.json
#8847 
Closes #8868
Closes #7137 
- Account > ERC721 - Token Transfer Events
- Contract > Creator and creation tx hash
- Contract > Verify Source Code
- Contract > Verify Proxy Contract
- Do not return twin contracts in getsourcecode RPC API endpoint
https://github.com/blockscout/docs/pull/220
=> New RPC API endpoints

.github/workflows/config.yml, CHANGELOG.md, docker-compose/services/db.yml, docker-compose/services/stats.yml
Resolves https://github.com/blockscout/blockscout/issues/8044
Migrate to Postgres 15.
Make Postgres 15 default option in the CI and docker-compose.
=> Make Postgres@15 default option

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/views/api/v2/transaction_view_test.exs, apps/explorer/lib/explorer/chain/log.ex
Resolves https://github.com/blockscout/blockscout/issues/9247
Wrong decoding of the logs in some circumstances described in the issue above ☝️ .
Change the key of `events_acc` mapping in the `find_method_candidates` function to store also topics. Otherwise, it applies the response from the 1st found event to other events.
=> Fix log decoding bug

CHANGELOG.md, apps/explorer/priv/repo/migrations/20240114181404_enhanced_unfetched_token_balances_index.exs
Long execution of query for method https://github.com/blockscout/blockscout/blob/502dec051c88e98a3a5beffb5e93be43a2957418/apps/explorer/lib/explorer/chain/address/token_balance.ex#L85
Add parital index with `where` clause exactly as in `unfetched_token_balances/0` function
Execution plan before index installed:
```
eth_goerli_dev=# explain analyze SELECT a0.*
FROM "address_token_balances" AS a0
WHERE (((((a0."address_hash" != '\x0000000000000000000000000000000000000000') AND (a0."token_type" = 'ERC-721')) OR (a0."token_type" = 'ERC-20')) OR (a0."token_type" = 'ERC-1155')) AND ((a0."value_fetched_at" IS NULL) OR (a0."value" IS NULL))) LIMIT 100000;
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Enhanced unfetched token balances index

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/indexer/test/indexer/fetcher/coin_balance_on_demand_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9172
Exclude first block from average block time calculation.
=> Exclude genesis block from average block time calculation

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex, apps/indexer/lib/indexer/pending_transactions_sanitizer.ex
After transactions denormalization, in case when we fill transaction in `PendingTransactionsSanitizer`, we should also fill `block_timestamp` field.
- Fill `block_timestamp` field in `PendingTransactionsSanitizer` as well
- Filter rpc transactions and token transfers by block consensus
=> Fix pending transactions sanitizer

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/first_trace_on_demand.ex
Fetching first trace for pending transaction is meaningless and causes minor bugs.
Check if transaction is pending before fetching its first trace
=> Don't fetch first trace for pending transactions

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex
Related to https://github.com/blockscout/blockscout/pull/9229
After the liquidation of block joins in transaction denormalization PR, there are places left where inner join with blocks was needed not only for select fields from it but for filtering non-pending transactions as well.
Added filters by `block_hash is not null` to places described above
=> Add missing filters by non-pending transactions

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/rpc_translator_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9194
//api/v1 path is prohibited.
Allow multiple slashes in the path before "api" for api v1 requests in order to make requests like this workable:
```
curl -s "http://localhost:4000//api/v1?module=contract&action=listcontracts&offset=1"
```
=> API v1 allow multiple slashes in the path before "api"

CHANGELOG.md, apps/explorer/priv/repo/migrations/20240114181404_enhanced_unfetched_token_balances_index.exs, apps/explorer/priv/repo/migrations/20240123102336_add_tokens_cataloged_index.exs
Change 2 DB indexes creation introduced in 6.1.0 release to `concurrent` creation.
=> Change index creation to concurrent

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
The `l1Timestamp` of `L2OutputOracle`'s `OutputProposed` Event indicates the time when the output was submitted in L1. Comparing this with the timestamp of the L2 block may result in an incorrect comparison.
For example,
when a withdrawal tx occurred 3 minutes ago in block 14 in L2, the most recent output submitted to the L2OutputOracle Contract is 1 minute ago, and the l2 block number in the most recent output is 10, timestamp comparison is meaningless. (This may occur due to gas price, etc.)
before PR, https://github.com/blockscout/blockscout/pull/8702
=> Change to use blocknumber instead of timestamp in withdrawal status

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/test/explorer/chain/block_test.exs, apps/explorer/test/explorer/chain/cache/gas_price_oracle_test.exs, config/runtime.exs
Closes #9201
- Calculate the base fee of the next block by ourselves instead of query the node
- Added `EIP_1559_BASE_FEE_MAX_CHANGE_DENOMINATOR` env variable with default value of 8 to accomplish the task above (https://github.com/blockscout/docs/pull/235)
- Added base and proirity fee 
Response example:
<pre>
{
"average_block_time": 15030.0,
"coin_price": null,
"coin_price_change_percentage": null,
"gas_price_updated_at": "2024-01-19T21:06:35.462186Z",
"gas_prices": {
"average": {
<b>"base_fee": 23.6,</b>
"fiat_price": null,
"price": 23.85,
<b>"priority_fee": 0.26,</b>
"time": 15030.0
},
"fast": {
<b>"base_fee": 23.6,</b>
"fiat_price": null,
"price": 25.18,
<b>"priority_fee": 1.59,</b>
"time": 15030.0
},
"slow": {
<b>"base_fee": 23.6,</b>
"fiat_price": null,
"price": 23.64, …
=> Add base and priority fee to gas oracle response

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/rpc/block_view.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/wei.ex, apps/explorer/test/explorer/chain/block_test.exs
Take into account the case when there are two uncles in a single block
=> Fix manual uncle reward calculation

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
Closes https://github.com/blockscout/blockscout/issues/9341
```
>>>  curl --request POST \
--url https://unreal.blockscout.com/api/v2/smart-contracts/0xc4330B6fb035F75107F29bf741B945167f2f5330/query-read-method \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--data '{"args": ["1000000000000000000000",["0x909Fd75Ce23a7e61787FE2763652935F92116461","0x9801eeb848987c0a8d6443912827bd36c288f8fb"]],"method_id": "d06ca61f","contract_type": "regular","from": "0xa8FCe579a11E551635b9c9CB915BEcd873C51254"}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   703  100   471  100   232   1759    866 --:--:-- --:--:-- --:--:--  2623
{
"is_error": true,
"result": {
"error": "protocol …
```
=> Fix read contract bug

CHANGELOG.md, apps/explorer/lib/explorer/chain_spec/geth/importer.ex
Resolves https://github.com/blockscout/blockscout/issues/9345
Integer balances in genesis.json lead to crashing genesis data import.
When, say, balance is indicated like this:
```
"0x...": {
"balance": 0,
"code": 
...
}
```
Add parsing function clause to parse integer balances.
=> Process integer balance in genesis.json

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/noves_fi_controller.ex, apps/explorer/lib/explorer/third_party_integrations/noves_fi.ex
Resolves https://github.com/blockscout/blockscout/issues/9350
add proxy endpoint for Noves.fi `describeTxs` API endpoint.
Input array of hashes is supported through comma-separated `hashes` list or via `hashes[0]`, ... , `hashes[i]`, ..., `hashes[n]`
Proxy endpoint on Blockscout side:
```
curl -X 'GET' --globoff 'http://localhost:4000/api/v2/proxy/noves-fi/transactions?viewAsAccountAddress=0x2e68e2d2bf87cbc636278bfe30a93a63a4a778b0&hashes[0]=0x0db65a24aaa672821f2737341f93df6a9786f6128c5e57db4bbfd307f64b1848&hashes[1]=0x2fd1facf2d631122befcaa5fe2ef7bfc471cf0fa84d5f17a7111961b9a775b9a'
```
or
```
curl -X 'GET' --globoff 'http://localhost:4000/api/v2/proxy/noves-fi/transactions?viewAsAccountAddress=0x2e68e2d2bf87cbc636278bfe30a93a63a4a778b0&hashes=0x0db65a24aaa672821f2737341f93df6a9786f6128c5 …
```
=> Noves.fi: add proxy endpoint for describeTxs endpoint

CHANGELOG.md, apps/indexer/lib/indexer/transform/address_coin_balances.ex
Related to https://github.com/blockscout/blockscout/pull/8575
We should filter out ERC-1155 token transfers from address coin balances params as well since they also cannot change the balance of native coin.
=> Remove ERC-1155 logs params from coin balances params

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/migrator/sanitize_missing_block_ranges.ex, apps/explorer/lib/explorer/utility/missing_block_range.ex, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
Since missing ranges sanitize should run only once (because it fixes data affected by already fixed bug), it makes sense to move it to a separate process and update its status once it's completed.
=> Move missing ranges sanitize to a separate background migration

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Current internal transactions fetcher does not correctly handle parent trace failures in some cases.
Consider the following call order: `A => B => C => D`, where call `B => C` reverts. Correct implementation should also mark call `C => D` as failed. Current implementation, however, considered only the status of the top-level call `A => B`, which is not correct. 
Current implementation also has a sub-optimal performance, as `remove_failed_creations` was at least `O(n^2)`, considering single internal transaction batch can contain thousands of transactions from multiple blocks, this can easily start to consume multiple seconds of CPU time.
Simple local benchmark of 1000 transactions containing 20 recursive traces each took current implementation 15 seconds to finish, while the new …
=> Improve marking of failed internal transactions

.github/workflows/publish-docker-image-for-shibarium.yml, CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/shibarium_view.ex, apps/indexer/lib/indexer/fetcher/shibarium/helper.ex, apps/indexer/lib/indexer/fetcher/shibarium/l1.ex, apps/indexer/lib/indexer/fetcher/shibarium/l2.ex
Current implementation of API v2 JSON output for Shibarium returns the `user` address field as a raw byte sequence. This PR extends this field to JSON object with extra data about the user address as it's implemented for other API v2 entities.
This change assumes that the `User` link on Deposits and Withdrawals UI pages must refer to L2 address page.
If the JSON object cannot be constructed on backend side, the `user` field will be a byte sequence (as a fallback solution).
=> Output user address as an object in API v2 for Shibarium

.github/workflows/config.yml, CHANGELOG.md
* Fix outdated deps cache in CI
=> Fix outdated deps cache in CI

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex
Resolves https://github.com/blockscout/blockscout/issues/9380
Filter out Vyper contracts in Solidityscan API endpoint.
=> Filter out Vyper contracts in Solidityscan API endpoint

CHANGELOG.md, apps/explorer/config/dev/geth.exs, apps/explorer/config/prod/geth.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod/geth.exs
Now `debug_traceBlockByNumber` uses `ETHEREUM_JSONRPC_HTTP_URL`, however it should use `ETHEREUM_JSONRPC_TRACE_URL`
Added `debug_traceBlockByNumber` to `method_to_url` keyword list, so that `debug_traceBlockByNumber` uses `ETHEREUM_JSONRPC_TRACE_URL`
=> Add `debug_traceBlockByNumber` to `method_to_url`

CHANGELOG.md, apps/explorer/lib/explorer/microservice_interfaces/bens.ex
Change bens integration for search: 
change endpoint from `GET /addresses:lookup` to `GET /addresses/{address}`
blocking on https://github.com/blockscout/blockscout-rs/pull/784
=> Change bens address search  to get_address func

apps/indexer/lib/indexer/fetcher/zksync/discovery/batches_data.ex
I have discovered a logic issue of collecting rollup transactions from the response of `eth_getBlockByNumber` if the transactions list is empty.
The code without fix returns `[]` if the transactions list in the current response of `eth_getBlockByNumber` is empty. But it is not correct since if any transactions have been already collected by handling the previous responses they will be cleared.
=> Proper handling of empty transactions list in etc_getBlockByNumber

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20240224112210_create_index_pending_block_operations_block_number.exs
Whenever there is a long backlog of blocks without fetched internal transactions, it makes sense to fetch them in `block_number desc` order instead of random as-is order, as more recent blocks likely contain more relevant information for the end user.
It may also lead to faster loading overall, as nearby blocks share most of the state Merkle Patricia tree, thus querying them sequentially from the same node may improve node's internal cache hit ratio.
=> Stream blocks without internal transactions in reverse order

CHANGELOG.md, docker-compose/docker-compose.yml, docker-compose/erigon.yml, docker-compose/external-backend.yml, docker-compose/external-db.yml, docker-compose/external-frontend.yml, docker-compose/ganache.yml, docker-compose/geth-clique-consensus.yml, docker-compose/geth.yml, docker-compose/hardhat-network.yml, docker-compose/microservices.yml, docker-compose/services/db.yml, docker-compose/services/stats.yml
Resolves https://github.com/blockscout/blockscout/issues/9496
Resolves https://github.com/blockscout/blockscout/issues/9411
Docker-compose setup doesn't work with Docker compose v2.24.6 because of error:
```
service "db" can't be used with `extends` as it declare `depends_on`
```
Add compatibility with Docker-compose version 2.24.6 by moving `depends_on` from the base to extended service.
=> Docker-compose 2.24.6 compatibility

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/eth_rpc.ex, apps/explorer/lib/explorer/smart_contract/reader.ex
Closes #9419.
Improve compliance with the [Ethereum JSON-RPC Specification](https://ethereum.github.io/execution-apis/api-documentation/).
Fix missing `0x` prefix for `blockNumber`, `logIndex`, and `transactionIndex` in `eth_getLogs` response.
Remove `transactionLogIndex` in `eth_getLogs` response.
=> Fix missing `0x` prefix in `eth_getLogs` response 

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex, apps/explorer/lib/explorer/chain.ex
* Add block transaction filter for queries like: `api/v2/blocks/<block_id>/transactions?type=[blob_transaction]`
* Add blob transaction counter in block view
=> Add blob transaction count and transaction type filter to block view

CHANGELOG.md, apps/indexer/lib/indexer/helper.ex
Shibarium instance started to display an error `key :block_number not found` in its logs. Because of that, `Indexer.Fetcher.Shibarium.L1` stopped working correctly. The error appeared due to the previous incorrect refactoring.
=> Fix Shibarium L1 fetcher

CHANGELOG.md, apps/explorer/lib/explorer/chain/polygon_zkevm/transaction_batch.ex, apps/explorer/priv/polygon_zkevm/migrations/20240306080627_make_timestamp_optional.exs, apps/indexer/lib/indexer/fetcher/polygon_zkevm/transaction_batch.ex
Closes https://github.com/blockscout/blockscout/issues/9564.
`Indexer.Fetcher.PolygonZkevm.TransactionBatch` module stopped working at the end of historical sync of the batches because of undefined timestamp for the latest unfinalized batches. This PR fixes it allowing to store `nil` in the `timestamp` column.
=> Fix timestamp handler for unfinalized zkEVM batches

apps/explorer/lib/explorer/market/history/cataloger.ex
https://github.com/blockscout/blockscout/blob/c914e71c1825594c3ccead57f7c1975f294aff54/apps/explorer/lib/explorer/market/history/cataloger.ex#L111-L122
Fixed the error message copied from line 112
=> Update log info

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
```
<<"expected at most one result but got 3 in query:\n\nfrom i0 in Explorer.Chain.InternalTransaction,\n  join: t1 in assoc(i0, :transaction),\n  where: i0.created_contract_address_hash ==\n  ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<247, 189, 163, 82, 139, 4, 84, 174, 143, 124, 94, 219, 23, 73, 196, 221, 79, 31, 4, 161>>},\n  where: t1.status == ^1,\n  select: %{init: i0.init, created_contract_code: i0.created_contract_code}\n">>},
```
- Add `limit 1` and `order_by: [desc: block_number]`
=> Fix MultipleResultsError in smart_contract_creation_tx_bytecode/1

docker-compose/external-backend.yml
The stats service in external-backend.yml has a dependency on backend, resulting in the error `Service 'stats' depends on service 'backend' which is undefined.`
Removed `depends_on: backend` in external-backend.yml to fix the error.
=> Fix stats service dependency in external-backend.yml

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex
There is no index on `token_transfers` `block_hash` field, so filtering by this field is complicated.
Update `token_transfers` `block_consensus` by `block_number` so the query will be executed via index scan instead of sequential.
=> Update token transfers block_consensus by block_number

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/block_reward.ex, apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex
- `apps/indexer/lib/indexer/fetcher/block_reward.ex` in some cases crashes a logs GenServer, it leads to stop of the entire application
- `Logger.warn` in `apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex` spams logs with irrelevant messages 
- fix the corner case in block_reward fetcher
- `Logger.warn` -> `Logger.debug`
=> Improve logging

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
Related to https://github.com/blockscout/blockscout/pull/9072
Resolves https://github.com/blockscout/blockscout/issues/9584
There is a bug in blocks responses to transactions responses transformation in function `EthereumJSONRPC.Geth.fetch_block_internal_transactions/2`. Its counter is incrementing from zero inside every block response and is used as response id, so when we are merging them together, same ids are overridden. It was the cause of missing internal transactions in the response of this function and therefore in blocks losing consensus because of mismatch between transactions and internal transactions.
Replaced local counter with the global one, add local counter for `transaction_index` field.
=> Fix Geth block internal transactions fetching

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/account_abstraction_controller.ex, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/helper.ex, apps/explorer/lib/explorer/migrator/sanitize_incorrect_nft_token_transfers.ex, apps/explorer/lib/explorer/migrator/token_transfer_token_type.ex, apps/explorer/lib/explorer/utility/microservice.ex, apps/explorer/test/explorer/chain_test.exs
Closes #9310 
- Add `/api/v2/proxy/account-abstraction/operations/{operation_hash_param}/summary` endpoint
- Add `decoded_call_data` field to `/api/v2/proxy/account-abstraction/operations/{operation_hash_param}` response
- Set default value of `query_decompiled_code_flag` to false in `hash_to_address/2` in Explorer.Chain
=> Add user_op interpretation

.github/workflows/config.yml, CHANGELOG.md
Closes #9579.
Add alternative `hex.pm` mirrors to make build more robust to request timeouts.
=> Setup alternative hex.pm mirrors

CHANGELOG.md, apps/explorer/lib/explorer/utility/massive_block.ex, apps/explorer/priv/repo/migrations/20240226074456_create_massive_blocks.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/catchup/massive_blocks_fetcher.ex, apps/indexer/lib/indexer/block/catchup/supervisor.ex, apps/indexer/lib/indexer/block/fetcher.ex
There are cases when reorg (or regular block) contains a lot of data and can't be imported in the regular amount of time. For such cases, we can add a separate fetcher that sets `timeout: :infinity` for such blocks so catchup fetcher won't get stuck.
- Added `MassiveBlocksFetcher` to handle blocks mentioned above
- Added new schema `massive_blocks` to store these blocks
- Store blocks as _massive_ if there was a timeout error in catchup fetcher
=> Massive blocks fetcher

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
In cases when block was unchanged during block import, function `Import.insert_changes_list` won't return this block, but we still would insert new `PendingBlockOperation` for it. And since `async_import_internal_transactions/1` operates with blocks, it means that the task for this block won't appear in `Indexer.Fetcher.InternalTransaction` queue and therefore the corresponding record in `pending_block_operations` will remain there until the next application restart.
Insert in `pending_block_operations` only actually updated blocks.
=> Don't insert pbo for not inserted blocks

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/counters/last_output_root_size_counter.ex, apps/explorer/test/explorer/counters/last_output_root_size_counter_test.exs, apps/explorer/test/support/factory.ex, config/runtime.exs
Part of #8961 
- Added `LastOutputRootSizeCounter` module
- Added `last_output_root_size` field to `api/v2/stats/` response under `optimism` chain type **(This field may be null if there is no output roots in the database)**
Example: 
```json
{
"average_block_time": 2000,
"coin_image": null,
"coin_price": null,
"coin_price_change_percentage": null,
"gas_price_updated_at": null,
"gas_prices": {
"average": null,
"fast": null,
"slow": null
},
"gas_prices_update_in": 32000,
"gas_used_today": "0",
"last_output_root_size": "16915",
"market_cap": "0",
"network_utilization_percentage": 18.463257133333332,
"static_gas_price": null,
"total_addresses": "12333",
"total_blocks": "401",
"total_gas_used": "0",
"total_transactions": "5071",
"transactions_today": "0",
"tvl": null
}
```
=> Add last output root size counter

CHANGELOG.md, apps/explorer/lib/explorer/microservice_interfaces/bens.ex
Closes #9625 
- Fix no function clause matching in BENS.item_to_address_hash_strings/1
=> Fix no function clause matching in BENS.item_to_address_hash_strings/1

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/ethereum_view.ex
Re-add `blob_tx_count` from https://github.com/blockscout/blockscout/pull/9490 missed during https://github.com/blockscout/blockscout/pull/9631 refactoring
=> Re-add missing blob transactions count

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex
Resolves https://github.com/blockscout/blockscout/issues/9567
Since we calculate delta in the response it would make sense to return only last values of balances with non-null values.
Return latest balances with non-null "value" in `fetch_coin_balance/2`
=> Fix fetch_coin_balance query to compare between balances with values

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
`MissingRangesCollector` won't start another chain crawling until `missing_block_ranges` is empty so if there are missing blocks above the point where collector started, they will be refetched only after all other missing blocks are processed. We should give higher priority to latest blocks.
Reset `MissingRangesCollector` `min_fetched_block_number` to `max_fetched_block_number` after the cycle is done
=> Reset missing ranges collector to max number after the cycle is done

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/beacon/blob.ex
Unfortunately, some beacon clients (e.g. lighthouse that we are using ourselves) return the same error for missed, orphaned and not yet available future beacon slots. Retries for such errors should be handled differently for old orphaned and recent unavailable slots.
For more robust retries in the future, separate retry fetcher can be implemented if necessary. Alternatively, retries can be based on enabling `poll: true` in the current fetcher, although not implemented for now to avoid unnecessary load on the database.
* Fix infinite retries in blob fetcher for past orphaned slots.
=> Fix infinite retries for orphaned blobs

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/indexer/lib/indexer/fetcher/token_balance_on_demand.ex
Close #9459 
- Now `TokenBalanceOnDemand` broadcasts only changed balances
=> Fix zero balances coming via WS

CHANGELOG.md, apps/explorer/lib/explorer/chain/optimism/txn_batch.ex, apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
The new implementation of `Indexer.Fetcher.Optimism.TxnBatch` module introduced in https://github.com/blockscout/blockscout/pull/9571  has incorrect blob decoding function for full blobs and doesn't take into account several blobs in one batch transaction.
=> Hotfix for Optimism Ecotone batch blobs indexing

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
`Indexer.Fetcher.Optimism.TxnBatch` module duplicates L1 tx hashes due to different frames containing in one transaction (when using EIP-4844 blobs). This PR fixes it.
=> Remove duplicated tx hashes while indexing OP batches

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/import_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/fetcher/token.ex, apps/indexer/lib/indexer/fetcher/token_total_supply_on_demand.ex, apps/indexer/lib/indexer/fetcher/token_updater.ex
Closes #9655 
- Metadata for tokens imported via admin-rs overwrited
- Removed unnecessary preloads on tokens update
- Spread `total_supply_updated_at_block` field filling
- Add check on `is_verified_via_admin_panel` field in `Explorer.Chain.update_token/3`
- Add `Map.put_new(:cataloged, nil)` to make on_conflict work as expected
=> Tokens import improvements

apps/explorer/test/support/fixture/smart_contract/large_smart_contract.sol
fix a typo: `subbmitter`->`submitter `
=> chore: fix typo

apps/explorer/lib/explorer/chain/token/instance.ex, apps/explorer/test/explorer/chain/import_test.exs, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/transform/address_token_balances.ex, apps/indexer/test/indexer/transform/address_token_balances_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9699
A wrong amount for ERC-404 token in `https://base.blockscout.com/api/v2/addresses/#{hash}/nft/collections` API endpoint.
Despite we [started to keep different token types in token transfers](https://github.com/blockscout/blockscout/pull/6893) of the same token based on the event signature (to what standard this event actually belongs) we shouldn't extrapolate this logic to token balances. However, token balances are derived from the token transfers params set. Thus, we override a token type in the balances as well. This leads to troubles in UI like incorrect filtering and wrong amount display.
This PR adds the actual token type to token transfers params set which is used by `AddressTokenBalances` transformer.
=> fix: erc-404 type stored in token balances tables

apps/block_scout_web/lib/block_scout_web/templates/transaction/_total_transfers.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/helper.ex
Resolves https://github.com/blockscout/blockscout/issues/9697
Transferred token value is null in the response of `/api/v2/tokens/#{hash}/transfers` API endpoint for ERC-404 token type even when it is not null in the DB.
=> fix: erc-404 token transfers null value

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
If there was an error in inner transaction tracing result, function `check_errors_exist/2` will miss it so the further step will fail since it expects successful results in transaction traces.
Update `check_errors_exist/2` so it checks inner transaction trace result as well.
=> fix: Fix Geth block tracing errors handling

apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex, apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9658
Currently, we get token image from CoinGecko API from `thumb` atribute -> and `small` as a fallback.
Change priority to s`mall` -> `thumb` as a fallback.
=> fix: Change CoinGecko token image attribute priority

apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex, apps/indexer/lib/indexer/transform/optimism/withdrawals.ex, cspell.json
Some OP chains write batches to Celestia blobs instead of EIP-4844 ones. As we currently don't have a service which would give the data from Celestia blob, the `Indexer.Fetcher.Optimism.TxnBatch` will ignore transactions with "derivation version" greater than 0.
Also, this PR removes a small but important typo in `Indexer.Transform.Optimism.Withdrawals`.
=> chore: Temporarily ignore OP batches written to Celestia

apps/explorer/priv/beacon/migrations/20240318154323_create_blob_transactions_index.exs
* Add index on recent blob transactions to avoid query performance issues. 
Affected API:
`/api/v2/transactions?type=[blob_transaction]`
Affected query SQL (simplified):
```sql
EXPLAIN
SELECT *
FROM transactions
JOIN blocks ON transactions.block_hash = blocks.hash
WHERE block_number IS NOT NULL
AND index IS NOT NULL
AND type = 3
ORDER BY block_number DESC, index DESC
LIMIT 50;
```
=> perf: Add EIP4844 blob transactions index

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
Solves an issue for `/api/v2/transactions/zkevm-batch/:batch_number` API endpoint.
=> fix: Separate ZkSync and ZkEvm readers in API controller

apps/indexer/lib/indexer/fetcher/token_instance/helper.ex, apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex, apps/indexer/test/indexer/fetcher/token_instance/helper_test.exs, cspell.json
Closes #9696 
- Fix UTF-8 json handling in NFT metadata fetching
- Add clause for ERC-404 in `Indexer.Fetcher.TokenInstance.Helper.prepare_request/4`
=> fix: Fix UTF-8 json handling in NFT metadata fetching

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/account_abstraction_controller.ex, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/explorer/lib/explorer/microservice_interfaces/account_abstraction.ex
Closes #9676 
- Add trying to decode internal calldata for user ops
=> feat: Add trying to decode internal calldata for user ops

apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs, apps/explorer/test/explorer/smart_contract/compiler_version_test.exs, apps/explorer/test/explorer/smart_contract/solidity/publisher_test.exs, apps/explorer/test/explorer/smart_contract/solidity/verifier_test.exs, config/runtime.exs
Resolves https://github.com/blockscout/blockscout/issues/9745
We provide a fallback to our sc-verifier microservice endpoint. However, integration with it is disabled by default.
Enable Rust sc-verifier microservice by default
=> chore: Enable Rust sc-verifier microservice by default

apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/authenticate_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/email_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/tags_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/account/api/v2/user_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/fallback_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/views/account/api/v2/account_view.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v2/tags_view.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v2/user_view.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
We kept both `/api/account/v1` and `/api/account/v2` for a while. Currently, frontend should use `.../v2` path. Thus, we can remove `.../v1`.
=> chore: Remove /api/account/v1 path

apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/cache/addresses_tabs_counters.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/counters/address_gas_usage_counter.ex, apps/explorer/lib/explorer/counters/address_token_transfers_counter.ex, apps/explorer/lib/explorer/counters/address_tokens_usd_sum.ex, apps/explorer/lib/explorer/counters/address_transactions_counter.ex, apps/explorer/lib/explorer/counters/block_burnt_fee_counter.ex, apps/explorer/lib/explorer/counters/block_priority_fee_counter.ex, apps/explorer/lib/explorer/counters/helper.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfers_counter.ex, apps/explorer/test/explorer/chain/address/current_token_balance_test.exs, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9352
Resolves https://github.com/blockscout/blockscout/issues/8902
`holder_count` in `tokens` table is not updated at ETS cache update.
Update `holder_count` in `tokens` table at the time of updating the same value in the ETS cache.
=> fix: Update token's holder_count in the db from ETS module

apps/indexer/lib/indexer/fetcher/optimism/withdrawal.ex, apps/indexer/lib/indexer/fetcher/polygon_edge.ex
The `Indexer.Fetcher.Optimism.Withdrawal` won't start because of invalid block range when using `safe` block as the end block of the range (this case is reproduced mainly on OP Mainnet). This PR adds a small but important fix so that the module wouldn't scan blocks excessively when the last known block from DB is behind the safe one.
=> fix: Add block range check into OP Withdrawals fetcher

config/runtime.exs
Reduce default API v1 limit by key 50 rps -> 10 rps
=> chore: Reduce default API v1 limit by key 50 -> 10

apps/block_scout_web/config/config.exs, apps/block_scout_web/test/block_scout_web/graphql/schema/query/address_test.exs, apps/block_scout_web/test/block_scout_web/graphql/schema/query/addresses_test.exs, apps/block_scout_web/test/block_scout_web/graphql/schema/query/introspection_test.exs, config/runtime.exs
Closes #9135.
A regression test for Bug Fix.
Slightly increase `max_complexity` limit for executing GraphQL queries. Fix tests that were dependent on the previously set limit.
=> fix: fetching GraphQL schema by GraphiQL IDE

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
Closes #9730 
- Replace tx gas_price with effectiveGasPrice from receipt
=> fix: Replace tx gas_price with effectiveGasPrice from receipt

apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/config_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/config_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/config_controller_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9728
/config/json-rpc-url API endpoint is unused by frontend.
Remove /config/json-rpc-url API endpoint.
=> chore: Remove /config/json-rpc-url API endpoint

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/support/factory.ex
In cases when `log_index` is not unique within block, function `Explorer.Chain.Import.Runner.Blocks.update_token_instances_owner/3` may encounter an error due to excess token transfers in query result.
Modified `update_token_instances_owner` queries for `polygon_zkevm` chain type so they use `transaction_hash` as an additional token transfer identifier.
=> fix: Add non-unique log_index support in update_token_instances_owner

apps/indexer/lib/indexer/block/catchup/missing_ranges_collector.ex
After the first chain inspection, `MissingRangesCollector` launches another inspection from the latest block. But all the checks after the first are not that important as first since they are done just as _sanitization_. However, all queries that `MissingRangesCollector` produce are complex and may use a lot of DB resources. It's useful to decrease count of such queries.
Increase `MissingRangesCollector` check interval after the first chain inspection is done.
=> chore: Increase MissingRangesCollector past check interval

apps/indexer/lib/indexer/supervisor.ex
A huge amount of `SELECT b0."number", b0."hash" FROM "blocks" AS b0 WHERE ((b0."consensus" = ?) AND b0."number" = ANY($1))` requests
- Disable BlockReward fetcher for unsupported variants: 
EthereumJSONRPC.Filecoin,
EthereumJSONRPC.Ganache,
EthereumJSONRPC.Geth,
EthereumJSONRPC.RSK
=> fix: Disable BlockReward fetcher for unsupported variants

apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/prometheus/instrumenter.ex, apps/block_scout_web/lib/block_scout_web/prometheus/phoenix_instrumenter.ex, apps/block_scout_web/lib/block_scout_web/utility/event_handlers_metrics.ex
Resolves https://github.com/blockscout/blockscout/issues/8912
- Renamed `BlockScoutWeb.Prometheus.Instrumenter` to `BlockScoutWeb.Prometheus.PhoenixInstrumenter`
- Added `BlockScoutWeb.Prometheus.Instrumenter` for purposes other than phoenix stats
- Added event handlers queue length metrics
=> chore: Add metrics for realtime event handlers queue length

apps/indexer/lib/indexer/fetcher/coin_balance/catchup.ex, apps/indexer/lib/indexer/fetcher/coin_balance/helper.ex, apps/indexer/lib/indexer/fetcher/coin_balance/realtime.ex
Related to https://github.com/blockscout/blockscout/pull/9182
Realtime coin balance fetcher doesn't broadcast them after import.
Added `fetcher_type` param to `Indexer.Fetcher.CoinBalance.Helper.run` which is used as `:broadcast` option for import.
=> fix: Broadcast realtime coin balances

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
Closes #9578.
Move `has_methods_*` and `has_custom_methods_*` fields from `/api/v2/addresses/{address_hash}` to `/api/v2/smart-contracts/{address_hash}` endpoint response.
Fix tests to expect calls to rpc node.
=> chore: move `has_methods_*` fields to `/smart-contracts` endpoint response

apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/smart_contract/reader.ex
Resolves https://github.com/blockscout/blockscout/issues/9853
Sized arrays are not properly processed before sending to the view.
Check the type of array item using `FunctionSelector.decode_type/1` instead of checking string ends with "[]".
=> fix: Correct processing of sized array to view in API v2

apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/wei.ex
Closes #9137
Resolves https://github.com/blockscout/blockscout/issues/9878
A regression test for Bug Fix.
Add a case for handling `nil` values in `Wei.hex_format`.
=> fix: handle transactions with `gas_price` set to `nil` in `transaction_revert_reason/2`

apps/indexer/lib/indexer/block/catchup/sequence.ex, apps/indexer/lib/indexer/bound_queue.ex, apps/indexer/lib/indexer/buffered_task.ex, apps/indexer/lib/indexer/memory/monitor.ex, apps/indexer/lib/indexer/memory/shrinkable.ex
In cases, when application exceeds memory limit, `Indexer.Memory.Monitor` is trying to shrink the queues. But after that, queues will be shrunk until the next application restart. If there is enough free memory, we should expand the queues back to speed up indexing. 
Added expand logic to `Indexer.Memory.Monitor`.
=> chore: Add queue expanding logic to memory monitor

apps/indexer/lib/indexer/fetcher/coin_balance/helper.ex
Related to https://github.com/blockscout/blockscout/pull/9596
There is one more case when Logger crashes the entire application.
=> fix: Coin balances fetcher error logging

apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/indexer/lib/indexer/fetcher/token_instance/metadata_retriever.ex, apps/indexer/test/indexer/fetcher/token_instance/metadata_retriever_test.exs, config/config_helper.exs, config/runtime.exs, cspell.json
Resolves https://github.com/blockscout/blockscout/issues/9897
Allow to provide authentication parameters for IPFS gateway URL endpoint.
New runtime env variables are added for management of authentication to IPFS gateway URL:
- `IPFS_GATEWAY_URL_PARAM_LOCATION` - whether to add auth params: to query string or to the headers. Available values: `"query"/"header"`.
- `IPFS_GATEWAY_URL_PARAM_KEY` - the key of the parameter.
- `IPFS_GATEWAY_URL_PARAM_VALUE` - the value of the parameter.
If the value of `IPFS_GATEWAY_URL_PARAM_LOCATION` is invalid, the application will stop and throw an explicit error.
=> IPFS gateway URL extra params

apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9805
Add COIN_BALANCE_HISTORY_DAYS value to the response of address's coin-balance-history-by-day API v2 endpoint
=> feat: Return number of days in address's coin-balance-history-by-day API v2 endpoint

apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/optimism_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex, apps/explorer/lib/explorer/application/constants.ex, apps/explorer/lib/explorer/chain/import/runner/optimism/dispute_games.ex, apps/explorer/lib/explorer/chain/import/runner/optimism/withdrawal_events.ex, apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex, apps/explorer/lib/explorer/chain/optimism/dispute_game.ex, apps/explorer/lib/explorer/chain/optimism/withdrawal.ex, apps/explorer/lib/explorer/chain/optimism/withdrawal_event.ex, apps/explorer/priv/optimism/migrations/20240328125102_fault_proofs_support.exs, apps/indexer/lib/indexer/fetcher/optimism.ex, apps/indexer/lib/indexer/fetcher/optimism/dispute_game.ex, apps/indexer/lib/indexer/fetcher/optimism/output_root.ex, apps/indexer/lib/indexer/fetcher/optimism/withdrawal_event.ex, apps/indexer/lib/indexer/supervisor.ex, config/runtime.exs
Closes https://github.com/blockscout/blockscout/issues/9893.
This PR adds support of Optimism Fault Proofs to correctly determine statuses of withdrawals indexed by `Indexer.Fetcher.Optimism.Withdrawal` module.
Also, the new `Indexer.Fetcher.Optimism.DisputeGame` module is introduced that indexes dispute games used by the Withdrawal module to get withdrawal status.
The changes are backward compatible with pre-Fault Proofs implementation and activated seamlessly after `OptimismPortal` contract upgrades.
Now, the withdrawal status can be one of:
- `Waiting for state root` (when waiting for appropriate dispute games to appear in `DisputeGameFactory` contract)
- `Ready to prove` (when appropriate dispute games found in `DisputeGameFactory` contract)
- `Waiting a game to resolve` (when …
=> feat: Support Optimism Fault Proofs

apps/explorer/lib/explorer/graphql.ex, apps/explorer/priv/repo/migrations/20240403151125_enhance_index_for_token_transfers_list.exs, apps/explorer/priv/repo/migrations/20240403151126_drop_index_for_token_transfers_list.exs, apps/explorer/priv/repo/migrations/20240403151126_drop_outdated_index_for_token_transfers_list.exs
Resolves https://github.com/blockscout/blockscout/issues/9808
503 response of the api/v2/tokens/#{hash}/transfers API v2 endpoint for seom tokens.
The simplified query looks like this:
```
SELECT t0.*
FROM token_transfers AS t0
WHERE (t0.block_consensus = TRUE)
AND ((t0.token_contract_address_hash = '\x...')
AND NOT (t0.block_number IS NULL))
ORDER BY t0.block_number DESC, t0.log_index DESC LIMIT 50;
```
And execution plan before the changes:
```
eth_sepolia=> explain SELECT t0.* FROM token_transfers AS t0 WHERE (t0.block_consensus = TRUE) AND ((t0.token_contract_address_hash = '\xdcF5D3E08c5007deCECDb34808C49331bD82a247') AND NOT (t0.block_number IS NULL)) ORDER BY t0.block_number DESC, t0.log_index DESC LIMIT 50;
QUERY PLAN
---------------------------------------------------------------- …
```
=> perf: Improve performance of token page transfers tab

docker-compose/microservices.yml
The stats service in microservices.yml has a dependency on backend, resulting in the error `service "stats" depends on undefined service backend`
Removed `depends_on: backend` in microservices.yml to fix the error.
=> fix: Remove backend dependency in microservices.yml

apps/explorer/priv/repo/migrations/20240404102510_enhance_index_for_token_holders_list.exs, apps/explorer/priv/repo/migrations/20240404102511_drop_outdated_index_for_token_holders_list.exs
Resolves https://github.com/blockscout/blockscout/issues/9815
Slow execution of the query under the hood of `/api/v1?module=token&action=getTokenHolders&contractaddress=#{hash}&page=0&offset=0` endpoint.
Query in question:
```
SELECT a0.*
FROM address_current_token_balances AS a0
WHERE (a0.token_contract_address_hash = '\x...')
AND (a0.address_hash != '\x0000000000000000000000000000000000000000')
AND (a0.value > 0)
ORDER BY a0.value DESC, a0.address_hash DESC
LIMIT 10
OFFSET 0
```
Current execution plan:
```
eth_sepolia=> explain SELECT a0.* FROM address_current_token_balances AS a0 WHERE (a0.token_contract_address_hash = '\x54FA517F05e11Ffa87f4b22AE87d91Cec0C2D7E1') AND (a0.address_hash != '\x0000000000000000000000000000000000000000') AND (a0.value > 0) ORDER BY a0.value DESC, …
```
=> perf: Enhance index for token holders list

apps/explorer/priv/repo/migrations/20240418135458_fix_index_for_unfetched_token_balances.exs, apps/explorer/priv/repo/migrations/20240418140425_drop_outdated_index_for_unfetched_token_balances.exs
Resolves https://github.com/blockscout/blockscout/issues/9911
After adding support of ERC-404 tokens underlined in `unfetched_token_balances/0` query was changed: new condition added: ` or tb.token_type == "ERC-404"`. We should reflect this in the corresponding index.
- Drop `unfetched_address_token_balances_index` index
- Create `unfetched_address_token_balances_index_v2` with all needed conditions.
=> perf: Adjust unfetched_address_token_balances_index to fit all bound query conditions

apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer/lib/explorer/account/tag_address.ex, apps/explorer/lib/explorer/account/tag_transaction.ex, apps/explorer/lib/explorer/account/watchlist_address.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/csv_export/address_token_transfer_csv_exporter.ex, apps/explorer/lib/explorer/chain/optimism/deposit.ex, apps/explorer/lib/explorer/chain/optimism/output_root.ex, apps/explorer/lib/explorer/chain/optimism/txn_batch.ex, apps/explorer/lib/explorer/chain/optimism/withdrawal.ex, apps/explorer/lib/explorer/chain/polygon_edge/reader.ex, apps/explorer/lib/explorer/chain/polygon_zkevm/reader.ex, apps/explorer/lib/explorer/chain/shibarium/reader.ex, apps/explorer/lib/explorer/chain/token/instance.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/chain/withdrawal.ex, apps/explorer/lib/explorer/chain/zksync/reader.ex, apps/explorer/test/explorer/chain/transaction_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9819
Skipping of edge cases in pagination leads to heavy meaningless queries being sent to the DB.
If 0 is sent for some of pagination key, we should avoid constructing query where `key < 0` since the DB doesn't store negative values for indexes, values or block numbers.
For instance, execution plan of some of the queries with not sanitized query:
```
eth_sepolia=> explain analyze SELECT t0.*, (SELECT transaction_hash FROM token_transfers WHERE transaction_hash = t0.hash LIMIT 1) IS NOT NULL FROM transactions AS t0 WHERE ((t0.block_number < 5613705) OR ((t0.block_number = 5613705) AND (t0.index < 0))) AND (NOT (t0.block_number IS NULL) AND NOT (t0.index IS NULL)) ORDER BY t0.block_number DESC, t0.index DESC LIMIT 51;
QUERY PLAN …
```
=> perf: Paging function edge cases fix

apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/lib/explorer/chain/address/metadata_preloader.ex, apps/explorer/lib/explorer/microservice_interfaces/bens.ex
Closes #9926 
- Add new clause to handle preload metadata to NotLoaded address after end domain preload
=> fix: Fix metadata preload

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Related to https://github.com/blockscout/blockscout/pull/9674
There is missing `refetch_needed: false` setting in block import process which causes blocks to infinitely refetch.
Add `refetch_needed: false` for all blocks imported by block fetchers
=> fix: Set refetch_needed: false on block import

apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex, apps/block_scout_web/test/block_scout_web/chain_test.exs, apps/explorer/lib/explorer/chain/search.ex
Closes #9504
Closes #9114
- add new type to search results: `ens_domain`
- add ens domain resolution on check-redirect
- remove outdated token resolution from check-redirect
=> feat: Add ENS category to search result; Add ENS to check-redirect

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket/web_socket_client_test.exs
Partially resolves https://github.com/blockscout/blockscout/issues/9867
There is a bug in dependency `websocket_client` which causes process crash in case when the handler (`EthereumJSONRPC.WebSocket.WebSocketClient`) returns `{:reconnect, state}` in the function `&ondisconnect/2`. But this bug doesn't appear if this function returns `{:reconnect, interval, state}`.
Updated `&ondisconnect/2` function to return `{:reconnect, interval, state}` instead of `{:reconnect, state}` so the process won't crash.
=> fix: Fix WebSocketClient reconnect

apps/indexer/lib/indexer/memory/monitor.ex, apps/indexer/lib/indexer/prometheus/instrumenter.ex
Resolves https://github.com/blockscout/blockscout/issues/9983
Added `memory_consumed` metric with label by fetcher or `total` that is set on every memory monitor check.
=> chore: Enhance indexer memory metrics

apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/utility/missing_balance_of_token.ex, apps/explorer/priv/repo/migrations/20240502064431_create_missing_balance_of_tokens.exs, apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/fetcher/token_balance.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/fetcher/token_balance_test.exs, cspell.json
There are tokens that doesn't support `balanceOf` function but we still keep and try to fetch balances for them which means that there would be endless errors on their fetching.
- Added table `missing_balance_of_token` that keeps information about such tokens and the max block number where `balanceOf` wasn't presented
- Filter token balances by this table before fetching
- Insert tokens for which `balanceOf` function returned `execution reverted`
- Filter token balances placeholders before insert
=> feat: Omit balanceOf requests for tokens that doesn't support it

apps/indexer/lib/indexer/fetcher/polygon_zkevm/transaction_batch.ex
The `Indexer.Fetcher.PolygonZkevm.TransactionBatch` module doesn't have 2-second initialization pause (like other indexing modules) to reduce restart intensity when DB issues. Due to that, the module stops restarting after 3 attempts until the whole Blockscout instance is reloaded (because Supervisor has a limitation of 3 restarts max within 5 seconds).
=> fix: Handle DB unavailability by PolygonZkevm.TransactionBatch fetcher

apps/block_scout_web/test/block_scout_web/views/api/v2/address_view_test.exs, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex, apps/explorer/priv/repo/migrations/20240419101821_migrate_proxy_implementations.exs, apps/explorer/priv/repo/migrations/20240425091614_add_proxy_type_column.exs, apps/explorer/test/explorer/chain/smart_contract/proxy/models/implementation_test.exs, apps/explorer/test/explorer/chain/smart_contract/proxy_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9952
Save smart-contract proxy type in the DB
`proxy_type` column is added to `proxy_implementations` table with this supported number of proxy types:
https://github.com/blockscout/blockscout/blob/1dff35f02594bbf7f6f9b29210b0f8b643c4e59a/apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex#L33-L44
=> feat: save smart-contract proxy type in the DB

apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/lib/explorer/microservice_interfaces/metadata.ex
Metadata microservice migrated to GET methods in endpoints
- Support GET endpoints
- Add chain id parameter to metadata request
=> chore: Migrate to GET variant of {{metadata_url}}/api/v1/metadata

apps/indexer/lib/indexer/fetcher/internal_transaction.ex
In some cases internal transactions fetching error doesn't contain info about for which transaction or block this error arose.
Show blocks range in internal transactions fetching error.
=> chore: Show blocks range in internal transactions fetching error

apps/indexer/lib/indexer/fetcher/optimism/withdrawal_event.ex
Blast optimistic rollup has a bit different implementation of `OptimismPortal` contract, namely extended `WithdrawalProven` and `WithdrawalFinalized` events. This PR adds these modified events to `Optimism.WithdrawalEvent` fetcher so it can index them.
=> chore: Add support of Blast-specific L1 OP withdrawal events

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token/instance.ex, apps/explorer/priv/repo/migrations/20240503091708_add_nft_instance_fetcher_aux_fields.exs, apps/indexer/lib/indexer/buffered_task.ex, apps/indexer/lib/indexer/fetcher/token_instance/helper.ex, apps/indexer/lib/indexer/fetcher/token_instance/retry.ex, apps/indexer/test/indexer/fetcher/token_instance/helper_test.exs, config/runtime.exs, cspell.json
Closes #9575 
- Add new fields to `token_instances` table:
- `retries_count`
-  `refetch_after`
- Add exponentional timeout for retry of token instances:
formula (in seconds): `min(coef * base ^ retries_count, max_refetch_interval)`
Could be tuned by new ENVS:
`INDEXER_TOKEN_INSTANCE_RETRY_MAX_REFETCH_INTERVAL`, default: `168h`
`INDEXER_TOKEN_INSTANCE_RETRY_EXPONENTIAL_TIMEOUT_BASE`, default: `2`
`INDEXER_TOKEN_INSTANCE_RETRY_EXPONENTIAL_TIMEOUT_COEF`, default: `100`
Values from retry count:
0: 1 min 40 s
1: 3 min 20 s
2: 6 min 40 s
3: 13 min 20 s
4: 26 min 40 s
5: 53 min 20 s
6: 1 h 46 min 40s
7: 3 h 33 min 20s
8: 7 h 6 min 40s
9: 14 h 13 min 20s
10: 1 d 4 h 26 min 40s
11: 2 d 8 h 53 min 20s
12: 4 d 17 h 46 min 40s
13: 9 d 11 h 33 min 20s (limited with default …
=> feat: Improve retry NFT fetcher

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/explorer/lib/explorer/chain/smart_contract/verification_status.ex
Closes #9985 
- Add fallback fetching UID status from Que
=> fix: Fix Unknown UID bug at smart-contract verification

apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
Resolves https://github.com/blockscout/blockscout/issues/10015
Remove last input parameter in `get_additional_sources` function.
=> refactor: get_additional_sources/4 -> get_additional_sources/3

apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex, apps/explorer/test/explorer/smart_contract/solidity/publisher_test.exs, apps/explorer/test/explorer/smart_contract/vyper/publisher_test.exs, apps/explorer/test/support/factory.ex
When trying to re-verify Vyper contracts an error with unique constraint violation occurs. Blockscout prints the error, but the verification hangs out indefinitely. 
For Solidity contracts re-verification works.
Added test cases for publishing the Solidity and Vyper contracts when there is already a verified one.
Defined a `create_or_update_smart_contract` function similar to the one defined for Solidity.Publisher module. Internally, it works the same way: checks if the contract is already verified and based on that calls either the update or create smart-contract method
=> fix: vyper contracts re-verificaiton

apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/clone_with_immutable_arguments.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex, apps/explorer/lib/explorer/etherscan/contracts.ex, apps/explorer/priv/repo/migrations/20240501131140_new_proxy_type_clones_with_immutable_arguments.exs
Superseed of https://github.com/blockscout/blockscout/pull/9993
Resolves https://github.com/blockscout/blockscout/issues/9739
Adding new proxy pattern "Clone with immutable arguments".
A new proxy type is added :clone_with_immutable_arguments
=> feat: Clone with immutable arguments proxy pattern

apps/block_scout_web/lib/block_scout_web/admin_router.ex, apps/block_scout_web/lib/block_scout_web/api_key_v2_router.ex, apps/block_scout_web/lib/block_scout_web/api_router.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/graphql/body_reader.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/smart_contracts_api_v2_router.ex, apps/block_scout_web/lib/block_scout_web/utils_api_v2_router.ex, apps/block_scout_web/lib/block_scout_web/web_router.ex, config/runtime.exs
Currently, it is allowed to send unlimited batched requests with `/api/v1/graphql` endpoint, which may cause a huge body size to send in a graphql request.
Allow only batch size = 1 of batched request at `/api/v1/graphql`.
=> fix: Disallow batched queries in GraphQL endpoint

apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/verification_controller_test.exs, apps/block_scout_web/test/support/fixture/smart_contract/smart_contract_verifier_vyper_multi_part_blueprint_response.json, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/rust_verifier_interface_behaviour.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex, apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex, apps/explorer/priv/repo/migrations/20240509014500_smart_contracts_add_is_blueprint_flag.exs, cspell.json
Resolves https://github.com/blockscout/blockscout/issues/10038
Adding indication if the verified contract is blueprint ([EIP-5202](https://eips.ethereum.org/EIPS/eip-5202) compatible) contract
- Add `is_blueprint` field to smart_contracts table
- Add `is_blueprint` to `/api/v2/smart-contracts/0x.../` endpoint response
=> feat: Blueprint contracts support

apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain/address/counters.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/etherscan/logs.ex, apps/explorer/lib/explorer/graphql.ex
Adding `from_address_hash == #{address_hash}` on `transactions` table is redundant in case of smart-contracts. In some cases it can lead to long query execution.
Before sending query to the DB we should properly propose where clauses: we should eliminate `from_address_hash == #{address_hash}` where clause for smart-contracts and leave it as is for EOAs. Since smart-contracts cannot be originators of transactions, there are no records satisfying this where clause in case of smart-contract address. Leaving this clause for smart-contracts leads to sequential scan of the whole token transfers table, which leads to long execution time of the original query.
=> fix: Eliminate from_address_hash == #{address_hash} clause for transactions query in case of smart-contracts

apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/nethermind/trace.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/trace_replay_block_transactions.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain_test.exs
Multiple problems in the current logic handling `revert_reason` have been discovered:
1. `transactions.revert_reason` column type is `text`, although it should be `bytea`, this bloats the storage unnecessary, as hex values are stored as text.
2. `transactions.revert_reason` contain irrelevant error messages, that should not be stored in the database. Here are the results of the `SELECT revert_reason, count(*) FROM transactions WHERE status = 0 AND revert_reason  IS NOT NULL GROUP BY revert_reason` query on Goerli: [revert_reasons_stat.csv](https://github.com/blockscout/blockscout/files/14009156/revert_reasons_stat.csv). Values like these are clearly not valid revert reasons and were saved by mistake:
* `err: insufficient funds for gas * price + value: ...`
* `execution reverted`
* …
=> fix: Rework revert_reason

apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/health_router.ex, apps/block_scout_web/mix.exs
Related to https://github.com/blockscout/blockscout/pull/10032
=> fix: Add healthcheck endpoints for indexer-only setup

apps/explorer/lib/explorer/smart_contract/compiler_version.ex
For the list of available vyper contracts for internal verification, the default number of items retrieved is 30, which is less than total number of currently existing Vyper releases (46). This makes the oldest compilers unavailable when using vyper verificaiton method.
Should fix the failing `/api/v2/smart-contracts/{address_hash}/verification/via/vyper-code success verification` test
Increases the number of items retrieved for Vyper releases to 100. Allows to get the oldest vyper compilers when using internal verification (i.e., sc_verifier is disabled)
=> fix: Update Vyper inner compilers list to support all compilers

apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex, apps/explorer/lib/explorer/chain/search.ex
Resolves https://github.com/blockscout/blockscout/issues/10092
Certified flag is not returned in search API endpoints in some circumstances.
=> fix: Fix certified flag in the search API v2 endpoint

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Implement `fetch_first_trace` used for revert reason fetching in Geth variant. Fix failing test related to missing `fetch_first_trace` implementation in Geth variant.
=> feat: implement fetch_first_trace for Geth

apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
Finalization of https://github.com/blockscout/blockscout/pull/10034
Improve address API response in case of Diamond proxy.
Return multiple implementations in a single property `implementations`:
```
implementations: [
"address": "0x...",
"name": ""
]
```
=> refactor: Improve response of address API to return multiple implementations for Diamond proxy

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/indexer/lib/indexer/fetcher/optimism/withdrawal_event.ex
The `Indexer.Fetcher.Optimism.WithdrawalEvent` module doesn't handle overlapped `WithdrawalProven` events (when the same withdrawal is proven more than once and so the next event overwrites the previous one). This PR fixes it.
Also, the new three fields were added to `EthereumJSONRPC.Receipt` (related to Optimism Fjord).
=> fix: Hotfix for Indexer.Fetcher.Optimism.WithdrawalEvent and EthereumJSONRPC.Receipt

apps/explorer/lib/explorer/chain/transaction.ex
Closes #10127 
Bug seems to happen whenever fallback `eth_call` approach for fetching revert reasons is used and it does not succeed for some reason.
=> fix: missing nil case for revert reason

apps/indexer/lib/indexer/fetcher/on_demand/token_balance.ex
It is invisible for what token update error happened.
Explicitly return in the log owner address hash, token contract address hash and block number, for which the error happened.
=> chore: Explicit message on token balance update error

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9744
We can return `is_verified=true` for the minimal proxy if the implementation is verified.
Return `is_verified=true` at `/api/v2/addresses/:address_hash` for the minimal proxy if the implementation is verified.
Chore:
- fix UI v1 address overview template to support an array of implementations
- generalize return in API v2 endpoints of `implementations` object as `[%{"address" => ..., "name" => ...}]`
=> chore: Return is verified=true for verified minimal proxy pattern

apps/explorer/lib/explorer/smart_contract/helper.ex, apps/explorer/test/explorer/smart_contract/helper_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9915
Remove write methods from read tabs.
Exclude from read tabs functions, for which `Writer.write_function?(function)` is true.
=> chore: Exclude write methods from read tabs

apps/explorer/config/config.exs, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/migrator/sanitize_incorrect_weth_token_transfers.ex, apps/explorer/test/explorer/migrator/sanitize_incorrect_weth_token_transfers_test.exs, apps/indexer/lib/indexer/transform/token_transfers.ex, apps/indexer/test/indexer/transform/token_transfers_test.exs, config/runtime.exs
Closes #8525 
Closes #9418 
- Now WETH transfers will be filtered on the indexing stage:
- Will be discarded deposit and withdrawal transfers which is emitted by a token which is not in `WHITELISTED_WETH_CONTRACTS` list
- WIll be discarded deposit and withdrawal transfers which has clones (same token, from, to, amount) within the same trancation and block
- In order to make historical data consistent, added `Explorer.Migrator.SanitizeIncorrectWETHTokenTransfers`, it follows the logic stated above.
- new envs:
- `WHITELISTED_WETH_CONTRACTS`
- `SANITIZE_INCORRECT_WETH_BATCH_SIZE`
- `SANITIZE_INCORRECT_WETH_CONCURRENCY`
https://github.com/blockscout/docs/pull/289
!!!
To be added in release notes:
Be careful in this release [10134](https://github.com/blockscout/blockscout/pull/10134) will be …
=> fix: Filter WETH transfers

apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/helper.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/10110
Gradually increase ttl for counters on the main page.
Set gradually increasing ttl for counters based on MapCache module:
- total block count
- total txs count
- total gas usage
- address sum
- address sum minus burnt
Disclosing "gradually":
`n < 10k blocks` -> 10 sec
`10k blocks <= n < 50k blocks` -> 30 sec
`50k blocks <= n < 150k blocks` -> 2 min
`n >= 150k blocks` -> default value for the given chache module
=> feat: Set dynamic ttl of cache modules derived from MapCache

apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_confirmations.ex
During indexing of an ArbitrumOne BS instance it was found that the tasks tracking Arbitrum batches status produce too much logs.
Since severity of some logs could be reduced and some of `info` logs could be combined, the approach to log actions  performed during the block confirmations discovery has been re-worked.
=> fix: excessive logging for Arbitrum batches confirmations

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v2/user_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex
Previously `address_with_info` was executing individual database query to fetch proxy implementations,  now it raises if proxy implementation is not preloaded to address with code.
Raise is debatable solution chosen to decrease chances that we miss preloads and either get load of queries and slow endpoint again or silently respond with nulls where proxy implementations should be
=> perf: replace individual queries with ecto preload

apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
During writing of documentation for new Arbitrum endpoint it was discovered that the field reflecting the number of blocks in the batch was named incorrectly: `block_count` instead of `blocks_count`
The name of the field was changed.
=> fix: rename field containing the number of blocks in the Arbitrum batch

apps/explorer/lib/explorer/chain/smart_contract/verification_status.ex, apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
Continuation of https://github.com/blockscout/blockscout/pull/9986
- Fix unknown UID bug
- Add fix for 
```
2024-06-10T20:50:47.705 application=explorer [error] Smart-contract verification error: response returned with invalid status code; status=400 Bad Request
2024-06-10T20:50:47.761 [error] Task #PID<0.1867.0> started from #PID<0.1866.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"code" => 13, "message" => "response returned with invalid status code; status=400 Bad Request"} of type Map
(elixir 1.14.5) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir 1.14.5) lib/string/chars.ex:22: String.Chars.to_string/1
(explorer 6.6.0) lib/explorer/smart_contract/solidity/publisher.ex:256: Explorer.SmartContract.Solidity.Publisher.unverified_smart_con …
```
=> fix: Fix unknown UID bug

apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain/transaction_test.exs
closes #9694 
- Replace empty arg names with argN
=> fix: Replace empty arg names with argN

apps/explorer/lib/explorer/chain.ex
`2024-06-10T19:46:58.168 application=explorer request_id=F9eyeGtaxOZUv_QAANfB [error] cannot truncate chardata because it contains something that is not valid chardata: :connect_timeout`
Added `to_string` for the reason
=> fix: cannot truncate chardata

apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/main_page_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/proxy/account_abstraction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/validator_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/withdrawal_controller.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/paging_helper.ex, apps/explorer/lib/explorer/chain.ex
Added `proxy_implementations` preload to every (hopefully) needed endpoint
=> fix: add proxy_implementations preloads

apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/main_page_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/explorer/lib/explorer/chain.ex
Unexpectedly on some chains like Arbitrum from address in transaction could be a smart contract
=> fix: add smart contracts preloads to from_address

apps/explorer/lib/explorer/chain/smart_contract/proxy.ex
Resolves https://github.com/blockscout/blockscout/issues/10238
yul smart-contracts don't have ABI.
Missing clauses added to `get_naive_implementation_abi` and `get_master_copy_pattern` functions
=> fix: Fix nil abi issue in get_naive_implementation_abi and get_master_copy_pattern functions

apps/explorer/lib/explorer/chain/import/runner/zksync/batch_transactions.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/chain/zksync/batch_transaction.ex, apps/explorer/priv/zk_sync/migrations/20240611091814_rename_field_in_batch_transactions.exs, apps/indexer/lib/indexer/fetcher/zksync/discovery/batches_data.ex, apps/indexer/lib/indexer/fetcher/zksync/status_tracking/proven.ex
1. Due to recent changes related to Arbitrum (#9312), ability to view batch transactions was broken.
2. Since ZkSync switched to Hyperchain approach, it is necessary to support another function delivering batches proofs to L1.
1. The DB scheme and code was change to use `tx_hash` instead of `hash` for the batch transactions.
2. Parsing parameters of the new function `proveBatchesSharedBridge` was added to support batch proofs delivery in ZkSync Hyperchain environment.
The database scheme was changed: the field `hash` in the table `zksync_batch_l2_transactions` will be renamed to `tx_hash` during migration.
=> fix: batch transactions view recovered and support of proofs through ZkSync Hyperchain

apps/indexer/lib/indexer/fetcher/zksync/utils/rpc.ex
There is a bug in the code responsible for getting the transaction body and receipts from L1 when the zkSync batch statuses are being explored. The code tries to match the binary with the expression `"0x" <> _` to identify if a transaction hash is already encoded in hexadecimal form.
Since 32 bytes (in raw form) representing a transaction hash can be anything, there could be a case where the clause above will match even though the transaction hash is not in encoded form.
The fix for this issue is to check the length of the binary sequence so that the hash in its raw form will not match the clause.
Another change is to reuse `repeated_call` function from `Indexer.Helper` in order to reduce the code duplication.
=> fix: proper hex-encoded transaction hash recognition in ZkSync batches status checker

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/token_transfer.ex
500 in `/api/v2/transactions/{}/summary` and `api/v2/tokens/{}/transfers?apikey={}`
Added necessary preloads
=> fix: add preloads to summary and tokens endpoints

apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/polygon_edge_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/shibarium_view.ex
Missing preloads in `TransactionInterpretation` module
=> fix: add preloads for tx summary endpoint

apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
Closes #10143.
A regression test for bug fix.
todo:
=> fix: `getsourcecode` in API v1 for verified proxy

apps/explorer/lib/explorer/chain/metrics/queries.ex
```
eth_sepolia=> EXPLAIN SELECT COUNT(*)
FROM "token_transfers" AS t0 INNER JOIN "blocks" AS b1 ON b1."hash" = t0."block_hash"
WHERE (b1."timestamp" >= now()::timestamp - interval '7 days') AND (b1."consensus" = true);
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------
Finalize Aggregate  (cost=16222495.56..16222495.57 rows=1 width=8)
->  Gather  (cost=16222495.34..16222495.55 rows=2 width=8)
Workers Planned: 2
->  Partial Aggregate  (cost=16221495.34..16221495.35 rows=1 width=8)
->  Parallel Hash Join  (cost=75404.73..16219207.30 rows=915218 width=0)
Hash Cond: (t0.block_hash = b1.hash)
->  Parallel Seq Scan on token_transfers t0  (cost=0.00..15625808.47 rows=197330947 width=33)
->  Parallel Hash …
```
=> perf: Speed-up query execution for weekly_new_token_transfers_number_query

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex
```
{"time":"2024-06-20T10:46:10.881Z","severity":"error","message": "#PID<0.25537.554> running BlockScoutWeb.Endpoint (connection #PID<0.25555.554>, stream id 1) terminated\nServer: eth-sepolia.k8s-dev.blockscout.com:80 (http)\nRequest: GET /api/v2/tokens/0xcE818599DaBa7e1e7B1bcc1Ce0607010ff4e0B83/instances\n** (exit) an exception was raised:\n    ** (RuntimeError) proxy_implementations is not loaded for address\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/helper.ex:61: BlockScoutWeb.API.V2.Helper.address_with_info/2\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/helper.ex:35: BlockScoutWeb.API.V2.Helper.address_with_info/5\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/token_view.ex:110: …
```
=> fix: add token instances preloads

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/explorer/lib/explorer/chain.ex
```
{"time":"2024-06-20T10:46:10.881Z","severity":"error","message": "#PID[0.25537.554](https://app.slack.com/client/0.25537.554) running BlockScoutWeb.Endpoint (connection #PID[0.25555.554](https://app.slack.com/client/0.25555.554), stream id 1) terminated\nServer: [eth-sepolia.k8s-dev.blockscout.com:80](http://eth-sepolia.k8s-dev.blockscout.com/) (http)\nRequest: GET /api/v2/tokens/0xcE818599DaBa7e1e7B1bcc1Ce0607010ff4e0B83/instances\n** (exit) an exception was raised:\n    ** (RuntimeError) proxy_implementations is not loaded for address\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/helper.ex:61: BlockScoutWeb.API.V2.Helper.address_with_info/2\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/helper.ex:35: …
```
=> fix: token instance preload

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
Closes #10251
Closes #10276
Fix revert reasons behavior in Geth's `fetch_first_trace` implementation on networks without support for `onlyTopCall`. New code ignores any extra received traces, or fallback to `eth_call` revert reason resolution if something when wrong.
=> fix: missing onlyTopCall option on some geth networks

apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
For transactions indexed before the Arbitrum-specific changes were deployed, the `api/v2/transactions/{tx_hash}` endpoint raises an error:
```
Request: GET /api/v2/transactions/0xf863e6b2b655e51e4e9f148c646b3d022125e7fc7277476f623510263beb8f54
** (FunctionClauseError) no function clause matching in Decimal.decimal/1
(decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal(nil)
(decimal 2.1.1) lib/decimal.ex:302: Decimal.sub/2
(block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:396: BlockScoutWeb.API.V2.ArbitrumView.extend_with_transaction_info/2
(block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:161: BlockScoutWeb.API.V2.ArbitrumView.extend_transaction_json_response/2
(phoenix 1.5.14) lib/phoenix/view.ex:472: …
```
=> fix: proper handling of Arbitrum transactions without gas_used_for_l1

apps/explorer/lib/explorer/utility/missing_balance_of_token.ex
Related to https://github.com/blockscout/blockscout/pull/10018
=> fix: Don't execute update missing_balance_of_tokens query for empty list

apps/explorer/lib/explorer/chain/metrics.ex, apps/explorer/lib/explorer/chain/metrics/queries.ex, apps/explorer/lib/explorer/prometheus/instrumenter.ex
Related to https://github.com/blockscout/blockscout/pull/10279
Related to https://github.com/blockscout/blockscout/pull/10063
Public metrics are not calculated despite they are being enabled.
- Fix condition to enable calculation of public metrics
- Add a simplified query to calculate and enable "Active accounts" metric back.
=> fix: public metrics enabling

.github/workflows/publish-regular-docker-image-on-demand.yml, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
```
{"time":"2024-07-01T11:27:25.102Z","severity":"error","message":"#PID<0.16749.440> running BlockScoutWeb.Endpoint (connection #PID<0.14932.440>, stream id 1) terminated\nServer: explorer.evm.shimmer.network:80 (http)\nRequest: GET /api/v2/transactions?block_number=5132212&index=0&items_count=200&filter=validated\n** (exit) an exception was raised:\n    ** (MatchError) no match of right hand side value: {:error, [%{code: -32601, message: \"the method debug_traceBlockByNumber does not exist/is not available\"}]}\n        (explorer 6.7.1) lib/explorer/chain.ex:4924: Explorer.Chain.get_block_index/1\n        (explorer 6.7.1) lib/explorer/chain.ex:4884: Explorer.Chain.format_tx_first_trace/3\n        (explorer 6.7.1) lib/explorer/chain.ex:2995: Explorer.Chain.fetch_tx_revert_reason/1\n …
```
=> fix: Add rescue on tx revert reason fetching

apps/explorer/lib/explorer/chain/internal_transaction.ex
Closes #10202 
- Replace `pending_block_operations` join with `WHERE (SELECT ...) IS NOT NULL`
=> fix: Fix slow internal transactions query

apps/explorer/config/prod.exs
Related to https://github.com/blockscout/blockscout/pull/9256
Error while running DB migrations in prod env:
```
{"time":"2024-07-02T13:56:58.020Z","severity":"warn","message":"setting ssl: true on your database connection offers only limited protection, as the server's certificate is not verified. Set \"ssl: [cacertfile: path/to/file]\" instead","metadata":{}}
{"time":"2024-07-02T13:56:58.025Z","severity":"error","message":"Postgrex.Protocol (#PID<0.211.0>) failed to connect: ** (DBConnection.ConnectionError) ssl connect: Options (or their values) can not be combined: [{verify,verify_peer},\n                                                {cacerts,undefined}] - {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}","metadata":{"error":{"initial_call":null,"reason":"** …
```
=> fix: Apply Ecto set explicit ssl_opts: [verify: :verify_none] to all prod repos

apps/explorer/lib/explorer/chain/metrics/queries.ex, apps/explorer/lib/explorer/prometheus/instrumenter.ex
Related to https://github.com/blockscout/blockscout/pull/10063
The current query for fetching deployed smart-contracts from transactions and internal transactions is not performant.
Remove join with `internal_transactions` table. Thus, we'll consider only smart-contracts created from regular transactions in that metric.
=> fix: simplify query for weekly_deployed_smart_contracts_number public metric

apps/explorer/lib/explorer/chain/arbitrum/batch_block.ex, apps/explorer/lib/explorer/chain/arbitrum/batch_transaction.ex, apps/explorer/lib/explorer/chain/arbitrum/l1_batch.ex, apps/explorer/lib/explorer/chain/arbitrum/l1_execution.ex, apps/explorer/lib/explorer/chain/arbitrum/lifecycle_transaction.ex, apps/explorer/lib/explorer/chain/arbitrum/message.ex, apps/explorer/lib/explorer/chain/arbitrum/reader.ex, apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_confirmations.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_l1_executions.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_messages_to_l2.ex
During synchronization of ArbitrumOne, it was found that there is no progress in marking L2->L1 messages as completed, even though transactions executing the messages are being discovered on L1. The root cause of the issue is that the database query to discover all confirmed but uncompleted messages uses the L1 block number to limit the number of messages to be handled, while the database refers to rollup blocks. Since the number of blocks in L1 is much lower than the number of blocks in L2, no confirmed messages are found.
To address this issue, it was decided not to limit the lookup of confirmed messages by the block. The number of irrelevant confirmed messages is not expected to be high, as it is assumed that, due to the nature of the Arbitrum rollup, there is a strong motivation to …
=> fix: proper lookup of confirmed Arbitrum cross-chain messages

apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/lib/explorer/migrator/filling_migration.ex, apps/explorer/lib/explorer/migrator/sanitize_incorrect_nft_token_transfers.ex, apps/explorer/lib/explorer/migrator/sanitize_incorrect_weth_token_transfers.ex, apps/explorer/lib/explorer/migrator/sanitize_missing_block_ranges.ex, apps/indexer/lib/indexer/fetcher/polygon_edge/deposit.ex, apps/indexer/lib/indexer/fetcher/polygon_edge/deposit_execute.ex, apps/indexer/lib/indexer/fetcher/polygon_edge/withdrawal.ex, apps/indexer/lib/indexer/fetcher/polygon_edge/withdrawal_exit.ex, apps/indexer/lib/indexer/fetcher/token_instance/sanitize_erc721.ex, apps/indexer/lib/indexer/fetcher/transaction_action.ex, apps/indexer/lib/indexer/fetcher/withdrawal.ex
Resolves https://github.com/blockscout/blockscout/issues/10291
DB queries and node requests moved from `init`s to `handle_continue`s
=> chore: Refactor init functions to use continue if needed

apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
https://github.com/blockscout/blockscout/issues/9347
Fix flickering test
> test/block_scout_web/controllers/api/v2/address_controller_test.exs:59
```
1) test /addresses/{address_hash} get address & get the same response for checksummed and downcased parameter (BlockScoutWeb.API.V2.AddressControllerTest) Error: test/block_scout_web/controllers/api/v2/address_controller_test.exs:59 match (=) failed The following variables were pinned: correct_response = %{"block_number_balance_updated_at" => nil, "coin_balance" => nil, "creation_tx_hash" => nil, "creator_address_hash" => nil, "ens_domain_name" => nil, "exchange_rate" => nil, "has_beacon_chain_withdrawals" => false, "has_decompiled_code" => false, "has_logs" => false, "has_token_transfers" => false, "has_tokens" => false, …
```
=> fix: Fix address controller flickering test

apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
Frontend since 1.31.0 doesn't use "implementation_name" and "implementation_address" props in API v2 endpoints.
Remove obsolete single properties:
- "implementation_name"
- "implementation_address"
in API v2 endpoints.
=> chore: Remove single implementation name, address from API v2 response

apps/block_scout_web/test/block_scout_web/controllers/api/v2/stats_controller_test.exs
Finalization of https://github.com/blockscout/blockscout/pull/10383/files
Previous attempt #10383 didn't help since `ExchangeRates` module is disabled globally in tests. This test, seems, flickering because of not empty exchange rates cache. This PR sets `MarketHistoryCache`'s `cache_period` to 0 for the test in order to exclude using cached values.
=> fix: Fix flickering /stats/charts/market test

apps/block_scout_web/config/runtime/test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_checker.ex, config/runtime.exs
Flickering tests in different locations with the same error message:
```
1) test /smart-contracts/{address_hash} get smart-contract (BlockScoutWeb.API.V2.SmartContractControllerTest) Error: test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs:97 ** (EXIT from #PID<0.16767.0>) an exception was raised:
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Explorer.TestHelper.mock_beacon_storage_pointer_request/3
The following arguments were given to anonymous fn/2 in Explorer.TestHelper.mock_beacon_storage_pointer_request/3:
%{id: 0, params: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 56, 54>>}, …
```
=> Fix missing expectation in mock_beacon_storage_pointer_request

apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
```
1) test /addresses get empty list (BlockScoutWeb.API.V2.AddressControllerTest)
Error:      test/block_scout_web/controllers/api/v2/address_controller_test.exs:2421
match (=) failed
The following variables were pinned:
total_supply = "252460800"
code:  assert %{
"items" => [],
"next_page_params" => nil,
"exchange_rate" => nil,
"total_supply" => ^total_supply
} = json_response(request, 200)
left:  %{
"items" => [],
"next_page_params" => nil,
"exchange_rate" => nil,
"total_supply" => ^total_supply
}
right: %{
"exchange_rate" => "2.5",
"items" => [],
"next_page_params" => nil,
"total_supply" => "252460800"
}
stacktrace:
test/block_scout_web/controllers/api/v2/address_controller_test.exs:2426: (test)
```
=> fix: /addresses empty list flickering test fix

apps/explorer/test/explorer/chain/cache/block_test.exs, apps/explorer/test/explorer/chain/cache/transaction_test.exs
```
Error: test/explorer/chain/cache/block_test.exs:32
Assertion with == failed
code: assert updated_value == 2
left: 0
right: 2
stacktrace:
test/explorer/chain/cache/block_test.exs:43: (test)
```
Double sleep timeout.
=> fix: Fix flickering "updates cache if initial value is zero" test

apps/explorer/test/explorer/chain_test.exs
Flickering test:
```
2) test transaction_estimated_count/1 returns integer (Explorer.ChainTest)
Error:      test/explorer/chain_test.exs:2224
** (exit) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
code: assert is_integer(TransactionCache.estimated_count())
stacktrace:
(con_cache 1.1.0) lib/con_cache/owner.ex:14: ConCache.Owner.cache/1
(con_cache 1.1.0) lib/con_cache.ex:228: ConCache.get/2
(explorer 6.7.2) lib/explorer/chain/cache/transaction.ex:6: Explorer.Chain.Cache.Transaction.get/1
(explorer 6.7.2) lib/explorer/chain/cache/transaction.ex:27: Explorer.Chain.Cache.Transaction.estimated_count/0 …
```
=> fix: Fix flickering transaction_estimated_count/1 test

apps/explorer/lib/explorer/etherscan/logs.ex
Part of #9347
`test list_logs/1 paginates logs (test/explorer/etherscan/logs_test.exs:181)`
- Fix order for query in case transaction denormalization is finished
=> fix: Fix logs sorting in API v1

apps/explorer/lib/explorer/chain/internal_transaction.ex
Resolves https://github.com/blockscout/blockscout/issues/10281
=> fix: Filter out internal transactions belonging to reorg

apps/block_scout_web/lib/block_scout_web/views/nft_helper.ex
Superseed of https://github.com/blockscout/blockscout/pull/10317
Allow fetching of token instance image from "properties" -> "image" property of the metadata JSON.
=> fix: allow fetching image from "properties" -> "image" prop in token instance metadata

apps/explorer/config/config.exs, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/chain/import/stage/block_following.ex, apps/explorer/lib/explorer/chain/import/stage/block_pending.ex, apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex, apps/explorer/lib/explorer/chain/import/stage/block_related.ex, apps/explorer/lib/explorer/migrator/token_transfer_block_consensus.ex, apps/explorer/lib/explorer/migrator/transaction_block_consensus.ex, apps/explorer/test/explorer/chain/import_test.exs
Reorgs detection and marking blocks as `consensus: false` (along with transactions and token transfers `block_consensus: false`) is executed in the different import stage from inserting transactions and token transfers. It means that these queries are executed in different DB transactions. It means that there is a space for race condition.
For example:
1. Some block is already inserted in DB but its transactions and token transfers aren't
2. Process of importing new block with the same number begins
3. Consensus of the block imported in step 1 is set to `false` since now it's a reorg
4. Consensus of transactions and token transfers of that reorg are set to `false` (but they are not inserted yet, so nothing happens)
5. Transactions and token transfers of the block inserted in step 1 are …
=> fix: Transactions and token transfers block_consensus

apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex, apps/explorer/lib/explorer/chain/cache/background_migrations.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/pending_block_operation.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex, apps/explorer/lib/explorer/chain/ordered_cache.ex, apps/explorer/test/explorer/chain/cache/block_test.exs, apps/explorer/test/explorer/chain/cache/transaction_test.exs
Fix flaking test
> test/explorer/chain/cache/block_test.exs:18
When cache process is restarted each time in the tests, it leaves an async task hanging, as it's not attached to the parent cache process. Result from this hanging task then re-appear in the newly relaunched cache process, along with the following error.
Proposed solution is to use `Task.start_link` instead of `Task.start` to link the async task with the cache process, so that it's killed whenever cache process is terminated.
=> fix: race condition in cache tests

docker-compose/README.md
The note detailing `docker compose` use for Docker's compose v2 plugin should be higher in the README since the document's first bash snippet includes `docker-compose up --build` which uses the "docker-compose" syntax.
This way the relevant note is readily visible above the first mention of "docker-compose" so skimmers trying to get the explorer up and running are immediately informed of the difference
*Things you added that don't break anything.  Regression tests for Bug …
=> doc: Move note in README.md higher for visibility

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex, apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain/transaction/state_change.ex
Closes #8647
Fixes https://github.com/blockscout/blockscout/issues/8878
Fixes https://github.com/blockscout/blockscout/issues/10337
- Refactor and optimize preloads
- Take into account internal transactions
=> fix: include internal transactions in state change

apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Part of #9347 
> test/explorer/smart_contract/solidity/code_compiler_test.exs:159
`code_compiler_test.exs` is `async: true`, `RustVerifierInterfaceBehaviour` was not disabled explicitly there. Most of the time `RustVerifierInterfaceBehaviour` would be properly disabled by some other test running in parallel, but sometimes it wouldn't, which lead to one of the test failing.
=> fix: code compiler test

apps/explorer/lib/explorer/chain/address/metadata_preloader.ex
Resolves https://github.com/blockscout/blockscout/issues/10438
=> fix: Missing clauses in MetadataPreloader functions

apps/explorer/lib/explorer/smart_contract/helper.ex
Resolves https://github.com/blockscout/blockscout/issues/10434
Resolve "key :bytes not found in: nil" error in the logs.
=> Fix "key :bytes not found in: nil" issue

apps/indexer/lib/indexer/fetcher/arbitrum/utils/rpc.ex
The existing version of binary search of the batch block ranges causes the infinite loop on the ArbitrumOne batch 4416.
The proposed changes implements the binary search more carefully. Also an iteration threshold was added to prevent infinite loops in the future. Another improvement is to add a cache for the Node Interface contract calls to reduce amount of RPC requests.
The changes was tested on the ArbitrumOne legacy blocks (where the binary search is required since no information about the rollup blocks in the batch delivery operation): `4074 .. 4541`.
=> fix: avoid infinite loop during batch block range binary search

apps/block_scout_web/lib/block_scout_web/notifier.ex
Preload token transfers associations by one query instead of multiple
=> chore: Token transfers broadcast optimization

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/fetcher/look_up_smart_contract_sources_on_demand.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/smart_contract/solidity/publish_helper.ex
Resolves https://github.com/blockscout/blockscout/issues/10456
> When the number of on-demand requests of LookUpSmartContractSourcesOnDemand module is high, mailbox of the process is full of incoming messages which are not yet processed, which caould cause memory leakage at API pod.
- change input data of the fetcher: instead of Address object use address hash string and address bytecode.
- move check of the lookup smart contract source codes fetch egilibility before checking of max concurrency.
Both steps should mitigate issue with high memory consumption.
=> perf: Reduce LookUpSmartContractSourcesOnDemand fetcher footprint

apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex, apps/block_scout_web/lib/block_scout_web/smart_contract_realtime_event_handler.ex
Related to https://github.com/blockscout/blockscout/pull/9018
=> chore: Move eth_bytecode_db_lookup_started event to smart contract related event handler

apps/explorer/priv/repo/migrations/20240718150123_add_no_overlap_index_to_missing_block_ranges.exs, apps/indexer/test/indexer/block/catchup/missing_ranges_collector_test.exs
Even though operations on `missing_block_ranges` are concurrent safe, there are situations when two instances of indexer is running at the same time (during deploy for example). This may cause ranges overlapping and therefore incorrect stored ranges.
Added no-overlapping ranges constraint to `missing_block_ranges`.
=> fix: Add no overlapping constraint to missing_block_ranges

apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
We don't have a test for receiving `:fetched_bytecode` event on the websocket endpoint.
=> chore: Add test for broadcasting fetched_bytecode message

apps/explorer/lib/explorer/chain.ex
Added missing `refetch_needed` condition to min missing block number logic
=> fix: Add missing condition to fetch_min_missing_block_cache

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/block_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction/history/historian.ex, apps/explorer/test/explorer/chain/transaction/history/historian_test.exs, apps/explorer/test/explorer/chain_test.exs
Closes #9742.
Regression test for Bug Fix
Initially, the timestamp_to_block_number function filtered blocks to include only those with timestamps differing by no more than one minute from the given timestamp. This PR removes that filtering, allowing for an indefinite range of search. Testing on the Sepolia database shows that the new query performs similarly to the previous one with filtering in terms of execution time.
=> fix: extend block search range for `getblocknobytime` method

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
Since most of the chain forks are based on Geth client, for maintainability purposes it is better to swap default JSON RPC variant to geth.
=> chore: Set Geth as default JSON RPC Variant

apps/explorer/lib/explorer/chain.ex
Filtering logs for address by associated transaction `block_consensus` field is not enough because in case of reorg there may be several logs associated with `block_consensus=true` transaction but with different `block_hash`es
Filter logs for address by block consensus directly
=> fix: Fix address_to_logs consensus filtering

apps/explorer/lib/explorer/token/metadata_retriever.ex
Resolves https://github.com/blockscout/blockscout/issues/10401
Sanitize response from `contractURI` property
In the given example the value in `contractURI` is " https://api-imx.boomland.io/api/v1/ticket".
We should trim whitespaces in the response.
=> fix: Sanitize contractURI response

apps/indexer/lib/indexer/application.ex
Recently :checkout_timeout error started appears: 
> `select min(updated_at) from token_instances ti where error=':checkout_timeout'`
> `2024-07-06 01:13:41.003`
The earliest date is later the frontend release 1.32, where token refetch button was added, so I assume that not increased `pool_size` is a root cause
- increase pool_size
=> fix: Fix :checkout_timeout error on NFT fetching

apps/explorer/lib/explorer/etherscan/logs.ex
Resolves https://github.com/blockscout/blockscout/issues/10440
Events `Topic` filter in getLogs API v1 endpoint is not checked to be a valid hash value.
Casting event topic to hash object before preparing Db query.
=> fix: Sanitize topic value before making db query

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/config_controller.ex, apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
Add config API endpoint for public metrics.
`/api/v2/config/public-metrics` endpoint is added.
Sample response (default update period is 24 hrs):
```
{"update_period_hours":24}
```
=> chore: Public metrics config API endpoint

apps/explorer/lib/explorer/chain/mud.ex
* Speed up `/api/v2/mud/worlds` performance
Postgres does not have an efficient "index skip scan" implementation, thus searching for distinct values requires a large seq scan. A workaround has been found through use of a secondary index together with a table id filter:
```
+------------------------------------------------------------------------------------------------------------------------------------------------+
|QUERY PLAN                                                                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------------------------+
|Limit  (cost=0.56..195702.49 rows=26 width=21) (actual time=2.227..22.875 rows=50 …
```
=> perf: speed up worlds list query

apps/explorer/lib/explorer/chain/arbitrum/reader.ex, apps/indexer/lib/indexer/fetcher/arbitrum/messaging.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/historical_messages_on_l2.ex
During synchronization of the Blockscout instance for Arbitrum One, it was found that not all transactions with the type `100` can be considered as deposit L1->L2 messages.
First of all, the following error occurred on the system when attempting to insert the message into the database.
```
** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 71052128300123780255705434601148651469646560887648206875893026519230861104461. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
(postgrex 0.18.0) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
(postgrex 0.18.0) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
(db_connection 2.7.0) …
```
=> fix: filter out incorrect L1-to-L2 Arbitrum messages 

.github/workflows/config.yml, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
There are internal transactions runner tests that follow the logic of considering `there are no internal txs for some transactions` case as invalid while for zetachain it's a valid case.
- Moved tests that follow mentioned logic to non-zetachain chain types
- Added an adaptation of these tests for zetachain
=> fix: Fix internal transactions runner test for zetachain

apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
Resolves https://github.com/blockscout/blockscout/issues/10458
Add block number to token transfer object in API v2 endpoint. This request was heard from API users.
=> feat: Add block number to token transfer object in API v2 endpoint

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/import_controller.ex, apps/block_scout_web/lib/block_scout_web/routers/api_router.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/import_controller_test.exs, apps/explorer/lib/explorer/chain/token.ex
Closes #8963 
- Add DELETE `/api/v2/import/token-info method` (expects `token_address_hash` and `api_key` as input parameters)
=> feat: Add DELETE /api/v2/import/token-info method

apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
- Add internal_transactions to tx interpreter request
=> feat: Add internal_transactions to Tx interpreter request

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex
Resolves https://github.com/blockscout/blockscout/issues/10442
Some transaction traces are transformed to internal transactions and addresses, which cannot pass validation before insertion into the DB.
trace with an error in smart-contract (create2) creation (see trace response from the node in the linked issue) generates such address among others:
```
%{
hash: "0x",
fetched_coin_balance_block_number: 17237541,
contract_code: "0x"
}
```
and such internal transaction with invalid created_contract_address_hash: `created_contract_address_hash: "0x"`:
```
%{
error: "execution reverted",
index: 0,
init: "0x...",
type: "create",
value: 100000000000000,
block_number: 17237541,
from_address_hash: "0xcfe6ab9f66c0abba8081ff0789272ee4688a5d0c",
gas: 1148773,
transaction_index: 23, …
```
=> fix: Fix internal transaction validation

apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
Although the changes to provide an associated L1 transaction for rollup transactions containing a cross-chain message were already made in https://github.com/blockscout/blockscout/pull/10590, it was found that for scenarios where the rollup transaction contains a message but there is no associated L1 transaction, there should be a more descriptive response to display the correct status to the end user in the UI.
The function `l1_tx_and_status_for_message` provides a map containing the L1 transaction and status of the message, which can be used in cases where the L1 transaction is not yet associated.
=> feat: more descriptive status for Arbitrum message for the transaction view

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/advanced_filter_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/utils_controller.ex, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/advanced_filter_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/suave_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/explorer/lib/explorer/chain/csv_export/address_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/csv_export/address_transaction_csv_exporter_test.exs
Closes #10190 
- Add `MethodName` field to txs CSV
=> feat: Add method name to transactions CSV export

apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
The following code raises an exception while Arbitrum-specific values are calculated to render the transaction view page:
https://github.com/blockscout/blockscout/blob/a9c2a08716941db3363f8016ce37dbf638a08c1d/apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex#L623-L625
The reason for this behavior is that the `gas_used` field in the database is `null` for dropped/replaced transactions. When the field is extracted from the transaction data, it is `null` as well:
https://github.com/blockscout/blockscout/blob/a9c2a08716941db3363f8016ce37dbf638a08c1d/apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex#L620-L621
As a result, the further usage of the `nil` value is not accepted in the `Decimal.sub` function.
Apply a default value of `0` for the value …
=> fix: proper default value of gas used for dropped Arbitrum transactions

apps/explorer/lib/explorer/application.ex, config/config_helper.exs, config/runtime.exs
Related to https://github.com/blockscout/blockscout/pull/10567
- Added `MODE` env variable so the application can configure which processes to run on the current instance
- Move `ShrinkInternalTransactions` migration under `indexer` or `all` mode so it will be executed on one instance only
Docs update: https://github.com/blockscout/docs/pull/312
=> chore: Run shrink internal transactions migration for indexer instance only

apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/explorer/token/metadata_retriever_test.exs, cspell.json
https://github.com/blockscout/blockscout/issues/10260
A part of https://github.com/blockscout/blockscout/pull/10282
Some IPFS resources are still requested from public IPFS gateway URL. For instance, if the value in `tokenURI` property is `https://ipfs.io/ipfs/...`, Blockscout will request it as is.
This PR refactors detection of IPFS content URL and routes those requests to configured IPFS Gateway URL. Next patterns will be processed:
- ipfs://...
- http(s)://.../ipfs/...
- ipfs/...
- Qm... (46 bytes)
- bafybe...
=> fix: Better detection IPFS links in NFT metadata fetcher

apps/explorer/lib/explorer/application.ex
Related to https://github.com/blockscout/blockscout/pull/10631
Add the `should_start?/1` missing condition to `configure_mode_dependent_process/2`
=> fix: Fix mode dependent processes starting

apps/explorer/lib/explorer/chain.ex
There is no check that error is already present in transactions in `update_replaced_transactions` query, which is used for setting `error` in transaction.
Add additional where clause `(is_nil(t.error) or t.error != "dropped/replaced")` in `update_replaced_transactions` query, which acquires transactions to be updated.
=> fix: Fix bug in update_replaced_transactions query

docker/Dockerfile
*NOTE*: perhaps it's safer to make a separate Dockerfile for this and then integrate this into your CI/CD with a non-root tag. Happy to help update your GitHub Actions workflows if interested.
See [feature request](https://blockscout.canny.io/feature-requests/p/docker-container-running-as-non-root).
(NOTE: It's possible that this can break things, depending on someone's environment.)
- Add non-root user/group in Dockerfile.
- Set owner ship of /app to new non-root user/group.
- Run container with new non-root user/group.
I did do a build for this in my own CI and confirmed that it …
=> Make Dockerfile use specified user with uid/gid

CHANGELOG.md, apps/explorer/lib/explorer/token/metadata_retriever.ex
Related to https://github.com/blockscout/blockscout/pull/10638
Fetching metadata from the URL like:
```
ipfs://QmRQkXzJu31dp5s4TaKwowNikxePRbiAWitxT5RDfZGoiV/3197
```
doesn't work.
=> fix: Fix for metadata detection at ipfs protocol

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/ordered_cache.ex
Closes #10445
Added `atomic_take_enough` function that fetches all the items from the cache at once instead of fetching them in map one by one.
=> fix: `nil` in `OrderedCache`

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs, apps/explorer/lib/explorer/etherscan/logs.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan/logs_test.exs, apps/explorer/test/support/factory.ex
* Fix tests failures related to faulty `log_factory`
* Fix type casting bug in RPC API, probably related to some underlying bug in Ecto
* https://base.blockscout.com/api?module=logs&action=getLogs&fromBlock=18939002&toBlock=18939002&address=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
=> fix: logs list serialization

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/basic.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_2535.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex, apps/explorer/lib/test_helper.ex
Resolves https://github.com/blockscout/blockscout/issues/10151
Diamond proxy pattern is undetected on proxy smart-contracts, that are not verified itself or verified and do not contain `facetAddresses` getter in the ABI.
Enable detection of EIP-2535 (Diamond proxy standard) no matter proxy smart-contract is verified or not and no matter where is `facetAddresses` getter is defined: in proxy or in implementation.
=> feature: Detect Diamond proxy pattern on unverified proxy smart-contract

apps/explorer/lib/explorer/chain/polygon_zkevm/reader.ex, apps/indexer/lib/indexer/fetcher/polygon_zkevm/bridge.ex
Polygon zkEVM bridge indexer throws the following error:
```
{"time":"2024-09-02T03:35:51.342Z","severity":"error","message":"GenServer Indexer.Fetcher.PolygonZkevm.BridgeL1 terminating\n** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(16)\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9\n    (ecto 3.11.2) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7\n    (explorer 6.8.0) lib/explorer/repo.ex:47: anonymous fn/5 in Explorer.Repo.safe_insert_all/3\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.8.0) lib/explorer/chain/import.ex:304: …
```
=> fix: Truncate token symbol in `Explorer.Chain.PolygonZkevm.BridgeL1Token` module

config/runtime.exs
Related to https://github.com/blockscout/blockscout/pull/10567
Docs update: https://github.com/blockscout/docs/pull/318
=> chore: Change shrink internal transactions migration default batch_size

apps/block_scout_web/lib/block_scout_web.ex, apps/block_scout_web/lib/block_scout_web/gettext.ex, apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/wei_helper.ex
https://github.com/blockscout/blockscout/pull/10657
```
warning: defining a Gettext backend by calling
use Gettext, otp_app: ...
is deprecated. To define a backend, call:
use Gettext.Backend, otp_app: :my_app
Then, instead of importing your backend, call this in your module:
use Gettext, backend: MyApp.Gettext
lib/block_scout_web/gettext.ex:23: BlockScoutWeb.Gettext (module)
```
Define Gettext dependency, as it is suggested nowadays https://hexdocs.pm/gettext/0.26.1/Gettext.html#module-gettext-api.
=> fix: Fix gettext usage warning

apps/explorer/test/explorer/migrator/sanitize_incorrect_weth_token_transfers_test.exs, apps/explorer/test/explorer/token/metadata_retriever_test.exs
* Fix some flaking tests in Explorer app
=> chore: fix flaking explorer tests

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/celo_view.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/celo/reader.ex
Closes #10607, #10628. 
1. It would be convenient for frontend to get current epoch number from stats endpoint. 
2. Amounts in wei should be formatted as strings for proper rendering on client's side.
3. We should add token in which base fee is paid. 
Under `:celo` chain type, the `/api/v2/stats` is extended with `celo.epoch.number`. See example:
```jsonc
{
"average_block_time": 5.0e3,
"celo": {
"epoch_number": 1431 // <- here it is
},
"coin_image": null,
"coin_price": null,
"coin_price_change_percentage": null,
"gas_price_updated_at": null,
"gas_prices": {
"slow": null,
"average": null,
"fast": null
},
"gas_prices_update_in": 32000,
"gas_used_today": null,
"market_cap": "0",
"network_utilization_percentage": 1.4027809714285715,
"secondary_coin_image": null,
"secondary_coin_price": null, …
```
=>  feat: Celo API updates

apps/indexer/lib/indexer/fetcher/token_balance.ex
Resolves https://github.com/blockscout/blockscout/issues/10711
=> chore: Extend missing balanceOf function with :unable_to_decode error

apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex, cspell.json
On `Unichain Private Testnet` the following error was discovered:
```
{"time":"2024-09-10T12:28:16.062Z","severity":"error","message":"GenServer Indexer.Fetcher.Optimism.TxnBatch terminating\n** (Postgrex.Error) ERROR 23503 (foreign_key_violation) update or delete on table \"op_frame_sequences\" violates foreign key constraint \"op_transaction_batches_frame_sequence_id_fkey\" on table \"op_transaction_batches\"\n\n    table: op_transaction_batches\n    constraint: op_transaction_batches_frame_sequence_id_fkey\n\nKey (id)=(1) is still referenced from table \"op_transaction_batches\".\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6\n    (indexer 6.8.0) …
```
=> fix: Avoid key violation error in `Indexer.Fetcher.Optimism.TxnBatch`

apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/transform/address_coin_balances.ex, apps/indexer/test/indexer/transform/address_coin_balances_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9455
Resolves https://github.com/blockscout/blockscout/issues/10592
Coin balances params that collected during internal transactions fetcher process are only stored in the coin balances fetcher state. It means that if coin balances fetcher crashes, these balances will never be fetched.
- Add an insertion of token balances placeholders to the internal transactions fetcher so if coin balances fetcher crashes, they will be eventually fetched anyway
- Fix coin balances params fetching from internal transactions
=> fix: Insert coin balances placeholders in internal transactions fetcher

apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/smart_contract/proxy_test.exs, apps/explorer/test/explorer/chain/transaction_test.exs
Resolves https://github.com/blockscout/blockscout/issues/10735
/api/v2/transactions API endpoint low performance on transactions to smart-contracts
Instead of sending DB query for fetching proxy implementation objects from the DB for each smart-contract from the transactions list, pre-processing is added which aggregates unique smart-contracts in the list and fetches proxy implementations for them in a single DB query.
=> perf: Improve performance of transactions list page

apps/explorer/lib/explorer/chain.ex
Resolves https://github.com/blockscout/blockscout/issues/10493
In case when token fetcher fails to get functions of token, it doesn't set `cataloged: true` to it and therefore the fetcher will constantly try to process this token again. But in such cases the token is marked as `skip_metadata: true`. So we should skip tokens with this setting from token fetcher query.
=> fix: Filter out tokens with skip_metadata: true from token fetcher

apps/explorer/lib/explorer/application.ex
Resolves https://github.com/blockscout/blockscout/issues/10669
Account feature is broken if `ACCOUNT_DATABASE_URL` is not set. However, it should work since Account-related tables are created in the main DB (which is defined in `DATABASE_URL`).
Enable account repo based on `ACCOUNT_ENABLED` flag.
=> fix: Fix account db repo definition

apps/indexer/lib/indexer/fetcher/arbitrum/rollup_messages_catchup.ex, apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex
As per the approach introduced in https://github.com/blockscout/blockscout/pull/10374, the logic to start the discovery process of missing batches attempted to identify a rollup block where the first missed message was expected. Although this approach seemed intuitive, the corresponding query to the DB became very heavy with an increasing number of rollup transactions. For example, on the ArbitrumOne instance, the query takes hours (based on logs) and likely causes excessive resource consumption, leading to issues such as:
```
(DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
```
To address the issue described above, a more simple approach has been implemented that starts looking for …
=> fix: get rid of heavy DB query to start Arbitrum missed messages discovery process

apps/indexer/lib/indexer/fetcher/arbitrum/da/anytrust.ex, apps/indexer/lib/indexer/fetcher/arbitrum/da/common.ex, apps/indexer/lib/indexer/fetcher/arbitrum/utils/rpc.ex, apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex
During indexing of the Arbitrum Nova Blockscout instance, it was found that the discovery of historical batches stuck on batch no. 145. During the investigation of the issue, three problems were identified:
- The approach to discover the blocks range in a batch does not work properly if the previously known batch contains 2 or 1 block.
- Since block 0 was excluded to discover the batch range, batch 1 cannot be indexed.
- The old version of AnyTrust DA certificates is not supported, although all batches below 119 are using this version.
1. The length of the blocks range is now calculated properly in `apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex`.
2. The lower limit of block numbers which can be requested in `findBatchContainingBlock` of the `NodeInterface` contract is …
=> fix: proper handling of old batches on Arbitrum Nova

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/search_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/search_controller.ex
Resolves https://github.com/blockscout/blockscout/issues/10575
Search is started even with 1 letter provided by the user.
Don't start search unless less 3 letters provided in the query.
=> fix: Set min query length in the search API endpoints

apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/explorer/lib/explorer/chain/smart_contract.ex
Resolves https://github.com/blockscout/blockscout/issues/10161
- Additional sources are not preloaded when bytecode twin is found.
- We shouldn't set additional sources from twin, if proxy smart-contract has been verified.
- Add preload of `:smart_contract_additional_sources` association in `get_verified_bytecode_twin_contract /2` function.
- Change priority in getting additional sources: firstly get from verified smart-contract. In other cases take from bytecode twin.
=> fix: Preload additional sources for bytecode twin smart-contract

apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
* When ABI-decoding method calls and logs, all address fields should be auto-checksummed. Non-checksummed format also causes incorrect identicons being displayed on the UI.
=> fix: decode addresses as checksummed

apps/indexer/lib/indexer/block/catchup/fetcher.ex
Related to https://github.com/blockscout/blockscout/pull/9403
=> fix: Clear null round blocks from missing block ranges

apps/explorer/lib/explorer/chain/ordered_cache.ex
Resolves https://github.com/blockscout/blockscout/issues/10790
Updated the `OrderedCache` preload logic to execute a single time for all new elements instead of per-element execution.
=> chore: Refactor OrderedCache preloads

apps/explorer/lib/explorer/tags/address_tag.ex, apps/explorer/lib/explorer/tags/address_tag_cataloger.ex, apps/explorer/lib/explorer/tags/address_to_tag.ex, apps/explorer/priv/repo/migrations/20240923173516_address_tags_add_primary_key.exs
Resolves https://github.com/blockscout/blockscout/issues/10817
`address_tags` table has no primary key, which leads to the problem with ORM [usage](https://github.com/SeaQL/sea-orm/issues/485).
This PR sets `label` as a primary keyat `address_tags` table.
Chore:
- remove unused functions.
- change visibility to private for functions unused outside the module.
- add specifications and document public functions related to "Assigning tags to addresses" functionality.
- light code refactoring.
=> chore: Add primary key to address_tags table

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/migrator/sanitize_missing_token_balances.ex, apps/explorer/priv/repo/migrations/20240923135258_reset_sanitize_missing_token_balances_migration_status.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/migrator/sanitize_missing_token_balances_test.exs
An incorrect change from [this PR](https://github.com/blockscout/blockscout/pull/8617) was leaked to the master.
- Incorrect change is reverted
- Modified the `sanitize_missing_token_balances` background migration to handle affected current token balances
- Added the DB migration to reset the status of `sanitize_missing_token_balances` background migration so it will be executed again for newly emerged conditions
=> fix: Revert the deletion of deriving current token balances

apps/block_scout_web/test/block_scout_web/controllers/metrics_contoller_test.exs, apps/explorer/lib/explorer/application.ex, apps/indexer/lib/indexer/application.ex, apps/indexer/lib/indexer/prometheus/collector/filecoin_pending_address_operations_collector.ex
Resolves https://github.com/blockscout/blockscout/issues/10812
Resolves https://github.com/blockscout/blockscout/issues/10824
After merging https://github.com/blockscout/blockscout/pull/10468, metrics at `/metrics` throw error.
- Configure `Explorer.Migrator.FilecoinPendingAddressOperations` module only for `:filecoin` chain type.
- Wrap `Indexer.Prometheus.Collector.FilecoinPendingAddressOperations` definition in case of `filecoin` compile time env only.
- Add test, that /metrics endpoint returns 200 HTTP status code.
=> fix: Repair /metrics endpoint

apps/block_scout_web/lib/block_scout_web/views/api/v2/celo_view.ex, apps/explorer/lib/explorer/chain/cache/celo_core_contracts.ex, apps/explorer/lib/explorer/chain/celo/election_reward.ex, apps/explorer/lib/explorer/chain/celo/reader.ex
Closes #10785.
Include token information in API response for address epoch rewards.
=> feat: (celo) include token information in API response for address epoch rewards

apps/explorer/config/config.exs, apps/explorer/config/runtime/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/migrator/sanitize_replaced_transactions.ex
Resolves https://github.com/blockscout/blockscout/issues/8186
There was a possible race condition in case of reorg is processed at about the same time with the new block on the same height. In that case, if a new block import `fork_transactions` step was executed before the reorg's transactions are inserted, the reorg-related transactions weren't cleared and therefore reorg would have transactions. This race condition was already fixed in https://github.com/blockscout/blockscout/pull/10285 but there are still transactions in the DB that were affected by this before the fix is applied.
Added the background migration that cleans up such reorg-related transactions.
=> fix: Sanitize replaced transactions migration

apps/block_scout_web/lib/block_scout_web/graphql/celo/resolvers/token_transfer.ex, apps/block_scout_web/lib/block_scout_web/graphql/celo/resolvers/token_transfer_tx.ex, apps/block_scout_web/lib/block_scout_web/graphql/celo/schema/query_fields.ex, apps/block_scout_web/lib/block_scout_web/graphql/celo/schema/types.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/block.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/token.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/token_transfer.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/transaction.ex, apps/block_scout_web/lib/block_scout_web/graphql/schema.ex, apps/block_scout_web/lib/block_scout_web/graphql/schema/types.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/graphql.ex, apps/explorer/lib/explorer/graphql/celo.ex
Closes #10771.
1. `BlockScoutWeb.GraphQL.Schema.Transaction` has been extracted into a separate module to introduce Celo-specific fields.
2. The `Address` object has been extended with a connection field for token transfers.
3. The `TokenTransfer` object now includes additional fields for transactions and tokens.
4. A `Token` object has been introduced.
5. The `Transaction` object has been extended with a `block` field.
6. The signature of `Explorer.Chain.TokenTransfer.token_transfers_by_address_hash/4` has been refactored for cleaner use in pipe chains.
7. Resolvers have been updated with new clauses to support retrieving additional associated entities.
8. Some resolvers now use the replica database when making queries for improved performance.
1. Support for the legacy GraphQL query …
=> feat: add verbosity to GraphQL token transfers query

apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/transaction_test.exs
Revert reason remains undecoded at Redstone instance https://explorer.garnetchain.com/tx/0xc8949a914aeb985292112dd1d835195a3e97dc78acb56d7f6a02a0d227b4fee8.
Trying to find error ABI in the instance DB by revert reason 4 bytes signature and use it to decode revert reason.
=> feat: Decode revert reason based on error ABI candidates from the DB

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Related to https://github.com/blockscout/blockscout/pull/8673
Check that the `latest` block is available before filtering archive balances
=> fix: Disable archive balances only if latest block is available

apps/block_scout_web/lib/block_scout_web/graphql/middleware/api_enabled.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/address.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/block.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/helper.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/internal_transaction.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/token.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/token_transfer.ex, apps/block_scout_web/lib/block_scout_web/graphql/resolvers/transaction.ex, apps/block_scout_web/lib/block_scout_web/graphql/schema.ex, apps/explorer/lib/explorer/graphql.ex
Should be merged after #10770.
Previously, each GraphQL resolver individually checked `resolution.context.api_enabled` to handle cases where the GraphQL API was disabled for an instance. This PR centralizes that logic into a separate middleware, streamlining the code and adhering to DRY principles.
- Introduced new middleware: `BlockScoutWeb.GraphQL.Middleware.ApiEnabled`, which verifies if the GraphQL API is enabled and returns an error if not.
=> refactor: use middleware to check if GraphQL API is enabled 

.github/workflows/publish-docker-image-for-celo.yml, apps/block_scout_web/lib/block_scout_web/graphql/celo/resolvers/token_transfer.ex, apps/block_scout_web/lib/block_scout_web/graphql/celo/resolvers/token_transfer_tx.ex, apps/explorer/lib/explorer/graphql/celo.ex
Fix issue when `tokenTransferTxs` GraphQL query returned unrelated token transfers in the response.
- Change the clause for the query
- Increase `API_GRAPHQL_MAX_COMPLEXITY`
=> fix: do not include unrelated token transfers in `tokenTransferTxs`

apps/block_scout_web/lib/block_scout_web/views/api/v2/celo_view.ex
We need to display when the block appeared for Election rewards tab on Address view.
**TODO:** create task on frontend to support this change.
=> fix: add missing block timestamp in election rewards for address

apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs, apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex, apps/indexer/test/indexer/fetcher/on_demand/token_instance_metadata_refetch_test.exs
Resolves https://github.com/blockscout/blockscout/issues/10877
Remove condition that metadata initially exists for NFT metadata re-fetch functionality.
Todo: create the task for frontend team to enable "re-fetch metadata" button in such case.
=> feat: Open access to re-fetch metadata button for token instances without metadata initially fetched

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_code.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_codes.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/signed_authorization.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/address/counters.ex, apps/explorer/lib/explorer/chain/import/runner/signed_authorizations.ex, apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex, apps/explorer/lib/explorer/chain/signed_authorization.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_7702.ex, apps/explorer/lib/explorer/chain/smart_contract/proxy/models/implementation.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/counters/helper.ex, apps/explorer/lib/explorer/utility/address_contract_code_fetch_attempt.ex, apps/explorer/priv/repo/migrations/20240904161254_create_signed_authorizations.exs, apps/explorer/priv/repo/migrations/20240918104231_new_proxy_type_eip7702.exs, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex, apps/indexer/lib/indexer/transform/signed_authorizations.ex
Closes https://github.com/blockscout/blockscout/issues/10774
This PR introduces initial support for EIP-7702 transactions and EOAs with code.
* Add the `signed_authorizations` table to store authorization tuples from EIP-7702 transactions.
* Enrich authorization tuples with the authority address recovered from the signature.
* Add `authorizationList` (including recovered authorities) to the `/transactions/:tx_hash` response.
* Add `set_code_transaction` tx type for EIP-7702 transactions.
* Preload one or zero signed authorization with `authority == :address` from the database during the `/address/:address` request. This preload is used solely to determine whether fetching the code is necessary.
* Fetch the contract code in the on-demand fetcher if the address has signed authorizations
* …
=> feat: EIP-7702 support

apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs, apps/explorer/lib/explorer/chain/transaction/state_change.ex
Fix #10821
Turned out that delegatecalls does not affect coin balances, so we need to ignore them in state changes calculations
=> fix: Handle delegatecall in state changes

apps/explorer/lib/explorer/chain/import/runner.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Resolves https://github.com/blockscout/blockscout/issues/9342
- Added deletion of coin balances related to blocks that lost consensus
- Added deriving new values of `fetched_coin_balance` and `fetched_coin_balance_block_number` fields for affected addresses
=> fix: Delete incorrect coin balances on reorg

apps/explorer/lib/explorer/chain/transaction.ex
Resolve https://github.com/blockscout/blockscout/issues/10942
Filter out nil implementations from the result of `combine_proxy_implementation_addresses_map/1` function.
=> fix: filter out nil implementations from combine_proxy_implementation_addresses_map function

apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/explorer/lib/explorer/chain/address.ex
Remove deprecated single implementation property of the smart-contract from the API response.
⚠️ It should be merged after https://github.com/blockscout/frontend/issues/2209 is released.
=> chore: Remove deprecated single implementation property of the smart-contract from the API response

apps/indexer/lib/indexer/block/catchup/massive_blocks_fetcher.ex
In case of `MassiveBlocksFetcher` crashes frequently, the `Catchup.Supervisor` will be terminated when `max_restarts` reached. It means that its other children (`MissingRangesCollector` and catchup fetcher) will be terminated as well.
Handle `MassiveBlocksFetcher` exceptions so the `Catchup.Supervisor`'s children won't be unnecessary restarted.
=> fix: Handle import exceptions in MassiveBlocksFetcher

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/address/scam_badge_to_address.ex
Resolves https://github.com/blockscout/blockscout/issues/10976
Addition to https://github.com/blockscout/blockscout/pull/10763
Foreign key violation when assigning `scam` label to the address, which is not present in the `addresses` table.
If the foreign key violation error arose at the scam address assignment, insert missing addresses and then repeat the assignment.
=> fix: Process foreign key violation in the Scam addresses assignment functionality

apps/explorer/test/explorer/migrator/sanitize_duplicated_log_index_logs_test.exs
```
1) test Sanitize duplicated log index logs correctly identifies and updates duplicated log index logs (Explorer.Migrator.SanitizeDuplicatedLogIndexLogsTest)
2024-10-22T15:31:23.9863590Z ##[error]     test/explorer/migrator/sanitize_duplicated_log_index_logs_test.exs:11
2024-10-22T15:31:23.9865332Z      ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
2024-10-22T15:31:23.9865828Z 
2024-10-22T15:31:23.9866072Z          * "logs_pkey" (unique_constraint)
```
=> fix: Fix failed tests

apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
Relates to https://github.com/blockscout/blockscout/pull/10913
Add tx_count prop in the response of address API v2 endpoints for compatibility with current version of the frontend
=> fix: Add tx_count and tx_types props in the response of address API v2 endpoints for compatibility with current version of the frontend

apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex, apps/explorer/lib/explorer/chain/cache/block.ex, apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/lib/explorer/chain/cache/gas_usage.ex, apps/explorer/lib/explorer/chain/cache/pending_block_operation.ex, apps/explorer/lib/explorer/chain/cache/transaction.ex, apps/explorer/lib/explorer/chain/map_cache.ex
Fix #10787
Fix #11026
Check if async task in cache executes at the moment, delete it from cache and create a new one otherwise
=> fix: Handle stalled async task in MapCache

apps/explorer/priv/zk_sync/migrations/20241028102407_rename_tx_count_fields_zksync.exs
Finalization of https://github.com/blockscout/blockscout/pull/10913
```
{"time":"2024-10-28T10:17:43.227Z","severity":"error","message":"GenServer Indexer.Fetcher.ZkSync.TransactionBatch terminating\n** (Postgrex.Error) ERROR 42703 (undefined_column) column \"l1_transaction_count\" of relation \"zksync_transaction_batches\" does not exist\n\n    query: INSERT INTO \"zksync_transaction_batches\" AS z0 (\"timestamp\",\"number\",\"inserted_at\",\"updated_at\",\"end_block\",\"start_block\",\"l1_transaction_count\",\"l2_transaction_count\",\"root_hash\",\"l1_gas_price\",\"l2_fair_gas_price\") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (\"number\") DO UPDATE SET \"timestamp\" = EXCLUDED.timestamp, \"l1_transaction_count\" = EXCLUDED.l1_transaction_count, \"l2_transaction_count\" = …
```
=> fix: Rename zksync l1/l2 _tx_count columns

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
This PR resolves an issue with calculating token supply for CMC format by properly taking into account token decimals. Previously, we divided total_supply by $10^{18}$, regardless of the token's actual decimals, which led to incorrect values. Now, the division correctly uses $10^{\texttt{decimals}}$, aligning with the real token supply values.
- Updated token supply calculations to divide by $10^{\texttt{decimals}}$ instead of the hardcoded $10^{18}$.
- Added regression tests to ensure accurate handling of decimals in future calculations.
Additional Notes: This fix was prompted by a requirement from the Celo team, but the improvement is universally applied rather than restricted to Celo chains.
=> fix: divide by `10^decimals` when calculating token supply in CMC format

apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/main_page_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex, apps/explorer/lib/explorer/chain/advanced_filter.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/token_transfer.ex
Some API endpoints return `is_scam: true` for address, which actually is not marked as scam.
- return `is_scam: false`, if related association is not loaded `%Ecto.Association.NotLoaded{}}`.
- add `:scam_badge` association preload for address in some places in the code, where it was missing.
=> fix: Fix scam badge value in some API endpoints

apps/indexer/lib/indexer/memory/monitor.ex
`Indexer.Memory.Monitor` is started even in `api` mode even though there is no `shrinkable` processes started in this case
Don't start `Indexer.Memory.Monitor` in `api` mode
Docs update: https://github.com/blockscout/docs/pull/336
=> fix: Indexer memory limit for api instance

apps/explorer/lib/explorer/chain/import/stage/block_related.ex
Related to https://github.com/blockscout/blockscout/pull/10879
In case of reorg, coin balances are deleted in blocks runner, but coin balances runner is located before blocks runner. It means that correct coin balances will be deleted along with reorged ones.
=> fix: Import blocks before coin balances

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/ranges_helper.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex
In case when `TRACE_FIRST_BLOCK` or `TRACE_BLOCK_RANGES` env variable is present, internal transactions fetcher will add non-traceable blocks into its queue anyway, which means that it will do a lot of unnecessary work.
=> fix: Filter non-traceable blocks before inserting them to internal txs fetcher queue

apps/explorer/lib/explorer/counters/transactions_24h_stats.ex
Resolves https://github.com/blockscout/blockscout/issues/11081
Change `where` clause in the query to use `transactions.block_timestamp` instead of `blocks.timestamp` when `transactions` table denormalization finished.
Execution plan after the changes:
```
explain analyze SELECT count(t0."hash"), sum(COALESCE(t0."gas_price", b1."base_fee_per_gas" + LEAST(t0."max_priority_fee_per_gas", t0."max_fee_per_gas" - b1.
"base_fee_per_gas")) * t0."gas_used"), avg(COALESCE(t0."gas_price", b1."base_fee_per_gas" + LEAST(t0."max_priority_fee_per_gas", t0."max_fee_per_gas" - b1."base_fee_per_gas")) 
* t0."gas_used") 
FROM "transactions" AS t0 INNER JOIN "blocks" AS b1 ON b1."hash" = t0."block_hash" 
WHERE t0."block_timestamp" >= (NOW() - INTERVAL '24 hour');
QUERY PLAN …
```
=> perf: Fix performance of Explorer.Counters.Transactions24hStats.consolidate/0 function

docker-compose/README.md, docker-compose/envs/common-stats.env, docker-compose/no-services.yml, docker-compose/proxy/explorer.conf.template, docker-compose/services/nginx-explorer.yml
Add simplified docker compose config without running microservices.
With the changes it is possible to launch such setup with: `docker compose -f no-services.yml up`.
=> chore: Add docker compose file without microservices

apps/block_scout_web/lib/block_scout_web/templates/robots/sitemap.xml.eex, apps/block_scout_web/lib/block_scout_web/views/robots_view.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/ordered_cache.ex, apps/explorer/lib/explorer/chain/token.ex
Resolves https://github.com/blockscout/blockscout/issues/11134
https://eth.blockscout.com/sitemap.xml - 503
- reduce number of elements from 200 to 50
- get rid of unnecessary preloads
- optimize preloads in ordered cache: 
- sort
- trim extra elements (which are out of max_size of cache)
- and only then, do preloads
=> fix: Fix sitemap timeout; optimize OrderedCache preloads

.devcontainer/README.md, .devcontainer/devcontainer.json, .gitignore
During the use of the devcontainer VSCode feature, it was found that access to GitHub servers via SSH is re-requested if `known_hosts` on the local machine contains ambiguous records. Another issue is that it could be excessive to share all the records in the local `known_hosts` with the guest system of the devcontainer.
Instead of mounting `known_hosts` from the local machine, the file is created from scratch in the guest system with only records related to GitHub servers.
=> chore: convinient way to manage known_hosts within devcontainer

.devcontainer/bin/bs, .github/workflows/config.yml, apps/block_scout_web/test/block_scout_web/views/nft_helper_test.exs, apps/explorer/priv/repo/migrations/20230815131151_drop_logs_address_hash_foreign_key.exs, apps/explorer/priv/repo/migrations/20230816061723_drop_token_transfers_and_transactions_address_foreign_key.exs, apps/explorer/priv/repo/migrations/20230817061317_drop_address_foreign_keys.exs, apps/explorer/priv/repo/migrations/20230821120625_drop_rest_address_foreign_keys.exs, apps/explorer/priv/repo/migrations/20230831122819_drop_current_token_balances_tokens_foreign_key.exs, apps/explorer/priv/repo/migrations/20230905085809_drop_token_balances_tokens_foreign_key.exs, cspell.json
If you run `cspell --config cspell.json "**/*.ex*" "**/*.eex" "**/*.js" --gitignore`, you see errors related because cspell treats Filecoin native addresses as words.
<details>
```
apps/block_scout_web/test/block_scout_web/views/nft_helper_test.exs:15:46 - Unknown word (Fgqz)
apps/block_scout_web/test/block_scout_web/views/nft_helper_test.exs:15:57 - Unknown word (Rten)
1135/2176 apps/explorer/lib/explorer/chain/filecoin/native_address.ex 2.92ms X
apps/explorer/lib/explorer/chain/filecoin/native_address.ex:132:36 - Unknown word (fabpafjfjgqkc)
apps/explorer/lib/explorer/chain/filecoin/native_address.ex:132:50 - Unknown word (douo)
apps/explorer/lib/explorer/chain/filecoin/native_address.ex:132:55 - Unknown word (yzfug)
apps/explorer/lib/explorer/chain/filecoin/native_address.ex:132:64 - …
```
=> refactor: cspell configuration

apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
Closes #11093 
Only render total_difficulty if it is not null in the old UI.
=> fix: Handle blocks without total_difficulty in old UI

apps/explorer/lib/explorer/chain/cache/gas_price_oracle.ex, apps/explorer/test/explorer/chain/cache/gas_price_oracle_test.exs
Close #10643
Fix #9834
- Handle float from database (related to #9834) though we hadn't faced such issue on our instances
- Return 0 priority fee if there is no transactions with non-zero gas price, but base fee is present
=> feat: gas prices with base fee if no transactions

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/pending_block_operation.ex
Resolves https://github.com/blockscout/blockscout/issues/10890
Estimated count of pending block operations is not suitable for indexed internal transactions ratio calculation because it should filter out those records that belong to non-traceable blocks (lower than `TRACE_FIRST_BLOCK`).
Count pending block operations for the same blocks range that considered as **full blocks range** in `indexed_ratio_internal_transactions/0`
=> fix: Omit pbo for blocks lower than trace first block for indexing status

apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
Incompatible changes were introduced in the endpoint at https://github.com/blockscout/blockscout/pull/10913.
Temporarily return `l1_tx_hashes` into the response of /batches/da/celestia/... API endpoint until the new version of the frontend is released with the binding to new props (https://github.com/blockscout/frontend/issues/2374).
=> fix: Return `l1_tx_hashes` in the response of /batches/da/celestia/... API endpoint

apps/explorer/lib/explorer/chain/token_transfer.ex
```
==> explorer
Compiling 425 files (.ex)
warning: invalid association `token_transfers` in schema Explorer.Chain.Transaction: associated module Explorer.Chain.TokenTransfer is not an Ecto schema
lib/explorer/chain/transaction.ex:294: Explorer.Chain.Transaction (module)
```
Replace import with alias to remove compilation dependancy (I assume this is the cause of the warning)
=> chore: invalid association `token_transfers`

apps/explorer/lib/explorer/chain/address/metadata_preloader.ex, apps/explorer/lib/explorer/microservice_interfaces/metadata.ex
Copy of https://github.com/blockscout/blockscout/pull/11170 by @lok52 
Closes #10207 
Fix the issue with invalid metadata requests to the Rust microservice.
* Do not send requests to the service in case of an empty addresses batch and return a default value instead.
* Filter out invalid address hashes prior to sending the request. In the issue I provided an example with an empty string in the request. I am still not sure why this empty string is appearing, but probably `item_to_address_hash_strings` invokes `to_string` on a `nil` value somewhere.
=> fix: invalid metadata requests

apps/explorer/lib/explorer/account/api/key.ex, apps/explorer/priv/account/migrations/20241121140138_remove_abused_api_keys.exs
Fix #10389 
Wrap key insert into a transaction with lock on identity row for which key is created, this way simultaneous creation is synchronised via postgres
=> fix: handle simultaneous api key creation

apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
Changed `json_rpc_named_arguments` schema
=> fix: Fix ETH JSON RPC deriving for Stylus verification

apps/block_scout_web/test/block_scout_web/controllers/account/api/v2/user_controller_test.exs
In test we get balances with 19 decimals in API with 16 decimals, previously round was done after summation which caused error accumulation and different result of sum from API and test
=> chore: fix watchlist address flaking test

apps/explorer/lib/explorer/third_party_integrations/auth0.ex
Auth0 restricts more than 3 retries and user get such error
Handle such scenario appropriately and send a proper error
=> fix: handle excessive otp confirmations

apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/repo.ex, apps/explorer/lib/explorer/utility/replica_accessibility_manager.ex, config/runtime.exs, cspell.json
Resolves https://github.com/blockscout/blockscout/issues/8111
- Added `ReplicaAccessibilityManager` module that periodically checks the accessibility of replica and sets the result to application variable
- All requests to replica are redirected to main DB depending on the value of the mentioned variable
- Added env variable `REPLICA_MAX_LAG` (check issue for details)
Docs update: https://github.com/blockscout/docs/pull/334
=> feat: Switch DB requests from replica to master in case of replica inaccessibility

PULL_REQUEST_TEMPLATE.md
**Description:** 
I noticed a small grammatical issue in the changelog section of the documentation. The sentence "If a fixes a bug" is incorrect and should be "If it fixes a bug". This was a simple mistake where "a" was used instead of "it," which affects readability and clarity.
It's important to correct such errors to maintain professionalism and ensure that the documentation is clear and accurate for all users.
=> chore: Fix grammatical error in changelog section Update PULL_REQUEST_TEMPLATE.md

docker-compose/README.md
This change fixes a small but significant inconsistency in the documentation. The command for launching Nethermind using `docker-compose` was missing the `.yml` extension:  
```bash
docker-compose -f nethermind up -d
```  
All other examples in the same list follow the standard naming convention of including the `.yml` extension. This fix updates the command to:  
```bash
docker-compose -f nethermind.yml up -d
```  
**Why this is important:**  
1. **Consistency:** All other commands in the list use the `.yml` extension, so this fix aligns the example with the expected format.  
2. **Usability:** Without the `.yml` extension, users might encounter errors or confusion when trying to run the command. Docker Compose expects a valid configuration file name, and omitting the extension could …
=> Corrected missing .yml extension in Nethermind example

apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
- Use proper module in Application.get_env in TokenInstanceMetadataRefetch
=> fix: Wrong usage of env in TokenInstanceMetadataRefetch

apps/explorer/lib/explorer/chain/address/current_token_balance.ex
Closes #10075 
Before
```
HolderAddress,Balance
0xAee8E96bED6c5445658447fdeE8EdD12A1fD79b4,2130924.609038455654704294
0xd460Ba0BDbF8670eC6890e20119d43f9cB627129,5171
0xC56C22f97b0f91d4e3Dad5853F6f4D6A1d67377a,5091
0x5568E298A1220Ca83f018cb81f8da3B3e617e7dC,5075
0xCF744120e164A5003DB4FaF8594939f3b8228c09,5043
0xfB7a13a7A09FAcf66857c7b229B250a847FBcB59,3451.409244135902436952
0x55dFa13f7e409560eA7d774F82BDCB90C2222222,2E+3
0xD0081080Ae8493cf7340458Eaf4412030df5FEEb,1352.35182255553852181
0xC57B48e66789045973A2891492fd1F504ef03EeA,1260.190650757137264076
0xD6Fde32dBa6d4E51023cd6581b2F8E304Cbf2dca,829.873098013376209106
```
After:
```
HolderAddress,Balance
0xAee8E96bED6c5445658447fdeE8EdD12A1fD79b4,2130924.609038455654704294
0xd460Ba0BDbF8670eC6890e20119d43f9cB627129,5171.0 …
```
=> fix: Get rid of scientific notation in CSV token holders export

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex, apps/block_scout_web/lib/block_scout_web/routers/api_router.ex, apps/explorer/lib/explorer/chain/celo/election_reward.ex, apps/explorer/lib/explorer/chain/celo/reader.ex, apps/explorer/lib/explorer/chain/csv_export/celo/address_election_rewards_csv_exporter.ex, apps/indexer/test/indexer/block/fetcher_test.exs
Closes #11194, closes #11201.
The Celo community requested that validators retain the ability to export epoch transaction data when migrating to our instance. This feature is crucial for calculating earnings from participating in validator groups within the Celo protocol.
For context, the legacy Celo explorer provides a similar feature on the [validator address page](https://explorer.celo.org/mainnet/address/0xc24baeac0Fd189637112B7e33d22FfF2730aF993/epoch-transactions), where users can generate a [CSV export](https://explorer.celo.org/mainnet/csv-export?address=0xc24baeac0Fd189637112B7e33d22FfF2730aF993&type=epoch-transactions) for this data.
- Introduced a new `/api/v1/celo-election-rewards-csv` endpoint and the `AddressElectionRewardsCsvExporter` module.
**⚠️ Note**: The exported table …
=> feat: add CSV export of epoch transactions for address

apps/indexer/lib/indexer/fetcher/token_balance.ex
Should be merged after #11195. 
Closes #11205.
=> fix: `entry/1` in token balance fetcher 

apps/block_scout_web/lib/block_scout_web/application.ex, apps/explorer/lib/explorer/chain/metrics/queries.ex
Resolves https://github.com/blockscout/blockscout/issues/11339
Eliminate compile warnings related to metrics.
=> fix: Fix metrics modules warnings

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs
Closes #11239 
- Return 404 instead of 200 for nonexistent NFT
=> fix: Return 404 instead of 200 for nonexistent NFT

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
=> fix: 403 instead of 404 on wrong captcha in api/v1

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/decode_error.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
Headers are not shown in the error when Blockscout failed to decode Ethereum JSONRPC response.
Show request headers together with URL and body in the error when Blockscout failed to decode Ethereum JSONRPC response
=> chore: Show request headers in the error when Blockscout failed to decode Ethereum JSONRPC response

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex, apps/block_scout_web/lib/block_scout_web/views/account/api/v2/tags_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/internal_transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/mud_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/polygon_zkevm_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/token_transfer_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/zksync_view.ex, apps/explorer/lib/explorer/account/notifier/email.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex, apps/explorer/test/explorer/account/notifier/email_test.exs
Finalization of https://github.com/blockscout/blockscout/pull/10913
This PR finalizes work on API props renaming for consistency purposes started in #10913.
Since dependent services are bound to new props
- fronted starting from v1.36.4
- interpreter service starting from v2.1.2.
Shorthand props (old) are removed from API responses. Full props (new) are left intact.
=> chore: Remove shorthands-duplicates from API responses

.devcontainer/docker-compose.yml, .github/workflows/config.yml, docker-compose/services/db.yml, docker-compose/services/stats.yml
Migrate from Postgres 15 -> 17 version.
Docker compose setup and Github Actions workflows are affected.
=> chore: Fixate Postgres 17 version in Docker compose and Github Actions workflows

apps/explorer/lib/explorer/account/api/key.ex, apps/explorer/lib/explorer/account/custom_abi.ex, apps/explorer/lib/explorer/account/identity.ex, apps/explorer/lib/explorer/account/public_tags_request.ex, apps/explorer/lib/explorer/account/tag_address.ex, apps/explorer/lib/explorer/account/tag_transaction.ex, apps/explorer/lib/explorer/account/watchlist.ex, apps/explorer/lib/explorer/account/watchlist_address.ex, apps/explorer/priv/account/migrations/20241128100836_remove_abused_custom_abis.exs, apps/explorer/priv/account/migrations/20241204093817_remove_abused_public_tags_request.exs
Fix #11241
- Perform operations of creating `custom_abi`, `public_tags_request`, `tag_address`, `tag_transaction` and `watchlsit_address` with database lock
- Migration for `custom_abi` and `public_tags_request`
Note:
Migrations for `tag_address`, `tag_transaction` and `watchlsit_address` are omitted since the limit for them is runtime configurable and these entities actually are not so harmful, watchlsit is protected with email notification limit, `tag`s do not take much space and can be removed by hand in certain cases
=> fix: handle simultaneous account entities creation

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
If an unknown key is met in the transaction receipt, an import will fail with an error like this:
```
{"time":"2024-12-19T09:41:35.595Z","severity":"error","message":"Task #PID<0.66107815.0> started from #PID<0.66211938.0> terminating\n** (ArgumentError) Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0x91c14345a072e82ae53c3d914c84183865244a6772d992ebdb8a54921e5ef776\", \"blockNumber\" => \"0x12626020\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0x2710\", \"effectiveGasPrice\" => \"0x3178d3de133\", \"from\" => \"0xA7fa116005b79D124855dC34008b6Ebdd1f9A688\", \"gas\" => 30000, \"gasUsed\" => \"0x2710\", \"logs\" => [], \"logsBloom\" => \"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> fix: ignore unknown transaction receipt fields

apps/explorer/lib/explorer/chain/transaction.ex
This pull request corrects a typo in the `transaction.ex` file to enhance readability and maintain consistency in the documentation comments.
**Before**:
- `ane`
**After**:
- `and`
- N/A
=> Fix Typo in `transaction.ex`

apps/block_scout_web/lib/block_scout_web/controllers/api/v2/advanced_filter_controller.ex, apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
Related to https://github.com/blockscout/blockscout/pull/10913
One more property in the response in API v2 doesn't follow [new naming convention](https://github.com/blockscout/blockscout/pull/10913).
- In addition to `tx_burnt_fee` add `transaction_burnt_fee` property in transaction view. (tx_burnt_fee will be removed after frontend will bind to the new prop).
- Remove usage of `tx_types` prop - frontend is bound to `transaction_types` property.
=> chore: Rename tx_burnt_fee prop in API v2 endpoint

.devcontainer/bin/bs
While using the `bs` script, it was observed that the database is not always dropped if a tab with an active SQL connection (e.g., for running an SQL script) is open in VSCode. This issue occurs silently, meaning the failure to drop the database goes unnoticed, potentially causing unintended behavior in subsequent `bs` commands.
The `initialize_db` action in the `bs` script was updated to display the output of `mix ecto.drop` if the command fails, providing better visibility into the issue.
=> fix: interception of an error during DB drop

apps/explorer/lib/explorer/chain/token/instance.ex
Related to https://github.com/blockscout/blockscout/pull/10263
Cleanup token instance metadata on nft collection metadata refetch
This pull request includes changes to the `apps/explorer/lib/explorer/chain/token/instance.ex` file to update the attributes set when a token instance is marked for refetching. The most important changes include adding new attributes to the `set` list and initializing their values.
Updates to attributes:
* [`apps/explorer/lib/explorer/chain/token/instance.ex`](diffhunk://#diff-05c6d0bbb8f8224b1201c221d7d5d5cb24bbcbc1b78ae5d728e6ca879d4fa65cL1047-R1059): Added `thumbnails`, `media_type`, `cdn_upload_error`, `is_banned`, `retries_count`, and `refetch_after` to the `set` list and initialized their values when a token instance is marked for refetching.
=> fix: Cleanup token instance metadata on nft collection metadata refetch

apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/settlement.ex, apps/indexer/lib/indexer/fetcher/arbitrum/da/anytrust.ex, apps/indexer/lib/indexer/fetcher/arbitrum/da/celestia.ex, apps/indexer/lib/indexer/fetcher/arbitrum/da/common.ex, apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/settlement.ex
When indexing an Orbit chain that uses AnyTrust as a Data Availability (DA) solution, an issue has been identified where multiple batches within the same processing chunk can reference the same data blob, causing database import failures.
This issue prevents proper indexing of Arbitrum Orbit chains where the AnyTrust committee legitimately uses the same data blob for multiple batches. The indexing process errors out with uniqueness constraint violations:
```
GenServer Indexer.Fetcher.Arbitrum.TrackingBatchesStatuses terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time
hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
(ecto_sql 3.12.1) …
```
=> fix: implement DA record deduplication for Arbitrum batch processing
