blockscout/blockscout

.credo.exs, .formatter.exs, apps/explorer/lib/explorer/application.ex, apps/explorer_web/config/config.exs, apps/explorer_web/lib/explorer_web/application.ex, apps/explorer_web/test/explorer_web/forms/transaction_form_test.exs
Fixes #92
* Extend formatter inputs to all .ex and .exs files
* Add root configuration files like `.credo.exs` and `.formatter.exs`.
* Add `apps` files that were missed in #86.
*  Format previously missed files
=> Format missed files

apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Resolves #106 
* Remove duplicate transaction hash from the details page
Before:
After:
=> Remove transaction hash from detail page

apps/explorer/lib/explorer/exchange_rates/rate.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs, apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs
For #18, I accidentially missed two values that should have been added. This adds that values to the `Rate` struct.
=> Add missing fields for rates

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/templates/transaction/show.html.eex, apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs, apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
Fixes #151
* Orders internal transactions by index on transaction show page
* This change causes the `transaction_hash_to_internal_transactions` function to exclude an internal transaction from the results if it has no siblings in the parent transaction
* Fixes swapped "From" and "To" address information on the transaction->internal transactions page
* Fixes pagination links
=> Exclude internal transactions with no siblings in parent transaction #151

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factories/chain/transaction_factory.ex, apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex, apps/explorer_web/lib/explorer_web/router.ex, apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex, apps/explorer_web/mix.exs, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer_web/test/explorer_web/features/address_page_test.exs, apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs, apps/explorer_web/test/explorer_web/features/pages/address_page.ex, coveralls.json
Resolves #15
* Adds internal transaction tab to address page, newest first
* Adds `address_to_internal_transactions` function to Chain context
* Refactor address page tests into separate module utilizing the page module test pattern
=> Internal transactions on address #15

apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/statistics/server.ex, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/exchange_rates/source.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex, apps/explorer/lib/explorer/exchange_rates/token.ex, apps/explorer/lib/explorer/market/history/cataloger.ex, apps/explorer/lib/explorer/market/history/source.ex, apps/explorer/lib/explorer/market/history/source/crypto_compare.ex, apps/explorer/lib/explorer/market/market.ex, apps/explorer/lib/explorer/market/market_history.ex, apps/explorer/mix.exs, apps/explorer/priv/repo/migrations/20180424203101_create_market_history.exs, apps/explorer/test/explorer/chain/statistics/server_test.exs, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs, apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs, apps/explorer/test/explorer/market/history/cataloger_test.exs, apps/explorer/test/explorer/market/history/source/crypto_compare_test.exs, apps/explorer/test/explorer/market/market_test.exs, apps/explorer/test/test_helper.exs, mix.lock
Resolves #148
Historical data for the configured currency is fetched for the previous year. Once fetched, the most recent day's worth of data is fetched on a interval. Additionally, multiple coins/tokens are fetched from coinmarketcap.com for exchange rates.
* historical data is fetched for the explorer's coin and kept up to date
* multiple tokens are fetched for exchanges rates
* additional fields captured for exchange rates
* `Explorer.ExchangeRates.Rate` renamed to `Explorer.ExchangeRates.Token` to better reflect a token's values at the current point in time
=> Add Historical Data

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/controllers/address_controller.ex, apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex, apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex, apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/features/address_page_test.exs, apps/explorer_web/test/explorer_web/features/pages/address_page.ex
Resolves #142 
* Adds transaction count for all transactions to or from an address on the address overview
=> Add transaction count to address page

apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/coveralls.json, apps/explorer/lib/explorer/application.ex
Removes usage of `Mix.env/0` in application startup since it isn't available at runtime for a distillery release.
* Application startup uses Mix configuration to conditionally start children instead of relying on `Mix.env`
=> Use configuration to conditionally start processes

apps/explorer/test/explorer/chain/statistics/server_test.exs
Fixes #94
* Don't match against `Statistics.fetch()` since the `%Statistics{}` from `Server.init` was previously changed to be empty to prevent `Statistics.fetch` from timing out `init` and killing the whole supervision tree and then VM.
=> Fix flaky tests

apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/indexer/block_fetcher_test.exs, apps/explorer/test/support/factory.ex, apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Fixes #171 
* Fix intermittent test failures from autogenerated duplicate `index` values by requiring the index to be passed in as an argument
=> Require index to be passed as an argument for internal transaction factory

apps/explorer_web/lib/explorer_web/exchange_rates/usd.ex, apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex, apps/explorer_web/lib/explorer_web/views/address_view.ex, apps/explorer_web/lib/explorer_web/views/chain_view.ex, apps/explorer_web/lib/explorer_web/views/currency_helpers.ex, apps/explorer_web/lib/explorer_web/views/transaction_view.ex, apps/explorer_web/lib/explorer_web/views/wei_helpers.ex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/exchange_rates/usd_test.exs, apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs, apps/explorer_web/test/explorer_web/views/chain_view_test.exs, apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
Resolves: #165 
Old:
`1,234.003,102,702,000,000,000`
New:
`1,234.003102702`
- Use custom format for `Cldr.Number.to_string!` to remove commas in decimal and trailing zeroes
- Always show at least 2 decimal places for USD values
- Add function to create USD structs from decimal representations
=> Remove decimal commas

apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Fixes: #214 
`$$ 1,234.00 USD USD` -> `$ 1,234.00 USD`
- Remove extra `$` and extra `USD` from USD values on homepage
=> Fix USD value labels on homepage

apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Fixes #120 
In the shuffle of harmonizing the theme work and the other bugfixes, this change was lost. This restores showing the Gas Price in ether instead of wei.
=> Restore lost change to show ether instead of wei for gas price

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Fixes #187
* Include internal transactions of type `create` even when they appear alone in a parent transaction
* Add internal transaction factory for `call` type
=> Only hide "call" type internal transactions

apps/explorer_web/config/prod.exs
Resolves #226 
During AWS deployment `pubsub` is causing a Redis dependency unnecessarily. Removing this will solve this issue.
=> Remove pubsub from explorer_web application

apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex, apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
Fixes #242 
* Fix Block Details page not displaying all transactions for the block (it was filtering out contract creation transactions without a `to` address)
=> Mark to_address_hash as optional association on block->transactions page

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/indexer/block_fetcher.ex, apps/explorer/lib/explorer/indexer/sequence.ex, apps/explorer/test/explorer/indexer/block_fetcher_test.exs, apps/explorer/test/explorer/indexer/sequence_test.exs, coveralls.json
Resolves #245
*  Extract common request code.
* Reverse the genesis index order as most users will care about recent blocks as opposed to the very beginning of the chain.  This should shorten the Time-to-Usefulness.
* `handle_get_block_by_number` handles the result from both `fetch_blocks_by_number` AND `fetch_blocks_by_number`, so it isn't handling just the `_by_number` result and is a misnomer.
* Remove unused `eth_*Filter` functions
=> Index from latest to genesis

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/paging_options.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/controller.ex, apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex, apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex, apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/views/address_view.ex, apps/explorer_web/lib/explorer_web/views/error_view.ex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs, apps/explorer_web/test/explorer_web/views/error_view_test.exs
Resolves #200 
* Fix paging
* Remove unnecessary joins by switching to `block_number` and `index` for paging instead of `hash` and using information already in the transactions table
Here are the before and after representative queries and plans for the transactions query:
Before:
```sql
SELECT t0."hash", t0."block_number", t0."cumulative_gas_used", t0."gas", t0."gas_price", t0."gas_used", t0."index", t0."internal_transactions_indexed_at", t0."input", t0."nonce", t0."public_key", t0."r", t0."s", t0."standard_v", t0."status", t0."v", t0."value", t0."inserted_at", t0."updated_at", t0."block_hash", t0."from_address_hash", t0."to_address_hash", b4."hash", b4."difficulty", b4."gas_limit", b4."gas_used", b4."nonce", b4."number", b4."size", b4."timestamp", b4."total_difficulty", …
```
=> Improve paging query #200

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/indexer.ex, apps/explorer/lib/explorer/indexer/address_extraction.ex, apps/explorer/lib/explorer/indexer/block_fetcher.ex, apps/explorer/lib/explorer/indexer/internal_transaction_fetcher.ex, apps/explorer/lib/explorer/indexer/pending_transaction_fetcher.ex, apps/explorer/lib/explorer/indexer/supervisor.ex, apps/explorer/test/explorer/indexer/address_extraction_test.exs, apps/explorer/test/explorer/indexer/block_fetcher_test.exs, apps/explorer/test/explorer/indexer/internal_transaction_fetcher_test.exs, apps/explorer/test/explorer/indexer/pending_transaction_fetcher_test.exs, apps/explorer/test/support/data_case.ex, apps/explorer/test/support/factory.ex, coveralls.json
Resolves #250
* Document `AddressExtraction.extract_addresses`.
* Use `EthereumJSONRPC.request/1` in `EthereumJSONRPC.Parity`.
* Rename `Indexer.BlockFetcher.monitor_task` to `Indexer.start_monitor` and make it public, so that all `*Fetcher`s can use it.
*  Check for required `timestamps` option as soon as possible as not including timestamps is a developer error, so it should be caught as soon as possible to allow the code to be fixed in development.
* Use `parity_pendingTransactions` JSONRPC to get the pending transactions and import them.  If they conflict with pre-existing transactions, then the previous transactions win, under the assumption that sometimes pending transactions repository transaction will `COMMIT` after the the
realtime index has `COMMIT`ed that same transaction being …
=> Index pending transactions

apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex, apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex, apps/explorer_web/lib/explorer_web/views/address_contract_view.ex, apps/explorer_web/mix.exs, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
#69
Shows the Smart Contract details at the `Code` tab, once it is verified.
=> Add Smart Contract details when verified

apps/explorer/lib/explorer/chain.ex, apps/explorer_web/lib/explorer_web/controllers/pending_transaction_controller.ex, apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex, apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex, apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs, apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
Resolves #251 
* Use statistics table to get estimated count of total transactions
=> Use table statistics estimate for total transaction

apps/explorer_web/assets/css/components/_address_link.scss, apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
Fixes #268 and #260 
Increase the number of characters in the address to 12 and remove the icon when an address is not a contract. It's very difficult to see the difference between an address icon and file icon.
=> Increase characters in address and remove address icon

README.md
This PR adds a notification at the `readme` file, warning about a `Solidity` dependency we now have to run our tests.
=> Add note at readme noticing the Solidity dependency

apps/explorer_web/mix.exs, mix.lock
=> Upgrade gettext dependency

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/statistics.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs, apps/explorer_web/test/explorer_web/features/pages/address_page.ex, apps/explorer_web/test/explorer_web/features/pages/block_page.ex, apps/explorer_web/test/explorer_web/features/pages/home_page.ex, apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex, apps/explorer_web/test/explorer_web/features/pages/transaction_page.ex, apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs, apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs, apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Resolves #241 
* When transaction contains a contract creation, the to field contains the contract address
=> Display contract create address #241

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/repo.ex, apps/explorer/test/explorer/buffered_task_test.exs, apps/explorer/test/explorer/repo_test.exs, coveralls.json
Fixes #270
* Include a `doctest` for `Explorer.Chain.import_blocks` that shows the same options can be imported twice without error as a regression test for #270.
* `rescue` all exception from `c:Ecto.Repo.insert_all/3` inside of `Explorer.Repo.safe_insert_all/3`, so that the schema, chunk, and options can be logged as an error, which makes it easier to figure out why the `Postgrex.Error` was raised and we can reproduce the exact data in regression tests.
* Use `conflict_target` and `on_conflict` to allow upserts of `internal_transactions` like all other tables in `insert_internal_transactions`.
* Increase receive timeout for BufferedTask crash retry because test is flaky on CI with the default 100ms timeout.
=>  on_conflict for insert_internal_transactions

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Solves https://github.com/poanetwork/poa-explorer/issues/263
There is a bug when an Address is a Contract one, it is not showing the Code tab.
This happened because we separated the `InternalTransaction` creation in an asynchronous operation, so when we create an `Address` we are no longer creating an `InternalTransaction` and we no longer have the `contract_code`at this moment.
In the `InternalTransactionFetcher` we use a function called `ecto_schema_module_to_changes_list_to_multi` that runs multiples inserts operations inside a `Ecto.Multi` but since our address is already created the `contract_code` wasn't being saved at the database.
This PRs adds alters the `on_conflict` in the `insert_addresses` so we make sure to update all `Addresses` with its `contract_code`
=> Fix Contract address not showing code tab

.circleci/config.yml, .tool-versions
Fix for
```
Starting container circleci/elixir:1.6.4-node-browsers
image cache not found on this host, downloading circleci/elixir:1.6.4-node-browsers
Error response from daemon: manifest for circleci/elixir:1.6.4-node-browsers not found
```
=> Update CircleCI to Elixir 1.6.5

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/supply.ex, apps/explorer/lib/explorer/chain/supply/proof_of_authority.ex, apps/explorer/test/explorer/chain/supply/proof_of_authority_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/controllers/api/v1/supply_controller.ex, apps/explorer_web/lib/explorer_web/router.ex, apps/explorer_web/lib/explorer_web/views/api/v1/supply_view.ex, apps/explorer_web/test/explorer_web/controllers/api/v1/supply_controller_test.exs
Resolves #225.
This PR adds API for calculating the total supply and circulating supply for a given coin. Each coin that adopts the explorer will need to implement the `Explorer.Chain.Supply` behavior and use its implementation for retrieving those values. For now, the explorer will default to using POA's implementation.
This PR also exposes a new route of `/api/v1` for an initial implantation of an explorer API. This allows for easier versioning going forward. If we want some sort of wrapper that includes extra data as part of any request, we will to create a ticket and discuss that shape.
The endpoint at `/api/v1/supply` will return a simple response in the format of:
```json
{
"total_supply": 123,
"circulating_supply": 100
}
```
=> Add API for getting total/circulating supply values

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md
Fixes #294 
An alternative proposal to #295.  This uses both `CONTRIBUTING.md` and `PULL_REQUEST_TEMPLATE.md` to put things that need to happen before you click Open Pull Request or that can't be done by `PULL_REQUEST_TEMPLATE.md`, such as setting the Title in `CONTRIBUTING.md` while `PULL_REQUEST_TEMPLATE.md` is limited to just the pre-filled Description for Pull Requests with italics (using `*words*`) place holder text explaining each section, which I think will be easier to use quickly as opposed to a check list where you need to generate the sections yourself and then delete the checkboxes.
* Add `CONTRIBUTING.md` with steps to do before the `PULL_REQUEST_TEMPLATE.md` populates the Pull Request form.
* Add `PULL_REQUEST_TEMPLATE.md` to pre-populate description for new Pull Requests.
* …
=> CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md

.circleci/config.yml
CircleCI `test` job is [broke](https://circleci.com/gh/poanetwork/poa-explorer/7043) as it cannot find `Bcrypt` function. 
* Rotate cache keys to cache bcrypt
=> Rotate cache keys to cache bcrypt

.circleci/config.yml
Build is still failing to find `Bcrypt`, but only on CircleCI.
* `_build symlinks` into `deps`, such as for the `priv` directory, which can contain compile NIF shared libraries, so for `_build` to be a complete cache, it needs `deps`.  As using the same directory for two caches leads to other classes of bugs, get rid of the the `mix-deps-get` cache and only have the `mix-compile` cache for `mix deps.get` and `mix compile`.
=> Cache deps with _build

apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/views/internal_transaction_view.ex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/views/internal_transaction_view_test.exs
Fixes #296
* Displays internal transaction `type` correctly on transaction page
* Displays Contract Creation link correctly on transaction->internal transactions and address->internal transactions pages
=> Show correct internal transaction type and contract link

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
Fixes #314
* Parity 1.11.4 sends a `removed` flag of whether a transaction was removed or not in the transaction receipt that was not sent in 1.10.6. As the flag value is already `true` or `false`, no conversion is
necessary when converting to Elixir.
You MUST upgrade to this version to maintain compatibility with the Sokol nodes currently on `sokol.poa.network`, which have been upgraded to Parity 1.11.4 to fix a bug in Parity itself.
=> Pass through removed flag for logs

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs, apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex, apps/explorer/test/explorer/indexer/address_balance_fetcher_test.exs, coveralls.json
Fixes #309
* Regression test for #309
* `AddressBalanceFetcher` uses max `block_quantity` for `hash_data` in batches passed to `run/2` to eliminate duplicate address hashes in one `ON CONFLICT DO UPDATE`.
*  Convert `eth_getBalance` error responses to `:error` tuple.
=> `AddressBalanceFetcher` uses max `block_quantity` for `hash_data` in batches

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs, apps/explorer/test/explorer/chain/statistics/server_test.exs, coveralls.json
Fixes #254
* When status 413 Request Entity Too Large is returned from JSONRPC, we can split the batch in half and try again.  Continuing to break up the chunks of the batch until we succeed or hit 1 request in the chunk, in which case we still need to error.
* Use `:capture_log` `@moduletag` to quiet `Statistics.Server` shutdown during tests.
=> Rechunk batch JSONRPC request when 413 is returned

apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Fixes #321 
Internal transactions on the transaction details page show how much gas was used by each event of the parent transaction. Right now we are displaying `gas limit` which is incorrect.
Changed the `gettext` to `Gas Used` from `Gas Limit`
=> Rename Gas Limit to Gas Used on Internal Transactions

apps/explorer/lib/explorer/chain.ex, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
Resolves #297 
* Display parent transaction/internal transaction on contract address page
* Don't display table headers when no transactions exist on address page
* Ensure transaction count includes contract creation transactions
=> Bug fix transactions not populating #297

apps/explorer/lib/explorer/chain/statistics.ex, apps/explorer_web/assets/js/app.js, apps/explorer_web/assets/js/lib/from_now.js, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/block/index.html.eex, apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex, apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex, apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex, apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/block_view.ex, apps/explorer_web/lib/explorer_web/views/pending_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/transaction_view.ex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #313
This will make sure as we live-update lists across the app we don't let ages get stale, which would result in full pages of `1 second ago`s that were live inserted.
- Calculate ages using Javascript every 1000ms and update the DOM accordingly.
- We were using `Timex.from_now` which does not get localized. The moment equivalent this PR transitions to does get localized.
- I've done the most basic of performance optimizations and tested with a page size of 10k. Everything seems to be fine.
=> Update ages in real-time

apps/explorer/lib/explorer/chain/statistics.ex, apps/explorer/priv/repo/migrations/20180626143840_add_inserted_at_index_to_blocks.exs, apps/explorer/test/explorer/chain/statistics_test.exs
Fixes #330 
Anecdotal performance change in development: page response time from > 15 seconds (timeout) to average response time < 20ms (see "Optimization Details" section for more specific information)
* Removes unused queries in `Explorer.Chain.Statistics` that accounted for 17s (exceeding the timeout) of wall time 
* Optimizes slow average block time query by limiting result set that window function uses to calculate average block time
* Optimizes slow velocity query by indexing `inserted_at` on `blocks`
Before: 
Query
```sql
SELECT timestamp - lag(timestamp) over (order by timestamp) as difference
FROM blocks
ORDER BY number DESC
LIMIT 100
```
Query Plan
```
Limit  (cost=378073.38..378073.63 rows=100 width=32) (actual time=4071.147..4071.178 rows=100 loops=1)
->  Sort …
```
=> Fix homepage timeout #330

apps/explorer/lib/explorer/chain/statistics.ex, apps/explorer/test/explorer/chain/statistics_test.exs
Fixes #330 
* Remove unused blocks per minute query
* Remove unused lag query
* Avoid table lookups for transactions per minute count query by selecting `inserted_at` column in index
Before:
Query
```sql
SELECT count(transactions.hash)
FROM transactions
WHERE transactions.inserted_at > NOW() - interval '1 minute'
```
Query Plan
```
Aggregate  (cost=138034.35..138034.36 rows=1 width=8) (actual time=221.715..221.715 rows=1 loops=1)
->  Bitmap Heap Scan on transactions  (cost=4053.99..137676.42 rows=143169 width=33) (actual time=27.196..200.698 rows=145075 loops=1)
Recheck Cond: (inserted_at > (now() - '00:01:00'::interval))
Heap Blocks: exact=22256
->  Bitmap Index Scan on transactions_inserted_at_index  (cost=0.00..4018.20 rows=143169 width=0) (actual time=23.933..23.933 rows=145075 …
```
=> More home page query optimizations

README.md
Change `LGPLv3` to `GPLv3` in README.md to reflect the correct license.
=> Update Readme fix LGPLv3 to GPLv3

.tool-versions, README.md, apps/explorer_web/assets/package-lock.json
* Clean up project requirements to make sure we are all running on the same versions. It became apparent through `package-lock.json` diffs after running `npm install` that we were running on different versions of NPM. While cleaning up this issue I came across a few other discrepancies.
* Upgraded Node version
* Removed unused Ruby dependency
* Made sure requirement versions in `README.md` matched the versions specified in `.tool-versions`
* Upgraded `package-lock.json` in `explorer_web` to NPM v6 format
* If you have installed PhantomJS using `npm install -g phantomjs-prebuilt` you will need to re-install it once you upgrade Node in order for `explorer_web` tests to pass
=> Upgrade and clean up project requirements

apps/explorer/package-lock.json
* The `apps/explorer` Node.js dependencies are not updated with the currently defined Node.js version in the project (`10.05`). This is similar to https://github.com/poanetwork/poa-explorer/pull/352.
* Run `npm install` with Node.js 10.5 inside `apps/explorer`.
=> Upgrade explorer Node.js dependencies to 10.5

apps/explorer_web/assets/package-lock.json, apps/explorer_web/assets/package.json
Now that https://github.com/sass/node-sass/issues/2355 is closed we can upgrade `node-sass` in order to resolve the `hoek` vulnerability.
=> Upgrade node-sass to quiet npm warnings it was generating

apps/indexer/lib/indexer/block_fetcher.ex
Fixes #332
Getting the last indexed block number seems to solve the problem. 
I have a few suspects of what has caused the bug but I lack comprehension from the Indexer most particular rules (mostly the Sequence).
I'd like to understand better what caused it before merging, but we can move on since this is a critical bug. 
After this, I'll start exploring #341 and I believe I would be more capable of explaining what happened here and write a few tests for this behavior.
=> Real-time indexing starting from the last indexed Block

apps/indexer/lib/indexer/block_fetcher.ex
We're defining the real-time interval to 5 seconds instead of 10 seconds. 👍
=> Set realtime interval to 5 seconds

.circleci/config.yml
`js/**/*.js` was not running eslint on files nested with extra nesting. `js/**` is what we have in `package.json` which works with everything so we should stick with that.
=> Fix eslint in CircleCI which was not running on everything it should

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
Fixes #367
Fixes #383
* Fixes the transaction details page when a transaction has multiple internal transactions of type create
* Fixes contract address page showing parent transaction with non-matching to and from addresses
=> Fix multiple results in Repo.One with multiple create type internal transactions

apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/lib/indexer/sequence.ex, apps/indexer/test/indexer/block_fetcher_test.exs, apps/indexer/test/indexer/sequence_test.exs
Fixes #387
* The previous `mode` is returned when you `Indexer.Sequence.cap` a sequence, so you can tell what mode you were in before without having to make a separate call to the sequence.
* `Indexer.Sequence.start_link` spawned processes now clean up themselves even when the calling process exits `:normal` in addition to the previous cleanup on crashes. 
* The change in #357 was broken because it did not work when the database was empty, so it has been reverted as it prevented testing this PR.  The realtime indexer will not fill holes.  The genesis task will be rewritten to fill holes in a later PR.
* `Indexer.Sequence.cap` returns the previous `mode` (`:infinite` or `:finite`) instead of `:ok`.
=> Convert Indexer.Sequence to GenServer to trap exits to ensure self-cleanup

apps/explorer/lib/explorer/chain.ex
Fixes #391 
* Changes reference from `Explorer.Chain.Hash.Truncated` to `Explorer.Chain.Hash.Address`
=> Change reference to Hash.Address

apps/indexer/lib/indexer/application.ex
We are facing this error when starting the `Indexer`:
```
** (EXIT) an exception was raised:
** (ArgumentError) :json_rpc_named_arguments must be provided to `Elixir.Indexer.InternalTransactionFetcher.child_spec to allow for json_rpc calls when running.
```
It was missing the `json_rpc_named_arguments` to `InternalTransactionFetcher` children.
Original PR https://github.com/poanetwork/poa-explorer/pull/384
=> Fix Indexer Supervisor tree

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex, apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/address_contract_controller_test.exs, apps/explorer_web/test/explorer_web/features/pages/address_page.ex, apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
This PR is about https://github.com/poanetwork/poa-explorer/issues/303
It adds a link that shows who created the contract and a link to the transaction id, though these links will be shown just when the account details page is a smart contract.
- A contract created by some user.
- A contract created by another contract, in this case, the creator link will send the user to contract creator and the transaction that created the contract.*
=> Add contract creator on Account details page

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex, apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex, apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* Currently, the API account balance endpoint allows users to get the
ether balance for a single address. This commit introduces support for
getting the ether balance for multiple addresses (maximum of 20) in a
single batch.
* Issue link: https://github.com/poanetwork/poa-explorer/issues/138
* Adding `Chain.hashes_to_addresses/1` to get multiple addresses from
the DB, given a list of hashes.
* Editing `balance/2` in `API.RPC.AddressController` to support multiple
addresses. Previously it only supported a single address.
* Editing `API.RPC.AddressView` to handle a single address differently than
multiple addresses. This is to mimic Etherscan's API.
* n/a
* n/a
* n/a
=> Enhance API account balance endpoint

apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex, apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex, apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* After a first iteration of the account balance  API endpoint was
merged into master, we noticed Etherscan has a separate action for
getting the Ether balance of multiple addresses in a single call:
`action=balancemulti`. This commit adds support for this action.
* Issue link: https://github.com/poanetwork/poa-explorer/issues/138
* Editing `API.RPC.AddressControllerTest` to have coverage for
`action=balancemulti` calls and make sure `action=balance` works as we'd
like when multiple addresses are given.
* Adding `balancemulti/2` to `API.RPC.AddressController`.
* n/a
* n/a
* n/a
=> Add RPC API account balancemulti

apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/lib/indexer/sequence.ex, apps/indexer/test/indexer/block_fetcher_test.exs, apps/indexer/test/indexer/sequence_test.exs
Resolves #340
* Regression tests for #340.
* Move `chunk_ranges` from `BlockFetcher` to `Sequence` as this will guarantee that any caller of `Sequence.start_link` or `Sequence.inject_range` ends up queuing chunked ranges.
* Cap genesis sequence immediately, to indicate we don't really want infinite ranges after all the missing blocks are found, it will stop at `0` anyway.
* Fix [off-by-one error](https://en.wikipedia.org/wiki/Off-by-one_error)s in `BlockFetcher.chunk_ranges`.
* Fix `chunk_ranges` for descending ranges.  
* Return error from `Sequence.start_link` if `:first` would cause a retraversal.  Retraversal occurs when `first` was set to the `latest_block_number` and the `step` was negative because the `prefix` of the missing block numbers which are all `<= latest_block_number` …
=> Fix chunking issues with BlockFetcher and Sequence

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs, apps/explorer/config/dev.exs, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs, apps/explorer_web/assets/css/app.scss, apps/explorer_web/assets/js/app.js, apps/explorer_web/assets/js/lib/smart_contract/read_function.js, apps/explorer_web/assets/package-lock.json, apps/explorer_web/config/test.exs, apps/explorer_web/lib/explorer_web/controllers/address_read_contract_controller.ex, apps/explorer_web/lib/explorer_web/router.ex, apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_read_contract/_function_response.html.eex, apps/explorer_web/lib/explorer_web/templates/address_read_contract/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/views/address_contract_view.ex, apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/address_read_contract_view.ex, apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/address_view.ex, apps/explorer_web/package-lock.json, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/controllers/address_read_contract_controller_test.exs, apps/explorer_web/test/explorer_web/features/address_read_contract_test.exs, apps/explorer_web/test/explorer_web/views/address_read_contract_view_test.exs, apps/explorer_web/test/explorer_web/views/address_view_test.exs
This PR is part of the #70 issue, it adds a page to read the smart contract functions.
**TODO**
=> Add 'Read Smart Contract' page

apps/explorer_web/assets/css/_typography.scss, apps/explorer_web/assets/css/components/_tile.scss, apps/explorer_web/assets/css/theme/_poa_variables.scss, apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex, apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex, apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex, apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/chain_view.ex, apps/explorer_web/lib/explorer_web/views/pending_transaction_view.ex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/features/pages/address_page.ex, apps/explorer_web/test/explorer_web/features/pages/block_page.ex, apps/explorer_web/test/explorer_web/features/pages/home_page.ex, apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex, apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs, apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs, apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
resolves #368 
resolves #400 
Visually show the current status of a given transaction. Current statuses are Success, Pending, Failed and Out of Gas. Failed and Out of Gas transactions are given a colored border to call attention to them. Transaction statuses will also live update as blocks are validated.
* Added a text label that describes the transaction's status
* Added a colored border to call attention to Failed and Out of Gase transactions
=> Add transaction status indicator

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
Fixes #418
* Under the assumption that gateway timeouts occur because it is taking too long for Sokol nodes to respond to batch requests, 504 Gateway Timeout should be treated the same as 413 Request Entity Too Large: the batch should be split in half and retried.
If we still get 504 Gateway Timeouts after this change, we'll need to
add a delay before retry.
=> Split batches on 504 Gateway Timeout

apps/explorer_web/assets/css/components/_dashboard-banner.scss
I want to resolve issue #405 
When open the homepage and click in *Mainnet* dropdown the network stats block the button click event.
Decreases *.dashboard-banner* *z-index* from 10 to 9. 
I've tested in other pages looks ok
=> Fix dropdown overlaps on homepage.

apps/explorer_web/.sobelow-conf, apps/explorer_web/lib/explorer_web/csp_header.ex, apps/explorer_web/lib/explorer_web/router.ex
Resolves #414
- Fix CSP to allow connection to the explorer_web websocket endpoint in order to support live updates.
=> Dynamically add websocket endpoint to CSP

.credo.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs, apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex, apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex, apps/explorer_web/lib/explorer_web/views/api/rpc/rpc_view.ex, apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* For users to be able to get the transactions for a given address hash.
Support for optional parameters will be added in an upcoming PR.
* Issue link: https://github.com/poanetwork/poa-explorer/issues/138
* Adding `Explorer.Etherscan` context, where we want to keep
etherscan-only logic within the Explorer app. This is because we want to
mimic the way their RPC API works. The only function in this module for
now is `list_transactions/1`, which gets all transactions for a given
address hash.
* Adding `txlist/2` action to `API.RPC.AddressController`, to handle
account transactions requests.
Example usage:
```
api?module=account&action=txlist \
&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a
```
* Editing `API.RPC.AddressView` and `API.RPC.RPCView` to format
responses for new API …
=> Add account transactions API RPC endpoint

apps/explorer/test/support/factory.ex, apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
Fixes #434 
* Fix flaky test by creating the internal transaction needed to display the contract page
=> Set up contract verification test with `create` internal transaction

apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20180606135149_create_tokens.exs, apps/explorer/priv/repo/migrations/20180606135150_create_token_transfers.exs, apps/explorer/test/support/factory.ex
It contains the modeling definition and factories of both entities that will be indexed after PR #334 (which where they came from originally ❤️).
We're breaking it in this PR since they're are the only dependencies for the front-end Token features. By doing this we'll be able to improve these issues workflow since we wouldn't need to rebase our PRs in a WIP.
The issues that have a dependency on it can be seen here: https://github.com/poanetwork/poa-explorer/projects/3?card_filter_query=label%3Atokens
=> Add Token and TokenTransfers schema

README.md, apps/explorer/config/test.exs, apps/explorer/config/test.secret.exs.example
Some local development environments run postgres on a non-standard port. The dev.secret.exs allows for that port to be overridden, but there's not a similar way to override the test environment. This PR allows the test environment to be overridden as well.
* Allow local test environment configuration overrides via an optional `explorer/config/test.secret.exs`.
=> Allow test environment configuration to be overridden similar to dev

apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs, apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex, apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* For users to be able to specify optional params to the API RPC account
transactions (action=txlist) endpoint.
Example usage:
```
/api?module=account&action=txlist \
&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a \
&startblock=100&endblock=150&page=1&offset=10&sort=asc
```
* Issue link: https://github.com/poanetwork/poa-explorer/issues/138
* Editing `Explorer.Etherscan.list_transactions/2` to support
`order_by_direction`, `page_number`, `page_size`, `start_block`, and
`end_block` options.
* Editing `API.RPC.AddressController` to support 'sort', 'page',
'offset', 'startblock', and 'endblock' params. Mimics Etherscan's API.
When the optional params are not provided we return a max of 10,000
transactions, order by block number in ascending order, and target all
blocks.
* n/a
* n/a
* …
=> Add optional params to account txlist API endpoint

apps/indexer/config/prod.exs
Import `prod` config file at the `indexer/config/prod.exs` instead of `dev`
=> Fix prod config file to use prod config instead of dev

apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Fixes #450 
Facebook and Instagram are not used by POA Network.  Github is a social link POA would like to promote.
- fixed Telegram link, was linking to Twitter
- removed social links to Facebook and Instagram
- added Github social link
=> Fixed social media links

apps/explorer_web/lib/explorer_web/application.ex
Resolves: #455 
* This is a quick fix to resolve the memory leak for now. The long-term solution is to do both of the following:
* Only send events to the client that originated in the realtime indexer.
* Optimize n+1 query to `Chain.hash_to_transaction` in the Notifier.
* Suppress memory leak caused by EventHandler.
=> Disable EventHandler (live updates) because of memory leak

apps/explorer/config/test.exs, apps/explorer_web/lib/explorer_web/notifier.ex, apps/indexer/config/dev/geth.exs, apps/indexer/config/dev/parity.exs, apps/indexer/config/prod/geth.exs, apps/indexer/config/prod/parity.exs, apps/indexer/lib/indexer.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/lib/indexer/bound_interval.ex, apps/indexer/lib/indexer/pending_transaction_fetcher.ex, apps/indexer/test/indexer/block_fetcher_test.exs
Fixes #421 
Fixes #453
* Remove need for `Indexer.start_monitor` by using `Task.Supervisor.async_nolink` because `Task.Supervisor.async_nolink` monitors the `Task` pid instead of linking, so it does the same thing as our `Indexer.start_monitor`.
* When a catchup_index task completes without error, increase the interval until the next check by 2 if no blocks were missing and decrease it by 2 if blocks were missing.  Minimum interval is the same as the realtime interval while the maximum interval is arbitarily chosen to be 10x the
realtime interval.
* `block_rate` is measured in milliseconds / block, but a rate would blocks / unit-of-time, so rename `block_rate` to `block_interval` to reflect it is the interval between blocks.
* The `realtime_interval` should be half of the `block_interval` …
=> Prevent holes and fill in holes during realtime indexing

.circleci/config.yml
Fixes #461
*NOTE*: This PR is purposely coming from a fork to test the fix.
* For fork PRs, `COVERALLS_REPO_TOKEN` is not set, so `mix coveralls.circle` fails to upload the results, which breaks the build. On forks, use `mix coveralls.html` instead, since it does not submit
the report, but will leave `cover/excoveralls.html`, which is stored as an artifact.
=> Don't submit test results to coveralls.ios for forks

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer_web/lib/explorer_web/application.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/test/indexer/block_fetcher_test.exs
Part 1: #460 
When initially indexing a chain, the event_handler genserver gets overloaded by trying to call Repo fetches for blocks/transactions published from historically indexed blocks.
* Only broadcast :realtime_indexer events to the channel and pass other events through as a no-op
=> Subscribe to only realtime-indexer events for channel broadcasts

apps/explorer/config/dev.exs, apps/explorer/config/dev/geth.exs, apps/explorer/config/prod.exs, apps/explorer/config/prod/geth.exs, apps/indexer/config/dev.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/prod.exs, apps/indexer/config/prod/geth.exs
Related to #183 
Allow switching the variant and URL for developing against Geth without changing the config files under source control.
* Environment variables (`ETHEREUM_JSONRPC_VARIANT` and `ETHEREUM_JSONRPC_URL`) used for testing Geth now work in `dev` too.  You can now switch to Geth by setting `ETHEREUM_JSONRPC_VARIANT=EthereumJSONRC.Geth` and its URL `ETHEREUM_JSONRPC_URL=https://...`.
=> geth configureable from environment

apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex, apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex, apps/explorer_web/lib/explorer_web/templates/block_transaction/_transaction.html.eex, apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex, apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex, apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/_internal_transaction.html.eex
Resolves: #474 
* Force the To and From addresses on the transaction tiles to stay on one line and not wrap to maintain layout consistency.
=> Fix transaction addresses wrapping onto two lines

apps/indexer/lib/indexer/block_fetcher/catchup.ex
* Fixes rebase during #366  picking wrong version with broadcasting turned on for catchup index, which we don't want
=> Restore don't broadcast from catchup

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan_test.exs, apps/explorer/test/explorer/import_test.exs, apps/explorer/test/support/factory.ex, apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs, apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs, apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs, apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Resolves #430 
Fixes #477 
* Fixes timeout issue on address transactions list
* Removed expensive left join or subselect queries that impacted the load time of the address page due to fetching the created_contract_address_hash from internal_transaction for display on the transactions cards
* This adds a denormalized transactions.created_contract_address_hash column
* Since there's a change to the indexer and a new column, you'll need to drop and re-run the indexer:
```
mix do ecto.drop, ecto.create, ecto.migrate
```
```sql
EXPLAIN ANALYZE
SELECT t0."hash", t0."block_number", t0."cumulative_gas_used", t0."gas", t0."gas_price", t0."gas_used", t0."index", t0."internal_transactions_indexed_at", t0."input", t0."nonce", t0."r", t0."s", t0."status", t0."v", t0."value", t0."inserted_at", …
```
=> Denormalize contract creation address on transaction

apps/explorer_web/assets/css/app.scss, apps/explorer_web/assets/css/components/_card.scss, apps/explorer_web/assets/css/components/_nounderline-link.scss, apps/explorer_web/assets/css/components/_tile.scss, apps/explorer_web/assets/js/app.js, apps/explorer_web/assets/js/lib/pretty_json.js, apps/explorer_web/assets/js/lib/try_api.js, apps/explorer_web/lib/explorer_web/controllers/api_docs_controller.ex, apps/explorer_web/lib/explorer_web/etherscan.ex, apps/explorer_web/lib/explorer_web/router.ex, apps/explorer_web/lib/explorer_web/templates/api_docs/_action_tile.html.eex, apps/explorer_web/lib/explorer_web/templates/api_docs/_model_table.html.eex, apps/explorer_web/lib/explorer_web/templates/api_docs/_module_card.html.eex, apps/explorer_web/lib/explorer_web/templates/api_docs/index.html.eex, apps/explorer_web/lib/explorer_web/views/api_docs_view.ex, apps/explorer_web/test/explorer_web/controllers/api_docs_controller_test.exs
closes #454 
* We'd like to provide an API documentation page with a 'Try it out' UI
for the API. We first considered using Swagger for this but when we
looked into it we realized it didn't fit our needs. It doesn't fit our
needs because Swagger is an API specification and the Swagger UI is
built for this specification. The Etherscan-compatible API we're
building doesn't meet the Swagger specification (name was changed to
OpenAPI on the latest version) so we can't easily use Swagger tools to
document our API.
* Issue link: https://github.com/poanetwork/poa-explorer/issues/454
* Adding API documentation page with 'Try it out' UI at `/api_docs`. The
API documentation data is defined within `ExplorerWeb.Etherscan` and
rendered by Phoenix templates, with partial templates for 'module
cards', …
=> Adds API docs page with 'try it' UI

apps/explorer_web/lib/explorer_web.ex, apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex, apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex, apps/explorer_web/lib/explorer_web/views/currency_helpers.ex, apps/explorer_web/lib/explorer_web/views/token_helpers.ex, apps/explorer_web/test/explorer_web/views/address_transaction_view_test.exs, apps/explorer_web/test/explorer_web/views/currency_helpers_test.exs, apps/explorer_web/test/explorer_web/views/token_helpers_test.exs
Resolves https://github.com/poanetwork/poa-explorer/issues/494
* Token transfers amount will be displayed according to the tokens' type. If the token is `ERC-721` a string with the `token_id` will be displayed instead.
* Handle possibles amount of token transfers nil, token's decimals nil and token's symbol nil.
* Consider thousands separator in the token's amount.
* ERC-721 token
* ERC-20 token without symbol
* ERC-20 token with the amount nil
=> Fix tokens transfers info according to the tokens' type

apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* For Etherscan compatibility, the existing API calls support GET and
POST requests. This commit adds test coverage to ensure we support both
GET and POST requests.
* Issue link: related to
https://github.com/poanetwork/poa-explorer/issues/138
* Adding GET/POST requests tests to `API.RPC.AddressControllerTest`
n/a
n/a
n/a
=> Improves API test coverage

apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex, apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
* Currently, the `account#balance` and `account#balancemulti` API calls
return the Ether balance. It was built this way initially because the
Etherscan docs say those API calls should return Ether. This seems to be
a bug in their documentation because the API responds with the balance
in Wei.
* Issue link: related to https://github.com/poanetwork/poa-explorer/issues/138
* Editing the `account#balance` and `account#balancemulti` API calls to
return Wei instead of Ether.
* Editing `API.RPC.AddressControllerTest` to assert account balances are
returned in Wei.
n/a
n/a
n/a
=> Edit API account balance actions to return Wei

apps/explorer_web/lib/explorer_web/etherscan.ex, apps/explorer_web/lib/explorer_web/templates/api_docs/_action_tile.html.eex
* For users to be able to see an example of what errors might look like
when perusing the API's docs pages.
* Issue link: related to https://github.com/poanetwork/poa-explorer/issues/138
* Editing `ExplorerWeb.Etherscan` to include "error" example values for
`account#balance`, `account#balancemulti`, and `account#txlist` calls.
Also, adding "description" field for responses.
* Editing `templates/api_docs/_action_tile.html.eex` to only render
model information for the first response in the responses table. Also,
rendering description field from the documentation data passed to the
template (from `ExplorerWeb.Etherscan`).
n/a
n/a
n/a
=> Adds error example values to API docs page

apps/explorer_web/assets/package-lock.json, apps/explorer_web/assets/package.json
This clears the vulnerability warning we keep seeing on the repo, which is actually not really a concern but could mask any other vulnerabilities that may come up.
* Upgrade to node-sass 4.9.3 as described in https://github.com/sass/node-sass/issues/2355#issuecomment-411749402 to clear vulnerability warning.
=> Upgrade node-sass to clear security vulnerability alerts

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/balance.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs, apps/explorer/test/explorer/chain/balance_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/market/history/cataloger_test.exs, apps/explorer/test/support/factory.ex, apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs, apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs, apps/explorer_web/test/support/feature_case.ex, apps/indexer/lib/indexer/balance_fetcher.ex, apps/indexer/lib/indexer/balances.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/lib/indexer/block_fetcher/catchup.ex, apps/indexer/lib/indexer/block_fetcher/realtime.ex, apps/indexer/test/indexer/balance_fetcher_test.exs, apps/indexer/test/indexer/balances_test.exs, apps/indexer/test/indexer/supervisor_test.exs
Resolves #491 
**Note:** This does not fix the underlying issue with `Ecto.Repo.stream` that killing the node leaves the query running in Postgres.  This just makes the query that hangs take less time, so it is less likely to be running on node death.  Fixing the zombie Postgres query will require changes upstream in `Ecto`.
* Balances will be created when a given (address_hash, block_number) is first seen, but with a `nil` value.  The BalanceFetcher will stream this value is `NULL` rows on restart to initialize the queue.
* Remove flaky tests that keep killing the builds.
* `Balance`s will be created with `nil` `value` when a given `address_hash` and `block_number` pair are encountered to mark that the `value` needs to be fetched.  This means `Balance` `value` cannot be assumed to be …
=> Use nil Balance value to indicate unfetched

apps/explorer_web/assets/css/_code.scss, apps/explorer_web/assets/css/_typography.scss, apps/explorer_web/assets/css/app.scss, apps/explorer_web/assets/css/components/_button.scss, apps/explorer_web/assets/css/components/_tile.scss, apps/explorer_web/assets/css/forms.scss, apps/explorer_web/assets/js/app.js, apps/explorer_web/assets/js/lib/expandable_textarea.js, apps/explorer_web/assets/js/lib/loading_element.js, apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex, apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex, apps/explorer_web/lib/explorer_web/templates/address_contract_verification/new.html.eex, apps/explorer_web/lib/explorer_web/templates/address_read_contract/_function_response.html.eex, apps/explorer_web/lib/explorer_web/templates/address_read_contract/index.html.eex, apps/explorer_web/priv/gettext/default.pot, apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
Resolves: #448 
Implement styling and layout improvements to the views associated to smart contracts within and address page. These changes will improve readability and maintain consistancy with other styling decisions. 
* Add accessibility attributes to form elements for use with assistive technologies.
* Added the ability to cancel the verifiy and pubish operation and return to the unverified "Code" view of the address page.
* Improve readability of element that display code blocks.
1. Navigate to a contract address details page.
2. Naviagte to the "Code" page of the page.
3. Review contract code and click the "Verify and Publish" button.
4. Review the verification form.
4a. Click the "Cancel" link to return to the code tab of the contract address details page.
4b. Submit an empty form …
=> contract page and read/verify contract layout and style improvements

apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer_web/assets/js/lib/loading_element.js
https://github.com/poanetwork/blockscout/issues/138
* For users to be able to click through to the API docs page, we want to add a link to to the top navigation bar.
* Adding API link to `_topnav.html.eex`
* Regenerating gettext files.
* Fixing ESLint errors that sneaked into master.
n/a
n/a
n/a
=> Add API Docs link to navbar

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex
Resolves #521 
Address page needs to load quickly (postgres needs to consistently pick the fastest query plan)
* Use Common Table Expression to force postgres to build a temporary table of transaction hashes that match the address
Before:
```sql
SELECT * FROM "transactions" AS t0 WHERE (t0."hash" = ANY(
(
SELECT t0.hash AS hash
FROM transactions AS t0
WHERE t0.to_address_hash = $1 OR t0.from_address_hash = $1 OR t0.created_contract_address_hash = $1
)
UNION
(
SELECT tt.transaction_hash AS hash
FROM token_transfers AS tt
WHERE tt.to_address_hash = $1 OR tt.from_address_hash = $1
)
))
ORDER BY t0.block_number DESC, t0.index DESC, t0.hash
LIMIT 50
```
Query Plan:
```
Limit  (cost=818157.59..818157.71 rows=50 width=310) (actual time=12495.738..12495.775 rows=50 loops=1)
->  Sort …
```
=> Use CTE for optimized address transactions query

apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/token_helpers.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_token_transfer_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/token_helpers_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Resolves https://github.com/poanetwork/poa-explorer/issues/386.
- Now there is a Token Transfers tab in the Transaction Details page. If the transaction contains at least one token transfer, this tab will appear and be loaded automatically when accessing the page.
<details>
<summary> <b> Token Transfers tab </b> </summary>
</details>
<details>
<summary> <b> List of Token Transfers </b> </summary>
</details>
- Add mobile dropdown to Logs in transaction details. When clicking on the Logs tab on mobile view, the way of displaying tabs was different than what was displayed on the Internal Transactions tab. If that was meant to be that way (not a bug), or if there is already a fix somewhere, please let me know so I remove this change from this PR. 🙂
I already started working on the points …
=> Show Token Transfers on Transaction Details page

apps/block_scout_web/assets/css/theme/_poa_variables.scss
Fixes #550 
The network drop-down links were the same color as the background color and could not be viewed.
- Changed the `dropdown-item:hover` attribute to `$primary`
=> Fix dropdown hover bg color

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/logs_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/api_docs/_module_card.html.eex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/lib/explorer/etherscan/logs.ex, apps/explorer/test/explorer/etherscan/logs_test.exs
Issue link: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get event logs in an Etherscan-compatible
way.
* Editing the router to add support for
`/api?module=logs&action=getLogs...` calls.
* Adding a new `API.RPC.LogsController` to handle log related requests.
* Adding `API.RPC.LogsView`
* Adding `Explorer.Etherscan.Logs` where we've added functions to help
us fetch logs as required by the supported filter parameters.
The `list_logs/1` function in this new module is exposed through the
`Explorer.Etherscan` context.
* Adding 'logs' module and 'getLogs' action to API docs.
n/a
n/a
n/a
=> Add event logs API support

apps/block_scout_web/assets/package-lock.json
It looks like we haven't committed `blockscout_web`'s `package-lock.json` (generated by running `cd apps/block_scout_web/assets && npm install; cd -`) after renaming to BlockScout; or did some requirement change and I don't have up to date versions? These are my `node` and `npm` versions:
```
$ node -v
v10.5.0
$ npm -v
6.1.0
```
- Upgrade `explorer_web`'s `package-lock.json` with Node.js 10.5.0 and Npm 6.1.0, by running `cd apps/block_scout_web/assets && npm install; cd -`.
=> Update nodejs dependencies

apps/explorer/lib/explorer/chain/hash/address.ex, apps/explorer/test/explorer/chain/hash/address_test.exs
Address strings provided by a user should be able to be verified or validated in some way. Some hashes have a checksum that can be checked via [EIP-55 checksum](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).
The code added is migrated from [web3.js](https://github.com/ethereum/web3.js/blob/develop/lib/utils/utils.js#L408-L447).
* Add function for validating address hashes
=> Add function for validating address hashes

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan_test.exs
* Issue link: https://github.com/poanetwork/blockscout/issues/138
* For users to be able to get a list of internal transactions for a
given transaction hash (Etherscan-compatible).
* Adding `Explorer.Etherscan.list_internal_transactions/1` to fetch
internal transactions data as needed to be Etherscan-compatible.
* Adding `txlistinternal/2` action to `API.RPC.AddressController`
* Adding `txlistinternal.json` `render/2` function head to
`API.RPC.AddressView` to render internal transaction lists as needed.
* Adding documentation for the new action. Documentation data lives in
`BlockScoutWeb.Etherscan`
* Making `where_transaction_has_multiple_internal_transactions/1` a
public function and adding doc, spec, and two new tests for it. This was
necessary to use it from …
=> Add API txlistinternal action for account module

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Issue link: https://github.com/poanetwork/blockscout/issues/571
* For API users to be able to get a token's total supply. Note that API
users are probably better off using the `token#getToken` endpoint which
returns a token's total supply plus other token related data they'll
probably need. Etherscan doesn't support `token#getToken` as of this
writing. This endpoint (`stats#tokensupply`) was added for
Etherscan-compatibility.
Example usage:
```
/api?module=stats&action=tokensupply&contractAddress={addressHash}
```
* Creating `API.RPC.StatsController` to process tokensupply requests.
* Editing router to route /api?module=stats&... requests to
`API.RPC.StatsController`
* Creating `API.RPC.StatsView` to render responses for the new API
endpoint as needed.
* Adding docs for the new …
=> Add stats#tokensupply API endpoint

apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/priv/repo/migrations/20180817021704_create_address_token_balances.exs, apps/explorer/test/explorer/import_test.exs, apps/indexer/lib/indexer/balances.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/test/indexer/supervisor_test.exs
#514 
This PR builds TokenBalances from TokenTransfer already existent data structure and creates in the database.
A TokenBalance is one of the 3 Addresses present in a TokenTransfer: `to_address_hash`, `from_address_hash` and `token_contract_address_hash`.  Every TokenTransfer is broken down and translated into this new entity.
In this PR only the records will be created in the database without their values (`value` and `value_fetched_at`), which will be fetched in the Realtime and Catchup indexers in a different PR, in order to unblock other issues that depend on this schema and improve the changes for the code review.
When the (already in progress #583) TokenBalanceFetcher is plugged to the indexers this infos will be fetched and updated.
- We'll stop creating `Chain.Balance`s out of …
=> Index TokenBalances

.credo.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/address/name.ex, apps/explorer/priv/repo/migrations/20180821142139_create_address_names.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/token_fetcher.ex
Resolves #189.
Addresses can be tied to a name even though that name doesn't appear in the chain's data on the addresses directly. This PR allows for an address to have many arbitrary names. An address will have a new name record inserted for any contracts that are verified as well as any token contracts that have been indexed. Other than that, a name will have to be set manually for something more specific like "POA Foundation Wallet".
* Add support for addresses to have many names
* Smart contract publishing adds a new address-name record
* Token indexing adds a new address-name record
* Initial migration automatically populates the `address_names` table with known names from other tables
* Run `cd apps/explorer && mix ecto.migrate`
=> Add support for named addresses

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Issue link: https://github.com/poanetwork/blockscout/issues/571
* For API users to be able to get a list of token transfer events by
address. A contract address can also be given, in addition to an
address. Optional params include: 'startblock', 'endblock', 'sort',
'page', and 'offset'.
Example usage:
```
/api?module=account&action=tokentx&address={addressHash}
```
* Adding `Explorer.Etherscan.list_token_transfers/3` to get token
transfer data required from db.
* Adding `tokentx/2` action to `API.RPC.AddressController` to handle
`?module=account&action=tokentx&...` API requests.
* Editing `API.RPC.AddressView` to render token transfer events as
needed.
* Deleting duplicate line in `Explorer.Chain.TokenTransfer`. This looks
like a typo.
* Other than adding tests for the new functions …
=> Add account#tokentx API endpoint

apps/explorer/lib/explorer/chain/import.ex, apps/explorer/priv/repo/migrations/20180817021704_create_address_token_balances.exs, apps/indexer/lib/indexer/address/token_balances.ex, apps/indexer/lib/indexer/balances.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/test/indexer/address/token_balances_test.exs, apps/indexer/test/indexer/balances_test.exs
Fixes #614
I ran this code as part of #193's branch against Ethereum Mainnet, which was trigger #614 immediately and the blocks were able to insert:
```
16:56:58.343 application=indexer [debug] realtime indexer fetched and imported block 6229871
16:56:58.427 application=indexer [debug] fetching 24 transaction receipts
16:56:59.897 application=indexer [debug] realtime indexer fetched and imported block 6229872
```
Before the changes in this PR, no blocks could be imported because the first one contains token balances that triggered #614.  Token usage seems to be much heavier on Ethereum Mainnet than on Sokol if you need something to test Token support against in the future.
* Port `on_conflict` from `Balance` to `TokenBalance` so that same, explicit rules are used instead of …
=> Fix uniqueness/on_conflict for address_token_balances

config/dev.exs, config/prod.exs, config/test.exs
* Forgot to set the path to the error log in #608.  Errors were only being shown in console and not written to `logs/<Mix.env>/error.log` during #193 testing.  Tested that it worked because I was able to trigger an error during #193 testing and the `error.log` was produced after the change.
=> Set error log path

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs, apps/explorer/config/dev/parity.exs, apps/explorer/config/prod/parity.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/lib/explorer/token/balance_reader.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/token/balance_reader_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/application.ex, apps/indexer/lib/indexer/block_fetcher.ex, apps/indexer/lib/indexer/block_fetcher/catchup.ex, apps/indexer/lib/indexer/block_fetcher/realtime.ex, apps/indexer/lib/indexer/token_balance_fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/block_fetcher/catchup/supervisor_test.exs, apps/indexer/test/indexer/block_fetcher_test.exs, apps/indexer/test/indexer/token_balance_fetcher_test.exs, apps/indexer/test/indexer/token_balances_test.exs, apps/indexer/test/support/indexer/token_balance_fetcher_case.ex
#514 
This PR makes the Indexers to fetch the TokenBalances `value` and `value_fetched_at` both in their own way:
- The Realtime indexer fetches the data synchronously
- The Catchup indexer fetches the data assynchronously
- The values are already fetching the values after we've tested it local, but the code still needs some improvements and tests.
=> Fetch TokenBalances values in Realtime and Catchup Indexers

apps/block_scout_web/config/dev.exs, apps/block_scout_web/config/prod.exs, apps/block_scout_web/config/test.exs, apps/ethereum_jsonrpc/config/dev.exs, apps/ethereum_jsonrpc/config/prod.exs, apps/ethereum_jsonrpc/config/test.exs, apps/explorer/config/dev.exs, apps/explorer/config/prod.exs, apps/explorer/config/test.exs, apps/indexer/config/dev.exs, apps/indexer/config/prod.exs, apps/indexer/config/test.exs, config/dev.exs, config/prod.exs, config/test.exs
Fixes #628
* The `Phoenix.CodeReloader` causes the file loggers to restart and reload their config, but when they reload, the current working directory has shifted from the project root to the OTP app root, so it produces log files under each OTP app (`apps/APP_NAME/logs`).  We don't want this, so compute the absolute path in the config files, so that the loaded `Application` environment has an absolute path in it that can't shift when the working directory changes.
=> Use Path.absname in config so that log paths are stable during reload of Application env

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Issue link: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get a list of blocks mined by a given
address.
Example usage:
```
/api?module=account&action=getminedblocks&address={addressHash}
```
* Adding `list_blocks/2` to `Explorer.Etherscan` to be get blocks as
required by the new API endpoint added in this commit.
* Adding `getminedblocks/2` action to `API.RPC.AddressController` to
handle `account#getminedblocks` API requests.
* Editing API.RPC.AddressView to render blocks as needed.
* Adding docs for `account#getminedblocks` API endpoint. API docs live
in `BlockScoutWeb.Etherscan`
=> Add account#getminedblocks API endpoint

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Issue link: https://github.com/poanetwork/blockscout/issues/138
* For API users to get a list of transactions in which the given address
is the 'to' in the transaction.
Example usage:
```
/api?module=account&action&txlist&address={someAddress}&filterby=to
```
* Editing `API.RPC.AddressController`'s `txlist/2` action to support a
`filterby` flag in which the only allowed value for now is `to`. This is
an optional parameter. When given this filters the returned transactions
to only those in which the given address matches the `to` field. When
not given, the address provided could match the to, from, or contract
address for the transaction.
* Editing `Explorer.Etherscan`'s `list_transactions/3` to support the
new `filterby` flag mentioned above.
* Editing API docs data in …
=> Add filterby flag to account#txlist

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
Resolves #618
**NOTE: This is an improved logging bug fix.  It does not fix why we're getting a `nil` "status`, which indicated `"status":null` in the JSON, but instead adds enough additional information to the exception to recover the block number or transaction hash so that we can use that information for further triage and bug reproduction.  #618 could turn out to be a bug in the node configuration, but we can't know that we the stacktraces we're getting now.**
* Use the validation pattern of reducing all entries while ok, but then switching to accumulating all errors once any error occurs. Finally, because the fields that identify the receipt precisely, such as
the transactionHash or blockNumber may not have an error, include the full receipt the `ArgumentError` exception.
=> Better error message when receipt cannot be converted to elixir

apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
Fixes #515 
Added the same class tag `mt-3` as seen on the all transactions page.
n/a
Fixed the spacing of the pagination button the account page and internal transaction page.
n/a
n/a
=> Fix spacing on account page pagination

apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves: #598 
Small design cleanup items to improve the UI.
=> Design cleanup items

apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/token_balances_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/654
* When some task within `Task.async_stream` gave a timeout the process was being killed. Now, we are dealing with possibles `timeout` ignoring them since the `TokenBalanceFetcher` will run again to fetch the balances.
=> Handle timeout when fetching token balances from blockchain

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/635
* For API users to be able to get a list of transactions in which a
given address is the 'sender' (address is the 'from' in transaction).
Example usage:
```
/api?module=account&action&txlist&address={someAddress}&filterby=from
```
* Editing `where_address_match/3` in `Explorer.Etherscan` to support
`filter_by: "from"` option.
* Editing `put_filter_by/2` in `API.RPC.AddressController` to support
'from' as an allowed value of the `filterby` parameter.
=> API account#txlist filterby=from support

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Work-around for #673.
Tested against the ETC URLs @acravenho provided.  During development, I was able to show that the new clause was used for the 21,000 gas.
@acravenho please verify the value-only transactions no longer show Out of Gas for you.
* We got demos coming up where we want ETC BlockScout to not show value-only transactions as Out of Gas.
*  The `gas_used == gas` heuristic means failures pre-Byzantium (and on ETC) is only a heuristic: it fails for value-only transactions where ETC submitters are using exactly the transaction base fee (21,000 gas) often.  Because this is so common, we'll use this work-around now until we can restructure EthereumJSONRPC and Indexer to verify pre-Byzantium status using Internal Transactions.
=> Temporary work-around for #673 value-only transactions

apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/address_token_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/410.
<details>
<summary><b>Tokens tab</b></summary>
</details>
- Add a token tab in the address page to list the tokens that address has interacted with;
- The query to get tokens that interacted with an Address now returns the result sorted first by type and then by name; it also supports pagination;
- Add a query that returns all the interactions between a token and an Address.
- Typos.
=> "Tokens" tab in address page

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Issue link: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get the ABI for a given contract address.
Example usage:
```
/api?module=contract&action=getabi&address={addressHash}
```
* Editing router to support `contract#getabi` API endpoint.
* Creating `API.RPC.ContractController.getabi/2` action to process
requests to `contract#getabi` endpoint.
* Creating `API.RPC.ContractView` to render `contract#getabi` responses.
* Adding documentation data for the new `contract#getabi` API endpoint.
Documentation data lives in `BlockScoutWeb.Etherscan`
=> Add contract#getabi API endpoint

apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/test/explorer/chain_test.exs
The query that gets the last token balances based on the block number was considering the next-to-last token balance when the last one had the value 0.
In order to this work properly, I'm moving the query that gets token balances from the last block to a sub-query and moving the condition to consider just values greater than 0 to the main query.  This way we are sure that we always are considering the last block and we are skipping the ones that have the value equal to 0.
=> Fix token balances' query to always consider the last block even when the value is 0.

apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
* To match Etherscan's API we want to ensure blocks returned by the
`account#getminedblocks` API endpoint are ordered by descending block
number. We noticed this wasn't the case when looking into a couple of
flaky tests on CI. This commit should also make sure the tests don't
randomly fail any more. These are the two tests:
- test/block_scout_web/controllers/api/rpc/address_controller_test.exs:1674
- test/explorer/etherscan_test.exs:1014
* Editing `Explorer.Etherscan.list_blocks/1` to order blocks by
descending block number.
* Related tests were edited according to the change above.
=> Orders account#getminedblocks by block number

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Part of: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to check the 'receipt status' for a given
transaction hash.
Example usage:
```
/api?module=transaction&action=gettxreceiptstatus&txhash={transactionHash}
```
* Editing router to support the new `transaction#gettxreceiptstatus` API
endpoint.
* Adding `API.RPC.TransactionController.gettxreceipstatus/2` action to
process requests made to the `transaction#gettxreceiptstatus` API
endpoint.
* Adding `API.RPC.TransactionView` to render transaction controller
responses as required.
* Adding `transaction#gettxreceiptstatus` API endpoint to the API docs
page. Docs data lives in `BlockScoutWeb.Etherscan`.
=> Add transaction#gettxreceiptstatus API endpoint

apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex, apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Is just an improvement for the https://github.com/poanetwork/blockscout/pull/726 according [to this comment](https://github.com/poanetwork/blockscout/pull/726#discussion_r217708620).
We used `overflow: auto` to deal with overflow width/hight. We could handle it better using `pre-wrap` since the overflow is just in the code area.
For the User, the final result is the same as before.
=> Improve Smart Contract's function response CSS style

apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
We used `conn.params['id']` instead of `conn.params['token_id']`. To fix it I'm changing to use `@token.contract_address_hash` for it doesn't depend from URL params anymore.
=> Fix Token Holders' link from Read Smart Contract page

apps/explorer/lib/explorer/chain/import.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/test/indexer/token_balance/fetcher_test.exs
Resolves #698
The `Indexer.TokenBalance.Fetcher` was being shut down when importing lots of token balances.
```
04:20:01.092 [error] Task #PID<0.13677.6> started from #PID<0.13236.6> terminating
** (stop) exited in: GenServer.call(Indexer.TokenBalanceFetcher, {:buffer, [ ... (truncated)
```
It was also raising an exception when the `Chain.import` returned an empty list.
```
`** (MatchError) no match of right hand side value: {:ok, %{token_balances: []}}`
```
* Increase the `timeout` used by the `GenServer.call` at the `BufferedTask.buffer` so it doesn't exit when the token balances list is too long.
* Add `error` treatment when something unexpected happens with the `Chain.import` at the `Indexer.TokenBalance.Fetcher`
=> Increase Indexer.TokenBalance.Fetcher timeout and add treatment error

apps/indexer/lib/indexer/token/fetcher.ex, apps/indexer/test/indexer/token/fetcher_test.exs
Fix https://github.com/poanetwork/blockscout/issues/693.
* When there was a large string to represent the name, type or symbol of a token, we would get an exception and the indexer would fail.
=> Handle large strings when fetching tokens

apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/priv/repo/migrations/20180831231919_modify_block_gas.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs
* `blocks.gas_used` and `blocks.gas_limit` need be larger to support private chains with higher limits than Ethereum mainnet (8 million), which fit in `integer`.
The column type can be converted from `integer` to `numeric` **without** a database reset, so you **only need to run `mix ecto.migrate`**.
=> Allow blocks.gas_used and gas_limit to be numeric to support higher limits on private chains

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Part of: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get the error for a given transaction
hash.
Example usage:
```
/api?module=transaction&action=getstatus&txhash={transactionHash}
```
* Adding `Explorer.Etherscan.get_transaction_error/1` to get the error
for a given transaction hash.
* Adding `API.RPC.TransactionController.getstatus/2` action to
process requests made to the `transaction#getstatus` API
endpoint.
* Editing `API.RPC.TransactionView` to render transaction errors
('status') as required.
* Adding `transaction#getstatus` API endpoint to the API docs
page. Docs data lives in `BlockScoutWeb.Etherscan`.
=> Add transaction#getstatus API endpoint

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Part of: https://github.com/poanetwork/blockscout/issues/138
* For API users to get the total supply in Wei.
Example usage:
```
/api?module=transaction&action=ethsupply
```
* Adding `API.RPC.StatsController.ethsupply/2` action to process
`stats#ethsupply` requests.
* Editing `API.RPC.StatsView` to render `ethsupply` responses as
required.
* Adding `stats#ethsupply` API endpoint to API docs page. API docs data
lives in `BlockScoutWeb.Etherscan`
=> Add stats#ethsupply API endpoint

apps/block_scout_web/lib/block_scout_web/notifier.ex
Fixes #739.
This fixes an issue where `created_contract_address` is expected to be preloaded for most view-related rendering but isn't preloaded for new transactions pushed over channels.
* Preload contract address names for new transactions pushed over channels
=> Preload contract addresses names for transaction push

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Part of: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get the latest coin price in BTC and USD.
Example usage:
```
/api?module=stats&action=ethprice
```
* Adding `API.RPC.StatsController.ethprice/2` action to handle requests
to the `stats#ethrpice` endpoint.
* Editing `API.RPC.View` to include render function clause to render
responses for `stats#ethprice` API endpoint as required.
* Adding `stats#ethprice` to API docs page. API docs data lives in
`BlockScoutWeb.Etherscan`
=> Add stats#ethprice API endpoint

apps/explorer/priv/repo/migrations/20180919175123_alter_token_decimals_to_bigint.exs, apps/explorer/test/explorer/chain_test.exs
Fixes #758
There are some decimals with bigger values than the supported by the `smallint` type.
https://www.postgresql.org/docs/9.1/static/datatype-numeric.html
This PR adds a new migration to alter the `Token` table column, so we don't drop and re-index the whole database just for this type.
When indexing a new chain some errors appeared in the `Token.Fetcher`, related to the size of the column `decimals`.
```
22:44:14.500 [error] Task #PID<0.10175.0> started from Indexer.Token.Fetcher terminating
** (ArgumentError) Postgrex expected an integer in -32768..32767, got 1000000000000000000. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
```
=> Alter Token decimals column to bigint

apps/indexer/config/dev.exs, apps/indexer/config/prod.exs, apps/indexer/config/test.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/token_balances_test.exs, config/config.exs
Resolves #720 
We've created a new log file that will write all errors, that doesn't break the code, that occurs while interacting with smart contracts when fetching a specific Address token balance. 
The errors will be logged during the Realtime indexer, that fetches the token balances synchronously, and the TokenBalance fetcher, that is triggered by the Catchup indexer and processed asynchronously. 
The logs are avaiable in: 
- `logs/dev/indexer/token_balances/error.log`
- `logs/test/indexer/token_balances/error.log`
- `logs/prod/indexer/token_balances/error.log`
The messages will look like:
```md
15:42:21.936 [debug] <Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction: 
<address_hash: 0xbfde6246df72d3ca86419628cac46a9d2b60393c, …
```
=> New log file for TokenBalances interaction errors

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import.ex
Resolves https://github.com/poanetwork/blockscout/issues/757
* Issue #757 was created after we noticed a few constraint violations
for the `error` column in the `transactions` table. The constraint
violations came about as we attempted to update transactions with a
successful status but some value for the error field. The constraint
is violated in this scenario because we expect successful transactions
to not have an error. [EIP 658](https://github.com/ethereum/EIPs/pull/658), which apparently is also called [EIP 98](https://github.com/ethereum/EIPs/issues/98#issuecomment-318670322),
says that the status should be set to 1 (success) if the outermost
code execution succeeded (internal transaction with index 0), or it
should be set to 0 (failure) if the outermost code execution failed. …
=> Derive status from internal transaction at index 0

apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_transfer_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/561
* List transactions with token transfers by a token in the Token's tab at the Address' page.
* Fix margin in the pagination button in the Tokens' page.
=> List transactions with token transfers by a token in the token's  tab at the Address' page

apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/realtime/supervisor.ex
* For the realtime fetcher to keep up on ETH we want it to fetch blocks
asynchronously. We noticed that the realtime fetcher was falling behind
on ETH mainnet. Currently the realtime fetcher fetches and imports one
block at a time. This commit changes that, so that whenever we're
notified of a new block number, through websockets, we start a new
process to fetch and import each block asynchronously.
* Also, whenever the websocket subscription, through which we're notified
of new block numbers, skips block numbers, we want to make sure the
skipped blocks are also fetched and imported.
* Adding a new `Task.Supervisor` called
`Indexer.Block.Realtime.Fetcher.TaskSupervisor` under the
`Indexer.Block.Realtime.Supervisor` supervisor. This supervisor was
created to supervise fetching and …
=> Realtime.Fetcher async fetching and no skips

apps/block_scout_web/lib/block_scout_web.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/tab_helpers.ex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/tab_helpers_test.exs, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/778
The code that defines the card header, where the tab links are, was
being repeated in every tab. This commit moves this code to a partial
and creates a little helper function to get the currently active tab. This
function simply looks for the current tab name in the request path.
=> Remove duplicated code from Transaction page

apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/800.
Errors may pop up that do not comply with the current expect API: they
may not include a `:message` key in its formation. When they did not, the
exception handler was throwing an exception.
=> Handle more errors types at Smart Contract Reader

apps/indexer/lib/indexer/block/realtime/fetcher.ex
Resolves: https://github.com/poanetwork/blockscout/issues/808 (should be tested first to know if it really stops the "Unknown block number" errors from happening)
* For Sokol, on staging, we noticed many errors like this one:
```
00:45:05.627 application=indexer [error] realtime indexer failed to
validate for block 4668478: [%{code: -32602, data: %{"blockNumber" =>
"0x473C3E", "hash" => "0x532e069e200be3e372da9680872826bb08caef91"},
message: "Unknown block number"}, %{code: -32602, data: %{"blockNumber"
=> "0x473C3E", "hash" => "0x95426f2bc716022fcf1def006dbc4bb81f5b5164"},
message: "Unknown block number"}, %{code: -32602, data: %{"blockNumber"
=> "0x473C3E", "hash" => "0xe797a1da01eb0f951e0e400f9343de9d17a06bac"},
message: "Unknown block number"}].  Block will be retried by catchup …
```
=> Realtime indexer waits half a second before fetch

apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
Fixes #799.
Transactions that create a contract address rely on the `created_contract_address` field to be preloaded when viewing the logs for respective transactions.
* Preload `created_contract_address` when viewing transaction logs
=> Preload created contract address for transaction logs

apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/mix.exs, apps/ethereum_jsonrpc/mix.exs, apps/explorer/mix.exs, apps/indexer/mix.exs, mix.lock
Resolves #591
1. `iex -S mix phx.server`
2. In a separate terminal: `open http://localhost:4000/wobserver`
1. Click the Applications tab
1. Check `block_scout_web`
1. Ensure that "block_scout_web" has a description
2. Check `iex` terminal.  Ensure no errors raised showing process tree.
2. Switch to `ethereum_jsonrpc` in the dropdown
1. Ensure there is a description
2. Check `iex` terminal.  Ensure no errors raised showing process tree.
3. Switch to `explorer` in the dropdown
1. Ensure there is a description
2. Check `iex` terminal.  Ensure no errors raised showing process tree.
4. Switch to `indexer` in the dropdown
1. Ensure there is a description
2. Check `iex` terminal.  Ensure no errors raised showing process tree.
2. Click the Processes tab (there will be a slight delay as there are …
=> Add Wobserver

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/814
* For API users to be able to get a list of tokens owned by a given
address.
Example usage:
```
/api?module=account&action=tokenlist&address={addressHash}
```
* Creating `Explorer.Etherscan.list_tokens/1` to fetch tokens owned by a
given address.
* Creating `API.RPC.AddressController.tokenlist/2` action to process
requests to `account#tokenlist` API endpoint.
* Editing `API.RPC.AddressView` to render token lists as required.
* Adding documentation data for the new API endpoint mentioned above.
Documentation data lives in `BlockScoutWeb.Etherscan`.
=> account#tokenlist API endpoint

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/test/explorer/chain/address/token_balance_test.ex, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/address/token_balances.ex, apps/indexer/lib/indexer/token_transfers.ex, apps/indexer/test/indexer/address/token_balances_test.exs, apps/indexer/test/indexer/token_transfers_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/810
As we always get errors trying to fetch token balances when the address is the burn address for Tokens ERC-721, we are gonna ignore them when we are processing the token balances from the token transfer.
* Stop indexing token balances for the burn address when the token type is ERC-721
* As we won't the burn address with ERC-721 indexed, we are gonna not receive this error anymore:
```
<Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction:
<address_hash: 0x0000000000000000000000000000000000000000, contract_address_hash: 0xeaa54040679ceda84af88ef5bd0895e8e841c2d5, block_number: 4609877, error: (-32015) VM execution error.>
```
=> Ignore burn address token balance for Tokens ERC-721

apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Resolves #793 
Due to the nature of named addresses being non-unique, multiple addresses may share the same name and be confused with another without the address's hash visible in context. This PR display 6 digits of the address's hash along with the name when used in links.
* Add function to shorten an address's hash to 6 hex digits
* Display shortened address hash next to address primary name in links
=> Display shortened addresses in named address links

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Fixes #843
* Regression test for #843.
* Use order of hashes passed to `Chain.hashes_to_addresses` to order returned `Address`es.
=> Ensure order is preserved for account multibalance

apps/explorer/.sobelow-conf, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/test/explorer/chain/import_test.exs
Resolves #408
* Update consensus blocks, transactions, and transaction forks automatically to support reorganizations as reorganizations are not transmitted with an obvious flag.
1. For transactions that are in blocks that will lose `consensus`, insert a transaction fork will the current `transactions.block_hash` as `transaction_forks.uncle_hash` and `transactions.index` as `transaction_forks.index`.
2. For those transactions that now have transaction forks, `null` out the fields they got from have transaction receipts.
3. Before inserting blocks, set `consensus = false` for any blocks with the same `number` as the blocks that will be inserted. 
4. **Insert blocks as before.**  If blocks are from reorganizations, they will have `consensus = true`, while if from the uncle fetcher they will …
=> Support reorganizations

apps/explorer/lib/explorer/chain/address/name.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/test/explorer/chain_test.exs
Resolves #772
This PR trims whitespace from token names and address names whenever the respective structs are inserted or updated via changesets.
* Token and address names are trimmed of whitespace
=> Trim address and token names of whitespace

apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/config/config.exs, apps/block_scout_web/config/prod.exs, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs, apps/explorer/config/config.exs, apps/explorer/config/prod/parity.exs, apps/indexer/config/prod/parity.exs, bin/deployment/health_check
Fixes #790 
The deployed URL schema should route from subfolders similar to `/poa/sokol` and `/poa/core`. So we are configuring Phoenix to generate links using this `custom/path` that will be configured in the environment.
Notice that, after this configuration, it just generates the link with the `/custom/path` prefixed. But Phoeniex doesn't have a route for that. So, it will be necessary a proxy configuration to strip this `/custom/path` for the URL once the envs are configured, otherwise, the routes never will reach the Phoenix application.
- Adds environment variables for `network`, `subnetwork`, `logo`, `network path`, and `check_origin`.
- Adds the ability to change the `title`, `network path`, `network icon`, and `check_origin` for deployment purposes.
- Refactor the view to use the …
=> Deployment fixes for the network path

apps/explorer/lib/explorer/chain.ex
Fixes #838
* Regression test for #838.
* Only count consensus blocks as not missing.
=> Only count consensus blocks as not missing

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
Resolves: https://github.com/poanetwork/blockscout/issues/138
* For API users to be able to get a list of internal transactions by
address.
Example usage:
```
/api?module=account&action=txlistinternal&address={addressHash}
```
* Adding `Explorer.Etherscan.list_internal_transactions/2` to get list
of internal transactions by address.
* Editing `Explorer.Etherscan` by changing the order of some of the
bindings within queries to be able to reuse `where_start_block_match/2`
and `where_end_block_match` in the new function mentioned above.
* Editing `API.RPC.AddressController.txlistinternal/2` to work when
getting internal transactions by txhash or address.
* Editing `account#txlistinternal` documentation data to account for the
fact that it can now be used with an address or txhash. …
=> account#txlistinternal by address API endpoint

apps/explorer/lib/explorer/chain/import.ex, apps/explorer/test/explorer/chain/import_test.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Fixes #850
* Regression test for #850
* Don't run imports for empty params
* Don't do async imports with empty lists
* Return `:error` tuples from `dervie_transaction_forks` instead of raising `MatchError`s.
* There was a bug with `where_forked`, where if there are no blocks it will select **ALL** transactions because no `WHERE` conditions are added to the `SELECT ... FROM transactions`. Instead of starting the initial query that way, start with `WHERE false`, so it will select nothing until the `OR`s for the block hashes and numbers are added.   This means that if there was ever no block, and no pending transactions in the database, all pre-existing transaction would have had a `transaction_forks` row created and their receipt fields blanked.
=> Fix where_forked selecting all transactions when there are no blocks being imported

apps/block_scout_web/assets/__tests__/pages/block.js, apps/block_scout_web/assets/__tests__/pages/chain.js, apps/block_scout_web/assets/__tests__/pages/transaction.js, apps/block_scout_web/assets/css/components/_animations.scss, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/css/components/_loading-spinner.scss, apps/block_scout_web/assets/js/pages/block.js, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex, apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
Resolves #775
In order to not fall behind while indexing blocks, the realtime indexer completes blocks asynchronously (meaning that blocks could come into the UI out of order).  The sequential ordering of blocks needs to be maintained.
* If a block is skipped, a placeholder block tile is inserted in the UI.  When the block is eventually finished and sent to the front-end with a channel update, the placeholder card is replaced.
* Functions for both the block list and home pages
=> 775 in order blocks realtime

apps/block_scout_web/assets/css/_typography.scss, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Resolves: #755 
Highlight the transaction status on the transaction details page to more clearly communicate the transaction's status at a glance. 
* Add color to the transaction status label to visually represent its status.
* Make the transaction tile error state more prominent by increasing the colored border width
n/a
n/a
n/a
=> Highlight transaction status

apps/block_scout_web/assets/js/pages/chain.js
Resolves #851 
Transactions were not live updating on home page.
* Restored live updating of transactions by fixing the event name that the transaction updates were subscribed to.
=> Fix channel event name for chain transactions.

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex, apps/indexer/config/dev/geth.exs
Related to #624
Some setup like ours will have the WebSocket connection in a private network to a local node and thus do not require a secure connection.
- Allow inscure websocket connections with `ws://` scheme instead of `wss://`.
- Read from `ETHEREUM_JSONRPC_WEB_SOCKET_URL` in `apps/indexer/config/geth.exs`.
=> Allow insecure WebSocket connections

apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/counters/token_transfer_counter.ex, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/token_transfer_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/token_transfer_counter_test.exs, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/uncle/fetcher.ex, apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Relates to #820
The `Tokens` pages have a performance problem due to the amount of data and the MVCC implementation in PostgreSQL.
This PR consolidate the token transfers count info.
This PR adds a `GenServer` that is responsible to consolidate the total of token transfers per contract hash and store it in a `ets` table.
The `Live Update` feature at the front-end already use events to constantly show new items, but for the `Live Update`, only the `realtime` events are important. For the token counter, both `realtime` and `catchup` are important, that's the reason why now instead of a boolean for the `broadcast` option, now we pass from where the event came (`realtime`, `catchup` and `uncle`)
=> Consolidate token transfer count

apps/block_scout_web/lib/block_scout_web/endpoint.ex
Resolves #879
This PR makes `BlockScoutWeb.Endpoint` aware of favicon-related assets for `Plug.Static` and allows them to be loaded. This also enables gzip of static assets to lower file-transfer bandwidth.
* Favicon-related assets are now loaded with `Plug.Static`
=> Set endpoint to load favicon-related assets

apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Resolves #884 
The `token holders` counter is being improved in the #880 issue, but the page is still slow with this information.
Removes the `token holders` count info from the token's page.
=> Remove token holders count from Token's page

apps/indexer/lib/indexer/internal_transaction/fetcher.ex
* Currently errors when importing internal transactions are being logged
with 'debug' level. Making them 'error' level would make sure we notice
them quicker and that they're prioritized accordingly.
Changed log levels from 'debug' to 'error', in `Indexer.InternalTransaction.Fetcher`.
=> Log InternalTransaction.Fetcher errors as error

apps/explorer/lib/explorer/chain.ex
In `where_transaction_has_multiple_internal_transactions` it counts every sibling unncessarily: I added a `limit` to it so it only `select`s up to `2`.
Related to #872 
The queries take a long time and the pages don't load correctly.
`Chain.where_transaction_has_multiple_internal_transactions/1` no longer counts every sibling unnecessarily, now only up to `2`.
=> Don't count every sibling unnecessarily.

apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
resolves #909 
- make validations tab bring needed block associations to check block type
- pass block type to the partial that was crashing so it won't anymore
=> Blocks validated tab for miner crashing

apps/block_scout_web/assets/__tests__/pages/block.js, apps/block_scout_web/assets/__tests__/pages/chain.js, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/assets/js/pages/block.js, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/assets/js/utils.js, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex, apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex, apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex, apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
Resolves #865 
Placeholders are put in for skipped blocks with live reload, but they aren't when the page is initially rendered (or refreshed).
* Add placeholders for skipped blocks on page render (for blocks list and homepage)
=> Fill-in skipped blocks on page render for blocks list

apps/block_scout_web/assets/js/pages/address.js, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/counters/block_validation_counter.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/block_validation_counter_test.exs
Resolves #875, related to #768.
As a user, I want to navigate to the `address` page and be able to see the number of `validations` the address has performed.
* I copied @amandasposito's changes to events by differentiating between `:realtime` and `:catchup` by using `atoms` instead of `booleans`.
* I noticed that the number of `validations` when viewing an `address` was being set to the number of `transactions`. Fixed this by setting `state.validationCount` to the number of validations passed in, not the number of transactions in [`address.js`](https://github.com/poanetwork/blockscout/compare/master...Lokraan:consolidate-validation-count?expand=1#diff-9ea2062dff8b90dd854d1db13438ede6)
=> Consolidate validation count

apps/explorer/lib/explorer/chain/hash.ex, apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex, apps/explorer/lib/explorer/exchange_rates/token.ex, apps/explorer/test/explorer/chain/hash/full_test.exs, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/coin_balance/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/lib/indexer/sequence.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/test/indexer/coin_balance/fetcher_test.exs, apps/indexer/test/indexer/internal_transaction/fetcher_test.exs, apps/indexer/test/indexer/token_balance/fetcher_test.exs
Related to #888
While adding memory manager for #888, I used `:observer` to see what the state of each of the fetchers looked like and realized that we were storing a lot of redundant parts of data structures.
* Optimize memory usage for entries in the work queues for the various fetchers
* `Indexer.Sequence` stores `%Range{first: first, last: last}` as `{first, last}` internally in its `:queue for a 45%-30% memory savings.
| max_block_number | Garbage Collection | Ranges (bytes) | Tuples (bytes) | Tuples / Ranges (%) |
|------------------|--------------------|----------------|----------------|---------------------|
| 5,000,000        | Before             | 41,050,964     | 22,445,660     | 54.68               |
| 5,000,000        | After              | 34,386,756     | 23,879,996     | …
=> Optimize entry memory usage for work queues

apps/block_scout_web/assets/__tests__/pages/address.js, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/854
* Refactor the transactions count by address to count only the transactions sent by the address.
* Improve the address' page and accounts' page performance since the query didn't try to count all transactions (including token transfers).
=> Refactor the transactions count by address to use the accounts nonce

apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/test/explorer/chain/address/token_balance_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/token_holders_counter_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/880.
- Cache the number of token holders a token has by adding an ets table to get this value. A GenServer that runs periodically is responsible for updating this table and fetching values.
=> Consolidate token holders count

apps/indexer/lib/indexer/address_extraction.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/mint_transfer.ex, apps/indexer/test/indexer/mint_transfer_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/932
* Considers logs topics according to the bridge hash (first topic) to index addresses when the networking is minting coins.
=> Considers mint transfers using logs to index the address

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs, apps/indexer/config/dev/parity.exs, apps/indexer/config/prod/parity.exs, apps/indexer/lib/indexer/address_extraction.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/test/indexer/address_extraction_test.exs, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Resolves: https://github.com/poanetwork/blockscout/issues/767
* "Parity’s consensus engine allows using a smart contract for block
reward calculation." - see https://wiki.parity.io/Block-Reward-Contract
for details. This means that we need to use `trace_block`
(https://wiki.parity.io/JSONRPC-trace-module#trace_block) to fetch the
block reward contract beneficiaries and update their balances. Currently
this doesn't happen so there are addresses (block contract reward
beneficiaries) with inaccurate balances and missing rows in the
`address_coin_balances` table.
* Adding `EthereumJSONRPC.fetch_beneficiaries/2` to help us fetch the
block reward contract beneficiaries of a given block range. This only
works with Parity.
* Editing Indexer's dev and prod config by adding `trace_block` config to …
=> Update block reward contract beneficiary balances

apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Closes #37
We're currently showing a 404 page if the address is not in our DB. Instead, we should be showing the address page with a 0 balance. The address exists, we either did not update the balance yet or the address has not balance.
* Create `Chain.find_or_insert_address_from_hash/1` which creates an address and returns it if one isn't found.
* Created tests for `Chain.find_or_insert_address_from_hash/1` and `Chain.hash_to_address/1`.
* Updated the query in `Chain.find_or_insert_address_from_hash/1` to return the loaded associations.
* Created a test for `Chain.hash_to_address/1`
=> Address 404 page

apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex, apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
There was an inconsistency in the navigation between the way users could get to the Block index pages and how they could get to the Transaction index pages. These changes adopt the Blocks navigation pattern for the Transactions. 
- Add a dropdown menu in the top nav for validated and pending transactions
- Remove the tab navigation from the transaction index pages
n/a
n/a
n/a
=> Add transaction dropdown menu to navbar

apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/internal_transaction_view_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/938
- Add a helper function to Internal Transaction view to get the type to be
displayed. When it is an Internal Transaction of type `:call`, show the
`:call_type` instead.
<details>
<summary><b>Internal Transaction tile with type</b></summary>
</details>
=> Add Internal Transaction type to the tile

apps/block_scout_web/config/prod.exs, apps/ethereum_jsonrpc/config/prod.exs, apps/explorer/config/prod.exs, apps/indexer/config/prod.exs, config/prod.exs
* To limit the total size of the logs retained while still allowing
analysis of recent events.
* Editing the logger backends to do file rotation every 50mb and keep
the last 19 log files per logger backend. 50mb * 20 = ~1gb
(☝️ edited this comment to reflect latest updates to branch/PR)
=> Adds log rotation

apps/indexer/lib/indexer/token/fetcher.ex
Resolves #956
Removes null bytes from token name and symbol prior to saving them in the database.
* Trim null bytes from strings when fetching tokens
=> Remove null bytes from token name and symbol

apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/blocks.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/mix/tasks/migrate.transaction.info.ex, apps/explorer/mix.exs, apps/explorer/priv/repo/migrations/20181011193212_add_fields_to_internal_transactions.exs, apps/explorer/priv/repo/migrations/20181017141409_add_index_to_internal_transaction_table.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/internal_transaction_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/etherscan_test.exs, apps/explorer/test/explorer/repo_test.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Resolves #872
Listing Internal Transactions for some specific Addresses with lots of Txs is very slow.
The query performance dropped from 15s to 949ms, the stats can be followed here:
https://explain.depesz.com/s/rmeQ
* Removed the joins with `transactions` and `blocks` and replaced with two columns `transaction_index` and `transaction_block_number`;
* Include in the `import/blocks.ex` a new `Multi.run` to ensure that the `internal_transaction`.`transaction_block_number` is up to date after a reorg.
* The `internal_transaction` query was taking too long and one of the reasons was because it was performing a sub-query in the internal_transactions table to identify if the transaction had siblings.
This was made because for every parent transactions there is one equal internal_transaction, …
=> Improve Internal Transactions listing performance

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
Fixes ganache ping/pong ws implementation. 
Ganache send `ping` message every N seconds and if it's not getting `pong` message it terminates ws connection.
Added `{:ping, ""}` ws message handler.
=> Fix ping/pong from ganache ws implementation

apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs, apps/explorer/test/explorer/smart_contract/reader_test.exs
Resolves #964
Geth requires a 2nd argument to be explicitly provided when running `eth_call` to execute contract functions. This PR sets `"latest"` as the default 2nd argument. This doesn't affect the values for Parity since it defaults to latest.
* Provide block argument for executing contract functions on Geth
=> Provide default 2nd arg for executing contract functions on Geth

apps/block_scout_web/lib/block_scout_web/notifier.ex
In certain instances the (auto generated) primary key for internal transactions can change, causing a lookup failure in the Notifier.
As the internal_transactions table has a not null, unique index on the {transaction_hash, index} fields and as these fields are already present in the message sent to the Notifier, this simple change addresses the situation where the primary key has changed due to the record being imported twice.
- Addresses GenServer BlockScoutWeb.EventHandler error due to nil internal_transactions pulled from database
=> Lookup internal_txs by {hash, index} in BlockScoutWeb.Notifier handle_event()

apps/ethereum_jsonrpc/config/config.exs, apps/ethereum_jsonrpc/config/test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/application.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/rolling_window.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/request_coordinator_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/rolling_window_test.exs
Whenever our requests for fetching chain data start hammering nodes, we do not do any sort of backing off to slow down our rate of requests to allow the node to reach a stable state. This PR adds a mechanism to keep track of the number of recent request timeouts from the last minute and adds a wait time to any outgoing JSON RPC request based on that number.
For each recent timeout, a delay is added to the request with some additional randomized jitter. The delay is calculated as `timeouts * (base_delay + jitter)` where the base delay is 20 seconds. This can be configured as we find values that work best in production. If a requests delay time were to exceed some threshold, the request won't be performed and `{:error, :timeout}` will be returned immediately.
As a whole, this PR is a first …
=> Add backoff for Ethereum JSON RPC requests

apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex, apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/test/explorer/chain_test.exs
After the merge of the Internal Transaction listing performance an error started to show:
```
18:40:26.599 [error] #PID<0.714.0> running BlockScoutWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /address/0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208/internal_transactions
** (ArgumentError) cannot convert nil to param
(phoenix) lib/phoenix/param.ex:67: Phoenix.Param.Atom.to_param/1
(block_scout_web) lib/block_scout_web/router.ex:1: BlockScoutWeb.Router.Helpers.block_path/4
(block_scout_web) lib/block_scout_web/templates/internal_transaction/_tile.html.eex:23: BlockScoutWeb.InternalTransactionView."_tile.html"/1
(block_scout_web) lib/block_scout_web/templates/address_internal_transaction/index.html.eex:61: anonymous fn/3 in …
```
=> Fix InternalTransaction listing page by removing transaction fields.

apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/block/realtime/fetcher_test.exs, apps/indexer/test/indexer/token_balance/fetcher_test.exs, apps/indexer/test/indexer/token_balances_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/948
* Increase `batch_size` and `init_chunk_size` from `TokenBalance.Fetcher` to process `100` of token balances at time.
* Ensure that token balances that gave errors interacting with smart contract are going to be fetched
=> Improve token balances fetcher

apps/indexer/lib/indexer/address/token_balances.ex, apps/indexer/test/indexer/address/token_balances_test.exs
relates to https://github.com/poanetwork/blockscout/issues/962
We don't need this extraction because it will try to fetch the balance from the own token in its contract and it doesn't make sense for us. We will stop to store a lot of unnecessary data and requests to the smart contract  removing this extraction.
If some token transfer takes place to the token, as it will be the `to_address_hash`, the token balance will be indexed normally.
=> Do not store token_hash as address_hash in token balances

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
Currently we are seeing a large amount of immediate timeouts due to the first implementation of how we handle throttle_timeout. The idea was that if we knew we were going to timeout eventually, why not just timeout immediately and let the caller go on with their day. @alexgaribay pointed out at the time that may have unexpected behavior, and we're seeing that behavior now. Callers fail and then repeatedly call until they reach their restart limit and crash.
Prevent stampedes via sleeping for the `throttle_timeout`, even when we've decided not to make the request to the API.
=> Prevent stampedes via sleeping for throttle_timeout even when request is not made

apps/block_scout_web/lib/block_scout_web/schema.ex, apps/block_scout_web/lib/block_scout_web/schema/scalars.ex, apps/block_scout_web/lib/block_scout_web/schema/types.ex
* We'd like to document the hash lengths for the different hashes
(nonce, full, address) in graphiql.
* Adding `BlockScoutWeb.Schema.Scalars` with address_hash, full_hash,
and nonce_hash scalars.
* Editing `BlockScoutWeb.Schema.Types` for the `block` object to use the
new scalars.
* Moving the `Absinthe.Type.Custom` `import_types/1` call to
`BlockScoutWeb.Schema.Types` where it's actually being used at the
moment (for `:decimal`). It was in `BlockScoutWeb.Schema`.
=> Add custom GraphQL scalar types

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
Resolves: #986 
Add a visual indicator to the code tab that a contract has been verified.
- Add text color to the check icon in the code tab
=> Highlight code tab when a contract is verified

apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/holder_view.ex, apps/block_scout_web/test/block_scout_web/views/currency_helpers_test.exs, apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs, apps/block_scout_web/test/block_scout_web/views/tokens/holder_view_test.exs, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/priv/repo/migrations/20181029174420_update_tokens_table_decimals_from_bigint_to_numeric.exs, apps/explorer/test/explorer/chain/address/token_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/test/indexer/token/fetcher_test.exs
resolves #1002 
* now large values for decimals column won't break
* change type of field decimals to decimal
you can do either of the following
1. run `mix ecto.migrate`
2.  run the following query:
```sql
ALTER TABLE tokens
ALTER COLUMN decimals TYPE numeric;
```
=> Gsf increase limit of token decimals field

apps/block_scout_web/assets/css/_typography.scss, apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
- Color code the internal transaction type labels so that they are more easily recognizable.
- Add a signifying color to the type label within the internal transaction tile.
n/a
n/a
n/a
=> Color code internal transaction type labels

apps/block_scout_web/lib/block_scout_web/application.ex, apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex, apps/block_scout_web/lib/block_scout_web/endpoint.ex, apps/block_scout_web/lib/block_scout_web/event_handler.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/schema.ex, apps/block_scout_web/lib/block_scout_web/schema/types.ex, apps/block_scout_web/test/block_scout_web/schema/subscription/token_transfers_test.exs, apps/block_scout_web/test/support/subscription_case.ex
* We'd like to support a GraphQL API subscription that allows users to
subscribe to token transfers for a given token.
Example subscription document:
```
subscription ($hash: AddressHash!) {
token_transfers(token_contract_address_hash: $hash) {
amount
from_address_hash
to_address_hash
token_contract_address_hash
transaction_hash
}
}
```
* Adding an `Absinthe.Subscription` supervisor to BlockScoutWeb's
supervision tree.
* Adding `Absinthe.Phoenix.Endpoint` to `BlockScoutWeb.Endpoint`.
* Configuring `BlockScoutWeb.UserSocket` to use `Absinthe`.
* Configure GraphiQL to use `BlockScoutWeb.UserSocket`.
* Editing `BlockScoutWeb.EventHandler` to subscribe to
`:token_transfers` type chain events.
* Adding `BlockScoutWeb.Notifier.handle_event/1` function head to handle
`:token_transfers` events. …
=> GraphQL token transfers subscription

apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex, apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex, apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
resolves #1004 
* when the contract returns something of type `address` it'll be treated as such now
* doing the same for the type `address payable` as it is a [valid type in solidity](https://solidity.readthedocs.io/en/develop/types.html#address)
=> address type is printed weird on smart contracts

apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
* For BlockScout users to learn about our GraphQL API.
* Editing `_topnav.html.eex` template to include link to `/graphiql`.
* Fixing `/api_docs/index.html.eex` template to use "BlockScout" instead
of "Explorer".
=> Add GraphiQL link to topnav

apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/chain/import/address/current_token_balances.ex, apps/explorer/priv/repo/migrations/20181026180921_create_address_current_token_balances.exs, apps/explorer/test/explorer/chain/address/current_token_balance_test.exs, apps/explorer/test/explorer/chain/import/address/address/current_token_balances_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/token_balances_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/962
Querying against `address_token_balances` to fetch the last balance from a specific Address is very slow because we need to apply a distinct token and sort by the last block number. In Ethereum mainnet, this kind of query was taking 50s with 100 million token balances (we probably will have more than 1 billion 😱).
Since most of our use cases are knowing the last balance from address, I'm creating a new table called `address_current_token_balances` that will store only the current token balances based on the last block. We still will keep the `address_token_balances` since it will be useful in the future.
* Fix token balances fetcher to schedule requests that gave errors to be fetched again later.
* Create table …
=> Improve performance in token holders tab on Token's page

apps/block_scout_web/lib/block_scout_web/schema/types.ex, apps/block_scout_web/test/block_scout_web/schema/query/block_test.exs
* For GraphQL API consumers to be able to fetch the hash for a given
block.
Sample usage:
```
query ($number: Int!) {
block(number: $number) {
hash
}
}
```
* Editing the block object in `BlockScoutWeb.Schema.Types` to include a
hash field of type `:full_hash`.
=> Adds hash to GraphQL block object

apps/block_scout_web/lib/block_scout_web/resolvers/address.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/schema.ex, apps/block_scout_web/lib/block_scout_web/schema/scalars.ex, apps/block_scout_web/lib/block_scout_web/schema/types.ex, apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
* We'd like to support GraphQL API queries for getting single or
multiple addresses by hashes. API users could use this instead of the `balance` and `balancemulti` actions on the RPC API.
Sample document:
```
query ($hashes: [AddressHash!]!) {
addresses(hashes: $hashes) {
hash
fetched_coin_balance
fetched_coin_balance_block_number
contract_code
}
}
```
* Creating `BlockScoutWeb.Resolvers.Address` with a single resolver
function that gets addresses by a list of hashes.
* Adding `:data` scalar to `BlockScoutWeb.Schema.Scalars`.
* Adding `address` object type to `BlockScoutWeb.Schema.Types`. Uses new
`:data` scalar mentioned above.
* Adding `addresses` field to query in `BlockScoutWeb.Schema`. Uses the
new `address` object type and the resolver function mentioned above.
* Editing …
=> GraphQL API query to get addresses by hash

apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/1042
* For the schema to be available at `/graphiql`
* Changing GraphQL `max_complexity` from 50 to 200 for introspection to
be possible on GraphiQL.
* Editing test that relied on a `max_complexity` of 50.
=> Fix no schema on GraphiQL

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/947
Shorten `Chain.address_to_transactions/2` by removing the query that was `left outer join` with token transfers, making it way faster to be processed.
=> Optmize address transactions page

apps/block_scout_web/lib/block_scout_web/schema.ex, apps/block_scout_web/lib/block_scout_web/schema/scalars.ex, apps/block_scout_web/lib/block_scout_web/schema/scalars/JSON.ex, apps/block_scout_web/lib/block_scout_web/schema/types.ex, apps/block_scout_web/mix.exs, apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs, apps/explorer/lib/explorer/chain.ex, mix.lock
* For GraphQL API users to be able to get a `smart_contract` by
address. RPC API users could use this instead of the `getabi` and
`getsourcecode` RPC actions.
Example usage:
```
query ($hashes: [AddressHash!]!) {
addresses(hashes: $hashes) {
fetched_coin_balance
smart_contract {
name
compiler_version
optimization
contract_source_code
abi
address_hash
}
}
}
```
* Adding `jason` dependency. Needed for `JSON` scalar type.
* Adding `dataloader` dependency to help Absinthe efficiently load data
in batches.
* Editing `Schema` by adding `context` callback. It adds a dataloader
source to context.
* Adding JSON scalar type. Needed by `abi` field in `smart_contract`
object.
* Adding `smart_contract` object type.
* Editing `address` object type to include `smart_contract` field.
* Adding …
=> Add smart_contract field to address object

apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex
Resolves #1046 
* Tokentx API endpoint now shows Token ID as token value when retrieving ERC-721 tokens.
=> Add TokenID to tokentx API endpoint

apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/test/indexer/token_balance/fetcher_test.exs
closes #1007 
- import addresses along with token balances in case an address wasn't indexed yet for some reason
=> import addresses when importing token balances

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Resolves #1060
The pending transactions list on the address page is causing extremely slow page load speed on Ethereum Mainnet. A future issue #60 will remove many of these "pending" transactions which are not actually "pending". Many of these transactions are dropped/replaced and would be removed from this list.
Remove the pending transactions info from the address page.
=> Remove the 'pending transactions' from the address transaction page.

apps/block_scout_web/lib/block_scout_web/etherscan.ex
* For RPC API users to know the RPC actions that map to existing GraphQL queries.
* Editing RPC API docs to include GraphQL references for `balance`,
`balancemulti`, `getabi`, `getsourcecode`, `getstatus`,
and `gettxreceiptstatus` actions.
=> Add GraphQL API references to RPC API docs

apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/block_transaction/404.html.eex, apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
Resolves #36 
- Better messages when a block is not found in the system
- Shows the block is not yet indexed if below the tip of the chain
- Shows the block is not yet generated if above the tip of the chain
=> Add 404 page for not found blocks

README.md
The current project timeline link in the README points to a page that doesn't exist in the Wiki. Probably because the project changed names.
The link will now redirect users to the correct page.
=> Fix project timeline link on README

apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/invalid.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/not_found.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
closes #38
* show a 404 specific for transactions when the transaction was not found
* show a 422 page for transactions when the transaction hash is invalid
* 404
* 422
=> transaction not found page and transaction hash invalid page

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction.ex
The address page was taking a long time to load, and the server was failing with a 504.
The slow query was composed of several `where`s and limiting the result to the page size (51). For some reason, running all of the filters together was very slow. This solutions runs a separate query for each filter, limiting the result to the same number. Then, the results are merged, sorted and limited again. This is done in the backend because there are few rows involved, but it could be done using `UNION` and an outer query too.
Notice that the queries are done sequentially. This could be further improved if each query is done in parallel.
=> Fix performance issue in address page

apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
Fixes #1082
Preloads `smart_contract` from `transaction` `to_address`.
=> Fix pattern matching error when transaction does not loads to_address.smart_contract

apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/internal_transaction_view_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/calls.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex, apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth/call_test.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth/calls_tests.exs, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/internal_transaction.ex, apps/explorer/lib/explorer/chain/internal_transaction/type.ex, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/priv/repo/migrations/20181107164103_eip6.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/lib/indexer/address/coin_balances.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/test/indexer/address/coin_balances_test.exs
Resolves #930
* Adopt [EIP-6](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6.md).  Geth has EIP-6, while Parity does not, but the Ethereum Yellow Paper includes EIP-6, so it is better to use EIP-6 when looking up community docs.
* Geth internal transactions
Get internal transactions using debug_traceTransaction and a custom tracer.  The tracer was based on the callTracer that ships with Geth, but rewritten to break it into more functions with more explicit purpose and to patch some holes in `callTracer`:
* All calls have gas and gasUsed, which patches the hole in `callTracer` for handling `DELEGATECALL`.
* All calls have value, which patches the hole in `callTracer` for handling `DELEGATECALL` and `STATICALL`.
Since the tracer needed to be resubmitted in whole anyway, it was …
=> Geth internal transactions

apps/ethereum_jsonrpc/mix.exs
This dependency was only being set to test and every time we tried to open an iex an error was raised.
**ethereum_jsonrpc**
```
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
** (Mix) Could not start application cowboy: could not find application file: cowboy.app
```
**explorer**
```
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Compiling 83 files (.ex)
Generated explorer app
** (Mix) Could not start application cowboy: could not find application file: cowboy.app
```
* Include `cowboy` as a `dev` dependency in the `ethereum_jsonrpc` app.
=> Add `dev` dependency to cowboy in the `ethereum_jsonrpc` app

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
* Support Parity 2.1 `pending` tag output: it returns `number: null` instead of `null` or an error.
=> Support Parity 2.1 pending tag output

apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, apps/indexer/test/indexer/token_balance/fetcher_test.exs, apps/indexer/test/indexer/token_balances_test.exs
Closes https://github.com/poanetwork/blockscout/issues/1093
For ignoring those token balances, we added a `retries_count` to `TokenBalance.Fetcher` consider whether it should be retried or not based on the number configured in `:token_balance_max_retries` within `apps/indexer/config.exs`
* Ignore tokens balances that raised errors according to the configured number
* Add a new log to see how many token balances will be retried
* Fix log of token balances that raised errors
=> Improve TokenBalance.Fetcher to ignore the ones that always raise errors

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/767 but note that @KronicDeth will be introducing, in an upcoming PR, a more involved approach to fixing this that will prevent these type of bugs from slipping through the cracks if Parity changes again in the future. As of this writing you can see Luke's changes here: https://github.com/poanetwork/blockscout/commit/2d0b0db1dd3ca8e4ccb6846c4237fd1f82e2b831
* For the indexer to update block reward contract beneficiaries for all
types (e.g. block, external, uncle, etc). For details on Parity's reward
types please see:
https://github.com/paritytech/parity-ethereum/blob/0f90696528e11e3e697a808e2d7983b9733d02bc/rpc/src/v1/types/trace.rs#L299-L308
=> fetch_beneficiaries/2 works with all reward types

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/test/explorer/chain/token_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/config/config.exs, apps/indexer/lib/indexer/token/metadata_updater.ex, apps/indexer/lib/indexer/token/supervisor.ex, apps/indexer/test/indexer/token/metadata_updater_test.exs
Closes #959 
After a token is indexed, there was no checking for possible metadata changes like total supply.
- System will request and uptade all cataloged tokens' functions on start
- The operation above will rerun every `:metadata_updater_days_interval` days
=> Async task to check token metadata

apps/block_scout_web/assets/js/pages/address.js
closes #1092
The validation count number was being wrongly updated at the page loading.
* Fix typo in `validation count` `load`.
=> Fix typo in "validation count" reducer when loading state.

apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex, apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/priv/repo/migrations/20181121170616_add_block_number_to_token_transfers.exs, apps/explorer/priv/repo/migrations/scripts/20181121170616_token_transfers_update_block_number_in_batches.sql, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/token_transfer_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Fixes https://github.com/poanetwork/blockscout/issues/1053
* Denormalized the `block_number` from the transaction to token transfers to avoid joins with the transactions' table and block's table.
* Paginates the results using the `block_number` and the `log_index`. It was using the `inserted_at` that would make the pagination inconsistent.
* The application will be able to open tokens that have several transfers.
* This need run the migration to add the `block_number` column at token transfer's table. You may need to run the script that copies the `block_number` from the transactions' table to token transfers' table
* Token tested: `0xd2f81cd7a20d60c0d558496c7169a20968389b40`
* Old query: 6s
* New query: 400ms
Also, sometimes the page didn't open when the users' click on the next page …
=> Fix performance issue at token transfers tab on Token's page

apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Closes #1084  
- Address token transfers now load first page asynchronously.
- Remove feature test for address token transfers page (see #1136)
- This test was inconsistent and not really adding any kind of validation to the codebase.
- It'd fail on CI in passing conditions and pass on local environment even when adding wrong asserts.
=> Async load in token transfers at adress page

apps/block_scout_web/assets/package-lock.json
Resolves #1037
The `jest` js lib we are using to write tests had a dependency that needed to be updated due to a security vulnerability.
* Fixed the dev dependency with `npm audit fix --only=dev`
=> Update npm dependencies

apps/explorer/lib/explorer/chain/internal_transaction/type.ex, apps/explorer/priv/repo/migrations/20181107164103_eip6.exs, apps/explorer/priv/repo/migrations/20181108205650_additional_internal_transaction_constraints.exs, apps/explorer/priv/repo/migrations/scripts/20181107164103_eip6.sql, apps/explorer/priv/repo/migrations/scripts/20181108205650_additional_internal_transaction_constraints.sql
Fixes #1109
Fixed #1112
* Separate schema and data migration for EIP-6. Use `NOT VALID` on constraint and don't put data updates in schema migration.  Instead, migrate data using script based on @amandasposito's scripts.
* Separate schema and data migrations for #1094.
1. `mix ecto.migrate`
2. `psql -d $DATABASE -a -f apps/explorer/priv/repo/migrations/scripts/20181107164103_eip6.sql`
3. `psql -d $DATABASE -a -f apps/explorer/priv/repo/migrations/scripts/20181108205650_additional_internal_transaction_constraints.sql`
=> Allow gradual data migration after schema and code is deployed

apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/resolvers/internal_transaction.ex, apps/block_scout_web/lib/block_scout_web/resolvers/transaction.ex, apps/block_scout_web/lib/block_scout_web/schema.ex, apps/block_scout_web/lib/block_scout_web/schema/scalars.ex, apps/block_scout_web/lib/block_scout_web/schema/types.ex, apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs, apps/block_scout_web/test/block_scout_web/schema/query/node_test.exs, apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs, apps/explorer/lib/explorer/graphql.ex, apps/explorer/test/explorer/graphql_test.exs
* For GraphQL API users to be able to get internal transactions. RPC API
users could use this instead of the `txlistinternal` RPC API action.
Example usage:
1.
```
query ($hash: FullHash!, $first: Int!) {
transaction(hash: $hash) {
internal_transactions(first: $first) {
edges {
node {
index
value
block_number
transaction_index
from_address_hash
to_address_hash
}
}
}
}
}
```
2. with pagiantion support via [Relay Cursor Connections](https://facebook.github.io/relay/graphql/connections.htm)
```
query ($hash: AddressHash!, $first: Int!, $after: ID!) {
transaction(hash: $hash) {
internal_transactions(first: $first, after: $after) {
page_info {
has_next_page
has_previous_page
}
edges {
node {
index
transaction_hash
}
cursor
}
}
}
}
```
* Editing the node interface and node field in …
=> GraphQL supports querying internal transactions

apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex, apps/explorer/lib/explorer/counters/block_validation_counter.ex, apps/explorer/test/explorer/chain/address_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/addresses_with_balance_counter_test.exs
Resolves #972
The wallet addresses count is being done [using the Explain Analyze command in order to improve performance](https://www.citusdata.com/blog/2016/10/12/count-performance?source=pg_weekly#dup_counts_estimated)
Even though the performance is good enough the result is highly inaccurate. The number can be seen at the [Home Page](https://blockscout.com/poa/core/) in the `Wallet addresses`, and in the [Accounts Page](https://blockscout.com/poa/core/accounts) in the `total addresses with a balance`.
* Add a new counter to cache the addresses with fetched coin balance > 0.
=> Add a cache to count the addresses with balance > 0.

apps/block_scout_web/lib/block_scout_web/plug/allow_iframe.ex, apps/block_scout_web/lib/block_scout_web/router.ex
* For our partners to be able to open BlockScout in an iframe.
* Creating `AllowIframe` plug.
* Editing router to have a new scope for write-only routes and a
separate one for read-only routes which allows for iframes (using the
plug mentioned above).
(This comment was edited to reflect the latest changes, after the conversation below.)
=> Allows other sites to open blockscout in iframe

apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Resolves [#1080](https://github.com/poanetwork/blockscout/issues/1080)
Top accounts page can contain addresses with primary names. This PR allows to display them on the page.
Address will be trimmed on small screen:
* Add primary names to the top accounts page
* Display trimmed address only if truncate variable is set to true or on small screens
=> Add primary names to accounts page

apps/block_scout_web/assets/__tests__/pages/transactions.js, apps/block_scout_web/assets/js/pages/transactions.js, apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
Closes https://github.com/poanetwork/blockscout/issues/1142
As we did in other pages that have a list of items, we removed the infinite scroll and make the first load async.
* The `Older button` is back
* When it receives a batch of transactions
* When it receives a new transaction
* Visit the page `/txs`
* Make some transaction in the network that your server is indexing and check if this transaction will be added on the top of the list. It shouldn't happen if the user is beyond the first page.
* Check if when a batch of transactions comes in, it will show a message like the one above in the PR description.
=> Refactor transactions page

apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_coin-balance-tile.scss, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/js/lib/coin_balance_history_chart.js, apps/block_scout_web/assets/js/lib/market_history_chart.js, apps/block_scout_web/assets/js/pages/address/coin_balances.js, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_by_day_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/event_handler.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/_coin_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_coin_balance_view.ex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/address_coin_balance_by_day_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/block_scout_web/test/block_scout_web/views/address_coin_balance_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/coin_balance.ex, apps/explorer/test/explorer/chain/address/coin_balance_test.exs, apps/explorer/test/explorer/chain_test.exs
Closes #433.
Add a tab to the address page showing the coin balance history for that address. There are two components in this tab: a chart showing how the balance changed in the last 90 days and a list of changes, each item being a block where the balance changed.
- List
- The list is loaded asynchronously.
- The list has simple paging. When you go to a previous page, only the list is updated.
- If a new block appears with a coin balance change for this address, it should show up in real time, but only in the first page.
- Chart
- The chart should load asynchronously.
- Each point in the chart show the max balance of that accound in that day.
- Days where the balance remained constant are not shown as points of the chart.
- The chart only shows information for the past 90 days.
=> Add balance history tab to address page

apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/assets/js/socket.js
Fixes https://github.com/poanetwork/blockscout/issues/1188
The balance update stopped working because the client was trying to subscribe twice in the channel topic. When the server receives a duplicated subscription, he closes the first connection to open a new
one.
See more about it: https://hexdocs.pm/phoenix/js/#phoenix
In our case, the client subscribed in the address channel in `address.js` and `transactions.js`, then the server was keeping only the last subscription.
=> Fix realtime address balance update

apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
resolves #1165
* limit the width of the addresses and names by truncating the excess text
=> fix overlapping names on token transfers

apps/block_scout_web/assets/css/components/_nav_tabs.scss, apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_validation_view.ex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Fixes https://github.com/poanetwork/blockscout/issues/1203
It was happening because the Blocks Validated page wasn't using the `address/_tabs.html` partial.
* User will see all tabs on the Block validated page.
* Decrease tabs padding
* Block Validated page
* All tabs in the same line thanks to the new padding
=> Fix Block Validated page to show all tabs

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/counters/block_validation_counter.ex, apps/explorer/lib/explorer/counters/token_holders_counter.ex, apps/explorer/lib/explorer/counters/token_transfer_counter.ex, apps/explorer/lib/explorer/repo.ex, apps/explorer/test/explorer/chain/token_transfer_test.exs, apps/explorer/test/explorer/chain_test.exs
Related to #1159.  Extracted from #1185.
* Have all uses of `Repo.stream` use new `Repo.stream_in_transaction`, so that none of them miss the `:infinite` timeouts if they are copied for a new one later.
* Instead of collecting everything with `Repo.all` before inserting into ETS tables, use `Repo.stream_each` to stream rows into ETS tables.  This will let data appear in the ETS table before all rows are returned from the database, so the readers will appear more responsive on restart.
* `Explorer.Counters.TokenTransferCounter`
* `Explorer.Counters.BlockValidationCounter`
* `Explorer.Counters.TokenHoldersCounter`
=> ETS streaming

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex, apps/indexer/lib/indexer/block/invalid_consensus/worker.ex, apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/supervisor.ex, apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/1181
* We noticed some blocks with invalid consensus values on Goerli.
* Editing the realtime fetcher to check, after insertion to DB, a
block's parent consensus value and trigger a refetch for that block
number if consensus is `FALSE`.
* Creating `Indexer.Block.Realtime.ConsensusEnsurer` module, where logic
to ensure a given block has consensus lives.
* Adding `list_block_number_with_invalid_consensus/0` to
`Explorer.Chain` to get block numbers with invalid consensus from DB.
* Adding `Indexer.Block.InvalidConsensus.Worker` to find blocks with
invalid consensus and queue them for refetching.
=> Ensures consensus is valid for parent blocks

.credo.exs, apps/block_scout_web/config/config.exs, apps/ethereum_jsonrpc/config/config.exs, apps/explorer/config/config.exs, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/uncle/fetcher.ex, apps/indexer/lib/indexer/buffered_task.ex, apps/indexer/lib/indexer/coin_balance/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/lib/indexer/pending_transaction/fetcher.ex, config/config.exs
Extracted from #1185.
```
2018-12-12T10:08:55.263 application=indexer fetcher=block_realtime [error] failed to fetch blocks for block 6069836: :timeout.  Block will be retried by catchup indexer.
^^^^^^^^^^^^^^^^^^^^^^
```
The underlined  (`^`) part is the new part of the format.
It works in a `BufferedTask` like `InternalTransaction.Fetcher` too
```
2018-12-12T10:08:18.621 application=indexer fetcher=internal_transaction [debug] fetching internal transactions for 10 transactions
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
* For each fetcher set the `Logger.metadata(fetcher: ...)` to a short semantic name.  Having the fetcher names allow faster triaging of bugs when a stacktrace is not present.  It also allows filtering logs by the fetcher in log analysis tools.
* For Fetchers that use …
=> Include fetcher in logger metadata

apps/block_scout_web/assets/js/lib/token_balance_dropdown.js, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/address/token_balance.ex, apps/explorer/test/explorer/chain/address/current_token_balance_test.exs, apps/explorer/test/explorer/chain_test.exs
Closes #1026.
This PR changes how the token balances of a specific addresses are obtained. The `address_token_balances` table was used before, now `address_current_token_balances` is used.
This significantly improves the performance of this query. For example, the time for a request (for a user with ~25 tokens) went down from 12 seconds to 3 seconds.
I also noticed that the request was being sent twice. I think this was caused because the `token_balance_dropdown.js` module was calling the function when it was imported. I don't think this is necessary, since the render function of the component was already doing this.
- The correct list of token balances is shown in the token balances dropdown.
- Each token has a link to the proper token page.
=> Improve token balances fetching for specific addresses

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token_transfer.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/priv/repo/migrations/20181212115448_add_indexes_to_token_transfers.exs, apps/explorer/test/explorer/chain/token_transfer_test.exs, apps/explorer/test/explorer/chain_test.exs
Resolves #1183
The `address` `transaction` listing (with an `address`  that has 7MM `transactions`) is loading within 7s using a db similar to the ethereum mainnet.
Normal addresses continue to load quickly as well
When a token is sent, the recipient (to) address of the token transfer is not seeing the token transfer on the transactions tab. 
* The bug was that only the first transaction that had token transfers was being shown.
=> Fix Address Trasaction query

apps/block_scout_web/config/config.exs, apps/ethereum_jsonrpc/config/config.exs, apps/explorer/config/config.exs, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher/receipts.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/uncle/fetcher.ex, apps/indexer/lib/indexer/coin_balance/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/lib/indexer/logger.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex, config/config.exs
Extracted from #1185
* Move chartable data out of human-readable prose and into logger metadata for easier extraction by log analysis tools.
* `block_number` - the block number being fetched by the realtime indexer
* `count` and `error_count` - the number of entries being fetched and those of count that had errors.
* `first_block_number` and `last_block_number` - numbers in `first_block_number..last_block_number` search range for catchup block fetcher to find missing blocks.
* `missing_block_range_count` - the number of ranges found in the search range.  More ranges for the same `missing_block_count` indicates the indexer is leaving more holes.
* `missing_block_count` - the total number of missing blocks found in the search range for the catchup block fetcher.
* `shrunk` - whether the …
=> Metadata instead of prose

apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Fixes #1216
* Log timeout in `PendingTransaction` fetcher instead of crashing
=> Log timeout in PendingTransaction fetcher instead of crashing

apps/indexer/lib/indexer/token_balances.ex
Fixes #1215
* The short-circuiting `[]` was not being used for `Indexer.TokenBalances.fetch_token_balances_from_blockchain` due to the use of `/1` and `/2` with a default.
=> Fix picking wrong clause for fetch_token_balances_from_blockchain

apps/indexer/lib/indexer/block/invalid_consensus/worker.ex, apps/indexer/lib/indexer/token_transfer/uncataloged/worker.ex
Fixes #1223
*  For large chains like ETH Mainnet, it is fairly common for the catchup fetcher to take a long time to calculate the missing block numbers and start the named Sequence used by `push_front(block)`.  Since this is normal and not exceptional, `InvalidConsensus.Worker` shouldn't log this and retry silently.
=> Don't log when queue is unavailable in Indexer.Block.InvalidConsensus.Worker

apps/explorer/lib/explorer/chain.ex
`Explorer.Chain.missing_block_number_ranges/1` takes minutes to 10s of minutes to return for the Ethereum Mainnet DB.
* Use lag windowing function to reduce missing block time
Ecto 3.0 gets us easy access to partitions and the windowing function `lag`.  `lag` is able to keep track of the previous row without a self-join.  Importantly, the new query with `lag` and no more `generate_series` completes in ~2.5 seconds on Ethereum mainnet using `:timer.tc(Explorer.Chain, :missing_block_number_ranges, [6889126..0])` on ETH Mainnet test DB 40 while the old version doesn't return after 5+ minutes.
I've heavily commented the new version of the query since this took awhile to figure out and most importantly finding the proper terminology: "gaps and islands" was key to find the starting query using …
=> Use lag windowing function to reduce missing block time

apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Fixes #1232
Port from #1185.
* `{:error, :timeout}` should have been caught, but additionally, it should never have been allowed to propagate out unassigned to a step as it is not possible to track the timeout to a specific fetch.
=> Label all steps in Block.Fetcher implementations

apps/indexer/lib/indexer/block/fetcher.ex
Fixes
```
2018-12-17T13:55:29.652 application=indexer fetcher=block_catchup first_block_number=6561714 last_block_number=6561714 [error] ** (WithClauseError) no with clause matching: {:import, {:error, :derive_transaction_forks, %Postgrex.Error{connection_id: 16967, message: nil, 
```
* Missed error pattern change in #1233
=> Missed error pattern change in #1233

apps/explorer/lib/explorer/repo.ex
Fixes #1238
* Use `reraise` and `__STACKTRACE__` as `reraise` is the current accepted idiom for reraising, not `raise` alone as it preserves the original stacktrace.
=> Use reraise and __STACKTRACE__ to reraise safe_insert_all errors

.credo.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/chain/import/runner.ex, apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex, apps/explorer/lib/explorer/chain/import/runner/block_rewards.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/logs.ex, apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/chain/import/stage.ex, apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex, apps/explorer/lib/explorer/chain/import/stage/addresses.ex, apps/explorer/lib/explorer/logger.ex, apps/explorer/lib/explorer/repo.ex, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
Ported from #1185.
* Stages will be between Import and the `Import.Runner`.  Unlike `Runner`s, which use 1 common `Ecto.Multi`, a `Stage` can produce 1 or more independent `Ecto.Multi` that will run in separate transactions.  
This allows addresses to be chunked into separate transactions, which releases the locks between transactions unlike the `INSERT`-level chunking that was all in 1 transaction.
=> Import stages

apps/block_scout_web/lib/block_scout_web/templates/address/_validator_metadata_modal.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/address/name.ex, apps/explorer/lib/explorer/validator/metadata_importer.ex, apps/explorer/lib/explorer/validator/metadata_processor.ex, apps/explorer/lib/explorer/validator/metadata_retriever.ex, apps/explorer/priv/repo/migrations/20181213111656_add_metadata_field_to_address_names.exs, apps/explorer/priv/validator_contracts_abi/metadata.json, apps/explorer/priv/validator_contracts_abi/validators.json, apps/explorer/test/explorer/validator/metadata_importer_test.exs, apps/explorer/test/explorer/validator/metadata_retriever_test.exs
closes #984 
* fetch metadata from validators' contracts and save it to the database
* modal that shows the info of a validator on the address page
---
*obs: data on the screenshots does not represent information on a real validator
=> validator metadata retrieval and display

apps/explorer/lib/explorer/chain/import.ex, apps/explorer/lib/explorer/repo.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/uncle/fetcher.ex
Resolves #1251
```
2018-12-17T14:52:29.991 application=db_connection [error] Postgrex.Protocol (#PID<0.994.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2264.0> timed out because it queued and checked out the connection for longer than 120000ms
2018-12-17T14:52:30.023 application=explorer fetcher=block_catchup first_block_number=6905195 last_block_number=6905191 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Address.TokenBalance using options because of error.
Chunk:
[...]
Options:
[...]
Exception:
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
2018-12-17T14:52:30.026 application=indexer fetcher=block_catchup first_block_number=6905195 …
```
=> Convert DBConnection.ConnectionError tcp recv: closed to {:error, :timeout}

apps/indexer/lib/indexer/block/fetcher.ex
* Accidentally used `step` variable twice when the actual error is like `{:import, {:error, import_step, ..., ...}` which would only allow `{:import, {:error, :import, ..., ...}`.
=> Don't use step variable twice

apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex
* Normally, it is good idea to only query the database once no matter the number of sockets for a channel, but most addresses don't have listeners, so it is cheaper to not query unless the channel is in use.
If we start to see popular addresses, [con_cache](https://hex.pm/packages/con_cache) can be used to only do the query once across all connected sockets for the same address.
=> Only query for coin balance when channel connected

apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex, apps/block_scout_web/lib/block_scout_web/views/block_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/block_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/block/reward.ex, apps/explorer/mix.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Resolves #23
Displays the reward value in the block tile at the home page, block details page and the address block validated page.
In the tile shows the combined reward value, and at the block details page shows the reward value detail.
* Add `:dev` dependency to `plug_cowboy` at the `explorer`, so `iex` can start.
=> Add reward value of a block in the tile and overview section.

apps/block_scout_web/config/config.exs, apps/ethereum_jsonrpc/config/config.exs, apps/explorer/config/config.exs, apps/indexer/config/config.exs, config/config.exs
* When `import_id` and `transaction_id` was added in `Logger` calls in #1242, they were not added to the `:metadata` allowed to be shown and so weren't appearing in the logs.
You can use the `import_id` key to see all DB transactions and queries used in one `Explorer.Chain.import` call.   This allows to calculate the elapsed time and how much each query is taking of that time.
=> Include import_id and transaction_id in logger metadata

apps/ethereum_jsonrpc/test/ethereum_jsonrpc/rolling_window_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex, apps/explorer/lib/explorer/chain/import/runner/block_rewards.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/logs.ex, apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/validator/metadata_importer_test.exs, apps/explorer/test/explorer/validator/metadata_retriever_test.exs, apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
* When the `ON CONFLICT` clause is triggered, it still causes a new tuple in Postgres to be written even if the value of all the columns is the same.  Making a new tuple means that the table needs to be vacuumed sooner and leads to more work and churn for the database and its storage.  But, there is a way to prevent this unnecessary churn: Postgres supports a `WHERE` clause on the `ON CONFLICT DO UPDATE` that allows us to not write a new row if the data would be the same.
While testing this, it already showed it can prevent unnecessary updates to the `tokens` table when the `MetadataUpdater` is running.
=> Use where clause for on_conflict to only write tuples that are different

apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs, apps/explorer/config/config.exs, apps/explorer/config/dev.exs, apps/explorer/config/dev/ganache.exs, apps/explorer/config/dev/geth.exs, apps/explorer/config/dev/parity.exs, apps/explorer/config/prod.exs, apps/explorer/config/prod/ganache.exs, apps/explorer/config/prod/geth.exs, apps/explorer/config/prod/parity.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/chain/import.ex, apps/indexer/config/dev/ganache.exs, apps/indexer/config/dev/geth.exs, apps/indexer/config/dev/parity.exs, apps/indexer/config/prod/ganache.exs, apps/indexer/config/prod/geth.exs, apps/indexer/config/prod/parity.exs, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/sequence_test.exs
* Use `:timer` functions to make timeout values clearer
*  Increase DB transaction timeout to 4 minutes.  This prevents DB timeouts against Eth Mainnet for stretches of 20 minutes when testing with block concurrency of 5 and block batch size of 5 while production is simultaneously running at 12x12.
=> Increase DB transaction timeout to account for Eth Mainnet performance

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Fixes #1262
* Regression test for #1262
* Add `ON CONFLICT` to `derive_transaction_forks`.  It did not have one because it was custom SQL and was missed when doing the updated `on_conflict` with queries pass.
=> Add ON CONFLICT to derive_transaction_forks

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Fixes #1266
* Regression test for #1266
* Allow block numbers to exceed missing block search range by > 1.
#1266 was triggered when the recorded block number exceeded the reported max block number as can happen temporary when the node that gives the latest block number is farther behind than the node that gave the block data.
The previous `Explorer.Chain.missing_block_number_ranges` query added in #1230 did not account for the max block number in the database exceeding the range max.  When this occurs, an errant range was produced by the #1230 query because it chose the greatest of the range and the max block when trying to find the end point for the gap search.
The testing did not catch #1266 because the doctests only used block numbers that exceeded the search range, by 1 and the bug …
=> Allow block numbers to exceed missing block search range by > 1

README.md, rel/vm.args
This will keep the explorer running in the case that the entire system crashes.
Enable the `-heart` option.
In order for `-heart` to do anything at all, an environment variable called `HEART_COMMAND` must be set. Additional environment variables can be set to configure its behavior, all of which are documented here: http://erlang.org/doc/man/heart.html
Questions:
Do we want to configure any of these by default? We might just want to make it entirely opt in behavior. Many systems rely on letting machines crash (for instance docker/kubernetes based architectures), so adding something like `-heart` would be an unwelcome change to those kinds of architectures.
=> feat: restart on heartbeat timeout

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/chain/wei.ex, apps/explorer/test/explorer/chain/block_test.exs, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/chain/wei_test.exs, apps/indexer/lib/indexer/block/supervisor.ex, apps/indexer/lib/indexer/block/uncataloged_rewards/importer.ex, apps/indexer/lib/indexer/block/uncataloged_rewards/processor.ex, apps/indexer/test/indexer/block/uncataloged_rewards/importer_test.exs
will resolve #1198
* added a multiplication operation to Wei(used in the importer)
* find blocks without reward
* import rewards for blocks without them
* if all blocks have rewards, check again in the next 24 hours in case something caused a gap
=> get rewards of blocks already indexed without rewards

apps/block_scout_web/assets/js/lib/currency.js, apps/block_scout_web/assets/js/lib/token_balance_dropdown.js, apps/block_scout_web/config/test.exs, apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex, apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs, apps/block_scout_web/test/block_scout_web/views/currency_helpers_test.exs, apps/block_scout_web/test/block_scout_web/views/tokens/overview_view_test.exs, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/known_tokens/known_tokens.ex, apps/explorer/lib/explorer/known_tokens/source.ex, apps/explorer/lib/explorer/known_tokens/source/my_ether_wallet.ex, apps/explorer/lib/explorer/market/market.ex, apps/explorer/test/explorer/known_tokens/known_tokens_test.exs, apps/explorer/test/test_helper.exs, config/test.exs
Closes #1237.
Show the token price for some known tokens. It uses the JSON given in the issue description for mapping addresses to token symbols. This means that if we have two tokens with the same symbol but different address, only one of them (if any) should show the associated price.
- The tokens tab in the address page should show the token price for the known tokens.
- The token balances dropdown should show both the unit price and the total balance in USD for that token (if a token has a price of $2 and the account has 100 tokens, it should show $200).
- The token page should show both the unit price of the token, and the market cap for that token (total supply times unit price).
=> Show token price in USD

apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/token_balance/fetcher.ex, apps/indexer/lib/indexer/token_balances.ex
Fixes #1295
* Move uniquifiation of address current token balances out of runner. For all other runners, it is the responsibility of the caller to ensure unique entries.  This ensures that the least amount of data as possible is sent to `Explorer.Chain.Import.all`, which speeds up the whole import process.
* Include block number when ordering token balances. The block number matters for ordering as a token can be updated for an address multiple times across different blocks in one insert.
* Order current token balance inserts to prevent deadlock
=> Order current token balance inserts to prevent deadlock

apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/mix.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/average_block_time_test.exs
Resolves (at least partially) #1288
* Store a running list of the last 100 block numbers and timestamps, and use that for the basis of calculating average block time. It also keeps itself up to date by also accepting a block as an argument, which it will incorporate into this and future calculations.
Currently its a pretty naive rolling calculation. I need to consider things like: 1.) could an already published block number be published as a new block again? If so, I need to make sure its not already in the list. 2.) Need to add a few tests.
Per feedback from @KronicDeth I've removed the expensive database fallback, and instead don't show the data if it is disabled.
=> feat: store averge block time in a genserver

apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs, apps/block_scout_web/test/support/feature_case.ex
There are some warnings/errors when we try to run the blockscout_web test suit, and it happens because there are some tests that need to be `async:false` and also there is a config missing in the `test/support/feature_case.ex`, so it shares the connection when it is needed.
Error example:
```
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.1089.0>.
When using ownership, you must manage connections in one
of the four ways:
* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process
The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.
The third option requires a …
```
=> Fix test warning db connection error

apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/uncle/fetcher.ex, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/block/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Resolves #1287
* For simple value transfers, the UI already doesn't show the redundant single internal transaction, but we can speed up the indexing by determine the internal transactions aren't needed when the transacion is a successful simple value transfer as determined by status being `:ok` and the input being empty (`0x`).
=> Don't fetch or import internal transactions for successful value transfers

apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Resolves #1303
* Don't fetch internal transactions for transactions that have token transfers from the logs if the status is `:ok` and the transaction did not create a contract.
=> Don't fetch internal transactions for simple token transfers

apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/lib/explorer/counters/average_block_time_duration_format.ex, apps/explorer/test/explorer/counters/average_block_time_test.exs
The recent changes for average block time performance brought to mind some things we could do better in rendering that average block time. I had to write a custom formatter which is a bit overkill, but this will give us a standard format with more accuracy than we had before.
* Render average block time out to one decimal place.
=> feat: render block time with up to one decimal point of accuracy

apps/explorer/lib/explorer/chain/block.ex, apps/explorer/test/explorer/chain_test.exs
Fixes #1310
* Regression test for #1310
* Switch reward factory to use build association idiom. `ExMachina` works better if we build associations with `build` instead of setting foreign keys.
* Restrict `Explorer.Chain.Block.get_blocks_without_reward` to consensus.
=>  Restrict `Explorer.Chain.Block.get_blocks_without_reward` to consensus

apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs
Fixes #1277
* Fix tests to use array order instead of name order to expose #1277.
* Order topics by array order, not name order in RPC API.
=> Order topics by array order, not name order in RPC API

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace/action.ex
Resolves #1115
* Guard against `nil` in `Parity.Trace.Action` input.
=> Guard against nil in Parity.Trace.Action input

apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Fixes #1311
* Prevent deadlocks due to order in the `SELECT transaction` for `Explorer.Chain.Import.Runner.Blocks.derived_transaction_forks` differing from order in `Explorer.Chain.Import.Runner.Transactions.insert` by sorting both by hash ascending.
=> Order derive_tranactions_forks SELECT to match transaction inserts

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/explorer/chain/import_test.exs
Fixes #1320
* Regression tests for #1320.
* Update `address_current_token_balances` and `address_token_balances` to remove those referencing replaced block numbers during reorgs.
1. Delete any `address_token_balances` with matching consensus block number.
2. Delete any `address_current_token_balances` with matching consensus block number.
3. Derive `address_current_token_balances` for any deleted in (2).
=> Update `address_current_token_balances` and `address_token_balances` to remove those referencing replaced block numbers during reorgs

apps/explorer/lib/explorer/counters/average_block_time.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex
Polling is swamping the db connections and also is causing us to reimport new blocks multiple times.
* Only schedule the next poll after the import of one poll is completed.
* Only import blocks that are new
* reschedule polling if we get a new head
* Change poll time to be 2 * average_block_time
* When we get a block in the avereage_block_time server, we don't do anything if we already have that block number.
=> fix: poll on import completion and only new blocks

apps/block_scout_web/assets/css/components/_footer.scss, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Part of #1344
* Improve the utility of the footer.
* Add a configurable list of other networks to link to.
* Use this information in the top right network drop down.
* Use this information in the footer.
* In both cases, the order of the configured list is honored.
* Look for an environment variable at compile time called `BLOCKSCOUT_VERSION`.
* Render this information in the footer.
* Add some basic but helpful information to the "Submit an Issue" link, including:
* Elixir Version
* Erlang Version
* User Agent
* BlockScout version (as supplied with the `BLOCKSCOUT_VERSION` environment variable)
* Add a configurable list of other explorers to link to. This can be turned on by changing it in `block_scout_web/config/config.exs` or by setting the environment variable …
=> feat: better footer, configurable network list

apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/priv/repo/migrations/20190114204640_add_tokens_holder_count.exs, apps/explorer/priv/repo/migrations/scripts/update_new_tokens_holder_count_in_batches.sql, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/support/chain/import/runner_case.ex
Fixes #1328
* `Token` `holder_count` stores `Explorer.Chain.count_token_holders_from_token_hash`, so it does not need to be recalculate for all runs.  The `holder_count` is `nil` and must be initialized with a data migration.  Since we know `count_token_holders_from_token_hash` across all tokens takes ~90
minutes the `token.holder_count` will be checked first, but if it is `nil`, `count_token_holders_from_token_hash` will still be called, which means the code can be deployed and the data migrations run in the background without blocking further deploys.
* When `CurrentTokenBalance`s change due to blocks being reorged in `delete_address_current_token_balances` and `derive_address_current_token_balances`, whether an `address_hash` is a holder can change, which means the token holder_count …
=> Store and maintain Explorer.Chain.count_token_holders_from_token_hash in tokens.holder_count

apps/block_scout_web/assets/css/components/_footer.scss
The footer will scale to the size of the image without this. This keeps it to a good size for the footer logo.
Wrong:
Fixed:
=> fix: add height for footer logo

apps/explorer/lib/explorer/chain/import/runner/tokens.ex, apps/explorer/test/explorer/chain/import/runner/tokens_test.exs
Fixes #1359
* Set Token `holder_count` to `0` for new tokens.  If there is a conflict, then the token is not new and existing `holder_count` is not overridden.  This ensures that pre-existing tokens that haven't been data migrated are kept as `holder_count` `NULL` and migrated tokens or new tokens passing through this change leave the `holder_count` unchanged.
=> Set Token holder_count to 0 for new tokens

apps/explorer/priv/repo/migrations/scripts/insert_address_current_token_balances_in_batches.sql
Fixes #1345
The number of `address_current_token_balances` that are missing because of the cause of #1345.
```sql
SELECT COUNT(*)
FROM (
SELECT DISTINCT token_contract_address_hash,
address_hash
FROM address_token_balances
EXCEPT
SELECT token_contract_address_hash,
address_hash
FROM address_current_token_balances
) AS address_token_balances_without_current
INNER JOIN address_token_balances
USING (token_contract_address_hash, address_hash)
WHERE value IS NOT NULL
```
The `(token_contract_address_hash, addres_hash)` pairs that are missing a `address_current_token_balances` because of the cause of #1345.
```sql
SELECT address_token_balances.token_contract_address_hash,
address_token_balances.address_hash
FROM (
SELECT DISTINCT token_contract_address_hash,
address_hash
FROM …
```
=> Make insert_address_current_token_balances_in_batches only insert new

apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/phoenix/html/safe.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex, apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex, apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex, apps/block_scout_web/test/block_scout_web/features/pages/transaction_logs_page.ex, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/test/explorer/chain/address_test.exs, apps/indexer/test/indexer_test.exs
Resolves #1125
* To be consistent with other explorers, and make copying addresses from blockscout as safe as possible, we display the checksum formatted version of addresses wherever we show addresses. The specification itself can be found here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md#specification
* Alter the representation of addresses both `to_string/1` and `Phoenix.HTML.Safe.to_iodata/1` to return the checksum formatted address.
=> feat: render addresses according to eip-55

apps/indexer/lib/indexer/block/realtime/fetcher.ex
Resolves #1358 
* We initially planned to allow turning off the polling, but @KronicDeth mentioned setting a safer interval and thats the new plan. Easier/safer. So this just ensures that we only ever poll once every 10 seconds, regardless of the average block time.
=> feat: add a minimum polling interval to protect from overrun

apps/block_scout_web/assets/js/lib/smart_contract/read_only_functions.js
For obvious reasons, we don't want to re-request every page we visit. This will also most likely offer at least a modest performance boost.
* if no `data-smart-contract-functions` elements were found, then
the loadFunctions function would do `$.get(null, {hash: null})`
(or maybe its `undefined`, doesn't matter), which would just result
in refetching the current page again.
=> fix: don't reload every page

README.md
Fixes #1373 
With the upgrade to `HTTP/2`, the Phoenix server only runs in `HTTPS` in development. This README edit provides instructions to upgrade the development environment.
- add instructions to the README to upgrade to `HTTPS`
=> Add HTTPS Upgrade to Readme

apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/test/explorer/chain/import_test.exs
Initially, internal transactions weren't indexed because of #1337. Now, some transactions don't have `error` and `status` fields from internal transactions because internal transactions from these transactions are already inserted. However `error`, `status` and `internal_transactions_indexed_at` fields in transactions table are updated only for newly created internal transactions.
- update transactions even if internal transactions are inserted
- add regression test
=> update transactions even if internal transactions are inserted

apps/explorer/priv/repo/migrations/scripts/update_replaced_transaction.sql
With millions of pending, dropped, and replaced transactions on Ethereum Mainnet the migration script is unable to complete without running them in batches. This PR adds a temp table and runs the migration in batches of 1000 transactions per batch.
Upgraded the migration script to run in batches.
=> Update migration script for dropped/replaced transactions

apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block_number_cache.ex, apps/explorer/test/explorer/chain/block_number_cache_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/data_case.ex
Fixes https://github.com/poanetwork/blockscout/issues/1379
- cache min and max block numbers
- use cached min and max values to calculate the indexed ratio
=> cache max and min block number

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
#1380 
Almost certainly some values in receipts of pending transactions have nil values (for example, `BlockNumber`)
- do not try to convert nil values to an integer in receipts response
=> fix receipts for pending transactions

apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
A bug has been noticed on `sokol`, `core`, and `xdai` where a massive number of blocks are being refetched multiple times. After running tests with the logging in this PR it is confirmed that we are reporting that reorgs are taking place. 
Now we have to determine whether these reorgs are actually happening or there is a bug in our reorg logic.
* Adds info log when we refetch a block due to a reorg.
=> Add Chain Consensus Logging

docker/Dockerfile, docker/Makefile
relates-to: #1387 
* Dockerfile: conditionally change coin name in gettext via environment
Note: This bakes the requested coin symbol into the docker image, rather than the default, "POA".  As some of the other environment variables can be changed between runs of the same image, changing the COIN variable will not change the coin name baked into an existing image.  To make such a change take effect after an image has already been built, simply `docker image remove blockscout_prod` before re-running `make start` to rebuild.
=> Dockerfile: conditionally change coin name in gettext via environment

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
Fixes #1397 
Fixes a small bug detailed in #1397 
* adds reward type `external` at index 2
Fixes no function clause matching in `EthereumJSONRPC.Parity.FetchedBeneficiaries.get_address_type/2`
=> Fix Beneficiaries External 2 on xDAI

apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/reward/fetcher.ex, apps/indexer/lib/indexer/block/transform.ex, apps/indexer/lib/indexer/block/transform/clique.ex, apps/indexer/test/indexer/block/transform_test.exs
An alternative to: #1372
Resolves #1404
Resolves #1392
The genesis block on clique blockchains needs to be special cased.
* Allow block_transformer to be configured via the environment variable `BLOCK_TRANSFORMER`. This must be done at compile time, so users may want to set it as an argument when building the container. Otherwise they will need to change that environment variable, and recompile. Alternatively, they can hardcode it as it was before.
* Special case the genesis block in the clique block transformer.
* Resolve other small errors when using clique
* Add a small amount of UI sugar for the genesis block
=> fix: import clique genesis blocks

apps/block_scout_web/config/dev.exs
resolves #1393 
*Why should we merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*
- Optional configuration of ssl key paths
- Add `CERTFILE` and `KEYFILE` envvars. Not breaking.
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as …
=> Optionally configure cert paths via envvar

apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex, apps/explorer/priv/compile_solc.js
Instead of manually replacing external library placeholders when compiling solidity code with external libraries we can pass them directly to the Solidity compiler.
https://solidity.readthedocs.io/en/v0.5.3/using-the-compiler.html#compiler-input-and-output-json-description
- pass external libraries to the Solidity compiler
=> pass external libraries to the Solidity compiler

apps/explorer/lib/explorer/chain/import/runner/block/rewards.ex, apps/explorer/priv/repo/migrations/20190208113202_add_unique_index_to_rewards.exs, apps/indexer/lib/indexer/block/reward/fetcher.ex
Fixes https://github.com/poanetwork/blockscout/issues/1416
https://pganalyze.com/docs/log-insights/app-errors/U126
```
The ON CONFLICT statement inserts the same row twice, as identified by the values in the constrained columns (i.e. those supposed to differentiate rows).
This usually happens if you don't de-duplicate your input before passing it to Postgres, as then ON CONFLICT would operate twice on the same set of values for the constraint clause, which is currently not supported.
```
- add unique index for `block_rewards` table
- deduplicate input data before upserting block rewards
=> add unique index on address_hash, block_hash and address_type for block_rewards

apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
In case something like #1411 happens again, we want to handle it a bit more gracefully.
* Don't return `nil` block numbers from `uncataloged_token_transfer_block_numbers`.
* Don't attempt to add non-integer block numbers to the sequence, and warn if we get one.
=> fix: cleanup uncataloged fetcher query, and push_front

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
Fixes #1430
On POA networks, rewardType will always be external and the type of the address being rewarded will depend on its position.
- Add index 3 to external validator type of fetched beneficiary
=> Add external 3 to fetched benficiaries

apps/block_scout_web/assets/css/components/address-overview.scss, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/mix.exs, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/events/subscriber.ex, apps/explorer/lib/explorer/chain/hash.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/indexer/lib/indexer/coin_balance/fetcher.ex, apps/indexer/lib/indexer/coin_balance/on_demand_fetcher.ex, apps/indexer/lib/indexer/coin_balance/supervisor.ex, apps/indexer/test/indexer/coin_balance/on_demand_fetcher_test.exs
Resolves #1156 	
* Visiting the address page now ensures we have a reasonably recent balance (within the past estimated day of blocks).
* Show the block that we have most recently updated the balance for.
* update the diffing logic for new balances on the FE. It used to just check if we sent it a balance card with different html. However, the balance card we send up always says `Fetching tokens...`, so it will almost always be different from what is there, since we fetch the tokens right away. So this sends along the balance in wei, and it uses that to determine if this new balance should be rendered. This should result in less reloading of that component for no reason.
* When an address is visited, we check if it has a stale (not recently updated) balance. If so, we double-check it, …
=> feat: synchronously fetch coin balances when an address is viewed.

apps/explorer/mix.exs, apps/explorer/priv/repo/migrations/20190214135850_add_index_on_block_number_to_address_token_balances.exs
I think the problem with importing new blocks is not in connection pool but  is that import query can not be finished because some sub queries take too long to execute. I see in pgadmin some requests that are still executing from my tests. 
https://github.com/poanetwork/blockscout/pull/1323
- add index on block number to address token balances
=> add index on block number to address token balances

apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20190215080049_add_index_on_fetched_coin_balance_to_addresses.exs, apps/explorer/priv/repo/migrations/20190215093358_add_compound_index_address_token_balances.exs
Mainnet 's blocks import wasn't working correctly because there are very slow queries in blocks runner. This PR with https://github.com/poanetwork/blockscout/pull/1444 adds a couple of indexes that should fix the problem.
1. There wasn't index on `fetched_coin_balance` in `addresses` table. It is needed. It's used in `count_addresses_with_balance`. It may not directly related to the issue. But the query was very slow.
2. https://github.com/poanetwork/blockscout/pull/1412 - this  request adds `not is_nil(t.block_number),` to  `uncataloged_token_transfer_block_numbers`. Transactions don't have index on `block_number`
3. `address_current_token_balances` does not have index on `block_number` which is used for their deletion in blocks runner
=> add indexes required for blocks runner

apps/explorer/priv/repo/migrations/20190213105501_add_constructor_arguments_to_smart_contracts.exs, apps/explorer/priv/repo/migrations/20190215105501_add_constructor_arguments_to_smart_contracts.exs
Fixes #1442 
This PR fixes an issue where a PR was merged that included a migration that was dated prior to migrations that have already occurred. 
- Drops `constructor_arguments` column from the `smart_contracts` table if it exists.
- Adds the `constructor_arguments` column to `smart_contracts` table
=> Fix constructor arguments migration

apps/explorer/priv/repo/migrations/20190219082636_add_indexes_for_block_reward_query.exs
Inspecting `pgadmin`'s dashboards I found out that `block_reward` query is executed very slowly. It uses `number` field from `blocks` table `block_range` field from `block_rewards` table. Both of these fields don't have indexes
- add indexes for block_reward query
=> add indexes for block_reward query

apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1438
Sometimes parent calls fail so we should propagate their errors to their child internal transactions
- propagate errors from parent calls
=> propagate errors from parent calls

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/log_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1440
The issue related to https://github.com/poanetwork/blockscout/pull/1398. Logs of pending transactions can have `nil` values
- do not try to convert nil values in logs
=> do not try to convert nils in logs

apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/lib/explorer/counters/average_block_time_duration_format.ex, apps/explorer/priv/repo/migrations/20190213180502_add_earliest_processing_start_to_transactions.exs, apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Resolves #1428
We want to show information on the time it took a transaction to complete.
We can't get this information completely accurately. All we can do is record the last time we checked for pending transactions, and the current time when we are fetching pending transactions. Using that information, we can determine a range in which the transaction must have started, and show that range in the explorer. If the process monitoring the pending transaction dies or if the application restarts, we will not be able to determine that information. We also won't be able to determine that information for any transaction that has already happened.
We should decide if we want to show anything at all on the pages where we have no information on how long the transaction took to complete. Should we …
=> feat: show an approximation of transaction time

apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
* We get an error when rendering address/:id/validations unless we provide the template with `coin_balance_status`.
* Provide the template with `coin_balance_status`.
=> fix: add coin_balance_status to address_validations

apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web.ex
Resolves #1468
* BLOCKSCOUT_VERSION was configured in a non-standard way that is harder/more annoying to use. This treats it like all of the rest of the application env variables that are mapped to environment variables.
* Switch BLOCKSCOUT_VERSION from compiled module attribute to application config.
=> fix: configure BLOCKSCOUT_VERSION in a standard way

apps/block_scout_web/assets/js/lib/coin_balance_history_chart.js, apps/block_scout_web/assets/js/lib/market_history_chart.js
fixes https://github.com/poanetwork/blockscout/issues/1419
- remove smoothing from coin balance chart
=> remove smoothing from coin balance chart

README.md
In step 9 users were prompted to `cd apps/block_scout_web` but not `cd -` after which would start the UI but not the indexer in step 10.
=> Fix BlockScout Readme Build Instructions

apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/indexer/config/dev.exs, apps/indexer/config/prod.exs, apps/indexer/config/test.exs, apps/indexer/lib/indexer/block/supervisor.ex, apps/indexer/lib/indexer/temporary/failed_created_addresses.ex, apps/indexer/lib/indexer/temporary/failed_created_addresses/supervisor.ex, apps/indexer/test/indexer/temporary/failed_created_addresses_test.exs, config/config.exs
part of https://github.com/poanetwork/blockscout/issues/1438.
In the issue 1438 it was found that we didn't set the correct status to internal transactions if a parent call has failed. This PR adds code meant to fix old internal transaction already in the DB.
- add temporary module to fix failed internal transactions
=> add temporary module to fix failed internal transactions

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/indexer/lib/indexer/replaced_transaction/fetcher.ex, apps/indexer/test/indexer/replaced_transaction/fetcher_test.exs
The replaced transactions fetcher was fetching all transactions in its `init`, but in reality to initialize the replaced transactions fetcher, we can just look for any pending transactions that have been replaced. Then, while its live, we check to see if any of the incoming transactions are replacing pending transactions.
* Optimize the `init` call for replaced transactions fetcher, and add handling logic.
=> feat: optimize/rework `init` for replaced transactions fetcher

apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
- do not do work in process initialization
- `FailedCreatedAddress` process was doing heavy work in its initialization. It's wrong because it was blocking other processes.
=> do not do work in process initialization

apps/explorer/priv/repo/migrations/20190228152333_change_constructor_arguments_to_text.exs
Resolves: #1497
* Make constructor_arguments a `text` field so that it can be longer than 255 characters.
=> fix: constructor_arguments must be type `text`

apps/explorer/test/explorer/chain_test.exs
The test was failing every 1st day of the month. I think it was caused by a date comparison issue
- fix test that fails every 1st day of the month
=> fix test that fails every 1st day of the month

apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
failed transaction fixer was choosing duplicated records and it was processing them multiple times
```
09:57:26.501 [debug] Started fixing transaction 0xd6f5e1f459fa223422d885db524780149640f25b09dd5b7a212947d02daf3be3
09:57:27.165 [debug] Finished fixing transaction 0xf0a29199169aa682bc8d3330a1f456cfcf4ce8ff8afba005ea0a21f91b417130
09:57:27.165 [debug] Started fixing transaction 0xd6f5e1f459fa223422d885db524780149640f25b09dd5b7a212947d02daf3be3
09:57:28.012 [debug] Finished fixing transaction 0xd6f5e1f459fa223422d885db524780149640f25b09dd5b7a212947d02daf3be3
09:57:28.012 [debug] Started fixing transaction 0xd6f5e1f459fa223422d885db524780149640f25b09dd5b7a212947d02daf3be3
09:57:28.377 [debug] Finished fixing transaction 0xd6f5e1f459fa223422d885db524780149640f25b09dd5b7a212947d02daf3be3 …
```
=> select only distinct failed transactions

apps/indexer/lib/indexer/address/coin_balances.ex, apps/indexer/test/indexer/address/coin_balances_test.exs
We can't extract params from logs params of pending transactions
```
2019-03-03T18:15:54.317 [error] Task #PID<0.8286.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Indexer.Address.CoinBalances.reducer/2
(indexer) lib/indexer/address/coin_balances.ex:32: anonymous fn(%{address_hash: "0xdac17f958d2ee523a2206206994597c13d831ec7", block_number: nil, data: "0x00000000000000000000000000000000000000000000000000000000007839b0", first_topic: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", fourth_topic: nil, index: nil, second_topic: "0x00000000000000000000000048686372756193c2663d1081c35d3d48e022c5fa", third_topic: "0x000000000000000000000000a5b1a8d0d45fc9729cc3f57c4f5b8c35da14d6f5", …
```
=> fix coin balance params reducer for pending transaction

apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain/contract_method.ex, apps/explorer/lib/explorer/chain/method_identifier.ex, apps/explorer/lib/explorer/chain/smart_contract.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/priv/repo/migrations/20181221145054_add_contract_methods.exs, apps/explorer/test/explorer/chain/transaction_test.exs, apps/explorer/test/explorer/smart_contract/publisher_test.exs, apps/explorer/test/support/factory.ex
* In order to show what function we suspect was called, we need to store and then list any potential contract ABI matches from other verified smart contracts. This will give users as much information as possible about unverified contract.
* Store any new method identifiers we receive.
* List them as possibilities on transactions for unverified transactions.
=> feat: decoding candidates for unverified contracts

apps/explorer/priv/repo/migrations/20190305095926_add_index_to_value_fetched_at.exs
the query is using `value_fetched_at` field to filter records
```
def stream_unfetched_balances(initial, reducer) when is_function(reducer, 2) do
query =
from(
balance in CoinBalance,
where: is_nil(balance.value_fetched_at),
select: %{address_hash: balance.address_hash, block_number: balance.block_number}
)
Repo.stream_reduce(query, initial, reducer)
end
```
https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/chain.ex#L1121
before adding index:
```
Gather  (cost=1000.00..12287343.90 rows=20456553 width=29)
Workers Planned: 2
->  Parallel Seq Scan on address_coin_balances a0  (cost=0.00..10240688.60 rows=8523564 width=29)
Filter: (value_fetched_at IS NULL)
```
after adding index:
```
Bitmap Heap Scan on address_coin_balances a0  (cost=383588.04..8443884.54 …
```
=> add index to value_fetched_at

apps/explorer/test/explorer/chain_test.exs
Our ci builds fails because of this test
- fix test that depended on date
=> fix test that depended on date

apps/indexer/lib/indexer/block/realtime/fetcher.ex
Timer is set using Elixir's `Process.send_after/3` method, which is incompatible with Erlang's `:timer` module.
Thus, `:timer.cancel` doesn't have any effect on it, and in fact returns `{:error, :badarg}`.
This causes more and more polling being scheduled after every websocket event, which might cause excessive flooding of a node with `eth_getBlockByNumber` requests after some running time.
=> Fix scheduling of latest block polling in Realtime Fetcher

docker/Dockerfile
Remove 1.7.1 version pin FROM bitwalker/alpine-elixir-phoenix
BlockScout now requires a later version of `alpine-elixir-phoenix`, so remove the pin to version 1.7.1
closes #1552
=> Dockerfile: remove 1.7.1 version pin FROM bitwalker/alpine-elixir-phoenix

apps/block_scout_web/assets/js/lib/from_now.js
Resolves https://github.com/poanetwork/blockscout/issues/1506
There is no exact date and time in the Transaction details page. It is useful for some applications ☝️ 
Exact date and time have been added only for Transaction details page. For other pages, a short record of date has been left.
=> (Feature) Exact date and time for Transaction details page

apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/smart_contract/reader_test.exs
partially fixes https://github.com/poanetwork/blockscout/issues/1258
we were getting a random result from calling contract because we weren't encoding integer parameters. But another issue was discovered
the value that should have been passed to `returnBytes1` is `"0x7b"` (hex encoding of 123). The result that was returned from parity is 
```
"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000017b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> encode integer parameters when calling smart contract functions

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Part of #1503 	
* To start off with, we should have a nicer error case when this happens. It makes it easier to debug, and also makes the problem less annoying for users, if determining the root cause takes a while.
* Don't show internal server error page when a contract creator cannot be determined.
=> fix: render a nicer error when creator cannot be determined

apps/indexer/lib/indexer/address/token_balances.ex, apps/indexer/test/indexer/address/token_balances_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1464
- fetch ERC721 token balances if sender is '0x0..0'
=> fetch ERC721 token balances if sender is '0x0..0'

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20190314084907_add_index_to_to_address_hash.exs, apps/explorer/test/explorer/chain_test.exs
Counting alll transactions take too much time. We need to implement some kind of cached counters to cache this value so the value is limited to `10_000` in the future
fixes https://github.com/poanetwork/blockscout/issues/1450
- add incoming transactions count to contract view
=> add incoming transactions count to contract view

apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/reward/fetcher.ex, apps/indexer/lib/indexer/block/reward/supervisor.ex
Not all chains distribute block reward, e.g. [SpringChain](https://explorer.springrole.com/). If chain don't have block reward, console is spammed with error: `application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch: @㍪: (404) Not Found`
Fixes #1526 and #1563. 
Just uncomment the line `config :indexer, Indexer.Block.Reward.Supervisor, disabled?: true` in apps/indexer/config/config.exs
=> add option to disable block rewards in indexer config

apps/block_scout_web/assets/js/lib/from_now.js, apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
Relates https://github.com/poanetwork/blockscout/pull/1551
1. We shouldn't display an exact time in a tile (the original issue https://github.com/poanetwork/blockscout/issues/1506 was only about the display of exact time in transaction details block):
2. Exact time doesn't display in transaction details block if the path doesn't start with `/tx`. For example, for Blockscocut instances tx details path begins with `/${preifx}/${chain}/tx`
- `in-tile` attribute has been added for elements inside tiles to exclude exact time display from them
- tx details page path search mask has been fixed.
- Exclude exact timestamp from tiles
- fix tx details page path search mask for displaying of exact time
=> (Fix) Exact timestamp display

apps/indexer/config/dev/parity.exs, apps/indexer/lib/indexer/block/supervisor.ex, apps/indexer/lib/indexer/shrinkable/supervisor.ex
Resolves #1566 
This allows a simple configuration to be set alongside other indexer configurations, which will just be merged with the entire configuration *only* for the realtime fetcher. This allows setting a dedicated node for the realtime fetcher.
There are a lot of downstream components called by the realtime fetcher, so we will definitely want to test this out in stg to make sure there are no unintended side effects.
=> feat: allow setting different configuration just for realtime fetcher

.circleci/config.yml, apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
- fix usd value on address page
=> fix usd value on address page

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
Resolves #1250
* Add an RPC endpoint that returns addresses, paginated, ordered by inserted_at
=> feat: rpc endpoint to list addresses

apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/reward/fetcher.ex, apps/indexer/test/indexer/block/fetcher_test.exs
Fixes #1584
If one address was rewarded for two different uncles in one block, cardinality violation occurred due to rewards not being properly reduced.
The reducing function from `Block.Rewards.Fetcher` is now reused in `Block.Fetcher`.
=> Reduce block_rewards in the catchup fetcher

README.md
PIRL has now deployed BlockScout for their main explorer. I've added this to the BlockScout Readme.
http://pirl.es/
=> Add PIRL to Readme

apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
There exists code to ensure long-running batch requests are split into smaller
batches in case we receive 504 (Gateway Timeout) errorfrom loadbalancer.
This PR adds handling of batches in the same manner in case there either is no
balancer, or its timeouts are configured larger than indexer's, and thus the
HTTP client library itself times out.
=> Chunk JSON-RPC batches in case connection times out

apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
=> fix usd fee

apps/indexer/lib/indexer/temporary/addresses_without_code.ex
- add more logging to code fixer process
=> add more logging to code fixer process

CHANGELOG.md, apps/indexer/lib/indexer/address/token_balances.ex, apps/indexer/test/indexer/address/token_balances_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1593
- do not fetch burn address balance
=> do not fetch burn address balance

CHANGELOG.md, apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
In this [commit](https://github.com/poanetwork/blockscout/commit/7f43ad585040fe8ff0f12e56dcce67f6ed5cc89a)
we stopped re-fetching internal transactions when fixing failed contract creations so  `status` field of internal transactions is not updated
Now, we will start using `contract_code` field of `addresses` to use as an indicator that we already processed that record.
- modify query to fetch failed contract creations
=> modify query to fetch failed contract creations

.circleci/config.yml
The tests are still flaky, so they might as well be flaky and fast.
=> Revert "Fix flaky tests"

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex, apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
The colour of the release link is too pale. For example for Goerli:
- class `footer-link` is added to to the release link in the footer.
=> (Fix) colour for release link in the footer

apps/indexer/lib/indexer/temporary/addresses_without_code.ex
`addresses without code` process is restarting on staging because the request to the database is timing out
```
10:31:49.877 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:32:50.879 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:33:51.881 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:34:52.883 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:35:53.885 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:36:54.887 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:37:55.889 [debug] Started fix_transaction_without_to_address_and_created_contract_address
10:38:56.891 [debug] Started …
```
=> infinity timeout for addresses without code query

CHANGELOG.md, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex, apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/internal_transaction/fetcher.ex, apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Fixes #1642
As there exist blocks without transactions we now pass the list of blocks to import routine instead of deriving this list from the list of fetched internal transactions.
This should prevent indexer from repeatedly fetching internal transactions for empty blocks, which is especially relevant for test-nets with lots of empty blocks.
=> Set internal_transactions_indexed_at for empty blocks

CHANGELOG.md, apps/explorer/lib/explorer/chain/address/current_token_balance.ex, apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex, apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs, apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
**Problem**: realtime fetcher db transactions take too long and often fail with a timeout. The reason of timeout is the `:deleted_address_current_token_balances` step of import, which selects previous balances for the rows we are going to update. The `SELECT` query it makes is extremely slow.
**Solution**: we incorporate fetching old balance value into the upsert itself. This is done by help of a transient `old_value` field, which is updated in `ON CONFLICT` clause of `INSERT` with the previous `value` and returned.
As we don't impose any more performance penalties for `INSERT` while removing a heavy `SELECT` completely, realtime fetcher should run much faster after this change.
**Upgrading**: migration `20190321185644_add_old_value_for_current_token_balances.exs`
=> Optimize token holder count updates when importing address current balances

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs, apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex, apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
- add petersburg evm version to smart contract verifier
- make petersburg default evm version
=> add petersburg evm version to smart contract verifier

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/smart_contract.ex
The first part of #1569 
This adds an rpc endpoint to list contracts according to the spec on that issue. We will probably want to leave this open until #1596 is merged, so that I can add those filters to this PR
* Adds a listcontracts action to the contracts rpc endpoint. See the attached issue for more information
* Adds a field `Address` to the contract model, to support the list endpoint.
* Modularize some of the pagination code so that you can set *one* of the pagination parameters without having to set both.
=> feat: add listcontracts endpoint

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Fixes #1644
When reorg occurs and the older of new blocks fails to be imported, the old consensus block remains in the database. Catchup fetcher ignores it, and we get a discontinuity in the main chain.
This commit adds an additional consensus loss step during block import: the parent block with hash not matching parent_hash of current block is marked non-consensus, thus creating a hole in main chain, forcing catchup fetcher to retry fetching it.
A query from `scripts/20190326202921_lose_consensus_for_invalid_blocks.sql` should be run to mark existing invalid blocks as non-consensus.
=> Force consensus loss for parent block if its hash mismatches parent_hash

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
When a user searches token by its name multiple matching addresses can be found
- do not fail if multiple matching tokens are found
=> do not fail if multiple matching tokens are found

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/test/explorer/smart_contract/verifier_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1653
If user-provided evm version is wrong,  we can try to verify contract using the latest evm version. If we couldn't verify the contract with the latest evm version we will try the version before the latest version.
- try to compile with the latest evm version if bytecode doesn't match
=> try to compile with the latest evm version if bytecode doesn't match

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/transaction_count_cache.ex, apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
Updating cache takes much time so we will use Postgres stats to calculate estimated transaction count
- use Postgres stats as fallback for transaction count
=> use postgres stats as fallback for transaction count

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
fixes https://github.com/poanetwork/blockscout/issues/1682
sometimes requests return atoms as a reason for request failure. For example, `{:error, :closed}` or `{:error, :request_timeout}`. these atome were raised ```raise :closed``` which is caused the error.
- do not fail if failure reason is atom
=> do not fail if failure reason is atom

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/priv/compile_solc.js, apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs, apps/indexer/lib/indexer/token/fetcher.ex
when verifying a contact we should allow a user to specify the number of optimization runs. Currently, 200 is used
- allow specifying number of optimization runs
=> allow specifying number of optimization runs

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/smart_contract.ex
This adds a `not_decompiled_with_version` filter to get decompiled contracts that were not decompiled with a specific version of the decompiler.
This includes everything from #1608 as well, so we should merge that first, then this will be a very small PR.
=> Add with version filter

apps/indexer/lib/indexer/address_extraction.ex
fixes https://github.com/poanetwork/blockscout/issues/1707
Some contracts created by main transactions. Other contracts are created by internal transactions. Setting the contract code from the main transaction's input will set invalid code if the contract was created in the internal transaction.
- do not set contract code from transaction input
=> do not set contract code from transaction input

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
We tend to forget adding changelog entries for PRs, so here's an extra reminder
=> Add a checklist to the PR template

CHANGELOG.md, apps/explorer/lib/explorer/chain/block_number_cache.ex
fixes the error when block number cache is initialized before repo
- rescue failing repo in block number cache update
=> rescue failing repo in block number cache update

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/test/explorer/counters/average_block_time_test.exs, apps/indexer/test/indexer/coin_balance/on_demand_fetcher_test.exs
Average block time was recalculated when new blocks were processes. But since block are not added consecutively average block time is getting wronger over time
- fix average block time calculation
=> fix average block time calculation

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1674
- add logs pagination in rpc api
=> add logs pagination in rpc api

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Roughly covers steps 5 and 6 from [my refactoring plan](https://github.com/poanetwork/blockscout/issues/1628#issuecomment-478768762).
Internal transactions and token balances are the slowest to fetch and import.
We'd rather have almost instant import of almost all block-related info than frequent timeouts in realtime fetcher and handing blocks over to catchup fetcher, which imports this data asynchronously anyway.
=> Remove internal tx and token balance fetching from realtime fetcher

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
fixes https://github.com/poanetwork/blockscout/issues/1737
- if the database has only one block on demand balance fetcher fails
=> fix empty block time

CHANGELOG.md, apps/indexer/README.md
Resolves #1628.
A brief description of indexer structure is added to `README.md` of `indexer` application.
Installation instructions are removed, as they don't make sense for sub-app of umbrella application.
=> Describe indexer structure and list existing fetchers

CHANGELOG.md, apps/indexer/config/prod/parity.exs, apps/indexer/config/prod/rsk.exs, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/block/realtime/supervisor.ex
Realtime fetcher already uses both websocket and JSONRPC polling for more reliable new block fetching.
Though, if no websocket was available, the realtime fetcher wouldn't start, and no new blocks arrived at all.
As we already have a polling fallback, we now make websocket optional.
This will also help with supporting [nodes without websocket API](https://github.com/poanetwork/blockscout/issues/1607#issuecomment-484135189).
To disable websocket API, pass `nil` in `subscribe_named_arguments.transport`.
=> Make websocket optional for realtime fetcher

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex
fixes https://github.com/poanetwork/blockscout/issues/1767
- fix first block parameter
=> fix first block parameter

CHANGELOG.md, apps/block_scout_web/assets/js/lib/from_now.js
fixes https://github.com/poanetwork/blockscout/issues/1764
- add timestamp to block overview
=> add timestamp to block overview

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
part of https://github.com/poanetwork/blockscout/issues/1732
optionally show ERC-20 token transfer info on the transaction page
=> optionally show ERC-20 token transfer info

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket/web_socket_client_test.exs, apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/geth.ex, apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/mox.ex, apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex, apps/indexer/README.md, apps/indexer/lib/indexer/block/realtime/supervisor.ex
Resolves #1738
* We want to set up a keepalive on websockets, because some servers will close the socket connection after receiving no messages after a period of time.
* Add a keepalive argument to the websocket server.
Doesn't really make sense to test a feature of a 3rd party library (in this context), so I don't think its necessary for me to add a test asserting the ping message is sent.
=> feat: set a websocket keepalive from config

apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/config/config.exs
Motivation:
Adjust coin from POA to RBTC at RSK instance of BlockScout
=> RSK v1.3.9: Change coin

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
with https://github.com/poanetwork/blockscout/pull/1777 resolves https://github.com/poanetwork/blockscout/issues/1732
- add ERC-721 info to the transaction overview page
=> add ERC-721 info to transaction overview page

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
fixes https://github.com/poanetwork/blockscout/issues/1791
- fix top nav autocomplete
=> fix top nav autocomplete

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex, apps/explorer/test/explorer/smart_contract/verifier/constructor_arguments_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1786
Currently, we're assuming that constructor arguments are concatenated with contract code in transaction input data. But some transactions have additional data between source code and constructor arguments in transaction input
- fix constructor arguments verification
=> fix constructor arguments verification

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
We couldn't fetch coin price for some coins
- make coinmarketcap's number of pages configurable
=> make coinmarketcap's number of pages configurable

.credo.exs, CHANGELOG.md
Logger macros don't evaluate their parameters since [Elixir 1.7.0](https://elixir-lang.org/blog/2018/07/25/elixir-v1-7-0-released/).
Creating a lambda for every log output is no longer needed.
=> Disable lazy logging check in Credo

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_nephew.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncle.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncles.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block/second_degree_relation.ex, apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex, apps/explorer/priv/repo/migrations/20190421143300_add_index_to_bsdr.exs, apps/explorer/test/explorer/chain/block/second_degree_relation_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex, apps/indexer/README.md, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/fetcher/uncle_block.ex, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/lib/indexer/temporary/uncles_without_index.ex, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/fetcher/uncle_block_test.exs
Fixes #1798 
Parity returns `null` for many uncle blocks, if they are fetched using `eth_getBlockByHash`. This is most probably caused by the fact that Parity only keeps full block data for recent non-consensus blocks.
This causes uncle_block fetcher to loop endlessly trying to fetch "missing" blocks, hogging both app server and Parity resources.
Instead, we use `eth_getUncleByBlockHashAndIndex` method, which works for all uncle blocks.
As we didn't previously store index of an uncle block within a nephew block, a new field and a temporary fixup fetcher is added to get the index from nephew blocks.
=> Use eth_getUncleByBlockHashAndIndex for uncle block fetching

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/supply/coin_market_cap.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex, apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex, apps/explorer/lib/explorer/exchange_rates/source/transaction_and_log.ex, apps/explorer/lib/explorer/exchange_rates/token.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs, apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs, apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs, apps/explorer/test/support/fakes/one_coin_source.ex
fixes https://github.com/poanetwork/blockscout/issues/1776
- use coinmarketcap for total_supply by default
=> use coinmarketcap for total_supply by default

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Fixes https://github.com/poanetwork/blockscout/issues/1752
Chaos in chains menu
=> (Chore) Divide chains by Mainnet/Testnet in menu

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
We are having issues with some contract verifications, and this endpoint will make it easier to verify contracts and test contract verifications. A `POST /verified_smart_contracts` with the same parameters as the JSONRPC endpoint (except snake cased, not camelcase).
* Adds a contract verification endpoint.
=> feat: verify contracts with a post request

CHANGELOG.md, rel/commands/clear_build.sh
To prepare code for deployment to the instance after local testing we need to clear build artefacts. We do it manually now.
- `./rel/commands/clear_build.sh` bash script has been added, which removes all of those artefacts
- I've updated deployment instruction here: https://forum.poa.network/t/deploying-blockscout-with-terraform/1952#preparing-blockscout.
=> (Chore) Clear build artefacts script

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/chain.ex, apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/1580
=> Able to search without prefix "0x"

CHANGELOG.md, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Resolves *[Add total blocks counter](https://github.com/poanetwork/blockscout/issues/1766)*
=> Add total blocks counter

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Uncle blocks fetched using `eth_getUncleByBlockHashAndIndex` API may have `null` in their `size` field.
We shouldn't crash in this case.
=> Handle nil size in block decoding routine

CHANGELOG.md, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
Uncle block API returns null values for block size, and we need to properly store them in the database.
=> Make block size field nullable

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
Pong messages are generating errors and killing the websocket connection.
* Handle the pong message correctly
=> fix: ignore `pong` messages without error

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/explorer/lib/explorer/chain.ex
Fixes bug where block counter and blocks list disagrees
=> Block counter calculates only consensus blocks

CHANGELOG.md, rel/commands/clear_build.sh
Add the ability to delete a folder with static assets before the launching of another Blockscocut instance.
- `-f` flag has been added to `clear_build.sh` script to be able to also delete `./priv/static/` folder before the launching of another Blosckout instance
=> (Chore) Add -f flag to clear_build.sh script delete static folder

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/views/address_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/address_view_test.exs, apps/explorer/lib/explorer/chain.ex
*[Internal server error for Accounts page](https://github.com/poanetwork/blockscout/issues/1839)*
Total supply may be nil, so if it is, we don't compute the balance percentage.
- added function that matches nil total supply
- updated specs
- added new test
=> Handle case when total supply is nil

apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block_count_cache.ex, apps/explorer/test/explorer/chain/block_count_cache_test.exs
* added cache for block counter
=> Add cache for block counter

apps/explorer/priv/compile_solc.js
`err` in this context seems to be an instance of `Error` and stringifies into `{}` even if it has a message inside
=> Stringify solc error message instead of Error instance

apps/explorer/lib/explorer/chain/import/runner/transactions.ex
For fetching smart contract codes need `created_contract_address_hash` field from the transaction:
https://github.com/poanetwork/blockscout/blob/8e6ee4ceb1e0a51996bbf072810a223e746f2d35/apps/indexer/lib/indexer/block/fetcher.ex#L221-L240
=> Transaction importer return created_contract_address_hash

CHANGELOG.md, apps/explorer/.gitignore, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/smart_contract/solc_downloader.ex, apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex, apps/explorer/priv/compile_solc.js
* This *may* be related to slowness issues with verifying contracts, and/or intermittent failures. Worst case scenario, this will improve speed/performance of the operation. Best case scenario it fixes some weird intermittent bugs w/ verification.
* Instead of downloading the solc compiler every time, we store each one in the priv directory.
The existing tests should cover this change pretty well.
Looks like there are a few issues to deal with, like what to do when asked to use `latest` version, that kind of thing.
=> fix: store solc versions locally for performance

README.md
Add Ether-1's Blockscout instance to README.md:
- blocks.ether1.wattpool.net
=> README.md: add blocks.ether1.wattpool.net for Ether-1

CHANGELOG.md, apps/block_scout_web/assets/css/components/_tile.scss
Closes #1883
To fix this.
It should work fine now.
- Fix status label text alignment.
=> (fix) status label alignment

CHANGELOG.md, apps/block_scout_web/assets/js/lib/list_morph.js
Fixes https://github.com/poanetwork/blockscout/issues/1298
Check the presence of overlap[i] object before retrieving properties from it
=> Check the presence of overlap[i] object

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/chain/address.ex
Resolves #1891 
We want to trigger a balance fetch on any stale balances when they are retrieved via the API, not only when they are viewed in the UI. So that consumers would know, I added an attribute to the response called "stale" that is set to `true` when we have determined that the balance is old and is worth checking again. This doesn't mean that the balance is *wrong* (it will usually be right), it just means that we haven't seen an update for it in the last 24 hours, so we're going to check it again.
* Fetch coin balance on demand for API requests.
=> feat: add on demand fetching and stale attr to rpc

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex
Resolves #1942
* Exclude empty contracts by default from the `unverified` and `not_decompiled` filters. Add an `empty` filter to fetch contracts that have an empty bytecode.
=> feat: exclude empty contracts by default

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/block.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/chain/transaction.ex, apps/explorer/priv/repo/migrations/20190508152922_add_old_block_hash_for_transactions.exs, apps/explorer/priv/repo/migrations/20190513134025_add_refetch_needed_to_block.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/indexer/README.md, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Due to race conditions described in #1911 transactions from a consensus block might get overwritten by the same transactions from a non-consensus block.
To prevent this we force a block refetch (by marking it as non-consensus), if a transaction belonging to it gets overwritten by the same transaction from a different block.
Also, a potential race condition is fixed in replaced transactions worker: it doesn't mark as `dropped/replaced` the transactions that eventually ended up in a block.
A transient `old_block_hash` field is added to `transactions` table for atomic deriving of re-collated transactions.
=> Force block refetch if transaction is re-collated in a different block

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
if a transaction has a big number of logs it's not apparent which page of logs is requested. Also, log index is  used for logs pagination
- add log index to transaction view
=> add log index to transaction view

.circleci/config.yml, CHANGELOG.md
Wrong parity tasks names in Circle CI
Correct parity tasks names in Circle CI config
=> Fix wrong parity tasks names in Circle CI

CHANGELOG.md, apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
* Start consolidating in a `handle_continue/2` hook instead of a task that is kicked off in the `init` callback.
I checked the box here, but I can't reproduce whatever is causing the queries to stack up. However, spawning a task from the init like that is suspect, and isn't how that would normally be done.
=> fix: consolidate address w/ balance one at a time

CHANGELOG.md, docker/Makefile
* Generate a predictable name for the blockscout container just as we do for the postgres container, rather than random generated names, for the sake of scripting.
=> docker/Makefile: always set a container name

CHANGELOG.md, apps/block_scout_web/mix.exs, mix.lock
* Wobserver has been getting out of date and is unsupported. I forked the fork we *were* using into one that was under poanetwork's umbrella so that we can fix it later if need be.
* This fixes an issue that caused wobserver to be unusable under https.
* I also had to clone the wobserver repo, and decided to clone it under the `poanetwork` umbrella, so that it could be changed more in the future if necessary.
* Wobserver has a fallback to use polling instead of ws. The websockets are not working, but I was able to get the polling version to work with HTTPS, so this fixes the short term issue. We'd would prefer websockets to work, but I have yet to discover what is broken about them, and wobserver itself appears to be abandoned.
=> fix: support https for wobserver polling

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex
Replace `block_consensus_count` function with an estimated count of blocks when the cache is empty.
Get 90% of the estimated count, because consensus blocks are ~90% of the total count.
=> Get estimated count of blocks when cache is empty

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/lib/explorer/smart_contract/solc_downloader.ex, apps/explorer/priv/repo/migrations/20190516140202_add_address_hash_index_to_decompiled_smart_contracts.exs, apps/explorer/priv/repo/migrations/20190516160535_add_decompiled_and_verified_flag_to_addresses.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Resolves #1951
* Due to poor performance with the filters for not decompiled and not verified smart contracts in the JSON RPC, this adds supporting fields on addresses to signify decompiled/verified contract addresses.
* Adds a Temporary fetcher that will backfill the old data.
* For performance reasons, I had to remove the "DecompilerVersion" attribute from the API response for listing contracts. I can add it back in if necessary, but things will become much slower. Since this was a new API endpoint, I don't think it would be too bad to remove that field. Let me know.
=> fix: add fields for contract filter performance

CHANGELOG.md, apps/block_scout_web/assets/css/components/_token_tile_view_more.scss, apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Closes #1981
To fix the missing tx hashes.
- Fixed the missing tx hashes.
- See above.
=> (Fix) Missing tx hashes

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_log-search.scss, apps/block_scout_web/lib/block_scout_web/templates/address_logs/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Issue: https://github.com/poanetwork/blockscout/pull/2037
We need to add _log-search.scss and connect it at the bottom of app.scss
Update index.html.eex at templates/address_logs
=> log search form styles added

CHANGELOG.md, apps/indexer/config/prod/geth.exs
https://github.com/poanetwork/blockscout/pull/1869#issuecomment-496886148
We should increase the timeout for geth indexers after implementing of https://github.com/poanetwork/blockscout/pull/1869
- increasing of the timeout for geth indexers from 1 minute to 10 minutes
=> Increase timeout for geth indexers

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs, apps/explorer/lib/explorer/etherscan/logs.ex, apps/explorer/test/explorer/etherscan/logs_test.exs
#1858 
* The listLogs api endpoint is very slow for moderate-large block ranges. The queries that this PR replaces would take about 500 seconds. These ones still aren't *that* fast, but they complete in 15-30 seconds for those same block ranges so it is a vast improvement.
* Use a more optimized query when provided with an address hash filter. We first limit our search to logs from transactions and internal transactions that were from, to, or creating the provided address. This limits the search space significantly.
Note: The existing tests reinforce correct behavior, but I can't write a unit test to confirm the performance characteristics.
=> fix: use better queries for listLogs endpoint

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs, apps/explorer/lib/explorer/chain/internal_transaction.ex
Resolves: #1938
* Show internal transactions that created the address when filtering for internal transactions *to* that address.
=> fix: show creating internal transactions

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/explorer/token/metadata_retriever_test.exs
We weren't setting name and symbol for some tokens because we were assuming they all have a string type
- allow bytes32 for name and symbol
=> allow bytes32 for name and symbol

apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
associations are loaded on the first page https://github.com/poanetwork/blockscout/blob/030c17c58bdd330fe54060585e9a8ccfb42fda9e/apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex#L78
- do not load associations for internal txs on transaction page
=> do not load associations for internal txs on transaction page

CHANGELOG.md, apps/block_scout_web/assets/css/components/_dropdown.scss, apps/block_scout_web/assets/css/components/_navbar.scss
Navbar element active class and hover
was:
now:
Logo size
was:
now:
=> Nav dropdown issue, logo size issue

CHANGELOG.md, apps/block_scout_web/assets/css/components/_btn_dropdown_line.scss, apps/block_scout_web/assets/css/theme/_goerli_variables.scss, apps/block_scout_web/assets/css/theme/_rinkeby_variables.scss, apps/block_scout_web/assets/css/theme/_sokol_variables.scss
1) Changed border-color to darken on dropdown hover
2) Sokol and Goerli: added more darken colors to dropdown item hover and navbar hovers
Now:
3) Ropsten colors improvements (links, buttons, tabs, etc). Now it looks like ropsten theme
=> Themes color improvements, dropdown color issue

CHANGELOG.md, apps/block_scout_web/assets/css/theme/_variables.scss
- We need to keep only base_variables connected and current theme connected without natural_variables. Natural variables is for 'blockscout' theme only.
- This will fix issues with dropdown list in header and etc...
- Can you send me a list of branches what I should update and create similar pull request? (if we need to do this)
=> Fixed theme variables connection issue: removed natural_variables connection

CHANGELOG.md, apps/block_scout_web/assets/css/components/_verify_other_explorers.scss
Fix for width of 'verify other explorers' block elements. Now if we have 2 or 1 elements instead of 3, they have max-width; 'more' button aligned to right
Now:
=> Fix for width of explorer elements

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/eth_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/eth_rpc_view.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/eth_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/wei.ex
Resolves #2015 
Example:
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xc94770007dda54cF92009BFF0dE90c06F603a09f", "latest"],"id":1}' <explorer>/api/eth_rpc
```
This mimics the `ethGetBalance` json rpc. The only issue is that we don't currently create balances for accounts that have a balance at the genesis block. A ticket for doing that is here: #2080
=> feat: eth_get_balance rpc endpoint

CHANGELOG.md, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/uncle_block.ex, apps/indexer/test/indexer/fetcher/uncle_block_test.exs
fixes https://github.com/poanetwork/blockscout/issues/2126#issuecomment-500333178
- add new function clause for uncle errors
=> add new function clause for uncle errors

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
https://github.com/poanetwork/blockscout/issues/2132
Then `SUPPORTED_CHAINS` is `[]`, we should hide the dropdown menu on the header
_Before_
_After_
=> Hide dropdown menu then other networks list is empty

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
Part of https://github.com/poanetwork/blockscout/issues/1612
Most of the time pending transaction query won't even start to execute because the request is timeout out on `Chain.pending_transaction_count()` query. Moreover, it looks like `pending_transaction_count` variable is not used
- remove pending transaction count
=> remove pending transaction count

apps/block_scout_web/config/config.exs, apps/block_scout_web/config/dev.exs
Compiling smart contracts in the contract verification process takes too much time. That's why we're increasing the timeout.
This is a temporary solution. A better approach would be to make it contract verification async. 
- increase request idle timeout
=> increase request idle timeout

CHANGELOG.md, apps/block_scout_web/assets/css/components/_transaction.scss, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/priv/gettext/default.pot
Issue: https://github.com/poanetwork/blockscout/pull/2102
1) Added styles for 'Download All Transactions as CSV' button
2) Moved it in 1 row with pagination
3) Duplicated at the bottom
Now:
=> Added styles for 'Download All Transactions as CSV' button

apps/explorer/lib/explorer/chain/block.ex
` total_difficulty` and `difficulty` fields are nullable in the db. uncle blocks don't have these fields. so let's make these fields optional
- make block difficulty params optional
=> make block difficulty params optional

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/js/pages/layout.js, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
1) We added fluid container to header to avoid this:
Before:
After:
2) We hide navbar on outside click
=> Header content alignment issue, hide navbar on outside click

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex, apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex, apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
* Right now the host is wrong in the API documentation page. 
* This uses the correct value to render the host in api docs, and allows it to be configured via `BLOCKSCOUT_HOST` env variable.
=> feat: add BLOCKSCOUT_HOST, and use it in API docs

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss, apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
1) Increased search length. Issue - https://github.com/poanetwork/blockscout/issues/2253
2) Removed link wrapping to next row (md-lg resolution)
before:
after:
=> Search length issue, tile link wrapping issue

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot
Added html/css for 'download csv' button to:
1. address_transaction/index.html.eex
2. address_token/index.html.eex
3. address_internal_transaction/index.html.eex
4. tokens/transfer/index.html.eex
but you need to add correct href for this buttons
=> 'download csv' button added to different tabs

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
fixes 
```
2019-06-28T11:08:39.926 [error] #PID<0.24465.30> running BlockScoutWeb.Endpoint (connection #PID<0.24400.30>, stream id 4) terminated
Server: 52.2.163.93:80 (http)
Request: GET /tokens/0xb22c9f8e45b3e351a955d89d777d2ccf14915268/token_transfers
** (ArgumentError) assign @address not available in eex template.
Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.
Available assigns: [:conn, :current_path, :token, :total_token_holders, :total_token_transfers, :view_module, :view_template]
(phoenix_html) lib/phoenix_html/engine.ex:132: Phoenix.HTML.Engine.fetch_assign!/2
(block_scout_web) …
```
=> remove not existing assigns in html code

CHANGELOG.md, apps/indexer/lib/indexer/fetcher/token_balance.ex, apps/indexer/test/indexer/fetcher/token_balance_test.exs
`Explorer.Chain.Import.Runner.Address.TokenBalances` fails with the `cardinality_violation` error because it tries to insert more than once token balances (for the same {token_contract_address_hash, address_hash, block_number} tuple) in a single database transaction.
This PR filters out duplicate parameters in `Indexer.Fetcher.TokenBalance` so that no duplicates are sent to be imported.
=> Remove duplicate params in `Indexer.Fetcher.TokenBalance`

CHANGELOG.md, apps/block_scout_web/assets/js/lib/currency.js
resolves https://github.com/poanetwork/blockscout/issues/2274
- increase threshold for scientific notation
=> increase threshold for scientific notation

CHANGELOG.md, apps/block_scout_web/assets/css/_typography.scss, apps/block_scout_web/assets/css/components/_network-selector.scss, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/assets/css/components/_token-balance-dropdown.scss, apps/block_scout_web/assets/css/components/_transaction.scss, apps/block_scout_web/assets/css/theme/_neutral_variables.scss, apps/block_scout_web/assets/css/theme/_poa_variables.scss, apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex, apps/block_scout_web/priv/gettext/default.pot
1) Added underline on hover for 'download csv' button
2) Fixed hover for transaction links on resolution 320-992
3) Fixed network selector gaps in 320px-375px resolution
Before:
After:
4) Added new styles for tokens dropdown
Before:
After:
5) Added dashed underline for contract links instead of dashed border with gap, added straight underline on hover
After:
6) Fixed token transfer info inside of tile for mobile resolution
Before:
After:
=> Typo issues, dropdown issues

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
##Motivation
This solves a recurring error from `Explorer.Chain.Import.Runner.InternalTransactions` that prevents internal transactions to be imported because the respective transaction fail to be updated.
The bug causing the problem is that when transactions have already their `status` set, the insertion of `internal_transactions` will not change it to reflect the existence of an error.
=> Fix internal transactions failing to be indexed because of constraint

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/page_not_found_controller.ex, apps/block_scout_web/test/block_scout_web/controllers/page_not_found_controller_test.exs
resolves https://github.com/poanetwork/blockscout/issues/2280
- add 404 status for not existing pages
=> add 404 status for not existing pages

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/recent_transactions_controller.ex, apps/block_scout_web/test/support/conn_case.ex, apps/block_scout_web/test/support/feature_case.ex, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/lib/explorer/chain/transactions_cache.ex, apps/explorer/test/explorer/chain/transactions_cache_test.exs, apps/explorer/test/support/data_case.ex, apps/indexer/lib/indexer/block/fetcher.ex
=> Add transactions cache

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/css/components/_dashboard-banner.scss, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
1) Banner stats size and gaps on 320-374px resolution (iphone 5, se)
Before:
After:
2) Added gap for stats container on md resolution
Before:
After:
3) Transactions title font-size issue
After:
Before:
=> Banner stats issues on sm resolutions, transactions title issue

CHANGELOG.md, apps/block_scout_web/assets/css/components/_card.scss, apps/block_scout_web/assets/css/components/_dashboard-banner.scss, apps/block_scout_web/assets/css/components/_stakes_table.scss, apps/block_scout_web/assets/css/components/_tile.scss, apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot
1) Fixed stats width for md resolution
Before:
After:
2) Transaction load animation fix on md resolution
Before:
After:
3) Block details row fix for sm resolutions
Before:
After:
4) Addresses tiles changed to table
Before:
After:
5) Address page card title issue on sm resolution
Before:
After:
6) Changed check mark color to white on active tab, Issue - https://github.com/poanetwork/blockscout/issues/1993
Before:
After:
=> Dashboard fix for md resolution, transactions load fix, block info row fix, address page issues, check mark issue

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
Fixes #2279 
It turns out a clause for render eth_get_balance.json went missing in #2100  (probably during a rebase/merge) and so it was enough to rewrite it.
=> Add eth_get_balance.json to AddressView's render

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex, apps/block_scout_web/test/block_scout_web/controllers/api/v1/health_controller_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Resolves https://github.com/poanetwork/blockscout/issues/2273
```
curl http://localhost:4000/api/v1/health
```
- add healthy block period checking endpoint
=> add healthy block period checking endpoint

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
this commit https://github.com/poanetwork/blockscout/commit/9e1b6b3752ff0bcaf6cf86be6356caba8ead2356 added a wrong path for transaction csv download
- fix transaction csv download link
=> fix transaction csv download link

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
fixes 
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"error" => %{"code" => -32601, "data" => nil, "message" => "Cannot find ommer for hash: 0x1251a9f1416c95e8f08a26422459202abbbfe71cdd9d90d3605d0711b6a4f78f"}, "id" => "0x0", "jsonrpc" => "2.0", "result" => nil}. This protocol is implemented for: Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Hash, Postgrex.Copy, Postgrex.Query, Cldr.Unit, Decimal, Float, DateTime, Time, List, Version.Requirement, Atom, Integer, Version, Date, BitString, NaiveDateTime, URI
(elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/string/chars.ex:22: …
```
=> fix interpolation in error message

CHANGELOG.md, README.md
GoJoy Chain is using BlockScout and thought it should be added to the README
- updated README
=> Add GoJoy Chain to README

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex, apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs
the scheme was hardcoded to `HTTP` in api docs. Because of that api requests didn't work if the scheme is `HTTPS`
- parse url for api docs
=> parse url for api docs

CHANGELOG.md, apps/explorer/lib/explorer/market/history/source/crypto_compare.ex, apps/explorer/lib/explorer/market/market.ex, apps/explorer/test/explorer/market/history/source/crypto_compare_test.exs, apps/explorer/test/explorer/market/market_test.exs
Service API that we're using for market history fetching started returning zeroes for some coins.
- fix market history overriding with zeroes
=> fix market history overriding  with zeroes

CHANGELOG.md, apps/block_scout_web/config/config.exs, apps/block_scout_web/config/dev.exs
Initially, increased request idle timeout was introduced in https://github.com/poanetwork/blockscout/pull/2194 to mitigate smart contract verification failures. But after https://github.com/poanetwork/blockscout/pull/2264 it's not necessary.
Note: it should be merged after https://github.com/poanetwork/blockscout/pull/2264
- remove request idle timeout configuration
=> remove request idle timeout configuration

CHANGELOG.md, docker/Makefile
Upgrade Postgres image version in Docker setup up to `10.6` since we use this version of DB on all hosted by POA team BS instances
Upgrade Postgres container image up to `10.6` version
=> Upgrade Postgres image version in Docker setup

apps/block_scout_web/lib/block_scout_web/controllers/pools_controller.ex, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transport.ex, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/staking/chain_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/test/explorer/staking/contract_state_test.exs, apps/explorer/test/explorer/staking/epoch_counter_test.exs
We should retrieve `MIN_CANDIDATE_STAKE` and `MIN_DELEGATOR_STAKE` from contract, not from env.
=> Retrieve `MIN_{CANDIDATE,DELEGATOR}_STAKE` from contract, not from env.

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/explorer/lib/explorer/chain.ex
Part of #2306 
Part of the reason is that it has to execute 3 queries, but since 2 of these queries are unrelated to each other (transactions and rewards) they will be executed in parallel.
=> Fetch rewards in parallel with transactions

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex, apps/explorer/config/config.exs, apps/explorer/priv/compile_solc.js, apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Currently, a user manually has to select the evm version when verifying smart contract even if he didn't change compilation settings.
This PR adds `default` evm version which uses the evm version that defaults to the specified Solidity version.
- add default evm version to smart contract verification
=> add default evm version to smart contract verification

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/transactions.ex, apps/explorer/test/explorer/chain/import/runner/transactions_test.exs
Solves a problem describe in [a #2105 comment](https://github.com/poanetwork/blockscout/issues/2105#issuecomment-510614617).
The problem is that a transaction's `created_contract_code_indexed_at` gets ignored during a conflicting update, so it is not updated.
In particular it is not reset to NULL and this has been source of errors.
Add `created_contract_code_indexed_at` as a field to check and update during an import with conflict.
=> Update created_contract_code_indexed_at on transaction import conflict

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
https://github.com/poanetwork/blockscout/issues/2132
Env variable `SUPPORTED_CHAINS` may be `="[]"`, then we have empty network selector
=> Disable network selector when is empty

CHANGELOG.md, apps/block_scout_web/assets/css/components/_footer.scss, apps/block_scout_web/assets/css/components/_network-selector.scss, apps/block_scout_web/assets/webpack.config.js
Before:
After:
- Configuration of webpack to exclude moment.js localization files except EN
- Removal of unused css
=> Page performance: exclude moment.js localization files except EN, remove unused css

docker/Dockerfile
Warnings are now treated as errors during the build.
* Docker build
* Operating System / base image: `bitwalker/alpine-elixir-phoenix:latest`
```
Jul 18 14:02:45 make[26845]: Step 14/16 : RUN mix compile
Jul 18 14:02:46 make[26845]: ---> Running in 068d8010237c
Jul 18 14:02:52 make[26845]: ==> ethereum_jsonrpc
Jul 18 14:02:52 make[26845]: Compiling 49 files (.ex)
Jul 18 14:02:58 make[26845]: warning: redefining @doc attribute previously set at line 94
Jul 18 14:02:58 make[26845]: lib/ethereum_jsonrpc/transport.ex:106: EthereumJSONRPC.Transport (module)
Jul 18 14:02:59 make[26845]: Compilation failed due to warnings while using the --warnings-as-errors option
Jul 18 14:03:00 make[26845]: The command '/bin/sh -c mix compile' returned a non-zero code: 1
Jul 18 14:03:00 make[26845]: make: *** …
```
=> docker/Dockerfile: pin bitwalker/alpine-elixir-phoenix:1.9.0

CHANGELOG.md, apps/explorer/lib/explorer/chain/transaction.ex
fixes https://github.com/poanetwork/blockscout/issues/2386
- show only one decoded candidate
=> show only one decoded candidate

CHANGELOG.md, apps/block_scout_web/assets/__tests__/pages/pending_transactions.js, apps/block_scout_web/assets/js/lib/async_listing_load.js, apps/block_scout_web/assets/js/lib/infinite_scroll_helpers.js, apps/block_scout_web/assets/js/lib/list_morph.js, apps/block_scout_web/assets/js/lib/redux_helpers.js, apps/block_scout_web/assets/js/lib/utils.js, apps/block_scout_web/assets/js/pages/address.js, apps/block_scout_web/assets/js/pages/address/coin_balances.js, apps/block_scout_web/assets/js/pages/address/internal_transactions.js, apps/block_scout_web/assets/js/pages/address/logs.js, apps/block_scout_web/assets/js/pages/address/transactions.js, apps/block_scout_web/assets/js/pages/address/validations.js, apps/block_scout_web/assets/js/pages/blocks.js, apps/block_scout_web/assets/js/pages/chain.js, apps/block_scout_web/assets/js/pages/pending_transactions.js, apps/block_scout_web/assets/js/pages/transaction.js, apps/block_scout_web/assets/js/pages/transactions.js, apps/block_scout_web/assets/js/pages/verification_form.js, apps/block_scout_web/assets/webpack.config.js
A part of https://github.com/poanetwork/blockscout/issues/2390
We don't use all of the methods of Lodash lib but we retrieve them all on the page load. This PR replaces imports of the whole Lodash lib with the methods used. It drastically decreases Lodash lib to load.
The lib size decreased from *527Kb* to *76Kb* (**86%** of savings)
The total size of app js code reduced from *2.24Mb* to *1.74Mb* (**23%** of savings)
**Before**:
**After**:
=> Reduce Lodash lib size (86% of lib methods are not used)

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/lib/explorer/market/market_history_cache.ex
https://github.com/poanetwork/blockscout/issues/2344 https://github.com/poanetwork/blockscout/issues/2343
Added two ENV vars to manage updating period of average block time and market history cache
* `AVERAGE_BLOCK_CACHE_PERIOD` in seconds
* `MARKET_HISTORY_CACHE_PERIOD` in seconds
=> Add ENV vars to manage updating period

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/smart_contract/reader.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/smart_contract/reader_test.exs
after #2111, #2249, #2216 and #2305 a few remaining controllers still have not been checked for possible improvements.
This PR is the result of going trough all these controllers.
There are 3 separate commits:
1) Removes unnecessary preloads and queries
2) Modifies `Explorer.Chain` functions to only take an hash/id where possible, just like it was done for Addresses
3) Adds new functions to `Exploerer.Chain` to only check for the existence of an entity
=> Controllers Improvements

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
Parentheses in % of market cap look redundant in `./accounts` page
**Before**
**After**
=> Remove parentheses in market cap percentage

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/router.ex
BS renders `Page not found` view if the path consists only from one part in URL (for instance `/1`). If the wrong path consists of multiple parts (for instance `/1/2/3/4/5/6/`), Blockscout doesn't handle them.
- search mask for `Page not found` page changed to:
https://github.com/poanetwork/blockscout/blob/7187e5766047df8fb0cf4840abb63f0b3616fa90/apps/block_scout_web/lib/block_scout_web/router.ex#L264
- Added missing function clauses for various controllers, that causes `Internal server error` when trying to open corresponding pages.
=> Fix "page not found" handling in the router

apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex, apps/explorer/lib/explorer/chain/staking_pool.ex, apps/explorer/lib/explorer/chain/staking_pools_delegator.ex, apps/explorer/lib/explorer/staking/contract_state.ex
The Wei balances were used by mistake, but all balances and amounts are actually in tokens.
=> Fetch and use staking token for all staking amounts

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
This timeout was implemented here https://github.com/poanetwork/blockscout/pull/2324 and was broken with a new type of loader https://github.com/poanetwork/blockscout/pull/2405 
Fixing of hiding of loader for txs block on the main page if loading less then 1 min
=> Fix hiding of loader for txs on the main page

CHANGELOG.md, rel/commands/clear_build.sh
Clearing script doesn't clear all `./node_modules` and `/logs/dev` folders
Add removal of all `/logs/dev` folders and all `/node_modules` excluding hidden folders and files
=> Fix clearance of logs and node_modules folders in clearing script

apps/block_scout_web/assets/css/components/_stakes_progress.scss, apps/block_scout_web/assets/js/lib/async_listing_load.js, apps/block_scout_web/assets/js/lib/modals.js, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_status.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_progress.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/test/explorer/chain_test.exs
1. Refresh list of pools on account change and show correct buttons.
AsyncLoadStore is improved to allow sending additional dynamic data from redux state, as well as refreshing currently displayed page. This allows showing table rows specifically for currently logged-in account with properly selected row buttons.
2. Make status modals generic and add modal utilities.
`open{Error,Warning,Success}Modal` methods just open corresponding modals.
`openQuestionModal` allows changing button titles and callbacks. It also automatically blocks UI for non-default callback.
3. Load contract ABIs after signing in, add `makeContractCall` utility.
After user signs in using MetaMask for the first time, the contract addresses and ABIs are pushed throught the websocket. They are saved in the state for …
=> Add generic client-side utilities for staking modals

apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/validator_info.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_address.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex
The modal window is rendered entirely on server and requested via websocket.
Bubbling of events is used to avoid setting event handlers on multiple rows.
=> Show modal window with validator/pool info

CHANGELOG.md, apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex, apps/indexer/lib/indexer/block/catchup/fetcher.ex
`last_block_number` is always 0 for indexed chain even if `LAST_BLOCK` is set
- fix logging for finished indexed with last block set
=> fix logging for indexed chain when last block is set

apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_me_tooltip.scss, apps/block_scout_web/assets/css/components/_modal.scss, apps/block_scout_web/assets/css/components/_stakes_table.scss, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/delegators_list.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/staking_pools_delegators.ex, apps/explorer/lib/explorer/chain/staking_pools_delegator.ex, apps/explorer/lib/explorer/staking/contract_reader.ex, apps/explorer/lib/explorer/staking/contract_state.ex, apps/explorer/priv/repo/migrations/20190731172720_add_reward_ratio_to_pool_delegators.exs
**NB!** `staking-latest` branch is updated to include this PR.
Delegator's reward ratio field is added and calculated as follows:
- if the pool is validator, `snapshotStakers` and `snapshotRewardPercents` arrays are fetched from contract, zipped and used for delegators' ratios.
- if a delegator made a stake during this epoch, they won't be present in the arrays above, so they will have `nil` for reward ratio
- if the pool is a candidate, _potential_ reward is calculated manually, while taking into account that pool always receives at least 30%.
The list of delegators is displayed in a modal window with the pool itself being added as the first row, and currently logged in user moved to top.
No paging is implemented for this table, as AsyncListingLoad component doesn't support more than one …
=> Show "Delegators List" modal window

CHANGELOG.md, apps/block_scout_web/assets/js/lib/awesomplete-util.js, apps/block_scout_web/assets/js/lib/awesomplete.js, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json, apps/block_scout_web/assets/webpack.config.js, apps/block_scout_web/lib/block_scout_web/csp_header.ex, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/package-lock.json, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
A part of https://github.com/poanetwork/blockscout/issues/2390
`awesomplete` js/css assets load synchronously contributing to page loading time. In addition, they are loaded from a 3d-party Github Repo directly.
- ~the latest~ 1.1.2 version of `awesomplete` utility installed as a regular npm dependency.
**Update**: `awesomplete` package downgraded to `1.1.2` https://github.com/poanetwork/blockscout/pull/2503/commits/1fb6fa5201bbca7367ea3be2f9ae5259965dcf88 because of this issue https://github.com/LeaVerou/awesomplete/issues/17193
- `awesomplete-util.js` copied to `./js/lib` and cleared out with ES linter
- `awesomplete.css` loading is changed to async loading since autocompletion is not a part of critical css.
- decreasing of every page loading time (➖ 300ms)
- independency of 3d-party …
=> Mitigate autocompletion library influence to page loading performance

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/address_logs/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
fixes https://github.com/poanetwork/blockscout/issues/2476
Some logs events can not be decoded because matching function is not found in the contract's abi.
For example https://blockscout.com/eth/mainnet/address/0x1c527e27aa092c566cdfcc537faf5acc74a62ea0/logs
the same is happening in etherscan https://etherscan.io/address/0x1C527e27aA092c566cdFCC537Faf5acC74A62Ea0#events
- hide decoded row if event is not decoded
=> hide decoded row if event is not decoded

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
- don't show empty token transfers on the transaction overview page
=> don't show empty token transfers on the transaction overview page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
fixes https://github.com/poanetwork/blockscout/issues/2544
- do not show eth value if it's zero on the transaction overview page
=> do not show eth value if it's zero on the transaction overview page

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss
Dark theme import should be at the end of sass file in order to apply it to all styles. Unintentionally changed before in this commit https://github.com/poanetwork/blockscout/pull/2514/commits/77b7d34d50225ad68b47cd0565ec972e33decc3e#diff-5cbc16d38bf2aa42b4b2ac22b572ceb7R78
=> Dark theme import to the end of sass

CHANGELOG.md, apps/block_scout_web/assets/js/lib/tooltip.js
**Problem:** there are a lot of tooltips in staking UI that are located in dynamically created DOM, which are currently not initialized correctly.
**Solution:** initialize tooltips on `<body>` with selector parameter.
=> Correctly handle dynamically created Bootstrap tooltips

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
When the page is loading or user switches between pages with the dark mode applied, the light mode is loading first and then dark mode applied after a while.
Raise the priority of dark theme class applying to `window.onload` event.
=> Fix dark theme flickering

apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/config/config.exs, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
The table is refreshed when new staking epoch starts and after an interval configured in `apps/block_scout_web/config/config.exs` (10 by default).
If no interval is configured, the table is only updated on new epoch.
=> Periodically refresh the table with staking pools

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/v1/health_controller_test.exs, apps/block_scout_web/test/support/conn_case.ex, apps/block_scout_web/test/support/feature_case.ex, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/blocks.ex, apps/explorer/lib/explorer/chain/cache/transactions.ex, apps/explorer/lib/explorer/chain/ordered_cache.ex, apps/explorer/test/explorer/chain/cache/blocks_test.exs, apps/explorer/test/explorer/market/market_history_cache_test.exs, apps/explorer/test/explorer/market/market_test.exs, apps/explorer/test/support/data_case.ex, apps/indexer/lib/indexer/block/fetcher.ex
Part of #2427 
Multiple caches exist to keep a page of the most recent `n` elements.
More are to be implemented, so it would be good to abstract their implementation.
This PR adds a behaviour and a macro (providing an implementation) to create this type of caches.
It also redefines the existing ones using the new macro.
Note: I did not write tests for the new module. however the existing tests for the transactions and blocks caches should cover the most important cases
=> Add generic Ordered Cache behaviour and implementation

CHANGELOG.md, apps/block_scout_web/assets/css/_images-preload.scss, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_network-selector.scss, apps/block_scout_web/lib/block_scout_web/templates/layout/_network_selector_item.html.eex
Network icons load every time when a user opens the network menu causing for a while:
Preload of network icons added with this PR
=> Network icons preload

CHANGELOG.md, apps/block_scout_web/mix.exs, mix.lock
In the PR (https://github.com/poanetwork/blockscout/pull/2516) we
broke backward compatibility with old blockscout releases. Now, we will
use new fork branches for absinthe deps forks in current releases
and return old forks to the old state to maintain backward compatibility.
- change branch for absinthe phoenix
=> change branch for absinthe phoenix

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/chain_spec/genesis_data.ex
From this point, genesis data fetching will start once and will
be retried on task failure. Also, this PR disables genesis
data fetcher process by default because most of our users won't
know that they should set chain spec for it.
- do not start genesis data fetching periodically
=> do not start genesis data fetching periodically

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
Instead of producing empty blocks nodes in Aura consensus protocol
broadcast an EmptyStep(step, parent_hash) message.
https://github.com/paritytech/wiki/blob/master/Aura.md#empty-steps
resolves https://github.com/poanetwork/blockscout/issues/2347
- add AuRa's empty step reward type
=> add AuRa's empty step reward type

apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item_account.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/staking/contract_reader.ex
Result of `stakeAmount` getter includes ordered withdrawals, which should not actually be displayed as part of stake from user's standpoint.
Thus, we now use `stakeAmountMinusOrderedWithdraw` getter for that amount and start showing the total amount of ordered withdrawals in top panel.
In addition, a couple of missing `is_deleted` filters is added.
Addresses [issue 18](https://github.com/poanetwork/blockscout/pull/2292#issuecomment-522098750).
=> Separate ordered withdrawals from active stakes

CHANGELOG.md, apps/indexer/lib/indexer/block/fetcher.ex
Sometimes due to some error (mostly network) we may
not fetch any data when indexing block. If block cache update
is triggered it fails.
This PR checks if list is passed to cache update function.
- skip cache update if there are no blocks inserted
=> skip cache update if there are no blocks inserted

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
fixes https://github.com/poanetwork/blockscout/issues/2493
Reward calculation is a heavy operation since it joins
`rewards` and `transactions` tables with `blocks`.
`transactions` is one of the largest tables in the DB.
So that was a reason for a request timeout. Removing rewards
fixed the issue. From this point rewards should be fetched
with `getblockreward` rpc.
Pagination is already implemented.
- remove rewards from getminedblocks rpc response
=> remove rewards from getminedblocks rpc response

apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
1. If an address has been a pool some time ago, but was deactivated since, we can't use `addPool()` method anymore due to limitations in the contract.
Instead, we fetch previously existing pool, provide unchangeable mining address, and use `stake()` method for reactivating the pool.
2. Banned pools can't become a candidate again, so the button is disabled. [Issue 13](https://github.com/poanetwork/blockscout/pull/2292#issuecomment-517391758).
=> Improve UI for becoming a candidate for existing pools

CHANGELOG.md, README.md
Xerom uses blockscout as a backup explorer, figured it would be good to show our support.
* Ran a beautifier over the README.md as well as CHANGELOG.md files
* Added Xerom to list of Additional Chains using BlockScout and linked their public instance. 
* Ran a beautifier over the README.md as well as CHANGELOG.md files
None.
None. 
No need.
=> Added Xerom to list of Additional Chains using BlockScout.

CHANGELOG.md, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address_transaction_csv_exporter.ex, apps/explorer/lib/explorer/chain/transaction.ex
Part of #2306 
The query used to fetch transactions for an address have been re-split and parallelized.
Note that the reason this was done is that, for some addresses more than others, executing a single query on the Transactions table with several `where` clauses is a lot slower than making them separately.
This may seem to contradict a previous change where the opposite operation has been done, but the difference is in the fact that previously the list of queries was run sequentially.
=> Execute all address' transactions page queries in parallel

apps/block_scout_web/assets/css/components/_form.scss, apps/block_scout_web/assets/js/lib/validation.js, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/assets/js/pages/stakes/move_stake.js, apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js, apps/block_scout_web/lib/block_scout_web/templates/common_components/_input_group.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex
Part of #2573
Currently, in case invalid data is entered in any of the modals related to staking, an error modal is displayed, and after it is closed, a user has to open it again and enter all the data from scratch.
Instead, the project designer has drawn inline error messages, which would be displayed immediately.
- New template component - Input Group added
- Raw HTML inputs replaced Input Group component in _stakes_modal_become_candidate.html
- Error state styles added for Input Group
- Some on submit validations replaced with on input blur (unfocus) validations for Become Candidate modal 
- Added functionality to disable submit button in case of invalid entries for Become Candidate modal
=>  Validate input data in staking modals in real time

apps/block_scout_web/assets/css/components/_form.scss, apps/block_scout_web/assets/js/lib/validation.js, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/assets/js/pages/stakes/move_stake.js, apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_input_group.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
As contract calls don't give very descriptive errors, we need to check preconditions in JS ourselves.
This PR adds these checks and tidies them up in general.
Also, `MIN_DELEGATOR_STAKE` defines minimal _total_ stake on particular pool.
Thus, we now allow adding less than that amount for existing stakes.
=> Validate staking contract calls in JS and allow adding <1 POA to existing stake

apps/block_scout_web/assets/css/components/stakes/_stakes.scss, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/claim_withdrawal.js, apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_claim.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_move.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_stake.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_withdraw.html.eex
**Problem:** putting both _Withdraw_ and _Claim_ functionality on one button is confusing and requires an additional question modal.
**Solution:** add a separate _Claim_ button that appears when there is an ordered amount available for claiming. To save space in the table, all button titles are moved into tooltips.
=> Separate Claim Withdrawal button from Withdraw

apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
Reinstating a pool is essentially staking something to it, so we reuse the existing Stake modal window with all of its checks and pool state chart.
=> Show Stake modal instead of Become a Candidate for existing pools

apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_claim.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_progress.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item_account.html.eex, apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex
**Problem:** fractional token amounts are too long and break page layout.
**Solution:** add token amount formatting function that cuts and ellipsizes token amounts according to token settings and passed parameters.
By default, amounts are cut to 5 fractional digits, "..." with tooltip is added if needed, and token symbol is attached. This can be changed by passing additional list of parameters.
=> Cut and ellipsize token amounts

CHANGELOG.md, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain/cache/block_number.ex, apps/explorer/lib/explorer/chain/cache/blocks.ex, apps/explorer/lib/explorer/chain/cache/transactions.ex, apps/explorer/lib/explorer/chain/ordered_cache.ex, apps/explorer/test/explorer/chain/cache/block_number_test.exs
Relates to https://github.com/poanetwork/blockscout/issues/2583
`Blocks`, `Transactions` and `BlockNumber` caches are updated by Indexer, but when Indexer runs separately from WebApp, caches aren't updated. So I added TTL for this caches to updating them without Indexer.
=> Add cache updating independently from Indexer

CHANGELOG.md, apps/explorer/lib/explorer/chain/cache/block_count.ex, apps/explorer/lib/explorer/chain/cache/transaction_count.ex
Using `Task.async` in caches causes problems because their result gets sent to the `ConCache.Owner` of the respective cache, that does not handle the call.
`Task.start` can be used instead of `Task.async`
=> Use Task.start instead of Task.async in caches

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex, apps/indexer/test/indexer/block/fetcher/receipts_test.exs
Reverts poanetwork/blockscout#2148
We started having missing token transfers and logs. For new blocks parity returns pending logs. Logs are used for token transfers and token balances update. I think it's better to fail a couple of times before parity start returning normal logs
PR 2148 just skips pending logs that's why we have missing token transfers and token balances
=> Revert "Filter pending logs"

apps/block_scout_web/assets/css/components/_check_tooltip.scss, apps/block_scout_web/assets/css/components/_stakes_table.scss, apps/block_scout_web/assets/css/components/stakes/_modal_become_candidate.scss, apps/block_scout_web/assets/css/components/stakes/_modal_delegators_info.scss, apps/block_scout_web/assets/css/components/stakes/_modal_stake.scss, apps/block_scout_web/assets/css/components/stakes/_modal_validator_info.scss, apps/block_scout_web/assets/css/components/stakes/_stakes.scss, apps/block_scout_web/assets/css/stakes.scss, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/js/lib/list_morph.js, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_address.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item_account.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex, apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
This PR is made to fix remin WEB UI issues for POSDAO Staking DApp, directly https://github.com/poanetwork/blockscout/pull/2292#issuecomment-522098750
This is a more clean version of https://github.com/poanetwork/blockscout/pull/2618 , so should contain commits for each fix and remove some unnecessary logic.
=> Fix staking UI issues (from #2292)

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Transactions have duplicate internal transactions. The issue is caused by chain reorganisations.
- remove non consensus internal transactions
=> remove non consensus internal transactions

CHANGELOG.md, apps/explorer/config/config.exs, docs/env-variables.md
Excluding of nonconsensus blocks from avg block time calculation was introduced here https://github.com/poanetwork/blockscout/pull/2266. But the default option was inclusion of such blocks whereas the most popular option is to calculate only consensus blocks.
- Change the default option of avg block time calculation - exclude nonconsensus blocks by default
- Add `UNCLES_IN_AVERAGE_BLOCK_TIME` to docs. It was missing.
=> Exclude nonconsensus blocks from avg block time calculation by default

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/addresses.ex, apps/explorer/test/explorer/chain/import/runner/addresses_test.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Currently, we update `fetched_coin_balance` field of an address
to nil, if changes have `fetched_coin_balance_block_number` bigger than
the current value in the DB.
https://github.com/poanetwork/blockscout/issues/2685
- do not update fetched_coin_balance with nil
=> do not update fetched_coin_balance with nil

CHANGELOG.md, apps/block_scout_web/test/support/conn_case.ex, apps/block_scout_web/test/support/feature_case.ex, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/accounts.ex, apps/explorer/test/explorer/chain/cache/accounts_test.exs, apps/explorer/test/support/data_case.ex, apps/indexer/lib/indexer/block/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/lib/indexer/fetcher/block_reward.ex, apps/indexer/lib/indexer/fetcher/coin_balance.ex, apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex, apps/indexer/lib/indexer/fetcher/contract_code.ex, apps/indexer/lib/indexer/fetcher/internal_transaction.ex, apps/indexer/lib/indexer/fetcher/pending_transaction.ex, apps/indexer/lib/indexer/fetcher/uncle_block.ex
Closes #2428 
NOTE: the cache is already set up to work without the Indexer, but it will only work after #2612 is merged.
=> Add ETS-based cache for accounts page

apps/block_scout_web/assets/css/_mixins.scss, apps/block_scout_web/assets/css/components/_check.scss, apps/block_scout_web/assets/css/components/_form.scss, apps/block_scout_web/assets/css/components/_i_tooltip.scss, apps/block_scout_web/assets/css/components/_modal_status.scss, apps/block_scout_web/assets/css/components/_stakes_table.scss, apps/block_scout_web/assets/css/components/stakes/_modal_bottom_disclaimer.scss, apps/block_scout_web/assets/css/components/stakes/_modal_delegators_info.scss, apps/block_scout_web/assets/css/components/stakes/_stakes.scss, apps/block_scout_web/assets/css/components/stakes/_stakes_progress.scss, apps/block_scout_web/assets/css/theme/_dai_variables.scss, apps/block_scout_web/assets/css/theme/_dark-theme.scss, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip.html.eex, apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_bottom_disclaimer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
This PR is made to fix remain UI issues related to the theme colors for POSDAO Staking DApp, directly https://github.com/poanetwork/blockscout/pull/2292#issuecomment-522098750
This is a more clean version of https://github.com/poanetwork/blockscout/pull/2618 , so should contain commits for each fix and remove some unnecessary logic.
=> Fix staking Theme colors UI issues (from #2292)

CHANGELOG.md, apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
#Motivation
It causes empty percentages on accounts page
- fix empty total_supply in coin gecko response
=> fix empty total_supply in coin gecko response

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Fixes #2681
Update block view template
=> Fix stuck label and value for uncle block height

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
The recently introduction of non-consensus block's data removal is not efficient enough to keep the pace with block creation.
This PR changes the logic to remove only data of blocks that lose consensus because they are being overridden (as opposed to also for blocks that are invalid neighbors) and changes the queries to perform.
=> Improve speed of nonconsensus data removal

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex, apps/block_scout_web/lib/block_scout_web/notifier.ex, apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs, apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs, apps/explorer/config/config.exs, apps/explorer/config/test.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/address.ex, apps/explorer/lib/explorer/counters/addresses_counter.ex, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/counters/addresses_counter_test.exs
Wallets counter on the main page accounts only addresses with non-zero balance of native coins.
It should account addresses with zero coins balance too. After all, address can have zero coin balance but own some tokens.
Wallets counter on the main page accounts all rows in the `addresses` table
=> Include all addresses taking part in transactions in wallets' addresses counter

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
resolves https://github.com/poanetwork/blockscout/issues/2686
- add log index to logs view
=> add log index to logs view

CHANGELOG.md, apps/explorer/lib/explorer/smart_contract/verifier.ex, apps/explorer/test/explorer/smart_contract/verifier_test.exs
fixes https://github.com/poanetwork/blockscout/issues/2727
bytecode of a library contains the address of a deployed library
- fix library verification
=> fix library verification

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
this runner updates internal_transactions_index_at field in blocks
table. but before this, it checks if these blocks are consensus, some
blocks may lose consensus.
we just shouldn't check if the number of updated records is exactly
equal to the number of records that we want to insert.
blocks that lost consensus will be re-fetched
fixes
```
no match of right hand side value: {7, nil}
(explorer) lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex:71:
```
- do not fail block `internal_transactions_indexed_at` field update
=> do not fail block `internal_transactions_indexed_at` field update

CHANGELOG.md, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex, apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex, apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
Explorer's blocks runner is severely slowed down by doing two operation on internal transactions:
- populating their block_number field
- removing those in blocks that have lost consensus
The field setting was introduced only to keep it [correct in case of a reorg](https://github.com/poanetwork/blockscout/commit/373248dbeeed03fc1d69f5adfc1b1e8a71550638), but those `internal_transactions` do not pose this problem anymore because they are removed.
For this reason we can remove the `block_number` field setting and simplify the remaining operation
Additionally, this PR also has a commit that solves one of the problems that causes `internal_transactions` failing to be imported because of an error on their `transactions` foreign key constraint. Another of such causes is solved as part of #2470
=> Remove internal_transaction block_number setting from blocks runner

.tool-versions, CHANGELOG.md, apps/block_scout_web/assets/css/theme/_dark-theme.scss
Fixed hovers for blockscout menu in dark mode desktop view. 
Menu hovers in dark mode desktop view were broken (i've created new hovers for new mobile menu, but they appeared in desktop view too.)
Added media query for mobile menu hovers, and issue was fixed.
https://www.loom.com/share/b4306e240cd24f06a2986c3ed4cc2245
=> Fixed menu hovers in dark mode desktop view

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
the longest part of addresses page loading was fetching validation
count for every address.
addresses are loaded from cache. it takes less than a second but
fetching validation count takes more than 5 seconds.
Moreover, validation_count is not used.
- optimize addresses page
=> optimize addresses page

CHANGELOG.md, apps/block_scout_web/assets/css/_layout.scss, apps/block_scout_web/assets/css/components/_address-overview.scss, apps/block_scout_web/lib/block_scout_web/templates/address_logs/_logs.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_logs.html.eex
This PR is related to #2533 issue
Wrong alignment in logs entry
Fixed wrong alignment in logs decoded view :
=> Fixed address alignment in logs decoded view.

apps/block_scout_web/assets/js/lib/modals.js, apps/block_scout_web/assets/js/pages/stakes.js, apps/block_scout_web/assets/js/pages/stakes/become_candidate.js, apps/block_scout_web/assets/js/pages/stakes/claim_withdrawal.js, apps/block_scout_web/assets/js/pages/stakes/make_stake.js, apps/block_scout_web/assets/js/pages/stakes/move_stake.js, apps/block_scout_web/assets/js/pages/stakes/remove_pool.js, apps/block_scout_web/assets/js/pages/stakes/utils.js, apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js
As an additional requirement, we want to restrict connection only to authorized chain network. For now it's xDai (id: 100) and posdao-test network (id: 101)
Requirement: https://github.com/poanetwork/blockscout/pull/2292#issuecomment-532163749
=> Allow connection only to authorized chain networks

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/csp_header.ex, apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/views/tokens/instance/overview_view_test.exs
- allow images from ['properties']['image']['description'] in nft token
- allow images from all sources
=> fix nft token instance images

CHANGELOG.md, apps/indexer/config/config.exs, apps/indexer/lib/indexer/block/catchup/fetcher.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs, apps/indexer/test/indexer/block/catchup/fetcher_test.exs, apps/indexer/test/indexer/block/realtime/fetcher_test.exs, docs/env-variables.md
Closes #1556 
and solves this error of `fetcher=internal_transaction`:
```
Exception:
** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "internal_transactions" violates foreign key constraint "internal_transactions_transaction_hash_fkey"
table: internal_transactions
constraint: internal_transactions_transaction_hash_fkey
```
While searching for the root cause of the `internal_transactions` issue an odd correlation with the order of the realtime's fetcher indexed block was noticed and found to be consistently happening.
Upon further inspection this also seems to be the cause (or at least one of the causes) for that same fetcher to be refetching the same block multiple time.
These errors both seem to happen when the `newHeads` websocket subscription skips a …
=> Allow Realtime Fetcher to wait for small skips

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/css/components/_inventory_token_instance_image_container.scss, apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex, apps/block_scout_web/lib/block_scout_web/views/tokens/inventory_view.ex, apps/explorer/lib/explorer/chain/token_transfer.ex
resolves https://github.com/poanetwork/blockscout/issues/2668
- add token instance images to inventory tab
=> add token instance images to inventory tab

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex, apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
https://blockscout.com/poa/sokol/tokens/0xb81afe27c103bcd42f4026cf719af6d802928765/token_transfers
- fix corresponding templates to add a missing whitespace
=> Fix stuck value and ticker on the token page

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/etherscan.ex, apps/explorer/test/explorer/etherscan_test.exs
fixes https://github.com/poanetwork/blockscout/issues/1319
the query was sorted by transactions.block_number field
which doesn't have db
index (https://github.com/poanetwork/blockscout/pull/2698).
Now we will start sorting by blocks.number since transactions are
joined with blocks anyway.
- optimize txlist json rpc
=> optimize txlist json rpc

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/test/explorer/chain_test.exs
Blokcscout shows " n% Blocks Indexed - We're indexing this chain right now. Some of the counts may be inaccurate." banner at the top even if blockchain doesn't have transactions
If there are no transactions in the blockchain, the banner is hidden
=> Hide "We are indexing this chain right now. Some of the counts may be inaccurate" banner if no txs in blockchain

CHANGELOG.md, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/js/pages/token_counters.js, apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/token_controller.ex, apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex, apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex, apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex, apps/block_scout_web/lib/block_scout_web/web_router.ex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po, apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/tokens/token_controller_test.exs
resolves https://github.com/poanetwork/blockscout/issues/2771
Token counters fetching is the slowest part of the token page.
- fetch token counters async
=> fetch token counters async

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex, apps/block_scout_web/priv/gettext/default.pot, apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
=> Fix for stuck gas limit label and value

CHANGELOG.md, apps/explorer/lib/explorer/etherscan.ex
https://github.com/poanetwork/blockscout/issues/2582
When using `block_number` field from the transaction table, the query is not timing out.
- fix `txlist` ordering issue
=> fix txlist ordering issue

CHANGELOG.md, apps/block_scout_web/assets/css/theme/_lukso_variables.scss
Before:
After:
Change LUKSO theme
=> LUKSO dashboard height fix

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex, apps/indexer/lib/indexer/block/realtime/fetcher.ex, apps/indexer/test/indexer/block/realtime/fetcher_test.exs
If indexing is started from scratch, realtime fetcher
tries to index large ranges of blocks. For example, 5..1852044.
It produces errors like
`failed to fetch: :emfile.  Block will be retried by catchup indexer`
This PR limits the number of blocks to 10
- fix realtime fetcher small skips feature
=> fix realtime fetcher small skips feature

CHANGELOG.md, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
```
2019-11-06T22:28:05.871 application=indexer fetcher=block_catchup first_block_number=6404723 last_block_number=6404723 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.FetchedBeneficiaries.get_address_type/2
(ethereum_jsonrpc) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:172: EthereumJSONRPC.Parity.FetchedBeneficiaries.get_address_type("external", 11)
(ethereum_jsonrpc) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:156: EthereumJSONRPC.Parity.FetchedBeneficiaries.trace_to_params_set/3
(ethereum_jsonrpc) lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex:132: anonymous fn/3 in EthereumJSONRPC.Parity.FetchedBeneficiaries.traces_to_params_set/2
(elixir) lib/enum.ex:3023: anonymous fn/3 in Enum.reduce/3
(elixir) lib/stream.ex:1571: …
```
=> Extend external reward types up to 20

CHANGELOG.md, apps/block_scout_web/assets/css/components/_navbar.scss
Before (Safari):
After (Safari):
Set `outline: none` for `nav-link`
=> Set outline none for nav dropdown item in mobile view

CHANGELOG.md, apps/block_scout_web/assets/css/app.scss, apps/block_scout_web/assets/js/app.js, apps/block_scout_web/assets/package-lock.json, apps/block_scout_web/assets/package.json, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
After returning of old networks menu https://github.com/poanetwork/blockscout/pull/2797, networks images preload wasn't removed https://github.com/poanetwork/blockscout/pull/2570
Remove preload of network images for enhanced networks menu since that menu was disabled for a while and networks menu styles itself
=> Remove networks images preload

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex, apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Paths for *non-critical*, *stakes*, *awesomplete* assets are relative and do not include a part of path like `/eth/mainnet` and thus are not cached on the front-end because of haproxy configuration to not cache files that are from the root path `./`
Fix paths for *non-critical*, *stakes*, *awesomplete* assets
=> Extend paths for css/js assets

CHANGELOG.md, apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex, apps/block_scout_web/lib/block_scout_web/etherscan.ex, apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/explorer/config/config.exs, apps/explorer/lib/explorer/application.ex, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/test/explorer/chain/cache/address_sum_test.exs, apps/explorer/test/explorer/chain/cache/block_count_test.exs, apps/explorer/test/explorer/chain_test.exs
Calculate the total supply of POA Core coin and use that endpoint for CMC and exchanges.
- the new JSON RPC endpoint in `stats` module
- the data is retrieved from ETS, ETS is updated every hour by default or configured via `ADDRESS_SUM_CACHE_PERIOD` ENV var
Addition of ENV vars to the docs https://github.com/blockscout/docs/pull/10
API will be available at `/api?module=stats&action=ethsupply`
The similar API but from CoinGecko moved to `/api?module=stats&action=ethsupplyexchange`
=> Coin total supply from DB API endpoint

CHANGELOG.md, apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
some token instances return integers as metadata
fixes
```
2019-11-19T09:35:55.538 [error] Task #PID<0.20704.5> started from Indexer.Fetcher.TokenInstance terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<104, 35, 202, 192, 134, 199, 8, 88, 185, 190, 194, 23, 112, 82, 10, 103, 36, 129, 169, 107>>}, token_id: #Decimal<3>}, errors: [metadata: {"is invalid", [type: :map, validation: :cast]}], data: #Explorer.Chain.Token.Instance<>, valid?: false>}
(indexer) lib/indexer/fetcher/token_instance.ex:63: Indexer.Fetcher.TokenInstance.run/2
(elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir) lib/task/supervised.ex:35: …
```
=> add token instance metadata check

apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/token.ex, apps/explorer/lib/explorer/token/metadata_retriever.ex, apps/explorer/test/explorer/chain/token_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/explorer/token/metadata_retriever_test.exs, apps/indexer/lib/indexer/fetcher/token_updater.ex, apps/indexer/lib/indexer/supervisor.ex, apps/indexer/test/indexer/fetcher/token_updater_test.exs, apps/indexer/test/support/indexer/fetcher/token_updater_supervisor_case.ex
More than 50% of requests that we're making to Ethereum node are `eth_call` requests that query token contracts for a name and a symbol
Example (data  starts with `0x313ce567`)
```
окт 02 10:21:26 ip-172-31-11-113.ec2.internal parity[24923]: 2019-10-02 10:21:26 UTC jsonrpc-eventloop-1 TRACE rpc  Request: [{"id":0,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x313ce567"
окт 02 10:21:26 ip-172-31-11-113.ec2.internal parity[24923]: 2019-10-02 10:21:26 UTC jsonrpc-eventloop-1 DEBUG rpc  [None] Took 36ms
окт 02 10:21:26 ip-172-31-11-113.ec2.internal parity[24923]: 2019-10-02 10:21:26 UTC jsonrpc-eventloop-1 TRACE rpc  Request: [{"id":0,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x313ce567"
окт 02 10:21:26 ip-172-31-11-113.ec2.internal parity[24923]: 2019-10-02 10:21:26 …
```
=> rewrite token updater

CHANGELOG.md, apps/block_scout_web/assets/js/lib/utils.js
Loaders showing delay on the main page was set to 1 second https://github.com/poanetwork/blockscout/pull/2324, what is too long. It was decreased to 100 ms. It means if the data will not be fetched from the server in 100 ms, mock loaders will be shown.
=> Decrease loaders showing delay on the main page

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/logs.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/priv/repo/migrations/20191121064805_add_block_hash_and_block_index_to_logs.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Part of #2865
This PR adds block_hash to logs table and adds it to a composite primary key. That's how we can get rid of heavy logs removal operation during blocks import.
=> do not remove logs

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs, apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs, apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs, apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex, apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/import/runner/blocks.ex, apps/explorer/lib/explorer/chain/import/runner/logs.ex, apps/explorer/lib/explorer/chain/log.ex, apps/explorer/priv/repo/migrations/20191121064805_add_block_hash_and_block_index_to_logs.exs, apps/explorer/test/explorer/chain/import/runner/blocks_test.exs, apps/explorer/test/explorer/chain/import_test.exs, apps/explorer/test/explorer/chain/log_test.exs, apps/explorer/test/explorer/chain_test.exs, apps/explorer/test/support/factory.ex
Part of #2865
This PR adds block_hash to logs table and adds it to a composite primary key. That's how we can get rid of heavy logs removal operation during blocks import.
=> do no remove non-consensus logs

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/test/explorer/chain/cache/address_sum_test.exs, apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs
on the first call address sum cache starts a task to
fetch a value from the DB and return nil
Related commit https://github.com/poanetwork/blockscout/commit/b87fc2d7ab2ef9d97c62292e2029f9c06c5b87a9
- fix address sum cache
=> fix address sum cache

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs, apps/explorer/lib/explorer/counters/average_block_time.ex, apps/explorer/test/explorer/counters/average_block_time_test.exs, apps/indexer/test/indexer/fetcher/coin_balance_on_demand_test.exs
1. If non-consensus blocks are excluded in the calculation, the total amount of accounted blocks is <= 100. But it should be 100 for both cases: excluding/including of non-consensus blocks.
2. function `refresh_timestamps` gets the latest blocks but there could be reorgs and thus missing blocks in the DB that contaminates the average value.
For instance, on Kovan it should be 4 sec:
- add an offset of 100 blocks in `refresh_timestamps` function
- fixate limit of 100 target blocks for the case, when we exclude non-consensus blocks from calculation
=> Offset in blocks retrieval for average block time

CHANGELOG.md, apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs, apps/explorer/lib/explorer/chain.ex, apps/explorer/lib/explorer/chain/cache/address_sum.ex, apps/explorer/test/explorer/chain/cache/address_sum_test.exs, apps/explorer/test/explorer/chain/import/runner/address/token_balances_test.exs
on the first call address sum cache starts a task to
fetch a value from the DB and return nil
Related commit https://github.com/poanetwork/blockscout/commit/b87fc2d7ab2ef9d97c62292e2029f9c06c5b87a9
- fix address sum cache
=> restart cache for tests
